### ISSUE TITLE
Question: Register anonymous listeners

### ISSUE THREAD

**Issue by erikvdvelden** [aws/aws-sdk-android#101]
In the examples the registration of a transferlistener is done with an anonymous class. I copied this pattern in my own code.
However, I noticed that sometimes I did not seem to receive all the callbacks. When I look in the code, it seems that the reference in s3 is only kept as a weakreference. Therefore, there seems to be nothing to prevent them from being garbage collected.
Now I changed my code to keep track of all my registered tranferListeners in my own class, to prevent them from being garbage collected. And indeed I now seem to receive more callbacks.

I am not confident enough to mark this as a bug, but maybe somebody can confirm this behaviour.

**Comment by fosterzhang** [comment]
Not a bug. It's a decision in v2.2.12 to prevent memory leak. But it seams to have some side effect. We'll be tweaking this in future releases. Stay tuned.

**Comment by erikvdvelden** [comment]
Thanks for the fast response!

I would suggest to at least update the examples to avoid anonymous listeners and show an example where the listeners are kept referenced from the calling class. Otherwise, you are trading one type of memory leak for another. Since typically the removal of the record would be done based on the callback. So if the callback is never received, the records would never be removed.

Alternative solutions could be to 
1) keep real references, but do a periodic cleaning of the records. I.e., records that are no longer active (canceled, failed, completed) could be removed after a certain time, if they are not explicitly cleaned by the SDK-user. Or, 

2) remove any records that reach a final state, after reporting it to the user via the callback. So you would only persistently keep the ongoing transfers, not the finished/failed ones.

Just my 2 cents.

**Comment by fosterzhang** [comment]
Thank your very much for your suggestions. This is improved in v2.2.13 release. Please update the SDK at https://aws.amazon.com/mobile/sdk/. Check out what is changed in the [change log](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md).
