### ISSUE TITLE
TransferUtility.upload runs slower and slower

### ISSUE THREAD

**Issue by dsuyang** [aws/aws-sdk-android#106]
My app takes photo and upload them to S3 at high frequency. The uploading speed is swift at the very beginning (less than a second), and then it takes longer and longer to complete (more than 6, 7 seconds). I set break points and found it is
`AWSClientManager.get().getTransferUtility().upload `
that **throttles the time.** 

I thought it was because the SQLite gets larger and larger? However, It doesn't makes sense as SQLite can handle large amount of data very well. 

Anyway, in order to maintain the high speed upload, I tried calling
`AWSClientManager.get().getTransferUtility().deleteTransferRecord(id);`
each time after the upload's callback shows the record is successfully uploaded.
**This helps a lot**, and the speed never drops, but after 701 queries, the program throws the following exception, which basically says the **SQLite runs out of space to allocate new cursors**...

I tried multiple times, and it always breaks at the ballpark of 700 queries. 
If you want to repeat the problem, simply set uploading frequency at 1 photo per second, you should notice the speed drop after a few minutes...

> 03-01 19:45:27.969 14175-14175/com.ripplearc.dsuyang.groundvisual E/libc: mmap fail (pid 14175, tid 14175, size 2097152, flags 0x1, errno 12(Out of memory))
> 03-01 19:45:27.969 14175-14175/com.ripplearc.dsuyang.groundvisual E/CursorWindow: Fail on mmap of ashmemFd: 809, errno: 12, msg: Out of memory
> 03-01 19:45:27.969 14175-14175/com.ripplearc.dsuyang.groundvisual E/CursorWindow: Could not allocate CursorWindow '/data/data/com.ripplearc.dsuyang.groundvisual/databases/awss3transfertable.db' of size 2097152 due to error -12.
> 03-01 19:45:27.979 14175-14175/com.ripplearc.dsuyang.groundvisual E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                                     Process: com.ripplearc.dsuyang.groundvisual, PID: 14175
>                                                                                     android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=701 (# cursors opened by this proc=701)
>                                                                                         at android.database.CursorWindow.<init>(CursorWindow.java:163)
>                                                                                         at android.database.CursorWindow.<init>(CursorWindow.java:127)
>                                                                                         at android.database.AbstractWindowedCursor.generateNewWindowCursor(AbstractWindowedCursor.java:195)
>                                                                                         at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:210)
>                                                                                         at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:165)
>                                                                                         at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:159)
>                                                                                         at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
>                                                                                         at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
>                                                                                         at com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver$TransferContentObserver.onChange(TransferObserver.java:200)
>                                                                                         at android.database.ContentObserver.onChange(ContentObserver.java:137)
>                                                                                         at android.database.ContentObserver.onChange(ContentObserver.java:152)
>                                                                                         at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:232)
>                                                                                         at android.os.Handler.handleCallback(Handler.java:739)
>                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                                         at android.os.Looper.loop(Looper.java:155)
>                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5696)
>                                                                                         at java.lang.reflect.Method.invoke(Native Method)
>                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
>                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by fosterzhang** [comment]
Judging from the stacktrace, you are probably not using the latest version. Leaked cursor is fixed in v2.2.10, and TransferListener is rewritten in v2.2.11 with huge performance improvement. Would you please update the SDK to v2.2.13?

**Comment by dsuyang** [comment]
Thank you so much, I did have 2.2.9...
I have been stress testing it for 2.5 hrs now, and everything looks fine. I will come back if any problems emerge down the road. 

Thanks again!
