### ISSUE TITLE
TransferObserver getState() not updated when setTransferListener is not registered

### ISSUE THREAD

**Issue by ledlie** [aws/aws-sdk-android#109]
Preface: I need to upload files in a specific order. So while the TransferUtility is good for most situations, I need to serialize uploads. So I start an upload and wait for it to finish. Previously I was using wait() and notify() to avoid polling, but there was a race condition where I was not being notified of completed transfers. So I switched to polling, which is ugly but simplifies the logic.

Problem: In the code below, when I setTransferListener, the values returned by observer.getState() change as expected. When I comment it out, observer.getState() always returns WAITING. This seems broken. The fact that I am adding something additional to listen should be independent of whether the original observer returns the correct state. Note that this is happening on a network thread (I only have one network thread).

<pre><code>
TransferObserver observer = client.upload(mNet.getUploadsBucketName(), key, file, objectMetadata);

//        observer.setTransferListener(new TransferListener() {
//            @Override
//            public void onStateChanged(int id, TransferState state) {
//                CLog.v(TAG, "onStateChanged state=" + state);
//            }
//
//            @Override
//            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
//
//            }
//
//            @Override
//            public void onError(int id, Exception ex) {
//                CLog.e(TAG, "putObject failed: " + ex);
//
//            }
//        });

        boolean success = false;
        long duration = 100;

        // TODO change to larger value
        long MAX_DURATION = 5000;
        while (true) {
            TransferState state = observer.getState();
            CLog.v(TAG, "loop duration=" + duration + " state=" + state);

            if (TransferState.COMPLETED.equals(state)) {
                mRunningByteCount += fileSize;
                CLog.d(TAG, "upload OK " + file.getName() + " length=" + fileSize);
                success = true;
                break;
            }
            if (TransferState.FAILED.equals(state)) {
                CLog.d(TAG, "upload failed " + file.getName() + " length=" + fileSize);
                break;
            }
            if (duration > MAX_DURATION) {
                CLog.e(TAG, "Timed out waiting for upload duration=" + duration);
                break;
            }

            try {
                Thread.sleep(duration);
            } catch (InterruptedException e) {
                CLog.e(TAG, "Could not block for upload");
            }
            duration *= 2L;
        }
</pre></code>

Result with `setTransferListener`:
03-05 09:35:35.129 V/S3Uploader(11937): loop duration=100 state=WAITING
03-05 09:35:35.143 V/S3Uploader(11937): onStateChanged state=IN_PROGRESS
03-05 09:35:35.229 V/S3Uploader(11937): loop duration=200 state=IN_PROGRESS
03-05 09:35:35.236 V/S3Uploader(11937): onStateChanged state=COMPLETED
03-05 09:35:35.429 V/S3Uploader(11937): loop duration=400 state=COMPLETED
03-05 09:35:35.430 D/S3Uploader(11937): upload OK 1457188314.bz2 length=954

Result without `setTransferListener`:
03-05 09:34:05.902 V/S3Uploader(11410): loop duration=100 state=WAITING
03-05 09:34:06.002 V/S3Uploader(11410): loop duration=200 state=WAITING
03-05 09:34:06.203 V/S3Uploader(11410): loop duration=400 state=WAITING
03-05 09:34:06.603 V/S3Uploader(11410): loop duration=800 state=WAITING
03-05 09:34:07.406 V/S3Uploader(11410): loop duration=1600 state=WAITING
03-05 09:34:09.007 V/S3Uploader(11410): loop duration=3200 state=WAITING
03-05 09:34:12.208 V/S3Uploader(11410): loop duration=6400 state=WAITING
03-05 09:34:12.208 E/S3Uploader(11410): Timed out waiting for upload duration=6400

**Comment by jhen0409** [comment]
You need call `observer.refresh()` to update the TransferObserver instance.

**Comment by fosterzhang** [comment]
@jhen0409's answer is correct. See [TransferObserver.refresh()](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/s3/transferutility/TransferObserver.html#refresh()). The Javadoc says:

> Refresh fields in the TransferObserver from the running transfer task. If TransferListener is set, then there's no need to call this method.

**Comment by ledlie** [comment]
Fair enough. IMO it would be useful if the Javadoc for TransferObserver.getState() mentioned this.

Since my application requires serialization, as mentioned above, I ended up switching to using an AmazonS3Client directly.
