### ISSUE TITLE
Search a cloud search domain

### ISSUE THREAD

**Issue by procedurallygenerated** [aws/aws-sdk-android#112]
Hey,

Any plans to allow searching a cloud search domain, something like the AmazonCloudSearchDomainClient.

Right now I'm trying to use com.amazonaws.DefaultRequest and signing it using AWS4Signer. Is that the way to go?

**Comment by fosterzhang** [comment]
Do you mind sharing a mobile specific use case of this feature? We'd like to evaluate its use case before adding support for it.

**Comment by varunvairavan** [comment]
I think a lot of people would love to use search within their apps. Whether it's searching for people near you, venues/locations near you. Finding a location/venue based on certain filters and sorted by distance or other parameters. Cloud search seems to be perfect for that. We've configured dynamoDB streams to send all updates to 

Right now we are building an app using cognito, dynamodb and s3. We need to allow the users to see venues near them, filtered by multiple search params and sorted by distance. It is hard to accomplish something like this using dynamodb. Cloud search seems to be perfect for that.

Am I missing something? Is there a better way to do this?

**Comment by fosterzhang** [comment]
Hmm, interesting use case. I'll do some research and get back to you ASAP.

**Comment by fadelakin** [comment]
@varunvairavan random question and sorry for popping up here. can you give an example of how you were able to link cloudsearch and android together? i'm having a bit of a difficulty.
