### ISSUE TITLE
What is the data usage overhead of TransferUtility.upload

### ISSUE THREAD

**Issue by dsuyang** [aws/aws-sdk-android#115]
My app is designed for outdoor and has to work over the 4G network, so the data consumption matters here. 

I use **TrafficStats.getUidRxBytes **and **getUidTxBytes** to profile the data usage. On average, it takes twice the amount of photo size to upload a photo. Say, for a 80Kib photo, the consequent data traffic will be more than 160Kib.

Is this data overhead considered normal and is there any way to improve it without cutting the size of the image?

Thanks!

**Comment by fosterzhang** [comment]
There is overhead due to chunked encoding + regular Http stuff, roughly 5-15% of the file size, but I don't expect it doubling the traffic. Do you have sample code for testing? And what's your S3 region?

**Comment by dsuyang** [comment]
I tested it with S3TransferUtilitySample. This is what I found: 
For an image larger than 1MB, the overhead is less than 15%
if the image is less than 100KB, the overhead doubles the traffic. 

I add the following code to OnStateChanged

```
if (newState == TransferState.COMPLETED) {
                int uid = getApplication().getApplicationInfo().uid;
                uid = android.os.Process.myUid();

                float rx = TrafficStats.getUidRxBytes(uid);
                float tx = TrafficStats.getUidTxBytes(uid);

                    CharSequence text = "Outgoing: " + String.format("%.2f KB", (tx-m_prev_tx)/1024)
                            + "\nIncoming: " + String.format("%.2f KB", (rx-m_prev_rx)/1024);
                    int duration = Toast.LENGTH_LONG;
                    Toast toast = Toast.makeText(getApplicationContext(), text, duration);
                    toast.setGravity(Gravity.TOP, 0, 10);
                    toast.show();
                    m_prev_tx = tx;
                    m_prev_rx = rx;
            }
```

Add following code to onStart, m_startRx, m_startTx, m_prev_tx, m_prev_rx should be declared as float and initialized as zero. 

```
m_startRx = TrafficStats.getUidRxBytes(uid);
        m_startTx = TrafficStats.getUidTxBytes(uid);
        m_prev_tx = m_startTx;
        m_prev_rx = m_startRx;
```

The AWS Console says S3 doesn't require a region selection?

Thank you!

**Comment by fosterzhang** [comment]
Statistics are measured at the network layer, so they include both TCP and UDP usage. They also include Http headers and chunked encoding data. The SDK doesn't make extra requests. I conclude ths kind of overheads is just normal.

See some explanation here http://stackoverflow.com/questions/25440796/android-trafficstats-getuidrxbytes-inaccurate if you are interested.

**Comment by fosterzhang** [comment]
S3 bucket lives in a region. Unlike other AWS resources, a S3 bucket is globally unique. So it make sense to show them all in console.

**Comment by dsuyang** [comment]
Thank you for your explanation! I appreciate it.
