### ISSUE TITLE
Implementing SQL DB in Android Studio

### ISSUE THREAD

**Issue by RyanS10** [aws/aws-sdk-android#123]
Hi, I am having trouble with implementing the database into Android Studio. I have the database set up in sql and have an instance set up in AWS, but I do not know how to add it into Android Studio? I have a facebook login working and trying to get the user details saved to the database, how is this possible? Thanks for the help.

**Comment by karthiksaligrama** [comment]
What database in aws are you talking about?

**Comment by RyanS10** [comment]
Relational database service

----- Reply message -----

**Comment by karthiksaligrama** [comment]
you cannot talk to an RDS instance to do database operations directly from android. You will need some sort of a web server or lambda to talk to your RDS instance and spit out a response. 

Take a look at this page for information on how to access rds from lambda. http://docs.aws.amazon.com/lambda/latest/dg/vpc-rds.html

You can then use the android sdk and make calls to the lambda function.

Alternatively you can also use API gateway as a proxy to your lambda function. You can find more information here http://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started.html
