### ISSUE TITLE
Update Proguard.md content.

### ISSUE THREAD

**Issue by filipedelimabrito** [aws/aws-sdk-android#128]
The Proguard.md contents are very old! And, as a better support for users, please, update it.

Taking advantage, thank you AWS for all your services!

**Comment by fosterzhang** [comment]
@filipedelimabrito Thanks for the suggestion. Would you please let me know which part is outdated?

**Comment by filipedelimabrito** [comment]
@fosterzhang The [Creating a Proguard Config](https://github.com/aws/aws-sdk-android/blob/master/Proguard.md#creating-a-proguard-config) is outdate. This section describes the use with Eclipse, and, as the Google says, only Android Studio is the IDE which is supported for Android development now. If you see a [referenced link](http://tools.android.com/recent/proguardimprovements) into this section (for example), you could see that this is a post from 2012!

So, I think that is unnecessary to maintain this section! But I believe that if you want to describe the  configuration with Eclipse IDE, the mention with Android Studio will be good too (and important).

The [Modifying proguard-project.txt for the AWS SDK for Android] (https://github.com/aws/aws-sdk-android/blob/master/Proguard.md#modifying-proguard-projecttxt-for-the-aws-sdk-for-android) shows actions to do in a _proguard-project.txt_ file, but, if you to mention it actions using Android Studio IDE, note that the file is named _proguard-rules.pro_.

The [Using Proguard with the AWS SDK for Android](https://github.com/aws/aws-sdk-android/blob/master/Proguard.md#using-proguard-with-the-aws-sdk-for-android) and [Conclusion and Additional Resources](https://github.com/aws/aws-sdk-android/blob/master/Proguard.md#conclusion-and-additional-resources) section is well written!

**Comment by fosterzhang** [comment]
@filipedelimabrito I'll update it ASAP.

**Comment by filipedelimabrito** [comment]
Great @fosterzhang!  Thank you for your time!

**Comment by karthiksaligrama** [comment]
i updated the proguard to make it more sensible with android studio, i'll keep iterating on the content as an when required. Closing the ticket for now
