### ISSUE TITLE
NoClassDefFoundError on StandardCharsets for API 18 and below

### ISSUE THREAD

**Issue by adelpuva** [aws/aws-sdk-android#129]
Hi!
The documentation says that AWS SDK supports Android API 10+, but two classes (https://github.com/aws/aws-sdk-android/search?utf8=✓&q=StandardCharsets)  uses **StandardCharset** that is only available from 19 (http://developer.android.com/reference/java/nio/charset/StandardCharsets.html)

**Comment by danielesegato** [comment]
This:
`StandardCharsets.UTF_8`
should be replaced with:
`Charset.forName("UTF-8")`

**Comment by fosterzhang** [comment]
@adelpuva Thanks for reporting this. We are aware of this issue and have a fix for it (as pointed out by @danielesegato). Stay tuned for the next release.

**Comment by fosterzhang** [comment]
@adelpuva This is fixed in v2.2.16. For detailed changes, please refer to the [change log](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md).

**Comment by adelpuva** [comment]
Thank you!

**Comment by adelpuva** [comment]
In the last SDK (2.3.0) is also user **StandardCharsets** class in _CognitoUser.java_:

`srpAuthResponses.put("PASSWORD_CLAIM_SIGNATURE", new String(Base64.encode(hmac), StandardCharsets.UTF_8));`
