### ISSUE TITLE
Missing Documentation: Contribution Guide / Code style / Setup Environment

### ISSUE THREAD

**Issue by danielesegato** [aws/aws-sdk-android#131]
I did a small pull request today, before doing so I tried to look for a contribution documentation if there was any guideline I should follow or code style I should comply.

I also looked on how to setup the development environment.

Found nothing :)

I ended up just using Intellij Community Edition and being very careful to change the bare minimum in my commit.

Going specific, I'm talking about issue #129 where I did a pull request to replace StandardCharsets with Charset.forName().

I found there are two StringUtils class, one in the core:
https://github.com/aws/aws-sdk-android/blob/1109ddd52623f394ec290a35025946b0d2332a63/aws-android-sdk-core/src/main/java/com/amazonaws/util/StringUtils.java
one in mobile connectors:
https://github.com/aws/aws-sdk-android/blob/1109ddd52623f394ec290a35025946b0d2332a63/aws-android-sdk-cognito/src/main/java/com/amazonaws/mobileconnectors/cognito/internal/util/StringUtils.java

The core one contained a public constant (would have named it DEFAULT_CHARSET but.. well whatever):
`public static final Charset UTF8 = Charset.forName(DEFAULT_ENCODING);`

the mobileconnectors one had the same variable, but private, and contained utility static methods to do stuff on strings and UTF-8.

Before doing what I did I asked myself if I should have used the core constant or not, decided not to because you created the other class in the mobileconnectors package.
I also though about adding an utility method `utf8bytesArray(String)` in the mobileconnectors StringUtils class and use it instead.

I ended up just adding two constants in both those two classes and use them: minimum modification because I didn't know how you wanted it to be handled in your project. 

I think a contribution documentation would benefit the project in helping both contributors and internals to follow your guide lines and avoid code duplication like that.

**Comment by fosterzhang** [comment]
@danielesegato Thanks for bringing this up. We'll update README to include this.

**Comment by fosterzhang** [comment]
@danielesegato I added a section in README to briefly talk about how to setup development environment and some code standards.

**Comment by danielesegato** [comment]
@fosterzhang nice! thanks! Having that and code styles will surely help anyone who want to contribute.
I see you use Eclipse :-) hope you'll migrate to Android Studio at some point cause it makes Android development a lot smoother.

**Comment by fosterzhang** [comment]
@danielesegato I agree with you that Android Studio and Gradle is the trend. Please bare with us for now :).
