### ISSUE TITLE
Ability to use S3 presigned PUT url with TransferUtility?

### ISSUE THREAD

**Issue by snkashis** [aws/aws-sdk-android#134]
Is it possible, or are there any plans to allow usage of the S3 TransferUtility with presigned PUT urls?Basically bypassing the need for a credentials provider, and using the URL as the credential, and using the presigned keyname as the forced `OBJECT_KEY`.

**Comment by fosterzhang** [comment]
@snkashis TransferUtility doesn't support presigned url at the moment. What's your use case?

**Comment by snkashis** [comment]
basically bypassing cognito identity pools to provide direct to s3 uploads for our users. Our server is already generating these presigned URLs and we would to continue using them. I currently have this working with retrofit, but it sounds like  transfer utility(through your optimization work) could do it much faster.

**Comment by fosterzhang** [comment]
Adding support of presigned url to TransferUtility is possible. However, it doesn't provide you with the expected values. The advantages of TransferUtility over direct putObject (or presigned url) are:
- automatically upload large objects with multipart upload in parallel.
- support of pause and resume.
- better handling of network status changes.

TransferUtility requires credentials to initiate multipart upload, which is impossible with a presigned url. Without multipart upload, TransferUtility doesn't give you any speed boost over retrofit.

**Comment by snkashis** [comment]
Okay, understood. Does TransferUtility take advantage of S3 Transfer Acceleration if enabled on the bucket?

**Comment by fosterzhang** [comment]
@snkashis not yet, but we are working on it.

**Comment by snkashis** [comment]
Ok got it, thank you.

**Comment by AmitBarjatya** [comment]
@snkashis I have a similar use case. Is it possible for you to share a code snippet on how you are doing it with Retrofit? It'd be very helpful for me.

**Comment by zekapp** [comment]
> @snkashis I have a similar use case. Is it possible for you to share a code snippet on how you are doing it with Retrofit? It'd be very helpful for me.

I stumble upon a thread related uploading presignUrl in Stackoverflow. it might help in case of you missed it.

https://stackoverflow.com/questions/45991720/upload-a-file-to-aws-s3-pre-signed-url-using-retrofit2
