### ISSUE TITLE
TransferListener problems 

### ISSUE THREAD

**Issue by sandeshnaroju** [aws/aws-sdk-android#135]
I am facing problems in uploading files to amazon s3. To track the uploading file status I am using TransferListener in addition to transferUtility. Exact problem is onProgressChanged method is not at all getting called sometimes. And sometimes it is working fine. I observed that the problem is occurring when I am trying to upload larger files. So here is how I have tried.

CODE:

      ` @Override
        protected void onPostExecute(Void aVoid) {
              super.onPostExecute(aVoid);

        Log.d("ID VALUE",String.valueOf(this.ID));

        if(sS3Client!=null&&this.ID==-1){

            Log.d("ID","InItial setup");

            sTransferUtility = new TransferUtility(sS3Client, this.ctx);

            observer = sTransferUtility.upload(remotepath, file.getName(), file);

            observer.setTransferListener(new UploadListener(this.progressBar,observer,file.getPath()));
            observerlist.add(observer);
        }

    }`

and UploadListener:

`

            private class UploadListener implements TransferListener{

               private ProgressBar progress;
               private TransferObserver localobserver;

        private int value;
        private String file;
        private DBoperations DB;

        private ContentValues CV;

        private ContentValues CV2;

        private UploadListener(ProgressBar progressBar,TransferObserver observer,String file){
            this.progress=progressBar;
            this.localobserver=observer;
            this.file=file;
            DB = new DBoperations(getContext());
        }
        @Override
        public void onStateChanged(int i, TransferState transferState) {

            switch (transferState.toString()) {
                case "IN_PROGRESS":
                {
                    observerlist.add(this.localobserver);

                    CV = new ContentValues();
                    CV2= new ContentValues();

                    Log.d("FILE UPLOAD","IN_PROGRESS");
                    CV.put(DBconstants.TableConstants.F_FILE_STATUS, constants.UPLOADING);

                    DB.updateInformation(DB, DBconstants.TableConstants.TABLE_FILES, CV, DBconstants.TableConstants.F_LOCAL_PATH, this.file);

                    CV2.put(DBconstants.TableConstants.UPLOAD_ID, i);
                    DB.updateInformation(DB, DBconstants.TableConstants.TABLE_FILES, CV2, DBconstants.TableConstants.F_LOCAL_PATH, this.file);

                }
                break;
                case "COMPLETED":
                {
                    CV= new ContentValues();

                    Log.d("FILE UPLOAD","COMPLETED");
                    CV.put(DBconstants.TableConstants.F_FILE_STATUS, constants.UPLOADED);

                    DB.updateInformation(DB, DBconstants.TableConstants.TABLE_FILES,CV, DBconstants.TableConstants.F_LOCAL_PATH,this.file);

                }
                break;

            }
        }
        @Override
        public void onProgressChanged(int i, long l, long l1) {
            updator();
            progress.setIndeterminate(false);
            progress.setProgress(value);
            Log.d(String.valueOf(i),String.valueOf(value));
        }

        @Override
        public void onError(int i, Exception e) {

        }
        private void updator()
        {
            value = (int) ((double) localobserver.getBytesTransferred() * 100 / localobserver
                    .getBytesTotal());

        }
    }`

How to avoid this issue? I am using now 2.2.15 version, I have been facing this since the release of 2.2.13. What are the best practices to avoid this kind of issues?

**Comment by fosterzhang** [comment]
Per http://stackoverflow.com/questions/37235556/transferutility-in-aws-sdk, this is caused by slow connection.
