### ISSUE TITLE
When s3 delete an object and listObject, the file is stll in S3

### ISSUE THREAD

**Issue by yangxijun** [aws/aws-sdk-android#137]
Here is my step
1. deleteObject with the Key
2. listObject to show all the object

result:
the key is still in the S3 and also can download it, but after 30sec it is deleted.

Is there any method to know the time of the delete so that I can delete and list the right result

**Comment by fosterzhang** [comment]
Amazon S3 offers eventual consistency for deleteObjects per [Amazon S3 FAQs](https://aws.amazon.com/s3/faqs/).

> Q:  What data consistency model does Amazon S3 employ?
Amazon S3 buckets in all Regions provide read-after-write consistency for PUTS of new objects and eventual consistency for overwrite PUTS and DELETES. 

If deleteObjects is successful, then those objects will be deleted eventually. There is no promise when they will be removed from listObjects.
