### ISSUE TITLE
Multipart upload with TransferUtility results in corrupted zip file

### ISSUE THREAD

**Issue by nero-tang** [aws/aws-sdk-android#138]
I've encountered a strange issue where uploading a large zip file (> 5MB) with TransferUtility will result in a corrupted zip file on S3.

Here is my code sample:

```java
sTransferUtility.upload(bucket, key, file)
                            .setTransferListener(new TransferListener() {
                                @Override
                                public void onStateChanged(int id, TransferState state) {
                                    if (state == TransferState.COMPLETED) {
                                        subscriber.onNext(getResourceUrl(bucket, key));
                                        subscriber.onCompleted();
                                    }
                                }

                                @Override
                                public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                                    // DO NOTHING
                                }

                                @Override
                                public void onError(int id, Exception ex) {
                                    subscriber.onError(ex);
                                }
                            });
```

Then I downloaded the zip file from S3 and it cannot be unzipped, also the file size is smaller than the original file.

This happens every time when a zip is multipart uploaded, but I didn't try other types of file though

**Library Version**: 2.2.16

**Comment by fosterzhang** [comment]
@nero-tang I can't reproduce it. How do you verify the zip, from the console or on device?

**Comment by nero-tang** [comment]
@fosterzhang `getResourceUrl` returns the public download link for that file, for example https://s3.amazonaws.com/some_bucket/some_file.zip. I tried download the file from both console and device, they're all the same.

**Comment by fosterzhang** [comment]
@nero-tang Is the original zip corrupted? Have you try to upload other file types? How to reproduce the issue? What is your device information?

**Comment by nero-tang** [comment]
@fosterzhang never mind, I figured out the issue is because the upload starts before the zip file output stream gets closed properly, closing the issue.
