### ISSUE TITLE
Synchronize when User is deleted

### ISSUE THREAD

**Issue by adelpuva** [aws/aws-sdk-android#143]
Hi,

I'm doing some tests, and I noticed a strange behavior.

I'm logged in my app, and then I deleted user from **User Pool** and his data from **Identity Pool**, but when I call `Dataset.synchronize()` it always called `SyncCallback.onSuccess()`.

I tried also to change same attributes:
```
Dataset dataset = syncClient.openOrCreateDataset(Const.DATA_SET);
dataset.putAll(userAttributes);
dataset.synchronize()
```

And works fine! `SyncCallback.onSuccess()` is called! But on the AWS console there's not any user! I've deleted before!

Obviously, if I logout cannot con login, user is was deleted, and services response is: `ResourceNotFoundException`.

When I say log out I do this:
```
userPool.getCurrentUser().signOut();
provider.clear();
syncClient.openOrCreateDataset(Const.DATA_SET).delete();
syncClient.wipeData();
```
I'm using last SDK:
```
compile('com.amazonaws:aws-android-sdk-cognito:2.2.17') 
compile('com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.2.17') 
compile('com.amazonaws:aws-android-sdk-s3:2.2.17');
```

Thank you

**Comment by mreddyg** [comment]
Hi,

The temporary credentials issued by the Cognito Identity Pool, against the tokens issued from Cognito User Pool, are valid for one hour. While these credentials are valid (i.e. before they expire), they are use-able for all tasks that accept these credentials, including  sync operations. Deleting the user in the User Pool and the user data from the Identity Pool will stop the Identity Pool from issuing new credentials, but the credentials that were already issued continue to be valid until they expire. 

Thanks,
Mahesh

**Comment by adelpuva** [comment]
Thank you for reply
