### ISSUE TITLE
How to set the count of uploading tasks in the same time

### ISSUE THREAD

**Issue by jinguoliang** [aws/aws-sdk-android#144]
I found that only one task is uploading data, is that true? I wathed code of transferutility but I didn't find out the cause. May you give me some help？

the sdk version is v2.2.17

**Comment by wdane** [comment]
If you look at https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferThreadPool.java , the number of threads the Transfer Utility uses, and therefore the number of upload tasks that can run at the same time is equal to the # of processors + 1. 

Please feel free to re-open this issue if this doesn't answer your question.

**Comment by jinguoliang** [comment]
Thank you for your answer. I saw the  max size of the thread pool . But I found the count of the tasks in uploading is not fixed，Sorry for ask you is there any control in deep of sdk, or just beacause of the time of creating connection

**Comment by jinguoliang** [comment]
oh, I know, the thread pool limit the count of the PartTask，thank you again
