### ISSUE TITLE
IoT has prerelease dependency

### ISSUE THREAD

**Issue by mockturtl** [aws/aws-sdk-android#145]
Consuming projects will not build. 

As of 2.2.16, `aws-android-sdk-iot` [depends](https://github.com/aws/aws-sdk-android/blob/c36e6f6937d16a661087d8c3e879b43cbfc8097f/aws-android-sdk-iot/pom.xml#L36) on `org.eclipse.paho.client.mqttv3:1.0.3-SNAPSHOT`.

[@797c0df](https://github.com/aws/aws-sdk-android/commit/797c0df0b964afdc4ec89664b1805543928e34e4#diff-c7bef8ef8c1b5ec9a63f22826e5254b1L29) | [changelog](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-2216-05102016)

Workaround: consumers can use 2.2.15, or add the upstream Paho snapshot repo. ([example](https://github.com/awslabs/aws-sdk-android-samples/pull/57))

**Comment by mockturtl** [comment]
It looks to me like upstream development is moving to [eclipse/paho.mqtt.android](https://github.com/eclipse/paho.mqtt.android) (contrast, `paho.mqtt.java`).

@jpwsutton  Do I understand the split correctly?

**Comment by jpwsutton** [comment]
Hi, that's right, we've split out the Android service from the Java Repository. However the 1.0.3-SNAPSHOT will be promoted to our 1.1.0 release sometime in the next few days. Once that has happened, It will be available in Maven Central like the current 1.0.2 service (http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22org.eclipse.paho.android.service%22)

That will mean that you won't have to add the eclipse snapshots repo. Of course if you want to continue using our snapshot builds, then you will have to add it (Maven central doesn't host snapshots).

**Comment by mockturtl** [comment]
Thanks for the clarification!

**Comment by fosterzhang** [comment]
@mockturtl AWS SDK for Android v2.2.21 updates Paho MQTT client to 1.1.0. It may take up to a day before jCenter catching up with Maven central. Consumers can take the latest version without adding the snapshot repo.
