### ISSUE TITLE
TransferService - WiFi with no internet access

### ISSUE THREAD

**Issue by isaachunyu** [aws/aws-sdk-android#149]
Hi,

If the device is connected to WiFi, but it has no internet access (e.g. printer).
        @Override
        public void onReceive(Context context, Intent intent) {
            if (ConnectivityManager.CONNECTIVITY_ACTION.equals(intent.getAction())) {
                boolean networkConnected = isNetworkConnected();
                Log.d(TAG, "Network connected: " + networkConnected);
                handler.sendEmptyMessage(networkConnected ? MSG_CHECK : MSG_DISCONNECT);
            }
        }
The "networkConnected" is still returning true in this situation. Therefore, the UploadTask won't stop and it causes all the upload tasks failed with "No address associated with hostname" exception.

Thanks

**Comment by fosterzhang** [comment]
@isaachunyu That's an expected behavior. TransferUtility relies on system information. I believe this is the best it can get from the system. What do you recommend?

**Comment by isaachunyu** [comment]
If the device is connected to WiFi, can the library send a ping message to some URL (e.g. https://s3.amazonaws.com/)? If the response code is 200, then we know the WiFi has internet connectivity.

**Comment by fosterzhang** [comment]
@isaachunyu That proves the device has network at that moment. There is no guarantee it's still the case 10 seconds later, unless you ping a server consistently, but that causes battery consumption problem. There are better network detection methods, like one provided by you, but they have their shortcomings. The SDK takes the simplest approach, as recommended by Android. See [Determining and Monitoring the Connectivity Status](https://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html).
