### ISSUE TITLE
When we forcibly close the app or app crash,Transfer Observer state do not change

### ISSUE THREAD

**Issue by iit2009060** [aws/aws-sdk-android#150]
When we forcibly close the app or app crash,Transfer Observer state remain in_progress if it was currently in progress,and if we revisit the app,we wont able to decide based on this state(to resume or not).Ideally it should update the transfer state when app closes or crash. I tried on the sample also,and was easily  replicated the issue.
To reproduce,
1. Start the transfer 
2. Close the app 
3.Open the app,it will still show the state IN_PROGRESS and  will do nothing

One thing I observed transfer listener also sets to null when app closes,but state remain same in transfer observer

**Comment by fosterzhang** [comment]
@iit2009060 app crash can cause transfers in stale state. However when app restarts, TransferUtility will recover previously active transfers. You need to activate the transfer service by manipulating a transfer, say start a new transfer or resume a transfer. If you have nothing to do, you can simply resume a non existing transfer `TransferUtility.resume(0)`. Listeners will set to null unavoidably. You have to reattach them to transfer observers. Once you do that, transfer state will be updated accordingly.

**Comment by iit2009060** [comment]
So we have one scenario, we are running notification,which currently update the progress of data uploaded. But when app crashes or close, we still show that notification  in a in progress state , as we do not have any information how to update it,and when we reload the app , based on the status check we resume the transfer(on Failed only). This is created a bad experience for our app. Why cant we can update in transfer observer status as failed whenapp closes or crash.

**Comment by iit2009060** [comment]
Is the Transfer Service stops when app closes.

**Comment by fosterzhang** [comment]
@iit2009060 Yes, the service stops when app closes. You can't do anything once the app crashes.

**Comment by iit2009060** [comment]
is there a way for you to update the transfer state before app closes or crash. I observed listeners was set to null , if there is a getter function for listener we can use this as to identify stale states.

**Comment by fosterzhang** [comment]
@iit2009060 One can implement [`Thread.UncaughtExceptionHandler`](https://developer.android.com/reference/java/lang/Thread.UncaughtExceptionHandler.html) to do some work when app crashes. However I see no compelling reason of doing it in the SDK. I recommend you look into why the app crashes and fix it instead. There isn't a good way to identify stale transfers. You can pause them all and restart.

**Comment by iit2009060** [comment]
I am not asking when the app crash. I am asking when app was closed by the user or if the service starts but battery dies .

**Comment by fosterzhang** [comment]
@iit2009060 There isn't a good way to know when an app is force closed by user. If there is one, it should be implemented by the app but not the SDK. All it has to do is to stops the TransferUtility and update notifications.

**Comment by iit2009060** [comment]
But how the listeners sets on transfer observer becomes null when app closes ?

**Comment by iit2009060** [comment]
We do not even have a function that we can mark the state of transfer observer to be failed when app closes.SDK do not provide that facility. For putting this logic in app , we need to have a control of states on transfer observer.

**Comment by fosterzhang** [comment]
@iit2009060 You don't update transfer state directly. However you can control a transfer, say when app closes, you simply pause or cancel a transfer which is provided by TransferUtility.

Listeners are part of the app. When app stops, all resources including listeners are gone.

**Comment by iit2009060** [comment]
Why we cant handle on the service level , when it is destroyed,cancel all uploads that are in progress ?.Because its the background process, we do not have information about the app closes, the only information we have is onActivity closed. User can traverse the app while uploading is processed.

**Comment by iit2009060** [comment]
http://stackoverflow.com/questions/20392139/close-the-service-when-remove-the-app-via-swipe-in-android

**Comment by iit2009060** [comment]
I think you need to overridde on Task removed.

**Comment by fosterzhang** [comment]
@iit2009060 I am not going to continue the discussion. I don't see any issue or missing feature of TransferUtility. The problem you described can be and should be resolved in your app.

**Comment by iit2009060** [comment]
I have used your samples and found the same issue .I am trying on my end to find the solution,but somehow in my app I have to introduce the hack  where in each call to destroy view we are cancelling the transfers. Service knows better when it is destroyed and restarted. Thank you.
