### ISSUE TITLE
AmazonClientException I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by erikcaffrey** [aws/aws-sdk-android#152]
Some time ago I had this error reading other issue here I could understand the problem was about of permission righ now my application works fine but sometimes I get this exception on 
android 4.2.2.

https://github.com/aws/aws-sdk-android/issues/53

**Comment by fosterzhang** [comment]
@erikcaffrey connection reset by peer is usually caused by bad network.

**Comment by erikcaffrey** [comment]
I am not sure of that because when the error happened my wifi connection was fine but thank you I will catch the exception and it should be fix.

**Comment by Bajranghudda1** [comment]
@fosterzhang 
I am facing this same strange issue sometimes, file name is "Get Started with Dorp box.pdf". 
Its working fine if i select another file first and then i can easily pick this one too, but whenever i try to pick this file first i always get this issue, but the strange thing is after picking any other file I don't get any exception and easily can upload this file too.
Is there any help ?
