### ISSUE TITLE
Incorrect: behaviour: aws send "upload success" code when first chunk of resized video has been uploaded

### ISSUE THREAD

**Issue by Gelassen** [aws/aws-sdk-android#154]
Hello, 

An year ago, I wrote an android client which sends media data to our AWS and our server. It works well. 
Now I have a new requirements to add some media pre-processing before upload, e.g. watermarking, video scaling etc. Here I faced with issue when upload resized video (via ffmpeg) to amazon. 

Steps to reproduce:
1. Resize the video via ffmpeg
2. Upload video via aws sdk in the amazon bucket

Expected behaviour:
Client sends video by by parts of 40kb, for each part client receives ProgressEvent with amount of uploaded data. When uploaded bytes amount becomes equal video bytes amount, client receives ProgressEvent.COMPLETED_EVENT_CODE

Observed behaviour:
Client send video by parts ~40kb. When first part uploaded it to the aws, client receives ProgressEvent.COMPLETED_EVENT_CODE. By link on video in the bucket the static image with 1-2 seconds of voice from the video. 

I check does it bug in my code or not by turning off scaling functional and upload original video -- video was uploaded successfully. Scaled video also was checked -- it is fine. Conclusion, something unobvious happens on AWS due upload scaled video by ffmpeg.

Could you please take a look what goes wrong with it? 

Command to create scaled video:
-y -i /storage/emulated/0/Android/data/<app package>/files/Pictures/.nomedia/mh/mh_VID_20160613_1839061133299835.mp4 -vf scale=640:-1 -r 15 -ab 12288 -vcodec mpeg4 -preset ultrafast -b 2097152 /storage/emulated/0/Android/data/<app package>/files/Pictures/.nomedia/mh/mh_VID_20160613_1839061133299835.mp4

**Comment by fosterzhang** [comment]
@Gelassen Would you please provide code snippet to reproduce the problem? If full size video can be uploaded correctly, I see no reason why the scaled video would fail. I suggest you check your code that does resizing.

**Comment by Gelassen** [comment]
I have double checked and confirm you are right (I scaled the video on PC and uploaded it via phone). It is an issue somewhere in my code which I should find
