### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Unknown URI: content://com.example/transfers/-1

### ISSUE THREAD

**Issue by sibelius** [aws/aws-sdk-android#162]
```jsx
Fatal Exception: java.lang.IllegalArgumentException: Unknown URI: content://com.example/transfers/-1
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBBase.query(TransferDBBase.java:149)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.queryTransferById(TransferDBUtil.java:431)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById(TransferDBUtil.java:695)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.execCommand(TransferService.java:280)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$UpdateHandler.handleMessage(TransferService.java:220)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by fosterzhang** [comment]
@sibelius do you mind sharing how to reproduce it?

**Comment by sibelius** [comment]
I think this happened because the device have no memory available

or because I try to update a file, then the device lose connection and this file is erased from the disk

**Comment by fosterzhang** [comment]
@sibelius I doubt what you described are the cause. You probably pass -1 to transfer utility.

**Comment by sibelius** [comment]
```java
File folder = new File(folderName);
File[] media = folder.listFiles(new FilenameFilter() {
            @Override
            public boolean accept(File file, String filename) {
                return filename.endsWith(".mp3") || filename.endsWith(".jpg");
            }
});
for (int i = 0; i < media.length; i++) {
   TransferObserver observer = transferUtility.upload(S3.BUCKET_NAME, media[i].getName(), media[i]);
}
```

**Comment by fosterzhang** [comment]
@sibelius Thanks for the code. I don't see anything wrong with it. Does the error happen frequently?

**Comment by sibelius** [comment]
No, it was just one time

Closing as it haven't happened anymore

Tks

**Comment by nagendraksrivastava** [comment]
dfwefwed

**Comment by dtvc** [comment]
13 of my users had the same problem during the last month. I personally never had it, so I don't know how to reproduce it. From the reports I can see that trim was called in half of the cases. I release all my broadcastreceivers on low memory and log it into crashlytics, that's why I can see ontrimmemory was called in half of the cases. Is there any way to catch this exception to show an error message?

**Comment by kwatra** [comment]
We had the same issue with one user. Looking at the TransferUtility code this could happen when the device is low on storage, or for some other reason SQLiteDatabase.insert() fails.

TransferUtility.[download()](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L130) or upload() try to insert a transfer record via:
```
dbUtil.insertSingleTransferRecord()
```
which eventually write to the underlying SQLiteDB via SQLiteDatabase.insert(). This call can return -1 as the row ID on failure, which is saved in the URI path leading to a URI of form (see [link](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferDBBase.java#L111)):

content://com.example/transfers/-1

**Comment by daxh** [comment]
Exactly the same situation. How to fix it ?
