### ISSUE TITLE
Amazon S3 Transfer Acceleration" - Timeplan?

### ISSUE THREAD

**Issue by 24ark** [aws/aws-sdk-android#163]
The "Amazon S3 Transfer Acceleration" was announced yesterday and it's really an important feature that I could make use of in my production android app:
https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions/

There are already examples of how to use this in other languages, but the android SDK doesn't seem to support it yet:
http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration-examples.html#transfer-acceleration-examples-sdks

Has it been planned when this feature should be added to the android SDK?

**Comment by fosterzhang** [comment]
S3 acceleration has been added to v2.2.17 release. See [release notes](http://aws.amazon.com/releasenotes/Android/5606404750751710).
