### ISSUE TITLE
TransferListener onProgressChanged reporting more bytesCurrent than bytesTotal.

### ISSUE THREAD

**Issue by nitingrov86** [aws/aws-sdk-android#167]
Check the logs for a particular file, this is showing up in TransferListener onProgressChange callback.

07-05 14:09:05.415 D/Upload Status: file id: 17, bytesCurrent: 0, bytesTotal: 1229654, percent: 0, total: 25728163
07-05 14:10:05.090 D/Upload Status: file id: 17, bytesCurrent: 458752, bytesTotal: 1229654, percent: 97, total: 25728163
07-05 14:10:06.282 D/Upload Status: file id: 17, bytesCurrent: 1671168, bytesTotal: 1229654, percent: 101, total: 25728163
07-05 14:10:07.241 D/Upload Status: file id: 17, bytesCurrent: 1229654, bytesTotal: 1229654, percent: 100, total: 25728163
Is this the known issue with sdk v2.2.16? Please let me know as it is creating a bad User Experience by making the percentage to go above 100%.

**Comment by fosterzhang** [comment]
@nitingrov86 This is fixed in v2.2.19. See [releasenotes](http://aws.amazon.com/releasenotes/Android/2688202614988726).

**Comment by nitingrov86** [comment]
thanks @fosterzhang
