### ISSUE TITLE
File failing after receiving full bytesCurrent same as bytesTotal

### ISSUE THREAD

**Issue by nitingrov86** [aws/aws-sdk-android#168]
Below logs are generated in onProgressChanged. For file 86 last recorded bytesCurrent are same as bytesTotal and then there is a timeout error for that file which causes a failure in upload.
D/Upload  Status: file id: 86, bytesCurrent: 1425408, bytesTotal: 1425817, total: 49959142
D/Upload Status: file id: 84, bytesCurrent: 1482752, bytesTotal: 1482890, total: 49959142
D/Upload Status: file id: 84, bytesCurrent: 1482890, bytesTotal: 1482890, total: 49959142
D/Upload Status: file id: 86, bytesCurrent: 1425817, bytesTotal: 1425817, total: 49959142
D/Upload Status: file id: 89, bytesCurrent: 1638400, bytesTotal: 1644224, total: 49959142
D/Upload Status: file id: 89, bytesCurrent: 1644224, bytesTotal: 1644224, total: 49959142

(AWS generated logs)
E/UploadTask: Failed to upload: 87 due to Unable to execute HTTP request: timeout
E/UploadTask: Failed to upload: 86 due to Unable to execute HTTP request: timeout
E/UploadTask: Failed to upload: 89 due to Unable to execute HTTP request: timeout

Log recorded in onStateChange on "FAILED" state.
D/Upload Status: Upload Failed for file: 86

As state change FAILED is coming after onProgressChange, it doesn't helps in creating a good user experience as progress goes to 100% on UI and then it fails. I am trying to create retries within my app which restarts the upload process of failed files so if some files are failing then the progress shouldnt reach 100%. Is there any way to handle it differently? Or this is the order in which current SDK 2.2.20 works. Please let me know.

**Comment by fosterzhang** [comment]
@nitingrov86 Is there a reliable way to reproduce the issue?

**Comment by nitingrov86** [comment]
@fosterzhang One way to reproduce it is to set socket timeout in ClientConfiguration to 1 sec. you will be able to see that onPreogressChange will be called for a particular file until bytesCurrent equals bytesTotal and then onStateChange is called to notify for the FAILED state.
Also, Nexus 5x for some reason with default timeout (15 sec.) does that most of the times without making any changes in ClientConfiguration. I hope this will help to recreate the issue. Please let me know if you have any questions.

**Comment by fosterzhang** [comment]
@nitingrov86 Thanks for the information. I'll get back to you ASAP.

**Comment by fosterzhang** [comment]
@nitingrov86 The progress is updated when data is written to the socket (buffered). It's possible that data fails to transfer over the wire due to socket timeout. Thus you see failure even if the progress shows completed. If this happens often, I suggest you increase socket timeout. We may revisit how progress is reported, but more likely we aren't going to change the behavior. Hope this explains.

**Comment by nitingrov86** [comment]
@fosterzhang thanks for your reply
