### ISSUE TITLE
About isRecoverable method of KinesisStreamRecordSender

### ISSUE THREAD

**Issue by JMASystems** [aws/aws-sdk-android#169]
The [isRecoverable] method of KinesisStreamRecordSender return true when state is in [InternalFailure,ServiceUnavailable,Throttling,ProvisionedThroughputExceededException].

Our application uses sts token vending machine(TVM).
When our tvm was stop state in trouble,all kinesis records in that term were losts.
This is caused by TokenExpireException.

It seems that recoverable states in [isRecoverable] methods is too few to a variety of situation.
So can you provide the way to override(or pluggable) [isRecoverable] methods to extends recoverable situations?

**Comment by fosterzhang** [comment]
@JMASystems In theory TokenExpiredException should be handled by AWS credentials provider and not propagate to Kinesis recorder. Of course overriding isRecoverable would be a nice feature. We'll evaluate it.

**Comment by deejvince** [comment]
+1 on that, We also experience the same behaviour. when the Cognito call gets throttled, we lose the records in the Kinesis client. it causes a very painful impact on our production stream.

Lior

**Comment by deejvince** [comment]
Bump?

**Comment by kvasukib** [comment]
Hi @deejvince, The [KinesisRecords.KinesisRecorder](https://github.com/aws/aws-sdk-android/blob/8d91ac8014c3b2643fd92560f890c58d11fbe069/aws-android-sdk-kinesis/src/main/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisRecorder.java#L170) constructor takes in a KinesisStreamRecordSender. So you can write your own RecordSender by implementing the RecordSender interface and create KinesisRecords based on your implementation of RecordSender.

Have you tried this? Does this work for you?

**Comment by minbi** [comment]
The `DeadLetterListener` is also available to recover records that will be eliminated from the local database.
