### ISSUE TITLE
AWS Android SDK  'java.lang.IllegalArgumentException' exception. Cannot evaluate $Proxy2.toString()

### ISSUE THREAD

**Issue by mariavalavan** [aws/aws-sdk-android#171]
I am getting error
Method threw 'java.lang.IllegalArgumentException' exception. Cannot evaluate $Proxy2.toString()

ApiClientFactory factory = new ApiClientFactory();final MytestClient client = factory.build(MytestClient.class);

I tried within asnyc also. It is not helping.

new AsyncTask<Void, Void, Void>() {
        @Override
        protected Void doInBackground(Void... params) {            
            ApiClientFactory factory = new ApiClientFactory();
            final MytestClient client = factory.build(MytestClient.class);           
            return null;
        }
    }.execute()

my generated code show as
aws-android-sdk-core-2.2.20

**Comment by fosterzhang** [comment]
@mariavalavan Are you in debug mode? `MytestClient` is a dynamically proxied object. It doesn't have toString() method defined. It should run fine in release mode.

**Comment by wdane** [comment]
Assuming resolved, feel free to re-open if issue comes up again.

**Comment by alokkumargupta** [comment]
I am also facing similar issue, not able to find soloution yet. Using below aws sdk api lib -
