### ISSUE TITLE
Multiple parallel downloads using TransferUtility hanging UI thread

### ISSUE THREAD

**Issue by ckarthikv** [aws/aws-sdk-android#172]
We had a use case in which we were trying to download multiple parallel files (around 20 parallel downloads of jpg files) with a transfer listener for each object being downloaded.

The UI thread was hanging badly with just a few parallel downloads.

The normal nomenclature of transferutility.download(bucket, key, file) is being used for each download object. Since the download function returns instantly, all these functions have been written in the main UI thread - Callbacks of the transfer listener have no operations other than printing a log.

Please advise. Thanks.

**Comment by fosterzhang** [comment]
@ckarthikv See https://github.com/awslabs/aws-sdk-android-samples/issues/68. Closing this.
