### ISSUE TITLE
File waiting around 15-20 minutes to update progress after first bytesCurrent are received for same file.

### ISSUE THREAD

**Issue by nitingrov86** [aws/aws-sdk-android#176]
I tried to upload multiple files. The observation was that one of the file started uploading and returned bytesCurrent equals to 0 but then it waited for 17 minutes to receive another update. Meanwhile other files were uploaded but the whole progress got stuck at 98% for around 10 minutes and then went onto 100% which doesn't makes a very good user experience. Check the below logs in which file with id 316 waited for 17 mins. I have noticed this issue intermittently but it does comes up and freezes the whole upload process.

Questions:
1. Is there a way if the whole upload process doesn't receive any progress updates for certain duration it times out and triggers reupload or something like that?
2. Is this a known issue?

07-21 17:52:57.001 21078-21078/ D/Upload Status: file id: 316, bytesCurrent: 0 percent: 48
07-21 17:58:20.691 21078-D/Upload Status: file id: 372, bytesCurrent: 6543340 percent: 96
07-21 17:58:20.761 21078-/D/Upload Status: file id: 375, bytesCurrent: 15409152 percent: 96
07-21 17:58:22.191 21078-/D/Upload Status: file id: 375, bytesCurrent: 15867904 percent: 96
07-21 17:58:23.741 21078-/D/Upload Status: file id: 375, bytesCurrent: 16539648 percent: 96
07-21 17:58:26.801 21078-/D/Upload Status: file id: 375, bytesCurrent: 16801792 percent: 96
07-21 17:58:28.341 21078-/D/Upload Status: file id: 375, bytesCurrent: 17262307 percent: 97
07-21 17:58:29.581 21078-/D/Upload Status: file id: 375, bytesCurrent: 17983203 percent: 97
07-21 17:58:31.401 21078-/D/Upload Status: file id: 375, bytesCurrent: 18900707 percent: 97
07-21 17:58:32.441 21078-/ D/Upload Status: file id: 375, bytesCurrent: 19359459 percent: 97
07-21 17:58:33.641 21078-/D/Upload Status: file id: 375, bytesCurrent: 20014819 percent: 98
07-21 17:58:34.841 21078-/D/Upload Status: file id: 375, bytesCurrent: 20604643 percent: 98
07-21 17:58:37.881 21078-21078/D/Upload Status: Upload transfer state: COMPLETED
07-21 17:58:37.881 21078-21078/D/Upload Status: Upload completed for file: 375

07-21 18:09:07.441 21078-21078/ D/Upload Status: file id: 316, bytesCurrent: 0 percent: 98
07-21 18:09:08.851 21078-21078/D/Upload Status: file id: 316, bytesCurrent: 663552 percent: 98
07-21 18:09:09.851 21078-21078/D/Upload Status: file id: 316, bytesCurrent: 1122304 percent: 98
07-21 18:09:10.871 21078-21078/D/Upload Status: file id: 316, bytesCurrent: 1581056 percent: 98
07-21 18:09:11.891 21078-21078/D/Upload Status: file id: 316, bytesCurrent: 2039808 percent: 98
07-21 18:09:12.911 21078-21078/D/Upload Status: file id: 316, bytesCurrent: 2498560 percent: 99
07-21 18:09:14.421 21078-21078/D/Upload Status: file id: 316, bytesCurrent: 3219456 percent: 99
07-21 18:09:15.511 21078-21078/D/Upload Status: file id: 316, bytesCurrent: 3678208 percent: 99
07-21 18:09:16.561 21078-21078/D/Upload Status: file id: 316, bytesCurrent: 4136960 percent: 99
07-21 18:09:18.041 21078-21078/D/Upload Status: file id: 316, bytesCurrent: 4792320 percent: 99

**Comment by wdane** [comment]
This is not a known issue. A few questions.

Is the percent you're showing the percentage of all files? If you are uploading a large number of files, or multiple large files the Transfer Utility will at most use

Runtime.getRuntime().availableProcessors() +1 threads for multi-part part uploads (multi-part upload will be used for anything over 5MB), and separately 
Runtime.getRuntime().availableProcessors() +1 threads for mixtures of downloads and 1 shot uploads (anything under 5MB)

So it's possible if you are uploading a large number of files, or files that are large that there is no available threads when it's submitted, or that it get's a thread but for whatever reason it's not getting CPU time until the threads are finished uploading.

What kind of connection does this happen on? It looks like you might be uploading a large # of files that are on the large side.

**Comment by nitingrov86** [comment]
@wdane Thanks for your reply.
Yes, the percent I am showing is the total percentage and I am trying to upload large number of files with each file <= ~5MB and video file ranging between 20MB - 30MB in size. I have also seen this issue for less number of files.

The connection I used was WiFi & 4G. Any other suggestions as why I am seeing this behavior which might be helpful to further investigate this?

**Comment by wdane** [comment]
@nitingrov86  Sorry about the problems you're having. If you look at https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferThreadPool.java you will see the way we determine threads.

One thing to try would be to only upload Runtime.getRuntime().availableProcessors() +1 files at a time, and trigger uploading another file when another one finishes. My guess is that there's a lot of thread contention.

It looks like you could use Runtime.getRuntime().availableProcessors() +1  threads for your <= 5MB items and a separate count of Runtime.getRuntime().availableProcessors() +1  threads for your video files and they should all work at the time time.  I understand that doing it this way means they won't trigger later on in the background, but if you spin up a service to keep triggering them it should work fine.  I would at least try this as it would be simply to implement, give a path forward, and determine if thread contention is actually the issue.

**Comment by wdane** [comment]
Closing for now, adding some internal notes that we should look at how Transfer Utility handles threading with respect to large numbers of uploads

**Comment by kvasukib** [comment]
We have added support for TransferUtilityOptions starting 2.6.16. Documentation: https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#native-transfer-utility-options

TransferUtilityOptions options = new TransferUtilityOptions();
options.setTransferThreadPoolSize(8);

TransferUtility transferUtility = TransferUtility.builder()
    // Pass-in S3Client, Context, AWSConfiguration/DefaultBucket Name
    .transferUtilityOptions(options)
    .build();

You can configure the size of the thread pool. By default, the thread pool is of size N + 1, where N is the number of available processors. Minimum: we support 2 threads and dedicate 1 thread for orchestrating the multipart transfer.
