### ISSUE TITLE
Passing an array is not getting to the lambda function

### ISSUE THREAD

**Issue by justdan0227** [aws/aws-sdk-android#180]
We have a default Generated SDK that did not use models in the Gateway console.  With that I've had to hand code the generated SDK to work and we have been 90% sucessfull so far passing simple string and getting back objects that the factory correctly decodes to the class pased.

However we have a function that requires an Array, and I've tried passing it as an ArrayList and as an [] array and the host still reports that the body has the model array name, not the actual array.  I have the declaration as follows:  Am I missing something on the way it should be defined?

I've tried both ways and the server still says the "media object" is blank.

```
@com.amazonaws.mobileconnectors.apigateway.annotation.Operation(path = "/drips/{dripid}/media", method = "POST")
Empty dripsDripidMediaPost(
        @com.amazonaws.mobileconnectors.apigateway.annotation.Parameter(name = "dripid", location = "path") String dripid,
        @com.amazonaws.mobileconnectors.apigateway.annotation.Parameter(name = "media", location = "query") JSONArray media);

@com.amazonaws.mobileconnectors.apigateway.annotation.Operation(path = "/drips/{dripid}/media", method = "POST")
Empty dripsDripidMediaPost(
        @com.amazonaws.mobileconnectors.apigateway.annotation.Parameter(name = "dripid", location = "path") String dripid,
        @com.amazonaws.mobileconnectors.apigateway.annotation.Parameter(name = "media", location = "query") MediaObject media[]);
```

**Comment by fosterzhang** [comment]
@justdan0227 The generated client can't handle array in query. Please use List. We'll put this as a feature request.

**Comment by justdan0227** [comment]
Oh really?  That's why I can't find the magic.  The iOS guys have it but I can't get it to work Android.  Are you telling me that I'll need to wait for AWS to add that support?

**Comment by fosterzhang** [comment]
@justdan0227 Just curious, is media a query parameter? How do you want to serialize a list of objects as query parameter?

**Comment by justdan0227** [comment]
well the media is an array of media update objects each with 3 String iVar's. When an endpoint returns and object or array, I simply have a class with public ivars and the AWS Factory appears to put everything in place.  However passing an Array of objects, I'm not sure of the declaration to get the serialization to happen

**Comment by fosterzhang** [comment]
@justdan0227 Two requirements:
- Taking an array as a query param. This is probably a non requirement, because the generated client would never have array unless modified by customer.
- Taking a complex object as query param. This is possible. I personally recommend it go to the body. If this is not an option for the server, then use API Gateway's mapping template to transform the request.
