### ISSUE TITLE
Infinite Loop in AbstractKinesisRecorder.nextBatch(..)

### ISSUE THREAD

**Issue by markrebhan** [aws/aws-sdk-android#182]
I found this loop after my Kinesis cache file was corrupted after my application stopped unexpectedly (crash or shut down). The next time I called KinesisFirehoseRecorder.submitAllRecords(), it get stuck in this infinite loop where it calls iterator.peek(), tries to parse the data, catches an exception, calls continue, calls iterator.peek(), etc. 

```
while (iterator.hasNext() && count < maxCount && size < maxSize) {
        String line = iterator.peek();
        if (line == null || line.isEmpty()) {
            continue;
        }
        // parse a line. Skip in case of corrupted data
        try {
            frp.parse(line);
        } catch (Exception e) {
            Log.w(TAG, "Failed to read line. Skip.", e);
            continue;
        }...
```

**Comment by wdane** [comment]
Interesting. And is it the .peek() call for the frp.parse(line) that is giving you the exception. Can  you post the stack trace?

Thanks,
Weston

**Comment by markrebhan** [comment]
W/AbstractKinesisRecorder: Failed to read line. Skip.
	 java.lang.IllegalArgumentException: Input is expected to be encoded in multiple of 4 bytes but found: 381
     at com.amazonaws.util.Base64Codec.decode(Base64Codec.java:197)
	 at com.amazonaws.util.Base64.decode(Base64.java:54)
	 at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileRecordParser.parse(FileRecordParser.java:45)
	 at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.nextBatch(AbstractKinesisRecorder.java:204)
	 at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.submitAllRecords(AbstractKinesisRecorder.java:125)
	 
	 ... times infinity

**Comment by markrebhan** [comment]
My current workaround is to call `KenisisFirehoseRecorder.deleteAllRecords()` on startup to wipe out that cache file

**Comment by minbi** [comment]
AWS Mobile SDK for Android version 2.6.4 has been released
