### ISSUE TITLE
Video not uploading while thumbnail is visible

### ISSUE THREAD

**Issue by arushijain45** [aws/aws-sdk-android#183]
I am trying to upload video and its thumbnail using aws s3. For this I am starting S3 upload operation and checking percentage of bytes transferred using upload.getProgress().getPercentTransferred(). When this value gives me 100 I upload its thumbnail. But what I got is only thumbnail being seen and videoUrl shows following error message:

`<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>69893043F20A7E53</RequestId><HostId>7JdaUYy8BuekoA7UP7+JsXSTMmnhqnd7LLM9lDxd0UbTpDZ2Ty9r6j0Aj2ZoY028Fv1WK1/cTiw=</HostId></Error>`

**Comment by wdane** [comment]
Just to clarify. The video is successfully uploaded to S3, and you can see it in the S3 console? But when you try and view it you get access denied?

If that's the case, check the permissions you have set on the object/bucket. This means that the however you are viewing it doesn't have permissions to see the bucket/object. How are you getting the object?

**Comment by arushijain45** [comment]
No, Video is not uploaded to S3 and I cannot see it in the console.

I have given all the required permissions as in 50% of cases, video get uploaded and I can view them but in rest of the cases video dont uploads and i get access denied error as shown above.

**Comment by wdane** [comment]
So sometimes the video works and sometimes the thumbnail works? Or only one of them work? The bucket might have different permissions if you are putting the objects in different paths of the bucket.

For instance /video/NAME could have permissions, but /thumbnail/NAME might not.

**Comment by wdane** [comment]
No response in a month, closing for now. Feel free to re-open if there are still problems.
