### ISSUE TITLE
Update changelog to version 2.3

### ISSUE THREAD

**Issue by yairkukielka** [aws/aws-sdk-android#185]
It would be great to know what changed. Thank you!

**Comment by karthiksaligrama** [comment]
@yairkukielka i apologize we will get this updated. In the mean time you can checkout the [release notes](https://aws.amazon.com/releasenotes/Android/1297525192759238)

**Comment by mockturtl** [comment]
Fixed.

https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-231-09082016

https://aws.amazon.com/releasenotes/Android
