### ISSUE TITLE
support for http2

### ISSUE THREAD

**Issue by yairkukielka** [aws/aws-sdk-android#187]
Hi,

would it be possible to support http2 within this sdk? 
Thank you!

**Comment by wdane** [comment]
Hi Yarikukeilka,

Currently the best way to use an http2 connection would be the same as your previous question about using OkHttp (https://github.com/aws/aws-sdk-android/issues/184). It looks like OkHttp supports Http2. There are currently no plans to natively support http2 in the SDK, but of course customer requests like this greatly influence our feature development.
