### ISSUE TITLE
NoClassDefFoundError on StandardCharsets for API 18 and below

### ISSUE THREAD

**Issue by adelpuva** [aws/aws-sdk-android#190]
[Re-Open an issue like https://github.com/aws/aws-sdk-android/issues/129.]

The documentation says that AWS SDK supports Android API 10+, but two classes (https://github.com/aws/aws-sdk-android/search?utf8=✓&q=StandardCharsets) uses **StandardCharset** that is only available from 19 (http://developer.android.com/reference/java/nio/charset/StandardCharsets.html)

The solution is replace _StandardCharsets.UTF_8_ with _Charset.forName("UTF-8")_.

Thank you

**Comment by karthiksaligrama** [comment]
Fixed with 2.3.1
