### ISSUE TITLE
Amazon s3 file upload, authorization mechanism exception signature v4

### ISSUE THREAD

**Issue by vaibhavbarmy** [aws/aws-sdk-android#192]
Failed to upload: 4 due to The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 6955447DF1849092)

I made a new amazon s3 bucket region mumbai (AP_SOUTH_1) today.
Can anybody guide me on how to resolve this issue?
As far as I know all the newly made regions since 2014 doesn't support v2 signature authorization?
Does aws-android-sdk comes with support for v4

**Comment by karthiksaligrama** [comment]
v4 is supported by default in regions which support v4 only. Are you still getting this problem?

**Comment by vaibhavbarmy** [comment]
No, I moved my s3 bucket to US region back then when I wasn't able to resolve the issue. The US bucket works fine with same code. I am not sure sure about Mumbai region yet.

**Comment by Shahgupta** [comment]
This issue is still there. It seems like android SDK doesn't support V4 by default. @karthiksaligrama can you help me specify signature version(V4) in request authentication in android SDK?

**Comment by karthiksaligrama** [comment]
@vaibhavbarmy  @Shahgupta i created a test bucket in AP_SOUTH_1 region and i was able to upload and download data from it using default configuration. Here is the code.


```
S3 = new AmazonS3Client(credentials);
S3.setRegion(Region.getRegion(Regions.AP_SOUTH_1));
S3.createBucket(BUCKET_NAME);

final long contentLength = 128 * 1024;
final File file = getRandomTempFile(KEY, contentLength);
S3.putObject(BUCKET, KEY, file);
final GetObjectRequest req = new GetObjectRequest(BUCKET, KEY);
final File output = new File("output");
output.deleteOnExit();
final S3Object obj = S3.getObject(req);
assertNotNull(obj);
assertFileEqualsStream(file, obj.getObjectContent());
obj.getObjectContent().close();

```

**Comment by Shahgupta** [comment]
@karthiksaligrama Actually I found it later that the issue is with aws cognito, I believe cognito doesn't support V4 as of now. And since Mumbai region only supports V4 we are unable to upload to S3. With the same code it's working in Singapore region and US west region.

**Comment by karthiksaligrama** [comment]
Cognito identity supports only V4.

**Comment by Shahgupta** [comment]
A month ago I tried to upload images to S3(Mumbai) through cognito but I got this exception:
**Failed to upload: 1 due to The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.**

So I moved my bucket to Singapore region. I have also tried US West (Oregon) that time and it was also working fine.

**Comment by love8587** [comment]
It was so strange and tricky for me. 
I struggled with this problem and I was trying many times to resolve it.
It suddenly worked so I made new bucket but it didn't work. because I had done nothing except changing code, I just waited for hours. Finally, it worked well although I did nothing.

**Comment by love8587** [comment]
I also changed bucket to resolve this problem. in my case, I changed the bucket from ap-northeast-2(Seoul) to ap-northeast-1(Tokyo).

**Comment by devxpy** [comment]
An entry in the `awsconfiguration.json` file will let you avoid changing the region in code - 

```
   "AmazonS3Client": {
        "Default": {
            "Bucket": "mybucket",
            "Region": "ap-south-1"
        }
    }
```

**Comment by kvasukib** [comment]
@devxpy Just a correction in the snippet:

```
"S3TransferUtility": {
        "Default": {
            "Bucket": "mybucket",
            "Region": "ap-south-1"
        }
    }
```

**Comment by devxpy** [comment]
@kvasukib I gues both are valid. If you are directly using `AmazonS3Client`, then this won't work :)

**Comment by kvasukib** [comment]
@devxpy Thankyou for your response. Currently `AmazonS3Client` doesn't support `awsconfiguration.json`. Only the `TransferUtility` supports `awsconfiguration.json`.

**Comment by devxpy** [comment]
@kvasukib Sorry! I just noticed that I forgot to remove the line from code, and yes I can confirm the same. 

Should I create a new issue?

**Comment by devxpy** [comment]
For now, I guess the hack would be to just - 

```kotlin
AWSMobileClient.getInstance().configuration.let {
    try {
        val defaultConfig = it.optJsonObject("S3TransferUtility")
        region = Region.getRegion(defaultConfig.getString("Region"))
        bucket = defaultConfig.getString("Bucket")
    } catch (e: Exception) {
        throw IllegalArgumentException("Failed to read S3TransferUtility " + "please check your setup or awsconfiguration.json file", e)
    }
}
```
