### ISSUE TITLE
AmazonServiceException  on pushing message to sqs with non-empty message attributes

### ISSUE THREAD

**Issue by kunalseedoc** [aws/aws-sdk-android#193]
"com.amazonaws.AmazonServiceException: The request must contain non-empty message attribute name. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 5417e05b-1bff-515c-9443-b01c0d89d26a)"

works fine if no message attribute is provided

**Comment by karthiksaligrama** [comment]
this is fixed with 2.3.6
