### ISSUE TITLE
Race condition in TransferService

### ISSUE THREAD

**Issue by staalezh** [aws/aws-sdk-android#197]
I found a race condition in TransferService when using different AmazonS3-client objects. TransferService has an AmazonS3-member which is assigned to in onStartCommand, and is used in execCommand to initiate a transfer:

`transfer.start(s3, dbUtil, updater, networkInfoReceiver);`

If two transfers are initiated around the same time, onStartCommand may be invoked twice before execCommand is invoked for the first time, and TransferRecord will use the wrong AmazonS3 client. 

In my case I had sub-classed AmazonS3Client to use SSE with S3, and as a result, the wrong encryption key was used in the transfer when the race condition kicked in.

**Comment by karthiksaligrama** [comment]
Thanks will fix this in next release

**Comment by karthiksaligrama** [comment]
Fixed with 2.3.8
