### ISSUE TITLE
Android 7.0 TransferState always WAITING

### ISSUE THREAD

**Issue by TOMKHAN** [aws/aws-sdk-android#199]
Hi.

I'm submitting two pictures one by one. First one always goes through, but the second one always get stuck (after some retries, it gets through somehow!?). 

First image is thumb and is being sent like this:
```
        File thumbFile = new File(thumbImagePath);
        TransferObserver obsThumb = transferUtility.upload(
                s3BucketNameForPhotos,
                "T" + imageId + ".jpg",
                thumbFile, new ObjectMetadata());
        obsThumb.setTransferListener(new UploadListener());
        i += simulateWaitForCompletion(obsThumb);
```

Second image is original picture and is being sent like this:
```
        TransferUtility newtransferUtility = getTransferUtility(context);
        TransferObserver obsOriginalPicture = newtransferUtility.upload(
                s3BucketNameForPhotos,
                imageId + ".jpg",
                file, new ObjectMetadata());
        obsOriginalPicture.setTransferListener(new UploadListenerForBigPicture()); 
        i += simulateWaitForCompletion(obsOriginalPicture);
```

Implementation of simulateWaitForCompletion method is (as suggested in this issue -> https://github.com/aws/aws-sdk-android/issues/91):
```
private int simulateWaitForCompletion(TransferObserver observer) {
        while (true) {
            if (TransferState.COMPLETED.equals(observer.getState())
                    || TransferState.FAILED.equals(observer.getState())) {
                if (TransferState.COMPLETED.equals(observer.getState())) {
                    return 0;
                } else {
                    return 1;
                }
            }
        }
    }
```

For the first picture, TransferState changes to COMPLETED state when upload completed. But for the second picture, it is always in WAITING state.

Known bug or? @fosterzhang anything?

Thanks.

**Comment by minbi** [comment]
Have you tried to listen for the change using:
`public void onStateChanged(int id, TransferState state);`

When you set the `TransferListener`, the above method should be part of its interface.
`obsOriginalPicture.setTransferListener(new UploadListenerForBigPicture());`

**Comment by TOMKHAN** [comment]
@minbi onStateChanged callback never gets called in this scenario.

**Comment by wdane** [comment]
If you do not wait for completion does it work?
What version of the SDK are you using (it may be worth upgrading to latest version if you are using an older version)?
Have you verified that the file is not null or empty?
Have you changed anything from the default config of the TransferUtility?

**Comment by TOMKHAN** [comment]
@wdane It will work, but I will have no information if the upload finished successfully. So I'm waiting for completion.

SDK version is updated to the latest. Not helping.

If the file is null or empty, I wouldn't even get to the code for uploading.

getTransferUtility method implementation is:
````
private TransferUtility getTransferUtility(Context context) {
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
        context, cognitoIdentityPoolId, region);
ClientConfiguration cc = new ClientConfiguration();
cc.setSocketTimeout(120000);
AmazonS3 s3 = new AmazonS3Client(credentialsProvider, cc);
return new TransferUtility(s3, context);
}
````
But that's suggested in https://github.com/aws/aws-sdk-android/issues/119 so I guess it's ok.

@fosterzhang where are you? :)

**Comment by KishanRakholiya** [comment]
I have solved this issue by refreshing TransferObserver object.
```
while(true) {
        transferObserver.refresh();  // Refresh TransferObserver object
       // YOUR CODE
} 
```
Above, code is tested in Nexus 6P with Android Nougat installed.

**Comment by wdane** [comment]
We will work on improving out Transfer Utility documentation to be more clear that refresh is needed.

**Comment by wdane** [comment]
We'll take this feedback to work on our Transfer Utility docs, thanks!

**Comment by TOMKHAN** [comment]
@wdane so transferObserver.refresh(); is now a workaround?

**Comment by TOMKHAN** [comment]
@wdane Are there any updates about this issue?

**Comment by kvasukib** [comment]
Hi @TOMKHAN, Can you upgrade to 2.6.18 (latest) and do the following?
We fixed bugs in the `TransferListener.onStateChanged() `in the latest release.

The following example demonstrates a way of waiting until both the uploads are complete. using `CountDownLatch`. Let us know if this works for you.

```java
CountDownLatch latch = new CountDownLatch(2);

obsThumb.setTransferListener(new UploadListener() {
   @Override
   public void onStateChanged(int id, TransferState state) {
       if (state == TransferState.COMPLETED || state == TransferState.FAILED) {
         latch.countDown();
       }
   }
});

obsOriginalPicture.setTransferListener(new UploadListenerForBigPicture() {
  @Override
   public void onStateChanged(int id, TransferState state) {
       if (state == TransferState.COMPLETED || state == TransferState.FAILED) {
         latch.countDown();
       }
   }
});

try {
    latch.await();
} catch (final InterruptedException exception) {

}
```

**Comment by snkashis** [comment]
@kvasukib the Changelog for 2.6.18 doesn't indicate any changes for TransferListener - https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-2618

**Comment by kvasukib** [comment]
@snkashis We fixed a lot of bugs and improved the stability of TransferUtility since 2.6.16. The Changelog is not detailed enough to cover every fix. Sorry about that. Can you upgrade to the latest and give us any feedback you have?

**Comment by usmanrana07** [comment]
I'm using 2.6.27 and still facing same issue.

**Comment by AlexeyKorshun** [comment]
I'm have this issue when start uploading in airplane mode. Nothing isn't happening when the connect is appear.

**Comment by sunithapremjee** [comment]
I have this issue with S3.How to solve??

**Comment by palpatim** [comment]
@AlexeyKorshun and @sunithapremjee Can you open new issues with your specific details and individual reproduction steps? Especially on old issues like this one, we find that issues that look the same on the surface in fact have different root causes. Plus, separating the issues out makes it less likely to confuse different conversations in a long thread.

**Comment by sunithapremjee** [comment]
![Uploadingfrom_AndroidApp_to_S3](https://user-images.githubusercontent.com/9869417/56693230-ee041400-66b1-11e9-9f94-477e4d7f9b1a.png)

**Comment by sunithapremjee** [comment]
I am trying to upload to S3bucket a photo from my android app.Please let me know what am I missing.I am new to this.I couldn't find anything in my S3 bucket and TransferState.COMPLETED == state is never called so save() function to update DynamoDb string data is also not getting called.

**Comment by kvasukib** [comment]
@sunithapremjee Sorry for the inconvenience caused. Can you open a new issue with all the required details for us to investigate because we do not want to discuss this on the closed issue.

Also, when you open the new issue, can you try adding a log statement in `onStateChanged()` callback to see if you are getting the different state updates and post the logs in the new issue?

**Comment by sunithapremjee** [comment]
Ok...I'll open a new Isuue.

**Comment by tosulc** [comment]
Hey @mutablealligator @wdane, I hope you still work here :)

I'm still on a solution with while(true) with transferObserver.refresh(); It's working just fine in production. But now the time has come to revisit that code and refresh it with 2025. solution.

Is the CountDownLatch latch solution still the only solution to the blocking of a thread while one picture gets uploaded?
