### ISSUE TITLE
Auto generated SDK has errors

### ISSUE THREAD

**Issue by yperess** [aws/aws-sdk-android#203]
In working with the auto-generated SDK I found some issues, specifically, the API functions do not specify any throwable objects yet they do happen. Generic errors can be caught with: 
com.amazonaws.mobileconnectors.apigateway.ApiClientException which extends java.lang.RuntimeException at the root (which is why you can catch it even though the generated API doesn't explicitly says throws ApiClientException).

I also ran into issues when the network connection drops (during authentication) when the calls throw java.net.UnknownHostException. This one is harder because I can't catch it since the API function doesn't explicitly says throws UnknownHostException.

Current workaround is to just wrap all the call with:
try {
    ...
} catch (Throwable tr) {
    ...
}

Though this is really bad practice.

**Comment by mlshon** [comment]
Hello,
Thank you for bringing this to our attention.  We will put this in our feature request.
