### ISSUE TITLE
Crash during upload

### ISSUE THREAD

**Issue by JulienArzul** [aws/aws-sdk-android#207]
Hello,

I'm using your SDK in an Android Application to upload videos to my Amazon S3 folder. I've included Fabric in my application and a crash from your SDK has been reported.

Enclosed is the report downloaded on Crashlytics. The report only includes info of one phone but it appeared on all Android versions that I support (minsdk to 4.4) with different manufacturers.

The crash doesn't seem to happen a lot. It must be an edge case.

Thanks

[aws_s3_issue_29_crash_57eacabe012d00016963dc9b6b42e002.txt](https://github.com/aws/aws-sdk-android/files/527422/aws_s3_issue_29_crash_57eacabe012d00016963dc9b6b42e002.txt)

**Comment by karthiksaligrama** [comment]
Thanks for the log. Can you please update the SDK to latest version and see if you are still seeing the problem. I believe its related to #223 which was fixed in 2.3.7 version of SDK.
