### ISSUE TITLE
Failed to resolve sdk cognito identity provider throw Gradle

### ISSUE THREAD

**Issue by miguelfreitas93** [aws/aws-sdk-android#208]
Hi,
I'm trying to compile com.amazonaws:aws-android-sdkcognitoidentityprovider:2.3.2 in Android Studio 2.2.1 and it gaves me the following error:
Error:(88, 13) Failed to resolve: com.amazonaws:aws-android-sdkcognitoidentityprovider:2.3.2

I'm using Gradle 2.2.1 and jcenter() and mavenCentral() repositories and it can't found the dependency anyway.

I hope you can help me, thanks in advance,
Miguel Freitas

**Comment by wdane** [comment]
Looks like it's in mavenCentral http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22aws-android-sdk-cognito%22

Additionally mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:get -DartifactId=aws-android-sdk-cognito -DgroupId=com.amazonaws -Dversion=2.3.3 seems to find it.

This is likely an error in your individual Gradle file (or network connectivity).

Resolving for now, feel free to re-open if you do not believe this to be the case.
