### ISSUE TITLE
TransferObserver.getState() not updated unless TransferListener registered - always WAITING

### ISSUE THREAD

**Issue by Chronos2011** [aws/aws-sdk-android#209]
While trying to synchronize the TransferUtility.upload() method, I found that the TransferState from the returned TransferObserver's getState() is not updated. The code below reliably provokes the issue on a Samsung Note 2 running Android 4.4.2 - if you remove (i.e. do not register) the anonymous TransferListener, the code below will enter an infinite loop because TransferObserver.getState() will continuously return WAITING (in contrast to the TransferState documentation).
Although, I cannot verify at the moment, it seems that the upload itself is successful.

This seems to be related with #199.

```
        TransferObserver transferObserver = transferUtility.upload(bucket, key, file);
        transferObserver.setTransferListener(new TransferListener() {
            // We need to set a dummy listener here - otherwise the upload will not start
            @Override
            public void onStateChanged(int id, TransferState state) {
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
            }

            @Override
            public void onError(int id, Exception exception) {
            }
        });
        while (true) {
            TransferState state = transferObserver.getState();
            Log.d(Constants.LOG_TAG, "Got state: " + state.name());
            switch (state) {
                case COMPLETED:
                    return true;
                case FAILED:
                    return false;
            }
            try {
                Thread.sleep(250);
            } catch (InterruptedException exception) {
                // This should not happen
                exception.printStackTrace();
            }
        }
```

**Comment by msquare097** [comment]
I have solved this issue by using below snippet.
```
while (true) {
     ......
     transferObserver.refresh();  // this will update your upload state.
     ......
}

```

Using above code, you also don't have to use `transferObserver.setTransferListener()`.
I have just apply the `transferObserver.refresh()` in `while `loop.

I have tested this in Samsung SM-G7102 OS 4.4.2 , Lenovo OS 4.2, Nexus 7 OS 6.1 And In nogut also which is Nexus 6p OS 7.0

**Comment by Chronos2011** [comment]
Thank you, @msquare097 ! Looking in the source code, I find that this is intended behavior. So this should be clearly documented in

* TransferObserver
* TransferObserver.getState()

since it obviously violates the https://en.wikipedia.org/wiki/Principle_of_least_astonishment - who would assume that you need to call an update method so that getters become valid? Especially when the class is named *Observer?

**Comment by msquare097** [comment]
Ya @Chronos2011 there are so many thing that amazon sdk should have to update.
First of all, to upload image on main thread, `while(true) { ... }` is just like a work around. It is not a proper solution for this. In older version TransferManager has a method waitForUpload.

So I hope in update, amazon SDK will give proper solution for this.

**Comment by Chronos2011** [comment]
You're right, @msquare097 - my issue report #210 deals with the unfortunate interface resulting in a `while(true)` loop. I have that on a separate `Thread`, though. Or did I miss the point?

**Comment by aliaksei-lithium** [comment]
I faced with this behavior and spent so much time to find where the problem...I need to upload a lot of files big/small - no matter from phone.
And when just remove ` transferObserver.setTransferListener(new TransferListener() {})` and move to solution (simplified):
```
  public Runnable listen() {
        return new Runnable() {
            @Override
            public void run() {
                while (true) {
                    transferObserver.refresh();
                    if (onStateChanged(transferObserver.getId(), transferObserver.getState())) {
                        break;
                    }

                   try {
                       TimeUnit.MILLISECONDS.sleep(500);
                    } catch (InterruptedException e) {
                       Log.w(TAG, e.getMessage(), e);
                    }
                }
            }
        };
    }
```
and submit this Runnable to ExecutorService with fixed pool, everything start working blazing fast with no errors and freezes.

**Comment by karthiksaligrama** [comment]
If you are using the `TransferObserver` directly to get the state then you always need to make the `transferObserver.refresh()` call , a better option would be to use the `setTransferListener` api.
