### ISSUE TITLE
Cannot provide listener in TransferUtility.upload()

### ISSUE THREAD

**Issue by Chronos2011** [aws/aws-sdk-android#210]
When trying to synchronize TransferUtility.upload(), I found there is no way (that I could find) to ATOMICALLY start an upload and register a TransferListener. For small files, this sometimes results in the upload being finished BEFORE the TransferListener is registered.
Trying to workaround doesn't really satisfy, since TransferObserver.getState() isn't reliable (see #209 and #199). I consider this shortcoming a severe issue.

**Comment by Chronos2011** [comment]
With new insights into #209 it is no more impossible but still very inconvenient to workaround this issue.

**Comment by TOMKHAN** [comment]
@wdane Is there a date on which we can expect TransferUtility to get this feature?

**Comment by karthiksaligrama** [comment]
added in 2.4.0

**Comment by snkashis** [comment]
@karthiksaligrama this fix is only available if you also want to pass `ObjectMetadata` a `CannedAccessControlList` in your `upload` call?What about without? https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L525

**Comment by kvasukib** [comment]
@snkashis Are you expecting to have an upload method with bucket, key, file, and listener?
