### ISSUE TITLE
Status Code: 400; Error Code: AccessDeniedException;

### ISSUE THREAD

**Issue by kimuraeiji214** [aws/aws-sdk-android#211]
com.amazonaws.AmazonServiceException: User: arn:aws:sts::135154376492:assumed-role/Cognito_FreezeUnauth_Role/CognitoIdentityCredentials is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-west-2:135154376492:table/User (Service: AmazonDynamoDB; Status Code: 400; Error Code: AccessDeniedException; Request ID: 3ATLD07CLQP498HIL28LU70SDRVV4KQNSO5AEMVJF66Q9ASUAAJG)

This is what I get when I try to access on dynamodb using AWS Android Sdk.
Anyhow, I can access the dynamodb via IOS SDK with same region and ARN without changing the permissions.

I attached following 2 policies separately.

{
   "Version": "2012-10-17",
   "Statement": [
       {
           "Sid": "Stmt1477507294000",
           "Effect": "Allow",
           "Action": [
               "dynamodb:*"
           ],
           "Resource": [
               "arn:aws:dynamodb:us-west-2:135154376492:table/Users"
           ]
       }
   ]
}

{
   "Statement": [
       {
           "Effect": "Allow",
           "Action": [
               "dynamodb:DeleteItem",
               "dynamodb:GetItem",
               "dynamodb:PutItem",
               "dynamodb:Scan",
               "dynamodb:Query",
               "dynamodb:UpdateItem",
               "dynamodb:BatchWriteItem",
               "dynamodb:BatchReadItem"
           ],
           "Resource": [
               "arn:aws:dynamodb:us-west-2:135154376492:table/Users",
               "arn:aws:dynamodb:us-west-2:135154376492:table/Users/index/*"
           ]
       }
   ]
}

**Comment by mlshon** [comment]
Hello,
It looks like you're attempting to perform the action on resource:
arn:aws:dynamodb:us-west-2:135154376492:table/User 

But your permission is for:
arn:aws:dynamodb:us-west-2:135154376492:table/Users

You're missing the 's'
