### ISSUE TITLE
S3TransferUtilitySample sometimes is not working (URGENT)

### ISSUE THREAD

**Issue by hvar90** [aws/aws-sdk-android#212]
i have a app for chating and when i test on my celphone all works well but some users of my app they have problems uploading files
i have :
SocketTimeout=150000;
ConnectionTimeout=150000;

so i have used my emulator and when i try upload a imagen, it sometimes works and it sometimes doesnt work and this is the information/stacktrace
these are 2 cases when it failed
E/UploadTask: Failed to upload: 3 due to Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (Service: Amazon S3; Status Code: 400; Error Code: RequestTimeout; Request ID: 2537BDA6D6D2AD9F)

E/UploadTask: Failed to upload: 1 due to Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed. (Service: Amazon S3; Status Code: 400; Error Code: RequestTimeout; Request ID: 8B007ECB053E175C)

also i have a question i have this configuration 
config.setMaxErrorRetry(3);
but when i get the error, it did not try again to upload the image, so, how can i try many times after that my upload fail ??

**Comment by wdane** [comment]
Can you provide a code snippet of how you are uploading the image.

Also not all errors are retried, certain errors are not likely to be fixed by retires, so they are not retried regardless of the MaxErrorRetry.

**Comment by hvar90** [comment]
```
public class HandlerUploads {
    private static final int socketTimeout = 150000;
    private static final int connectionTimeout = 150000;
    private static final String bucketName =   "secret";

    static void uploadFile(Context c,String pathToUpLoad,File file,TransferListener transferListener) {

        CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                c,
                "secret", // Identity Pool ID
                Regions.US_EAST_1 // Region
        );

        ClientConfiguration config = new ClientConfiguration();
        config.setSocketTimeout(socketTimeout);
        config.setConnectionTimeout(connectionTimeout);
        config.setMaxErrorRetry(4);      
        AmazonS3 s3 = new AmazonS3Client(credentialsProvider,config);
        TransferUtility transferUtility = new TransferUtility(s3, c);
        TransferObserver observer = transferUtility.upload(
                bucketName,
                pathToUpLoad,
                file
        );
        observer.setTransferListener(transferListener);
    }
}
```

**Comment by hvar90** [comment]
i have a new big problem, suddenly i can not see the images on the cellphone, S3 is having a big error because the images are sotred on S3 but from the cellphone it can not see 
i have this message on my console 
S3 Acceleration Upload Errors
2016-12-09T01:17:01Z We are investigating errors uploading content to Amazon S3 via S3 Transfer Acceleration. Uploads using the Amazon S3 regional endpoints are operating normally.

**Comment by karthiksaligrama** [comment]
try increasing your timeouts. If your network is flaky then you may need higher values for defaults.

**Comment by karthiksaligrama** [comment]
Assuming resolved. Closing
