### ISSUE TITLE
Android – Strange behaviour when downloading an object from S3

### ISSUE THREAD

**Issue by xgranell** [aws/aws-sdk-android#213]
I’m using Android Studio (last update) with the latest SDK version (2.3.3). My app build.gradle is:

```apply plugin: 'com.android.application'
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"
    defaultConfig {
        applicationId "com.example.xxxxx.xxxxx"
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.amazonaws:aws-android-sdk-core:2.3.+'
    compile 'com.amazonaws:aws-android-sdk-s3:2.3.+'
    compile 'com.amazonaws:aws-android-sdk-ddb:2.3.+'
    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.3.+'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.3.+'
}
```

I try to download an Object from a bucket with properties:
```
Bucket:	bbbbbbbbbbb
Region:	Frankfurt
Creation Date:	Mon Aug 08 20:35:57 GMT+200 2016
```

So it fully supports **AWS4-HMAC-SHA256** signatures as stated in documentation.

I’ve got an identityPool in the North Virginia region with roles and permissions to reach the previous bucket.

In **iOS**, I use the instructions displayed in Cognitio console to access bucket:
```
AWSCognitoCredentialsProvider *credentialsProvider = [[AWSCognitoCredentialsProvider alloc]
   initWithRegionType:AWSRegionUSEast1
   identityPoolId:@"us-east-1: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"];
```

And all works fine in iOS.

In Android, I follow the instructions in console (the same identityPool as in iOS because the application is the same):
```
CognitoCachingCredentialsProvider credentialsProvider =
         new CognitoCachingCredentialsProvider(getApplicationContext(),
                                             "us-east-1: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                             Regions.US_EAST_1);
```
And when trying to download the object, I use:
```
AmazonS3 s3 = new AmazonS3Client(credentialsProvider);
TransferUtility transferUtility = new TransferUtility(s3, getApplicationContext());
TransferObserver observer = transferUtility.download(
                    "bbbbbbbbbbb",     // The bucket to download from
                    "myfile.json",    // The key for the object to download
                    myFile);       // The file to download the object to
```
Surprisingly, **in Android does not work and logs error message**: “**E/DownloadTask: Failed to download: 1 due to The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest;**”

Reading all documentation, is clear that my bucket supports it, and both regions also did. I can’t understand why this, especially if in iOS all works perfectly, I’ve never had such issue.

Finally I get success when calling with:
```
ClientConfiguration cli = new ClientConfiguration();
AmazonS3 s3 = new AmazonS3Client(credentialsProvider,cli.withSignerOverride("AWSS3V4SignerType"));
```
Why this?

But now, Android shows me another error: “**Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1' (Service: null; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: 53A81C66A7C0D0A4), S3 Extended Request ID: HLNGlaGw04rsniDfOOpyAlcpw35RAldsEQysYIf5v8YDK0pKzOdJ1GMBdn6fN1BuB4Nnl/NruZ0=**”

So, I decided to create a new identityPool in Frankfurt ('eu-central-1’), the same region to which bucket belongs to. IAM roles were correctly assigned to this new identityPool, and access to unauthenticated identities is enabled. Roles are global. Console doesn’t display any error. And I followed instructions on console:
```
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
    getApplicationContext(),
    "eu-central-1:yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy",
    AWSRegionEUCentral1
);
```
First of all, Android Studio displays a compilation error because AWSRegionEUCentral1 cannot be resolved. So it’s a mistake from documentation. I tried with:
```
CognitoCachingCredentialsProvider credentialsProvider =
              new CognitoCachingCredentialsProvider(getApplicationContext(),    
                                "eu-central-1 yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy",  
                                Regions.EU_CENTRAL_1);
```
And now a new error appears: “**Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-central-1' (Service: null; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: 0E4C682A5B5860A0), S3 Extended Request ID: wM81jwyJ8Wg+uZXgjpw3AKfEbqKXAHKBPBUqQ5vDnE8QY0FNbiSHAAYiQCMfFxT6QbM67ae+/Z4=**”

So, it doesn’t matter which credentials I use, the error remains identical. May be credentials never change whether region I use? May be the app id “com.example.myapp.app” is always mapped to 'us-east-1' region? 

What’s going wrong? Why in iOS works and not in Android?  Where is my mistake?

Thanks in advance.

**Comment by mlshon** [comment]
Try setting the region on the S3 client.  It defaults to us-east-1 if it's not specified, but your bucket was created in Region: Frankfurt

**Comment by xgranell** [comment]
Thanks **mlshon**, it works.
