### ISSUE TITLE
java.lang.UnsupportedOperationException when using AmazonS3EncryptionClient with TransferUtility [Urgent] 

### ISSUE THREAD

**Issue by hs8058** [aws/aws-sdk-android#214]
Hi,
Created the issue at https://github.com/aws/aws-sdk-java/issues/917 and has been advised to create it here.
Has anyone tried using AmazonS3EncryptionClient with TransferUtility?
Irrespective of the chosen CryptoConfiguration, when ObjectMetadata.addUserMetadata is internally called during the building of the putobject request, an exception is raised, which is apparently the result of ObjectMetadata.usermetadata being an UnmodifiableMap, which makes it impossible to add the required custom meta data:
When using AmazonS3EncryptionClient.putObject directly (not using TransferUtility), such an error does not happen.
It won't make a difference if InstructionFile or Metadata is used. Either way, the library does try to change usermetadata which raises the exception.
V 2.3.3 has been used for this issue.
This is urgent.
Here is the exception:
java.lang.UnsupportedOperationException
at java.util.Collections$UnmodifiableMap.put(Collections.java:1280)
at com.amazonaws.services.s3.model.ObjectMetadata.addUserMetadata(ObjectMetadata.java:196)
at com.amazonaws.services.s3.internal.crypto.EncryptionUtils.encryptRequestUsingInstruction(EncryptionUtils.java:362)
at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleEO.putObjectUsingInstructionFile(S3CryptoModuleEO.java:354)
at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleEO.putObjectSecurely(S3CryptoModuleEO.java:87)
at com.amazonaws.services.s3.internal.crypto.CryptoModuleDispatcher.putObjectSecurely(CryptoModuleDispatcher.java:85)
at com.amazonaws.services.s3.AmazonS3EncryptionClient.putObject(AmazonS3EncryptionClient.java:412)
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:203)
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:85)
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:44)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

**Comment by hs8058** [comment]
UPDATE:

Apparently, JsonUtils.jsonToMap returns a Collections.unmodifiableMap when called internally.
Apparently, the underlying issue for this scenario is that after the transfer record gets persisted, when it's picked up for processing, userMetadata of the request is populated from the database by TrasferUtility using JsonUtils.jsonToMap but then EncryptionUtils.encryptRequestUsingInstruction tried to change userMetadata to add content length and other encryption-related details to it and that's why the error happens.

I think the solution is to either make sure JsonUtils.jsonToMap does not return a Collections.unmodifiableMap, OR, adding such metadata before persisting the transfer record which may have its own challenges.

Temporarily, I modified JsonUtils.jsonToMap to return a Map and replaced the class in the jar file, which has resolved the issue before you guys have a chance to change things.

Best,

H.

**Comment by karthiksaligrama** [comment]
What version of SDK are you using? I tried to reproduce this problem and i wasn't. Do you have some code snippet that i can use?

**Comment by hs8058** [comment]
Update:
The latest SDK version (2.3.8) was used with the same outcome.
Added case number #229, which is linked to this issue as well.
It is now confirmed that by not returning Collections.unmodifiableMap in JsonUtils.jsonToMap, the problem is NOT resolved. 
In fact, what is happening is that when uploading files, the wrong size attribute is added to the metadata if you avoid returning  Collections.unmodifiableMap and that's why during downloading, the checksum (or wrong key) error happens.
When other mechanisms like direct putobject or TransferManager are used for uploading files, no error occurs during the download and decrypting process.
TransferUtility obviously has issues...

**Comment by hs8058** [comment]
Yet another update:

At com.amazonaws.mobileconnectors.s3.transferutility.UploadTask, inside createPutObjectRequest, if you discard the userMetadata setting method, the upload the download processes will succeed with no error while at the downloading end, the download also succeeds.

In our use case, we are NOT  adding any custom user meta data therefore, it is OK but in real life, it's not a permanent solution.

/*
if (upload.userMetadata != null) {

            om.setUserMetadata(upload.userMetadata);

        }*/

**Comment by hs8058** [comment]
Update:

Annoyingly,  we still get random errors for files uploaded with TransferUtility with small sizes even after the above change. At least that cured it for some cases.

We really can not afford spending more time on this issue.

Still it's a wonder why we have to avoid touching userMetadata to succeed in uploading and why if we do so, the same method works for larger files but not for smaller files randomly.

I think we will end up using the TransferManager for now, even though we will lose the option of retrying upon network disconnections. Really frustrating.

**Comment by karthiksaligrama** [comment]
resolved with 2.4.0

**Comment by hs8058** [comment]
Update: This is to confirm that 2.4.6 does not raise this exception anymore.

However, there is another problem: With files that are bigger than 5 M and will be uploaded in multiparts, the service won't simply do anything with them!

it just raises that the state is InProgress but it remains so forever.
