### ISSUE TITLE
After upgrading amazon android sdk for version "2.2.5" to "2.3.2" the same code that was functioning properly started to error out.

### ISSUE THREAD

**Issue by kunalseedoc** [aws/aws-sdk-android#218]
Code snippet to reproduce problem:
public void simulateSqsProblem(String queueURL, CognitoCachingCredentialsProvider credentialsProvider) {
    try {
        AmazonSQSClient amazonSQSAsyncClient = new AmazonSQSClient(credentialsProvider);
        SendMessageRequest request = null;
        request = new SendMessageRequest().withQueueUrl(queueURL);
        if (request != null) {
            MessageAttributeValue messageAttributeValue = new MessageAttributeValue();
            messageAttributeValue.setStringValue("paramValue");
            messageAttributeValue.setDataType("String");
            request.addMessageAttributesEntry("paramName", messageAttributeValue);
            request.withMessageBody("messageBody");
        }

        SendMessageResult result = amazonSQSAsyncClient.sendMessage(request);

        if (result.getMD5OfMessageBody() != null) {
            //here for version 2.2.5
            Log.d("SQS", "message sent");
        }
    } catch (Exception e) {
        e.printStackTrace();
        //here for version 2.3.2
        Log.d("SQS", "error occurred");
    }

}

Results:

In case of version 2.2.5:

Output: Successful
Body of call:
Action	SendMessage
MessageAttribute.1.Name	paramName
MessageAttribute.1.Value.DataType	String
MessageAttribute.1.Value.StringValue	paramValue
MessageBody	messageBody
Version	2012-11-05

In case of version 2.3.2:

Output: Error
 "The request must contain non-empty message attribute name."

Body of call:
Action	SendMessage
MessageAttribute.entry.1.Name	paramName
MessageAttribute.entry.1.Value.DataType	String
MessageAttribute.entry.1.Value.StringValue	paramValue
MessageBody	messageBody
Version	2012-11-05

**Comment by karthiksaligrama** [comment]
Thanks for the info, Please downgrade to 2.2.21 will get this fixed in the next release.

**Comment by karthiksaligrama** [comment]
Fixed with 2.3.6
