### ISSUE TITLE
Resume FAILED does not work on v2.3.3

### ISSUE THREAD

**Issue by diogomonte** [aws/aws-sdk-android#219]
I've seen the following issue reported in January.

https://github.com/aws/aws-sdk-android/issues/87

I recently updated to version 2.3.3 and apparently the "resume" is not working for FAILED files. 
Any updates about it?

**Comment by mlshon** [comment]
Could you provide more details?
Any sample code, repro steps, etc...

Did it stop working when you updated to 2.3.3? Our newest Android SDK is 2.3.5

**Comment by karthiksaligrama** [comment]
assuming this was resolved. Please reopen if the problem persists.
