### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by RapsIn4** [aws/aws-sdk-android#223]
https://github.com/aws/aws-sdk-android/blob/23c58741cfbcf8b2f06858b458765fa47abe967e/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferService.java#L172

intent can be null and this causes a NPE.

**Comment by karthiksaligrama** [comment]
Will fix in next release

**Comment by karthiksaligrama** [comment]
resolved with 2.3.7
