### ISSUE TITLE
SQS - improper empty attributes handling

### ISSUE THREAD

**Issue by mj-daft** [aws/aws-sdk-android#226]
Hi,

I was integrating Amazon SQS SDK in my project for a while, when a problem occurred. And it looks like this:

When I don't specify any message attributes, everything works as expected, message is delivered to the queue:

```
SendMessageRequest request = new SendMessageRequest()
                .withQueueUrl(sqsQueueUrl)
                .withMessageBody("{\"to be\":\"or not to be\"}");

amazonSQSClient.sendMessage(request);
```

(`sqsQueueUrl` is a proper queue url, prefetched earlier)

If I add some:

```
SendMessageRequest request = new SendMessageRequest()
                .withQueueUrl(sqsQueueUrl)
                .withMessageBody("{\"to be\":\"or not to be\"}")
                .withMessageAttributes(buildMessageAttributes(10));

amazonSQSClient.sendMessage(request);

// far far in a code

private Map<String, MessageAttributeValue> buildMessageAttributes(long id) {
    Map<String, MessageAttributeValue> result = new HashMap<>();
    result.put(
            "some_id",
            new MessageAttributeValue()
                    .withDataType("String")
                    .withStringValue(String.valueOf(id))
    );
    return result;
}
```
I got an exception on line `amazonSQSClient.sendMessage(request)` with a message 
`The request must contain non-empty message attribute name.`

Is it mine misunderstanding or SDK bug? I haven't found anybody with such issue.

Best regards,
Martin

**Comment by karthiksaligrama** [comment]
this is fixed with v2.3.6 Please update to the latest sdk and try again
