### ISSUE TITLE
how  i get Identity Pool ID?

### ISSUE THREAD

**Issue by songdings** [aws/aws-sdk-android#227]
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                MY-ACTIVITY.getApplicationContext(), // Application Context
                "MY-IDENTITY-POOL-ID", // Identity Pool ID
                Regions.SELECT_YOUR_REGION // Region enum

how  i get Identity Pool ID?  I only has  ACCESS_KEY_ID   and SECRET_KEY?  what  should  i  do ?

**Comment by minbi** [comment]
Hi songdings,

In your AWS account,
* navigate to Cognito Service
* choose Federate Identities
* choose the user pool that you need or create one
* at the top right, click "Edit identity pool"

You should be able to find the identity pool string
formatting looks like us-east-1:3fef5b38-1234-abc1-bec3-d74bb3bb74d0

If you have trouble finding it based on this information, please feel free to re-open this issue.
