### ISSUE TITLE
KinesisStreamRecorderSender's partitionKey is always random

### ISSUE THREAD

**Issue by JMASystems** [aws/aws-sdk-android#228]
In aws-sdk-android/aws-android-sdk-kinesis/src/main/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisStreamRecordSender.java,
partitionKey is generated by UUID.random.
But we want to set the static partition key.
So do you have any plan to custom partition key generator implementation.

**Comment by azsolinsky** [comment]
An improvement has been made to allow setting a static partition key in the configuration. See the 2.3.9 release notes for more details: https://aws.amazon.com/releasenotes/1894188094590101
