### ISSUE TITLE
It's possible to login on Cognito in offline ?

### ISSUE THREAD

**Issue by PaolinoAngeletti** [aws/aws-sdk-android#232]
I'm developing an Android app which provides a login screen with username and password. When there is connection, an HTTP request is made to verify the username and password entered on Cognito.

My question was whether you can verify your username and password (always on Cognito) even when the connection is absent. Why else in my app you can not make a login without connection on Cognito, and then I will have to implement other roads.

I'm not talking about the ability to store data offline (with CognitoSyncManager), but the ability to make a real login with username and password on Cognito when we're offline.

More probabily the answer is negative, but my idea is this:

`

            if(haveInternetConnection(context))
            {

                // if i have connection, i proceed to default and without problems
                username = ViewHelper.getStringValue(activity, EDIT_TEXT_USERNAME_ID);
                password = ViewHelper.getStringValue(activity, EDIT_TEXT_PASSWORD_ID);

                final CognitoUser cognitoUser = cognitoUserPool.getUser(username);

                cognitoUser.getSessionInBackground(authenticationHandler);

            }
            else
            {

                // if i not have connection, i want access to cognito with data saved locally. 
               // it's possible?
                CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                        context,
                        "XXX", // Identity Pool ID
                        Regions.XX // Region
                );

                // Initialize the Cognito Sync client
                CognitoSyncManager syncClient = new CognitoSyncManager(
                        context,
                        Regions.XX, // Region
                        credentialsProvider);

                Dataset dataset = syncClient.openOrCreateDataset("myDataset");
                String user = dataset.get("username"); 
                String password = dataset.get("password");

                // here the code for log in to cognito
            }
        }
`

I hope that I have explained well.
Thansk for help

**Comment by mreddyg** [comment]
There is no way to verify the username and password of a user, without a network call (connection) to Cognito. The username and password cannot be validated locally on the device, the service contains the information required to authenticate a user.
However, if a user has already signed-in on a device and has not signed-out, the device could still have valid cached tokens. When a user signs-in to a Cognito user pool, a Cognito session is returned for that user. The session is a set of tokens (Id, Access and Refresh) which, basically, indicate that the user has successfully authenticated and hence has signed-in. So, the user is signed-in as long as the tokens remain valid.
