### ISSUE TITLE
How to increase maxStorageSize?

### ISSUE THREAD

**Issue by chrisvire** [aws/aws-sdk-android#237]
I am reading the AWS Mobile Analytics documentation for [Submitting Events](http://docs.aws.amazon.com/mobileanalytics/latest/ug/submitting-events-sdk.html).  I see that the client stores a maximum of 5 megabytes of event data.  I can see that the "maxStorageSize" is requested in:

https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-mobileanalytics/src/main/java/com/amazonaws/mobileconnectors/amazonmobileanalytics/internal/delivery/FileEventStore.java

I would like to be able to collect events for a long period of time.  In my App, the user may be disconnected for several weeks.
If I need to adjust the storage size, what is the correct way to change this max storage size for my App?  Is this possible?

In https://github.com/aws/aws-sdk-ios/issues/500, it asks how to increase the max storage size.  @karthiksaligrama says, "added in 2.4.12".  Will this be added in aws-sdk-android as well?  If so, how would a user of the SDK make this change?

The current release of AWS Android SDK is 2.3.8.

**Comment by chrisvire** [comment]
I am not interested in using the Pinpoint service (pushing notifications to drive user engagement).  I just want to gather some usage analytics.  Would you consider making the equivalent change in Android as is being done in iOS?

**Comment by karthiksaligrama** [comment]
yes you can.
