### ISSUE TITLE
Problems with Retrieve data from Dynamo DB [ANDROID]

### ISSUE THREAD

**Issue by PaolinoAngeletti** [aws/aws-sdk-android#238]
Hi, i've the following problem:
I try to retrieve data from Dynamo DB , but the response that I receive is: 'The provided key element does not match the schema'

The code is:
`try {

                HashMap<String, AttributeValue> key = new HashMap<String, AttributeValue>();
                key.put("id", new AttributeValue().withN("1"));

                GetItemRequest request = new GetItemRequest()
                        .withTableName("Utente")
                        .withKey(key);

                try {
                    GetItemResult result = client.getItem(request);
                    if (result != null) {
                        AttributeValue nome = result.getItem().get("nome");
                        Log.d("DynamoDB",nome.toString());
                    } else {
                        Log.d("DynamoDB","NOT FOUND");
                    }
                } catch (Exception e) {
                    Log.e("Unable_retrieve_data: ",e.getMessage().toString());
                }`

This is the Table Schema:

![immagine](https://cloud.githubusercontent.com/assets/24671034/21689107/99b65e80-d36f-11e6-93d5-4458ca82d2a7.png)

My Key (id) is number, and i in the code pass an integer (withN).

![immagine](https://cloud.githubusercontent.com/assets/24671034/21689119/a64eeef0-d36f-11e6-8451-72ce3f702808.png)

This is a very strange error: some help??
Thanks

**Comment by karthiksaligrama** [comment]
is id your hash key?

**Comment by PaolinoAngeletti** [comment]
I've created this table with a partition key (id) and without a sort key.
In that situation, what do you mean with hask hey ?

![immagine](https://cloud.githubusercontent.com/assets/24671034/21716758/be9b4af6-d40c-11e6-8d32-306033f9d047.png)

**Comment by PaolinoAngeletti** [comment]
I've solved the problem with this code:

`credentialsProvider = new CognitoCachingCredentialsProvider(
                context,
                AWSConfiguration.AMAZON_COGNITO_IDENTITY_POOL_ID,
                AWSConfiguration.AMAZON_DYNAMODB_REGION
        );
        client = new AmazonDynamoDBClient(credentialsProvider);
        client.setRegion(Region.getRegion(Regions.EU_WEST_1));`

I've have to indicate at client what is the region where is the database, it's not enough declare it into credentialsProviders object
