### ISSUE TITLE
Lambda Payload Security

### ISSUE THREAD

**Issue by billywong4d** [aws/aws-sdk-android#240]
Hi, 

  I just wanna know if the android sdk encrypts the lambda payload before sending to AWS. I'm passing sensitive information (Acc Pwd). If not, is there any suggestion how I might do this securely?

Thank you so much for helping.
Billy

**Comment by karthiksaligrama** [comment]
the sdk does not encrypt lambda payload. the trick here is that the lambda payload decryption need to handled by lambda service which it currently does not. So when the service adds support for encrypting payload, we will add it in the sdk.

**Comment by billywong4d** [comment]
Does the payload send to the server through HTTP or HTTPS?
