### ISSUE TITLE
Pinpoint Notification Icon White

### ISSUE THREAD

**Issue by neo17** [aws/aws-sdk-android#243]
* What service are you using?
_Pinpoint_

* In what version of SDK are you facing the problem?
_aws-android-sdk-pinpoint:2.3.8_

* Is the issue limited to Simulators / Actual Devices?
_Both_

* Can your problem be resolved if you bump to a higher version of SDK?
_No_

* Is this problem related to specific Android/OS version?
_Yes Android 5.0 Lolipop and Above

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
_Sending a test push notification will be sufficient_

Hello!

We have an issue with the notification Icon when we are using the AWSPinpoint SDK. 

As you know from Android 5.0 the notification icons now should be material design specific otherwise they will display as a square white icon. 

In your Pinpoint Console there is no way to specify which Notification Icon should be use. Checking the implementation of the NotificationClient.java I notice that you expect the icon to be specified in the pushBundle of the GCM notification but still there is no way to change this property through the Pinpoint Console. Since we can’t specify a notification icon resource id through the pushBundle of GCM the NotificationClient.java as a fallback uses the application default notification. This is not cool since the result in most of the cases will be just a white square for the notification icon in the status bar. [Here a link](https://support.xtremepush.com/hc/en-us/article_attachments/203534175/Screenshot_20151206-212851-2.png
)

Is there any way to specify a custom notification icon for the status bar in the pinpoint sdk? 

Some might want to display a push notification icon that is different from their application icon!

Thanks!

**Comment by rcha** [comment]
Hi, 

Actually the console has a way to specify the Notification Icon.

When creating a campaign on the "Message" step there is an Advanced tab which you can expand. 

There you will find a text box for "Android image icon URL".

**Comment by neo17** [comment]
Hello. 

Sorry if my first screenshot was a little bit misleading.

The "Android Image Icon URL" field is not responsible about the System Bar notification Icon. 

I have configured a notification in the console like this: 

<img width="674" alt="logo-configuration-console" src="https://cloud.githubusercontent.com/assets/5824180/21884204/a49c4a10-d8b2-11e6-8870-64b5b50065dc.png">

And here is the result: 

![notificationstatusbar](https://cloud.githubusercontent.com/assets/5824180/21884144/663dcfbe-d8b2-11e6-91c0-654ef711f51b.jpg)
![notificationexpanded](https://cloud.githubusercontent.com/assets/5824180/21884145/667fb06e-d8b2-11e6-86ed-6c2992a8e8f4.jpg)


In the green arrow we can see the Notification Status Bar Icon and on the red arrow it is the icon we have configured int the console. 

As you can see the configuration of the "Android image icon URL" is not affecting the Status Bar Notification Icon.

**Comment by rcha** [comment]
Hi, 

We currently don'y support setting that asset via the console.

However, it should default to using your application icon. 

Please make sure that your icon is transparent and conforms to: https://material.io/guidelines/style/icons.html

Make sure you have set your application icon inside your Manifest file as well:

``
<application
        android:icon="@mipmap/ic_launcher"
``

**Comment by baole** [comment]
I tried to add new field in the remoteMessage payload and Pinpoint shows the icon on status bar as expected

`            val data = mutableMapOf<String, String>()
            data.putAll(remoteMessage.data)
            data.put("pinpoint.notification.icon", "ic_notification_statusbar")

            val notificationDetails = NotificationDetails.builder()
                    .from(remoteMessage.from)
                    .mapData(data)
                    .intentAction(NotificationClient.FCM_INTENT_ACTION)
                    .build()
`

Is there a better way to configure notification icon?

**Comment by kvasukib** [comment]
@baole Can you describe what is the issue? Can you explain what is the expected behavior and the observed behavior?

**Comment by baole** [comment]
Our app have dedicated status bar icon and we don't want to show app icon on status bar. The above workaround helps to show our dedicated status bar icon for our app.
