### ISSUE TITLE
Android InteractionClient missing a toString 

### ISSUE THREAD

**Issue by snbaker** [aws/aws-sdk-android#245]
https://github.com/aws/aws-sdk-android/blob/5637df98513e458dd09cecdf7e5b28c603e2842c/aws-android-sdk-lex/src/main/java/com/amazonaws/mobileconnectors/lex/interactionkit/InteractionClient.java#L598

is missing toString() so this expression never evaluates to true. the other conditions have toString.

**Comment by minbi** [comment]
Hi snbaker,

Thank you for bringing this to our attention.

**Comment by azsolinsky** [comment]
This issue has been corrected in the 2.3.9 Release. See the release notes for more details: https://aws.amazon.com/releasenotes/1894188094590101
