### ISSUE TITLE
No changelog available

### ISSUE THREAD

**Issue by niqo01** [aws/aws-sdk-android#25]
I cannot decide when to update the sdk because I don't know what change

**Comment by Mudeem** [comment]
Thank you for writing to us. We are in the process of updating the source on GitHub. In the meanwhile, you can refer to the release notes available here: https://aws.amazon.com/releasenotes/Android.

**Comment by Mudeem** [comment]
The source for the android SDK has been updated on Github. Change log is also up to date. If you have any questions, please feel free to reach out to us.
