### ISSUE TITLE
AWS Auto Resume

### ISSUE THREAD

**Issue by lanetteamkaushal** [aws/aws-sdk-android#256]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
-- I am using s3 bucket with cognito Identity Pool ID.

* In what version of SDK are you facing the problem?
-- 2.3.9 (Android 5.1 x86 emulator)

* Is the issue limited to Simulators / Actual Devices?
-- In both 

* Can your problem be resolved if you bump to a higher version of SDK?
-- I am already on latest version

* Is this problem related to specific Android/OS version?
-- Can't say

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
-- Internet is available 
-- Upload one big file to upload in s3 bucket.
-- Attach TransferObserver with upload.
-- Pause Transfer by transferUtility.pause({requestID});(Which returns true)

**Current Behaviour** 
-- next thing onProgressChanged with same {requestID}

**Expected Behaviour**
-- onStateChanged should called with TransferState.PAUSED
-- Transfer should be Paused until manually resume.

**Comment by karthiksaligrama** [comment]
I don't understand. Are you saying that when you pause the transfer the transfer state is not set to paused and the `onStateChanged` method is not called?

**Comment by lanetteamkaushal** [comment]
Hi @karthiksaligrama ,

Yes you understood me correct.

**Comment by kvasukib** [comment]
Hi @lanetteamkaushal,

Are you still facing this issue? Can you put a log statement in onStateChanged() to see if the transfer is paused?

**Comment by FilenkovMaxim** [comment]
And same behavior I see with work pause when downloading with TransferUtility. It doesn't stop and continue downloading several parts. Some time it download all file, some time paused in several seconds.

**Comment by kvasukib** [comment]
Hi @FilenkovMaxim,

What version of SDK are you using? Also, what is the Android Platform that you are running against?

**Comment by FilenkovMaxim** [comment]
Hi @kvasukib 
I'm using aws-android-sdk-s3:2.4.7 and watching the problem on Android 6 and 7

**Comment by FilenkovMaxim** [comment]
I checked with 2.6.5 version, pause doesn't work (

**Comment by kvasukib** [comment]
Thanks, @FilenkovMaxim for confirming it. We are looking into it.

**Comment by kvasukib** [comment]
Hi @lanetteamkaushal and @FilenkovMaxim, We have fixed bugs and made some improvements to TransferUtility in 2.6.16. Can you please upgrade to the latest and see if this fixes the issue?

**Comment by FilenkovMaxim** [comment]
@kvasukib Thank you! I'll do it on some next days.
