### ISSUE TITLE
API Gateway: throws NPE when query parameter is null

### ISSUE THREAD

**Issue by kubode** [aws/aws-sdk-android#258]
* What service are you using?

API Gateway(Generated API Client)

* In what version of SDK are you facing the problem?

2.3.8

* Is the issue limited to Simulators / Actual Devices?

Not limited.

* Can your problem be resolved if you bump to a higher version of SDK?

No.

* Is this problem related to specific Android/OS version?

AFAIK, 4.4 and 7.0.

Here is the cause of the problem.
https://github.com/aws/aws-sdk-android/blob/1cdab8ab8da4675ebdd6f9d616a4c8f69236cc56/aws-android-sdk-apigateway-core/src/main/java/com/amazonaws/mobileconnectors/apigateway/ApiClientHandler.java#L208

This code throws NPE when `arg` is `null`.

I think the query parameter should not provide to the get parameter when it is null.

**Comment by minbi** [comment]
Hi @kubode,

Thank you for bringing this to our attention. We will try to get this into our next release.

**Comment by karthiksaligrama** [comment]
resolved with 2.4.0
