### ISSUE TITLE
Refresh of tokens fails due to missing deviceKey when signed using email+pwd

### ISSUE THREAD

**Issue by brdloush** [aws/aws-sdk-android#259]
Hello,

I'm using cognito user pool (without federated identities) in android application
using following dependencies:

- `com.amazonaws:aws-android-sdk-cognito:2.3.8`
- `com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.3.8`

(I've observed the same issue with 2.3.9 as well, but I'm still sticking with 2.3.8 for now as we didn't perform regression tests with 2.3.9 yet.)

I've run into a problem where refreshing access token using refresh token consistently fails if the user signed in using "email & password" credentials instead of the "internalUsername + password" combination.

There's always a chance that I'm using the API in a wrong way, but since everything is working just fine when "internalUsername+password" is used, I believe there might be a bug in SDK. 

From my observation it seems that the issue might be in a way how DeviceKey is being stored in SharedPreferences.

Here's what happens in my testing scenario..

1) I peform clean installation of the android app, so there are no values stored in shared preferences.

2) I sign in using "email+password". Using remote debug breakpoints, I can see that `confirmDevice` method gets called, which caches(saves) the DeviceKey into SharedPreferences using `CognitoDeviceHelper.cacheDeviceKey` call. What is important here is that in spite of the fact that I've signed in using `email+password` combination, a proper (non-null) value of `user.internalName` is actually used when deriving a SharedPreferences key. Therefore, the DeviceKey gets stored under "internalUsername-derived key". This will become important in Step 4..

3) I keep calling user.getSession succesfully for nearly an hour. Both access and refresh token remain unchanged - as expected. I even try to close and re-run the application again and am still getting valid session, using still the same tokens.

4) After approx. 55 minutes, the `cachedTokens.isValidForThreshold()` returns false when I'm trying to get user session. This is expected - access token should get refreshed. The `getCachedSession()` method calls `refreshSession()`. Then, the `initiateRefreshTokenAuthRequest` doesn't know value of neither `deviceKey` nor `usernameInternal` (I closed and re-started the app in step 3..) Therefore it's calling `CognitoDeviceHelper.getDeviceKey(userId, pool.getUserPoolId(), context);`, where `userId` holds the user *email*, not internalUsername. As a result, `initiateRefreshTokenAuthRequest` is trying to look up Device Key in SharedPreferences, but using incorrect key derived from email value. But  SharedPreferences only contain previously stored (see step 2) DeviceKey under a key derived from internalUsername. Finally since deviceKey value remains `null`, the cognito "refresh" API call fails with  `NotAuthorizedException` (due to missing header with DeviceKey). Due to the exception, `getCachedSession` method clears both tokens (access+refresh) and attempts to sign-in user again using "email+password" combination (via `AuthenticationHandler.getAuthenticationDetails` user code callback). But at this moment we obviously no longer have password, therefore I end up unauthorized.

Now, as already stated, everything is working fine when I use "internalUsername+password" 
instead of "email+password" when signing in.
 
I've hacked together a simple android app where the mentioned scenario can be simulated
and debugged quickly: https://github.com/brdloush/cognito-login-via-email-issue-android (you just need to provide cognito pool details & valid user credentials).

If this is a bug, would you suggest any workaround until the issue gets fully resolved?

**Comment by mreddyg** [comment]
Hi,

I agree, this is a bug in the SDK and we are working to fix this it. The next version of the SDK should have the fix. <br/>Unfortunately there is no workaround for this issue. I will update when the fix is available.<br>Thank you for the detailed analysis on the bug.

**Comment by keshavkaul** [comment]
This has still not been fixed. Any updates on this?

**Comment by keshavkaul** [comment]
@brdloush Any workarounds you have found apart from entering `internalUsername` and `password` instead of `email` and `password`?

**Comment by brdloush** [comment]
Nope, no workaround.

We had to force our users to log in using username+password combination instead of email+password until this bug gets resolved.

**Comment by keshavkaul** [comment]
I'll try logging in with email and password, get the internal username for that user and log him again using internal username. Hope this works. Thanks for the quick reply!

**Comment by keshavkaul** [comment]
@mreddyg Any updates on this? I have tried everything but no solution.

**Comment by carterhudson** [comment]
I'm experiencing the same issue. 
@brdloush when you say `internalUsername` what are you referring to?

**Comment by minbi** [comment]
SDK version 2.4.6 has been released, please re-open if the issue has not been resolved.

**Comment by nateridderman** [comment]
To be clear, upgrading to 2.4.6 provides a method to get the username from the `CognitoUserSession`. You still need to make sure you use that when you call `CognitoDeviceHelper.getDeviceKey()`.

**Comment by ChrisSawczukMSM** [comment]
This sounds exactly like https://github.com/aws-amplify/aws-sdk-android/issues/2728 and in the latest version of the library available, this is still an issue, effectively making USER_PASSWORD_AUTH unusable.
