### ISSUE TITLE
No peer certificate

### ISSUE THREAD

**Issue by riosc** [aws/aws-sdk-android#26]
Hi, I am having an intermittent issue when I try to upload a set of images to a S3 bucket. Basically my application tries to upload a set of 40 – 50 images. But in middle of the process the SDK shows  this error repeatedly. I have noted that it happens in newer android versions 4.4 or higher, but in 4.0 and 4.2 it doesn’t happen.

![screen shot 2015-01-20 at 1 25 47 am](https://cloud.githubusercontent.com/assets/1650591/5812235/8c6306e4-a044-11e4-8f1f-18f6dcf37d01.png)

**Comment by riosc** [comment]
This a painful issue because it get stuck the request for a long time up to it lunches a read time out exception.

**Comment by fosterzhang** [comment]
Is it possible to provide code snippet to reproduce the bug?

**Comment by riosc** [comment]
Hey, thanks for your response.

For any reason in the new version (v2.1.9) of the amazon SDK it doesn’t happens. But if you are still interested in how to replicate it in the previous versions, I could send you a code snipped to replicate it. So let me know if you want I send a sample with the issue.


Best Regards

**Comment by fosterzhang** [comment]
Since it doesn't happen in the latest version, I assume it's a none issue. Feel free to reopen this issue happens again.
