### ISSUE TITLE
Is there any way to delete multi part records?

### ISSUE THREAD

**Issue by tkcmrc** [aws/aws-sdk-android#263]
Hi,
I'm using `TransferUtility` to upload large files to S3.
I'd like to clear transfer records in `awss3transfertable.db` after completed a multipart uploading.
As far as I see the JavaDoc, `TransferUtility` has a delete method `deleteTransferRecord(int id)` but this method deletes just only a main record (not delete part records), right?
So the size of `awss3transfertable.db` becomes larger a little by little.
Is there any way to delete part records?

* What service are you using?
Amazon S3

* In what version of SDK are you facing the problem?
`aws-android-sdk-s3:2.3.9`

**Comment by karthiksaligrama** [comment]
The `TransferUtility` doesn't really save the part in the database. It saves the file reference instead with the markers to the status of the transfer e.g TransferState`, uploaded bytes, bytes total etc. See [TransferDBUtil.java](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferDBUtil.java#L632). So it doesn't really use up that much space.

**Comment by tkcmrc** [comment]
Thank you for your quick reply!
Yeah I know the size is not so large. However my app might be used on devices which has low storage. So I just would like to save spaces as much as possible.
For now, there isn't such method, right?

**Comment by karthiksaligrama** [comment]
No not at this time.

**Comment by tkcmrc** [comment]
Got it. Thank you for your support!
