### ISSUE TITLE
onSuccess callback is missing from verifyAttribute function

### ISSUE THREAD

**Issue by jpuhakka** [aws/aws-sdk-android#266]
While developing this I noticed that call to onSuccess callback is missing from successful verifyAttribute call (in my implementation I changed to use verifyOnBackground which works fine, but this bug should be fixed)

https://github.com/aws/aws-sdk-android/blob/1cdab8ab8da4675ebdd6f9d616a4c8f69236cc56/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L1088

Above code should have call to callback.onSuccess() (L1088)

### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito

* In what version of SDK are you facing the problem?
2.3.9

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

**Comment by minbi** [comment]
SDK version 2.4.6 has been released, please re-open if the issue has not been resolved.
