### ISSUE TITLE
S3 Android Mobile SDK - Cursor Window Full

### ISSUE THREAD

**Issue by idhira** [aws/aws-sdk-android#267]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3 - aws-android-sdk-s3

* In what version of SDK are you facing the problem?
aws-android-sdk-s3 version 2.3.9

* Is the issue limited to Simulators / Actual Devices?
Actual Devices

* Can your problem be resolved if you bump to a higher version of SDK?
I am using the latest library

* Is this problem related to specific Android/OS version?
I am using Android Lollipop 5.1

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
I've posted this issue on aws forums but realized that this is probably a better avenue to see if there is a resolution.  https://forums.aws.amazon.com/thread.jspa?threadID=251655&tstart=0

I upload several files per day in my android app. After a while I get CursorWindow is full errors as seen below. I am using 2.3.9 and supposedly this error is fixed.  I added more logging to my application and see that I am around transferId 200,000 for some users which I assume to be 200,000 transfers? I went through the documentation and TransferService code. I believe that loadTransfersFromDB() in TransferService.java is causing the CursorWindow error. This is because of querying for all transfer types -> dbUtil.queryAllTransfersWithType(TransferType.ANY);

When querying all types, it also picks up Completed transfers. I thought the removeCompletedTransfers() method in TransferService would delete the records but it does not. There is also no documentation I could find that states the completed transfer records are retained in the database.  I assumed completed transfers would be automatically erased :(.  Is there a purge function I can call to purge the entire database of transfer records? or should I call transferUtility.deleteTransferRecord() for each transfer id up until 200,000 that is in an end state (Complete, Failed, Canceled or Unknown)? If possible I think there needs to be documentation somewhere to state to delete transfers after reaching an end state or a fix in place to actually delete the completed transfer records if it makes sense or fix the query to limit the number of records returned or possibly another resolution.

What is the best way to fix this issue for the time being? I do not need to keep track historically of completed transfers.

Sample Code:
`
public void doUpload(final File file, String key){
        TransferUtility transferUtility = application.getTransferUtility();
        
        TransferObserver transferObserver = null;
        try {

            transferObserver = transferUtility.upload(BUCKET, key, file);
            Log.d(TAG, "transferId:" + transferObserver.getId() + ", key:" + transferObserver.getKey() + ", file:" + file.getName() + ", starting to upload");

            FileUploadTransferListener transferListener = new FileUploadTransferListener();
            transferObserver.setTransferListener(transferListener);

            int waitTime = 0;
            int sleepTime = 10000; //10 seconds
            int timeLimit = 3 * 60 * 1000; //3 min
            while (!FINAL_TRANSFER_STATES.contains(transferListener.getCurrentState()) && waitTime < timeLimit) {
                Log.d(TAG, "Uploading file - key:" + transferObserver.getKey() + ", state:"+ transferListener.getCurrentState() + ", transferId:" + transferObserver.getId());
                Thread.sleep(sleepTime);
                waitTime = waitTime + sleepTime;
            }

            if (TransferState.COMPLETED.equals(transferListener.getCurrentState())) {
                Log.i(TAG, "Upload successfully completed, local file being deleted. transferId:" + transferObserver.getId() + ", key:" + transferObserver.getKey());
                file.delete();
            }

            if (transferListener.getCurrentState() == null) {
                boolean result = transferUtility.cancel(transferObserver.getId());
                Log.w(TAG, "transferId:" + transferObserver.getId() + ", TransferListener state is null(" + transferListener.getCurrentState() +
                        "), TransferObserver state:" + transferObserver.getState() + ". Canceled upload for transferId with result:" + result);
            }

            if (waitTime >= timeLimit) {
                Log.w(TAG, "Upload time too long. transferId:" + transferObserver.getId());
            }

            Log.d(TAG, "transferId:" + transferObserver.getId() + " upload process complete with status: " + transferListener.getCurrentState());
        } catch (Exception e) {
            Log.e(TAG, "Unable to upload and cleanup file. transferObserver - " + transferObserver, e);
        } finally {
            if (transferObserver != null) {
                transferObserver.cleanTransferListener();
            }
        }
    }

`

* Please include a stacktrace if applicable.
Log Output:
03-15 22:10:40.775 6909 21595 W CursorWindow: Window is full: requested allocation 67 bytes, free space 9 bytes, window size 2097152 bytes
03-15 22:10:41.601 6909 21595 W CursorWindow: Window is full: requested allocation 67 bytes, free space 9 bytes, window size 2097152 bytes
03-15 22:10:42.432 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:43.304 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:44.156 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:45.015 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:45.881 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:46.758 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:47.643 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:48.537 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:49.442 6909 21595 W CursorWindow: Window is full: requested allocation 67 bytes, free space 9 bytes, window size 2097152 bytes
03-15 22:10:50.354 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 228 bytes, window size 2097152 bytes
03-15 22:10:51.275 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:52.206 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:53.143 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:54.087 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:55.041 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:56.005 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:56.980 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:57.961 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:58.950 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:10:59.944 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:11:00.959 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 205 bytes, window size 2097152 bytes
03-15 22:11:01.975 6909 21595 W CursorWindow: Window is full: requested allocation 408 bytes, free space 80 bytes, window size 2097152 bytes
03-15 22:11:02.981 6909 21595 D TransferService: 0 transfers are loaded from database
03-15 22:11:02.982 6909 21595 D TransferService: Stop self

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Hi @idhira, Thank you for your patience. We have fixed this issue in 2.6.16. Starting 2.6.16, the completed transfers will be automatically removed from the database when the transfer state reaches COMPLETED. Please let us know if this fixes the issue.
