### ISSUE TITLE
Use a server generated pre-signed url to upload a file to a bucket through the SDK

### ISSUE THREAD

**Issue by rahulsh12** [aws/aws-sdk-android#270]

**Comment by karthiksaligrama** [comment]
I'm not sure what you are looking for here? If your question is can i use server generated persigned url to upload a file to a bucket then yes thats possible.

**Comment by rahulsh12** [comment]
If my client is receiving a pre-signed url (signature, policy, key) from our servers for uploading/downloading a file from a bucket, is it possible to use any of the SDK's APIs (TransferUtility, TransferManager, others) to upload/download that file with the info of the pre-signed url ONLY ?
@karthiksaligrama

**Comment by karthiksaligrama** [comment]
you cant use presigned url with transfer manager or transfer utility, You need to use raw http client like `HttpsUrlConenction` or `OkHttp` for downloading contents from a pre-signed url.

**Comment by MujasSam** [comment]
Hi Karthik do you have any sample java code for this?

**Comment by mharis99** [comment]
you can directly access the preSigned URL with PUT request providing the following headers
Content-Type:image/jpeg (can be any of your type )
x-amz-acl:public-read
