### ISSUE TITLE
Upload does not timeout if internet access is down

### ISSUE THREAD

**Issue by timautin** [aws/aws-sdk-android#271]
Hi,

I'm using AWS to upload files to S3. I'd like the upload to timeout if the network is down. Currently if I shut down the WiFi during an upload, I receive a PAUSED state changed, followed by a WAITING_FOR_NETWORK state changed, and then nothing. I would expect the upload to be stopped after the socket timeout.

Not sure if this behavior is desired, but the on iOS SDK the timeout is respected. Here is my client configuration:

```
ClientConfiguration configuration = new ClientConfiguration();
configuration.setConnectionTimeout(30000);
configuration.setSocketTimeout(30000);
configuration.setMaxErrorRetry(2);
```

I'm using v2.2.11 of the SDK, on a Nexus 5X running Android 7.1.1. The problem also occurs on other devices / OS versions.

When I stop the WiFi, the following is printed in the logcat:

> 03-29 11:15:15.948 25431-28694/fr.largus.argus360 I/AmazonHttpClient: Unable to execute HTTP request: timeout
>                                                                       java.net.SocketTimeoutException: timeout
>                                                                           at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
>                                                                           at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
>                                                                           at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
>                                                                           at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
>                                                                           at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
>                                                                           at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
>                                                                           at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
>                                                                           at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
>                                                                           at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
>                                                                           at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
>                                                                           at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
>                                                                           at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
>                                                                           at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:517)
>                                                                           at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
>                                                                           at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java)
>                                                                           at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
>                                                                           at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
>                                                                           at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
>                                                                           at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
>                                                                           at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4212)
>                                                                           at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1619)
>                                                                           at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:194)
>                                                                           at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:76)
>                                                                           at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:41)
>                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>                                                                           at java.lang.Thread.run(Thread.java:761)
> 03-29 11:15:15.951 25431-28694/fr.largus.argus360 D/UploadTask: Transfer 2 is interrupted by user
> 03-29 11:15:42.428 25431-26154/fr.largus.argus360 D/TransferSerivce: Stop self

**Comment by karthiksaligrama** [comment]
This is by design. If the network goes down we pause the transfer and wait for connection to become active again. If the connection times out we fail the transfer. 

IOS sdk has a different design as compared to android.

**Comment by timautin** [comment]
Thanks for the answer!

So if I understood correctly, the socket timeout is used to trigger the state change, and the connection timeout should fail the transfer? If so, that's not the behavior I have. Once I shut down the WiFi and received the state change notification, I can wait forever, nothing happens and the transfer never fails. Is this by design too?

**Comment by mecoFarid** [comment]
@karthiksaligrama Why did you just close the ticket without giving any reference to the docs saying this is expected behaviour and how it should be resolved? The settings OP has posted implies we will get connection error or some kind of state change to `failure` but app gets stuck at this forever. Closing the question without a valid argument makes no sense. Just saying iOS and Android has different implementation and this is by design in Android is still not an answer to the problem
