### ISSUE TITLE
How to upload to the bucketname directory

### ISSUE THREAD

**Issue by wangshaolei** [aws/aws-sdk-android#275]
### How to upload to the bucketname directory
I dont find the API.
compile 'com.amazonaws:aws-android-sdk-s3:2.4.0'
thanks.

**Comment by karthiksaligrama** [comment]
this is not supported in the sdk today. you will ahve to iterate through the files in the directory and upload each file.

**Comment by wangshaolei** [comment]
@karthiksaligrama i think i have a problem, means of expression.
for example, dashboard i have a custom ddirectory under the bucket. i want to upload the file to the directory. if the directory dont exist, and auto create the directory.

understand me? thanks

**Comment by karthiksaligrama** [comment]
so say you want to upload a file called b.txt  in a directory A and A is not present, You simply set the key name of the file as A/b.txt and it will auto create that directory for you on s3.

**Comment by wangshaolei** [comment]
@karthiksaligrama

**Comment by wangshaolei** [comment]
@karthiksaligrama 
my code:
final TransferObserver transferObserver = transferUtility.upload(BUCKET_NAME, "android111111" + "/" + srcFile.getName(), srcFile);
but errormessage:
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.ca-central-1.amazonaws.com": No address associated with hostname

**Comment by karthiksaligrama** [comment]
You cognito region is set to ca-central-1. Cognito is not supported in CA-CENTRAL-1 as of today. SO you need to use a cognito from a different region.

**Comment by wangshaolei** [comment]
@karthiksaligrama thanks~
