### ISSUE TITLE
proguard issue with android-sdk-s3 which use org.bouncycastle

### ISSUE THREAD

**Issue by iam1492** [aws/aws-sdk-android#276]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
`
compile 'com.amazonaws:aws-android-sdk-s3:2.4.0'
compile 'com.amazonaws:aws-android-sdk-core:2.4.0'
compile 'com.amazonaws:aws-android-sdk-cognito:2.4.0'
`
* In what version of SDK are you facing the problem?
`compile 'com.amazonaws:aws-android-sdk-s3:2.4.0'`

* Is the issue limited to Simulators / Actual Devices?
It's proguard issue. Not device.

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
having a proguard issue when build.

* Please include a stacktrace if applicable.

Following warning is stopping build.
`
Warning: org.bouncycastle.jce.provider.X509LDAPCertStoreSpi: can't find referenced class javax.naming.NamingEnumeration
Warning: org.bouncycastle.jce.provider.X509LDAPCertStoreSpi: can't find referenced class javax.naming.NamingException
Warning: org.bouncycastle.jce.provider.X509LDAPCertStoreSpi: can't find referenced class javax.naming.directory.Attribute
Warning: org.bouncycastle.jce.provider.X509LDAPCertStoreSpi: can't find referenced class javax.naming.directory.Attributes
...
...
Warning: org.bouncycastle.x509.util.LDAPStoreHelper: can't find referenced class javax.naming.directory.DirContext
`

If I add following to my proguard rule file the above error disappeared. But I'm not sure that I can remove the warning with this option.
`-dontwarn org.bouncycastle.**`

If I add keep class option to proguard rule then too method count problem is occur. What is good solution? 
If it is no problem to add `-dontwarn org.bouncycastle.**` then please update your proguard.md file.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
Hello, We are aware about the issue and will be fixed with 2.4.1 SDK release.

Thanks,
Rohan

**Comment by karthiksaligrama** [comment]
fixed with 2.4.1
