### ISSUE TITLE
hi, Failed to upload

### ISSUE THREAD

**Issue by wangshaolei** [aws/aws-sdk-android#279]
### Failed to upload: 4 due to Unable to execute HTTP request: Unable to resolve host "cognito-identity.ca-central-1.amazonaws.com": No address associated with hostname

today happen， the other day is well

**Comment by rohandubal** [comment]
Hi,

This is due to the region being incorrectly set for your cognito identity user pool. In your application code, please set the Cognito Identity region to the correct region. Your pool id should have the region at the start of pool id string.

Thanks,
Rohan

**Comment by wangshaolei** [comment]
@rohandubal thanks, i will try agin, keep in touch

**Comment by wangshaolei** [comment]
@rohandubal but iOS the same config is well, and upload success.  android is bad.

**Comment by wangshaolei** [comment]
@rohandubal hi,
1 Create a identity pool
2 Authentication providers -> User Pool ID and App Client ID?
config this? user pool id, how setting?

**Comment by wangshaolei** [comment]
how can i create ca-central-1 user pool

**Comment by wangshaolei** [comment]
@rohandubal i cant select ca-center-1 that in create user pool id , why.
