### ISSUE TITLE
Get File Url after upload

### ISSUE THREAD

**Issue by marcoRS** [aws/aws-sdk-android#28]
Hello, What is the proper way to obtain a file's url after an upload?

**Comment by fosterzhang** [comment]
The url of the uploaded file is at https://\<bucket>.s3.amazonaws.com/\<key>. If you want a presigned URL, please refer to http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#generatePresignedUrl(java.lang.String,%20java.lang.String,%20java.util.Date,%20com.amazonaws.HttpMethod).
