### ISSUE TITLE
Hi upload fail

### ISSUE THREAD

**Issue by wangshaolei** [aws/aws-sdk-android#280]
### Failed to upload: 4 due to Unable to execute HTTP request: Unable to resolve host "cognito-identity.ca-central-1.amazonaws.com": No address associated with hostname

i cant create ca-center-1 user pool, and the same COGNITO_POOL_ID, BUCKET_NAME,Regions.CA_CENTRAL_1 , that iOS is well and Android is bad. why?

**Comment by rohandubal** [comment]
Hi,

Cognito is not available in CA Central 1. You should be using the correct region where you Identity Pool Exists. The following regions are supported: http://docs.aws.amazon.com/general/latest/gr/rande.html#cognito_identity_region 

Thanks,
Rohan
