### ISSUE TITLE
External Libraies Bug

### ISSUE THREAD

**Issue by wangshaolei** [aws/aws-sdk-android#282]
### External Libraies Bug

why compile 'com.amazonaws:aws-android-sdk-s3:2.4.1  include 1_commons-io-1.3.2 and commons-io-1.3.2， i understand, that cause gradle error?

**Comment by mlshon** [comment]
What SDK version are you using?
Try using the latest version.

**Comment by wangshaolei** [comment]
@mlshon hi, i use sdk version com.amazonaws:aws-android-sdk-s3:2.4.1
what's the last version

**Comment by mlshon** [comment]
2.4.1 is the latest version.
I listed `com.amazonaws:aws-android-sdk-s3:2.4.1` as a dependency in my gradle file and there was no gradle error.

**Comment by wangshaolei** [comment]
@mlshon but, i use com.amazonaws:aws-android-sdk-s3:2.4.1 that include 1_commons-io-1.3.2 and commons-io-1.3.2 at the same time.
i must use  for example
```java
 compile('com.amazonaws:aws-android-sdk-s3:2.4.1') {
        exclude module: 'commons-io'
    }
```

**Comment by mlshon** [comment]
Can you paste your gradle?
I am not able to reproduce this error you're getting.

**Comment by minbi** [comment]
AWS SDK for Android v2.4.1 has been released
