### ISSUE TITLE
Best practice to upload multiple files at once?

### ISSUE THREAD

**Issue by gajicm93** [aws/aws-sdk-android#285]
I have a requirement to upload multiple photos from an Android device to S3 "at once", where multiple might be hundreds, and also, I'm interested in only tracking the upload progress for the whole group of photos, not everyone of them individually..
In general, zipping them in a single file, and then just uploading the zip would do the thing, but that's not an option for me for multiple reasons?

So what would be the best practice for this? Is there any better way to achieve this than starting 300 upload jobs in a for loop?

**Comment by mlshon** [comment]
Hi, this is not something that we provide so you'll have to implement something on your own.

**Comment by gajicm93** [comment]
@mlshon I see that deprecated TransferManager had a feature like this, MultipleFileUpload? There's nothing like it in TransferUtility?
