### ISSUE TITLE
How can we generate auth header for S3 secure URL's 

### ISSUE THREAD

**Issue by rahulgautam** [aws/aws-sdk-android#29]
Feature Request:

Currently SDK provides feature to get the preSignedURL.
But we also need that the SDK should provide a way to generate [authentication header](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#ConstructingTheAuthenticationHeader).

 That will enable these secure URL's to be downloaded and cached easily with all the image cache libraries available for example picasso, ion, UIL etc.

Thanks

**Comment by fosterzhang** [comment]
Would you please elaborate authentication header? How do you use it?

**Comment by rahulgautam** [comment]
Yeah Sure,

By [Authentication Header](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#ConstructingTheAuthenticationHeader) I mean `Authorization: AWS AWSAccessKeyId:Signature` header that I can set for a request.

Why I want this?
Because I want to use image download and cache libraries like picasso, ion, UIL.
These does not work with query string authentication technique for a given image URL.

I find that [AWS4Signer](https://github.com/aws/aws-sdk-android/blob/master/src/main/java/com/amazonaws/auth/AWS4Signer.java) and AWS3Signer in AWS Android SDK has methods to create a `Authorization` header value. But not exposed.

Thanks

**Comment by fosterzhang** [comment]
OK. We will take this into consideration.

**Comment by sumitsahu2207** [comment]
I'm also looking for helper classes which can be used to generate aws signature version 4 requests for REST API.
Please suggest

**Comment by angli13** [comment]
This is so important in android's workflow, it is such a pain to get the object only to show an image.
