### ISSUE TITLE
Iot Android Mobile SDK - AWSIotClient.setRegion Broken

### ISSUE THREAD

**Issue by ckerkhoff** [aws/aws-sdk-android#290]
Using AWSIotClient.setRegion() breaks the endpoint URL. When trying to set the region to us-west-2 the resulting endpoint becomes https://execute-api.us-west-2.amazonaws.com which doesn't work. Changing the endpoint to https://iot.us-west-2.amazonaws.com works.  Alternatively, changing serviceName to iot before calling setRegion and back to execute-api afterwards works as well.

**Comment by rohandubal** [comment]
Hi,

Thank you for reporting this issue. We will update the thread once we fix it.

Thanks,
Rohan

**Comment by karthiksaligrama** [comment]
resolved with 2.4.3
