### ISSUE TITLE
Upload file to S3 synchronously

### ISSUE THREAD

**Issue by gusavila92** [aws/aws-sdk-android#291]
Hi.

I've been using the Amazon S3 SDK for Android without any problems so far. My next goal is to upload a file to S3 synchronously implementing my own thread, but I don't know how to do this. Documentation is not clear in this aspect.

Thanks.

**Comment by defaultbr** [comment]
i was looking for this thing too, i did a method that i pass the file position and it take from a previsoly populated list (mediaFiles.listFiles()), for example:

```
File[] list_of_files = source_folder.listFiles();

public void doUpload(int position) {
currentObserver = AmazonS3Utils.transferFileToBucket(transferUtility, list_of_files.get(position), new AmazonTransferCallBack() {
...
if (state == TransferState.COMPLETED) {
                                uploadNextFile(position + 1);
                            } else if (state == TransferState.CANCELED) {
                                uploadNextFile(position + 1);
  } else if (state == TransferState.FAILED) {
                                uploadNextFile(position + 1);

                            } else if (state == TransferState.WAITING_FOR_NETWORK) {
                                transferUtility.cancel(currentObserver.getId()); //cancel and start next
                                uploadNextFile(position + 1);

                            }
}
```

so i start it calling `doUpload(0)`  and depending which state its is (im using the ones above), it upload the next file. Its not the perfectly, the most beautiful, but its working

of course add some null check(i delete the file on finish) before starting the upload

**Comment by minbi** [comment]
If the provided code does not suit your case or if you have a different use case, please re-open this issue.

**Comment by gusavila92** [comment]
I managed to do it using thread signaling with wait() and notify(). It introduces a lot of boilerplate code but it works. Although, I think that you should implement in future releases a more straightforward way to do this. It would be great!

**Comment by defaultbr** [comment]
would be better to change aws-sdk-android to do it sync and the dev handle it


today is so easy to sync things in the background, eg: kotlin + anko

```
async(UI) {
val result = bg { uploadFileAndMethodAndGetReturn(file) }.await()
}
```

:octopus:
