### ISSUE TITLE
S3 putObject: Colon (":") is handled incorrectly and produce misleading access denied error

### ISSUE THREAD

**Issue by kemsky** [aws/aws-sdk-android#294]
Policy part:

```
"Resource": [
                "arn:aws:s3:::bucket-test-1/vacancy/${cognito-identity.amazonaws.com:sub}/*"
            ]
```

`${cognito-identity.amazonaws.com:sub}` is user `IdentityId`, which always *has* a colon (i.e. `eu-west-2:cedbe8f4-8fc8-4946-964f-767328d1e4a3`).

Currently, `putObject` does not work in this scenario and throws Access Denied (huh?).

If i remove `${cognito-identity.amazonaws.com:sub}` constraint from policy, then file is created, *but* actual folder name will have colon replaced by `%3A` and it becomes clear why policy rejected request. 

aws cli does not have this problem (using same credentials, bucket etc.).

**Comment by minbi** [comment]
Hi @kemsky ,

I could not reproduce your issue. The following is my configuration which may help.

Policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::s3uploadbug",
                "arn:aws:s3:::s3uploadbug/folder:colon/*"
            ]
        }
    ]
}
```

Code:
```
File file = new File(filePath);

AmazonS3Client client = new AmazonS3Client(new CognitoCachingCredentialsProvider(
        getApplicationContext(),
        Constants.COGNITO_POOL_ID,
        Regions.fromName(Constants.COGNITO_POOL_REGION)));
client.putObject(new PutObjectRequest(Constants.BUCKET_NAME, "folder:colon/new:colon.jpg", file));

for (S3ObjectSummary summary : client.listObjects(Constants.BUCKET_NAME).getObjectSummaries()) {
    System.out.println("key: " + summary.getKey());
}

// TransferObserver observer = transferUtility.upload(Constants.BUCKET_NAME, "folder:colon/abc:colon.jpg", file);
```

**Comment by kemsky** [comment]
You should check actual folder name in S3 since client may do `urlEncode`/`urlDecode` and show 'correct' key.

**Comment by minbi** [comment]
I am seeing the correct file names being displayed in the browser.

Why version of SDK are you using? Please try 2.4.2 if possible.
Has the key you specified to the client already have url encoding?

**Comment by kemsky** [comment]
I was using 2.4.0 and update to 2.4.2 fixed this problem.

`Amazon S3: fixed an issue which caused resource path to be incorrectly encoded.`

Well, things are changing too fast :)
