### ISSUE TITLE
java.lang.IllegalArgumentException' exception. Cannot evaluate $Proxy1.toString()

### ISSUE THREAD

**Issue by shaivyaaggarwal** [aws/aws-sdk-android#296]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
aws api gateway

* In what version of SDK are you facing the problem?
2.4.2

* Is the issue limited to Simulators / Actual Devices?
Yes

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I have called the get method inside an AsyncTask and it gives me the exception. The code for AuthClient is as follows - 
```android
@com.amazonaws.mobileconnectors.apigateway.annotation.Service(endpoint = "myApi")
public interface HRISauthClient {

    /**
     * A generic invoker to invoke any API Gateway endpoint.
     *
     * @param request
     * @return ApiResponse
     */
    com.amazonaws.mobileconnectors.apigateway.ApiResponse execute(com.amazonaws.mobileconnectors.apigateway.ApiClientFactory request);

    /**
     * @return Output
     */
    @com.amazonaws.mobileconnectors.apigateway.annotation.Operation(path = "/", method = "GET")
    Empty rootGet();
}
```

And my code inside the Async task is -

```android
private class HRISauth extends AsyncTask<Void, Void, Void> {
        @Override
        protected Void doInBackground(Void... params) {
            ApiClientFactory factory = new ApiClientFactory();
            final HRISauthClient client = factory.build(HRISauthClient.class);
            Empty obj = client.rootGet();
            return null;
        }
    }
```

* Please include a stacktrace if applicable.
Method threw 'com.amazonaws.mobileconnectors.apigateway.ApiClientException' exception. Cannot e
```valuate $Proxy1.toString()

**Comment by MayaShen** [comment]
Hi shaivyaaggarwal,
Have you resolved the issue? I run into the same issue and haven't found any solution yet.

**Comment by shaivyaaggarwal** [comment]
Hi MayaShen, 

The issue actually exists in their code so couldn't fix it.
Though my code works without fixing it.

**Comment by MayaShen** [comment]
Thanks, shaivyaaggarwal!
I followed aws tutorial, and I found the reason that I was unable to get the proper result back is because the model and the lambda output in the tutorial don't match. Once I changed the model the problem was gone. But same as you said the exception is still there and it doesn't block the execution.

**Comment by btackney** [comment]
How did you solve this issue? Im expereincing the same error even using a blank app with exact code from tutorial https://aws-amplify.github.io/docs/android/api.

**Comment by Gingeskahn18** [comment]
# Push - i have the same Problem here
