### ISSUE TITLE
Amazon Lex Doesn't Support All ABIs

### ISSUE THREAD

**Issue by sewar** [aws/aws-sdk-android#298]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Amazon Lex

* In what version of SDK are you facing the problem?
2.4.2

* Is the issue limited to Simulators / Actual Devices?
Actual Devices

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Test on an Android device with CPU architecture arm64-v8a, x86_64, mips or mips64.

* Please include a stacktrace if applicable.
```
FATAL EXCEPTION: Thread-9
 Process: com.app, PID: 951
 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.app-1/lib/arm64, /data/app/com.app-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libblueshift-opus.so"
     at java.lang.Runtime.loadLibrary0(Runtime.java:984)
     at java.lang.System.loadLibrary(System.java:1562)
     at com.amazon.blueshift.bluefront.android.audio.encoder.OpusEncoder.<clinit>(OpusEncoder.java:77)
     at com.amazonaws.mobileconnectors.lex.interactionkit.internal.audio.LexAudioRecorderBuilder.<init>(LexAudioRecorderBuilder.java:56)
     at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient$1.run(InteractionClient.java:313)
     at java.lang.Thread.run(Thread.java:761)
```

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by sewar** [comment]
To clarify, libblueshift-opus.so and libblueshift-audioprocessing.so are not included for arm64-v8a, x86_64, mips or mips64 ABIs. If you have any other native library with the device ABI included then Android will use it and crash for missing libraries.

**Comment by jamesatfish** [comment]
I've raised the same issue with AWS Support, as we're developing Lex applications for Samsung S7/S8 devices (arm64-v8a) and this is a showstopper.

Unfortunately no potential resolution as yet, just an acknowledgment they are aware of the issue.

**Comment by minbi** [comment]
libblueshift-opus.so has been released for arm64-v8a, x86_64, mips and mips64 architectures

**Comment by minbi** [comment]
Please re-open if they don't work for you

**Comment by alexgblanco** [comment]
@minbi What do you mean it has been released? Where do I get it?  Thanks.

**Comment by minbi** [comment]
@alexgblanco ,

AWS SDK for Android version 2.6.0 has been released.

In your gradle file dependencies, please use:
```
compile('com.amazonaws:aws-android-sdk-lex:2.6.0@aar') { transitive = true; }
```
