### ISSUE TITLE
Jackson is still used in 2.1.9

### ISSUE THREAD

**Issue by SoMCUSDev** [aws/aws-sdk-android#30]
According to the http://aws.amazon.com/releasenotes/0908276529378471 one of the changes is: Replacing Jackson with Gson 2.2.4 in the core runtime library. The file size is reduced to 1.3Mb and the total number of methods is down to 7.5k. Improve the performance of unmarshalling Json responses. 

However, jackson-core-2.1.1.jar is still part of the SDK binary release and it's used in the https://github.com/aws/aws-sdk-android/blob/master/src/main/java/com/amazonaws/util/json/JacksonFactory.java

Should it be removed?

**Comment by ddrscott** [comment]
I'm hitting the `LinearAlloc exceeded capacity (5242880)` issue and I believe removing Jackson would be an easy size savings. Especially if there's already a different serialization library getting used.

**Comment by fosterzhang** [comment]
Jackson is used to compile the SDK, but is no longer part of the core runtime. You don't need it to use the SDK. In fact, you have the option to use Jackson as the Json engine (not fully supported yet).
