### ISSUE TITLE
Unable to set credentials to CognitoCachingCredentialsProvider

### ISSUE THREAD

**Issue by patelrohan22** [aws/aws-sdk-android#300]
How to set accessKeyId, cognitoToken, secretKey and sessionToken to CognitoCachingCredentialsProvider?

Didn't find setter or constructor?

**Comment by jbailey2010** [comment]
The credentials provider is meant to get you these credentials, there isn't a way to pass some arbitrary set in. It's meant to use Cognito's scoped down credentials, and allowing any arbitrary set would not follow that use case. If that's a hard blocker, you may be better off using an arbitrary AWS credentials provider.
