### ISSUE TITLE
I can not found unlinkIdentity function anywhere in the code  ,but there had descriptions in doc

### ISSUE THREAD

**Issue by 1983suiyi** [aws/aws-sdk-android#302]
I can not found unlinkIdentity function anywhere in the code  ,but there had descriptions in doc.is there anybody know this ?

**Comment by kvasukib** [comment]
Hi @1983suiyi,

Can you point us the document which refers it?

**Comment by KateLeeCandy** [comment]
https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_UnlinkIdentity.html

**Comment by KateLeeCandy** [comment]
Why android SDK not correspond it

**Comment by KateLeeCandy** [comment]
https://github.com/aws-amplify/aws-sdk-android/issues/645
