### ISSUE TITLE
There should be a way to invoke a particular version/alias of a lambda function, without duplicating the interface for each version/alias

### ISSUE THREAD

**Issue by Dretch** [aws/aws-sdk-android#303]
I want to have my android integration tests invoke the `DEV` versions of my lambda functions, but otherwise I want my app to use the `PROD` versions.

This requires changing the alias at runtime. At the moment it seems like I would need to duplicate each `@LambdaFunction` interface, give each duplicate a different `qualifier`, and select the correct interface at runtime in my android app. This would be an awful lot of boilerplate.

The regular Java SDK has a `LambdaInvokerFactory.Builder` class [0] that looks like it would solve this problem, but alas, this class does not exist in the android SDK (`com.amazonaws:aws-android-sdk-lambda:2.4.3`). Would it be possible to add this class?

[0] https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/lambda/invoke/LambdaInvokerFactory.Builder.html

**Comment by kvasukib** [comment]
H @Dretch,

Thanks for pointing it out. We are taking it as a feature request.

**Comment by Dretch** [comment]
Awesome, thanks!

**Comment by fahmad2** [comment]
Hi All,

Can someone update on the status of this feature request?
