### ISSUE TITLE
Model schema for model ErrorResponse_errorResponse is not supported by SDK generation. Please ensure object schemas contain 'properties' and array schemas contain 'items'

### ISSUE THREAD

**Issue by jagdish-176** [aws/aws-sdk-android#307]
I'm using '$ref' to refer schema definition and also its nested schema, but its giving me error.

* What service are you using?
Api Gateway

* In what version of SDK are you facing the problem?
Latest on API gateway

* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific Android/OS version?
No
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
1) Use following schema for sdk
`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "errorDefinition": {
      "id": "/properties/errorResponse",
      "properties": {
        "category": {
          "id": "/properties/errorResponse/properties/category",
          "type": "string"
        },
        "causedBy": {
          "type": "object",
          "$ref": "#/definitions/errorDefinition"
        }
      },
      "type": "object"
    }
  },
  "id": "errorSchema",
  "properties": {
    "errorResponse": {
      "$ref": "#/definitions/errorDefinition"
    }
  },
  "type": "object"
}
`
2) Map to any end point response
3) Error will popup saying
 Model schema for model ErrorResponse_errorResponse is not supported by SDK generation. Please ensure object schemas contain 'properties' and array schemas contain 'items'

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by mlshon** [comment]
Hi,
take a look at the [example model](http://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-models.html#getting-started-models-add-models).
You can see how `properties` and `items` is used.

**Comment by bhaskardabhi-oviyum** [comment]
I am getting same error. Same model was working before now its throwing error.
`--- 
properties: 
  activities: 
    items: 
      $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverActivityData"
    type: array
  allowed: 
    type: boolean
  asset: 
    $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/Asset"
  assetID: 
    description: "Asset id of handover"
    type: integer
  completedAt: 
    description: "Time when Handover was completed"
    type: string
  contractID: 
    description: "Contract ID of Handover"
    type: integer
  from: 
    $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromTo"
  fromID: 
    description: "From ID who is meant to be handover the asset"
    type: integer
  handedBy: 
    $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromTo"
  handedByID: 
    description: "ID of Person who handed asset to the person"
    type: integer
  handedByType: 
    $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromToType"
  handedByTypeID: 
    description: "Type ID of Person who handed asset to another person"
    type: integer
  handedTo: 
    $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromTo"
  handedToID: 
    description: "ID of Person whom asset was handed"
    type: integer
  handedToType: 
    $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromToType"
  handedToTypeID: 
    description: "Type ID of Person whom asset was handed"
    type: integer
  handoverStatus: 
    $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverStatus"
  handovers: 
    items: 
      $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/Handover"
    type: array
  id: 
    description: "Unique identifier for Handover"
    type: integer
  parentID: 
    description: "Handover ID of parent"
    type: integer
  scheduledAt: 
    description: "Time when Handover is scheduled"
    type: string
  sequenceNumber: 
    description: "sequence Number of handover"
    type: integer
  status: 
    description: "Status of handover"
    type: integer
  template: 
    $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverTemplate"
  templateID: 
    description: "Template id of handover"
    type: integer
  to: 
    $ref: "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromTo"
  toID: 
    description: "To ID to which asset is meant to be handovered"
    type: integer
required: 
  - assetID
  - fromID
  - handedByID
  - handedByTypeID
  - handedToID
  - handedToTypeID
  - id
  - parentID
  - scheduledAt
  - sequenceNumber
  - status
  - templateID
  - toID
type: object
`
I don't think anything is wrong with the model.

**Comment by bhaskardabhi-oviyum** [comment]
I am getting same issue. Same model was working before now its throwing error.
`{
	"type": "object",
	"required": [
		"assetID",
		"fromID",
		"handedByID",
		"handedByTypeID",
		"handedToID",
		"handedToTypeID",
		"id",
		"parentID",
		"scheduledAt",
		"sequenceNumber",
		"status",
		"templateID",
		"toID"
	],
	"properties": {
		"id": {
			"type": "integer",
			"description": "Unique identifier for Handover"
		},
		"templateID": {
			"type": "integer",
			"description": "Template id of handover"
		},
		"assetID": {
			"type": "integer",
			"description": "Asset id of handover"
		},
		"fromID": {
			"type": "integer",
			"description": "From ID who is meant to be handover the asset"
		},
		"toID": {
			"type": "integer",
			"description": "To ID to which asset is meant to be handovered"
		},
		"handedByTypeID": {
			"type": "integer",
			"description": "Type ID of Person who handed asset to another person"
		},
		"handedToTypeID": {
			"type": "integer",
			"description": "Type ID of Person whom asset was handed"
		},
		"handedByID": {
			"type": "integer",
			"description": "ID of Person who handed asset to the person"
		},
		"handedToID": {
			"type": "integer",
			"description": "ID of Person whom asset was handed"
		},
		"parentID": {
			"type": "integer",
			"description": "Handover ID of parent"
		},
		"sequenceNumber": {
			"type": "integer",
			"description": "sequence Number of handover"
		},
		"scheduledAt": {
			"type": "string",
			"description": "Time when Handover is scheduled"
		},
		"completedAt": {
			"type": "string",
			"description": "Time when Handover was completed"
		},
		"status": {
			"type": "integer",
			"description": "Status of handover"
		},
		"contractID": {
			"type": "integer",
			"description": "Contract ID of Handover"
		},
		"handoverStatus": {
			"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverStatus"
		},
		"from": {
			"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromTo"
		},
		"to": {
			"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromTo"
		},
		"asset": {
			"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/Asset"
		},
		"handedByType": {
			"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromToType"
		},
		"handedToType": {
			"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromToType"
		},
		"handedBy": {
			"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromTo"
		},
		"handedTo": {
			"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverFromTo"
		},
		"template": {
			"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverTemplate"
		},
		"activities": {
			"type": "array",
			"items": {
				"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/HandoverActivityData"
			}
		},
		"handovers": {
			"type": "array",
			"items": {
				"$ref": "https://apigateway.amazonaws.com/restapis/zptprbq0fe/models/Handover"
			}
		},
		"allowed": {
			"type": "boolean"
		}
	}
}`
