### ISSUE TITLE
regions.xml, awssdk_config_default.json & mimetypes.xml should be deleted?

### ISSUE THREAD

**Issue by SoMCUSDev** [aws/aws-sdk-android#31]
Looks like after rework in 2.1.9 those 3 files are no longer needed:
https://github.com/aws/aws-sdk-android/blob/master/src/main/resources/mime.types
https://github.com/aws/aws-sdk-android/blob/master/src/main/resources/awssdk_config_default.json
https://github.com/aws/aws-sdk-android/blob/master/src/main/resources/com/amazonaws/regions/regions.xml
& this particular constant is no longer used: https://github.com/aws/aws-sdk-android/blob/master/src/main/java/com/amazonaws/regions/RegionUtils.java#L43 as well

**Comment by fosterzhang** [comment]
We will remove three non java files in the coming release. RegionUtils is still needed, but it's possible to be removed.

**Comment by SoMCUSDev** [comment]
RegionUtils.java is a valid one as a whole. I was talking about one constant:
  private static final String FALLBACK = "regions.xml"; (https://github.com/aws/aws-sdk-android/blob/master/src/main/java/com/amazonaws/regions/RegionUtils.java#L41).
I think it should be removed if regions.xml is removed.

**Comment by fosterzhang** [comment]
regions.xml and awssdk_config_default.json are removed in v2.2.0 release. mime.types is still there as a reference.
