### ISSUE TITLE
The specified key does not exist after 2.3.9

### ISSUE THREAD

**Issue by maxbax** [aws/aws-sdk-android#310]
After version 2.4.1 (I think for this forum question https://forums.aws.amazon.com/thread.jspa?threadID=252898) our upload system doesn't work. It works until 2.3.9 sdk Android library version.
The problem is that upload function encodes key and we can't download the file in the future. 

If in the key we use spaces or other encodeble chars (in the key we specify the file name), the library during upload encodes the key and the saves the file with chars encoded.

For example if we pass the key "File Test 123.pdf" to the upload function we receive the next effects in the bucket:

- with 2.3.9 version "File Test 123.pdf" file saved
- with 2.4.1 or later "File%20Test%20123.pdf" file saved

When I try to use url with that key (something like this https://....s3.amazonaws.com/u/0/....../File%20Test%20123.pdf?Signature=....) I can download the first file, but I receive an "The specified key does not exist" error with the second. 

I think the key have to remains the same as I passed to the upload function and so I aspected to find in the bucket the file with that alias

Thanks,
Max

**Comment by mlshon** [comment]
Hi, thanks for reporting this to us.  We will take a look!

**Comment by acarlsen** [comment]
I have the same issue. Seems to be no way to avoid the url encoding if you have spaces in object key name. They will get displayed as %20 in S3 console. If I create a folder with spaces in name in console it displays normally.

**Comment by kvasukib** [comment]
Thanks, @acarlsen for reporting this to us. We are working on it.

**Comment by minbi** [comment]
Version 2.4.5 has been release with a fix.

**Comment by maxbax** [comment]
The version 2.4.5 resolve the space problem but not the general problem. If I write a special char into key string the upload doesn't work well.
The problem is not only for space, but for all special chars.
For example you can use "😂" as key

**Comment by apiraino** [comment]
@minbi @kvasukib can we have a confirmation on whether the comment of @maxbax? We need to update the Android SDK because of this issue and we're not sure whether it's completely fixed.

Thanks for your feedback!

**Comment by defaultbr** [comment]
just to mention, with 2.3.9 my file can have special char at name like: 'Saída', while 3.4.3 cant (The file is never uploaded to s3)

**Comment by kwong93** [comment]
I can also confirm, I uploaded file with the key 2017-08-01@02-47-38-M-10666-e713e147-a58a-4327-920a-b3ea006c15de.jpg and it converted the '@' symbol to %40.

**Comment by fulingfan** [comment]
on 2.6.15 version will converted the '@' symbol to %40，can fix it？

**Comment by ajayprakashshukla** [comment]
I think there is space at a encoding time, that's why there showing %20. When we can remove space then there not will be show %20.
