### ISSUE TITLE
Android SDK - DynamoDB Boolean

### ISSUE THREAD

**Issue by atnegrete** [aws/aws-sdk-android#313]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
DynamoDB

* In what version of SDK are you facing the problem?
2.4.2

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
Android

I am having issues with the Bolean attribute type, when I save items to the database all the Boolean attributes get converted to Number (0 or 1) on the database. 

From documentation I found that:
Boolean	N (number type), 0 or 1.
Alternatively, you can use @DynamoDBNativeBooleanType to map a Java Boolean to the DynamoDB BOOL data type. For more information, see Java Annotations for DynamoDB.)

But @DynamoDBNativeBoolean is not working, not sure what's going on. 

Here's what I have
```
@DynamoDBAttribute(attributeName = "completed")
@DynamoDBNativeBoolean
public Boolean getCompleted() {
return _completed;
}
public void setCompleted(final Boolean _completed) {
this._completed = _completed;
}
```
Thanks

**Comment by kvasukib** [comment]
Hello @atnegrete ,

Thanks for reporting to us. We are looking into it.

**Comment by kvasukib** [comment]
Can you elaborate on what is not working? Is the value in _completed not getting stored in the database?

As per http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/dynamodb_om.html,
Note that _completed is a nullable type. With the DynamoDB Object Mapper, primitives and nullable types behave differently. On a save(), an unset nullable type is not sent to DynamoDB; an unset primitive is sent as its default value.

Can you check if the variable is set before save() is called?

**Comment by atnegrete** [comment]
Yeah, the Boolean value is getting set before save()

The value on the database somehow gets converted from Boolean to Number. It gets converted to 1 if the value was true and 0 if it was false.

**Comment by minbi** [comment]
It looks like you have a typo. `@DynamoDBNativeBoolean`*Type*

**Comment by atnegrete** [comment]
Yes I mentioned I saw that for Java, but I think for the Android SDK it's only @DynamoDBNativeBoolean ?

@DynamoDBNativeBooleanType doesn't exist

**Comment by atnegrete** [comment]
I just want to mention I have been using **@dynamodbnativeboolea** & it doesn't work

**Comment by minbi** [comment]
There does not appear to be anything wrong with your code. I have tried similar with the following code and console shows "true" and "false":

```
@DynamoDBAttribute(attributeName = "boolTest")
@DynamoDBNativeBoolean
public Boolean getBoolTest() {
        return _boolTest;
}
```

DynamoDB service may have implemented fixes in the time that has elapsed. We're sorry we could not address this fully.
