### ISSUE TITLE
AmazonCognitoAuthDemo doesn't build, gets "Failed to resolve: :aws-android-sdk-cognitoauth-2.4.4" 

### ISSUE THREAD

**Issue by banshee** [aws/aws-sdk-android#318]
If you open the AmazonCognitoAuthDemo project in Android Studio Canary 6 (as of commit ddde5dcef89f66c068e97c672cd4bf361be5dac2), you get:

Failed to resolve: :aws-android-sdk-cognitoauth-2.4.4

**Comment by minbi** [comment]
You can replace the dependency in build.gradle with:
`compile 'com.amazonaws:aws-android-sdk-cognitoauth:2.4.4@aar'`

**Comment by minbi** [comment]
Assuming this issue has been resolved.
