### ISSUE TITLE
2.1.9 Gson is include in core instead of being simple dependency

### ISSUE THREAD

**Issue by niqo01** [aws/aws-sdk-android#32]
I was wondering why is Gson repackaged and included in core instead of being declared as simple outside dependency which user would add themselves?

I am personally using Gson 2.2.4 in my Android project too, it's sad my project now include Gson twice.

**Comment by niqo01** [comment]
Would it be easy to build a version -core-no-deps?

**Comment by fosterzhang** [comment]
Your request is heard. We'll evaluate this option. As a short term solution, you can build the core jar yourself following the https://github.com/aws/aws-sdk-android/blob/master/README.md
