### ISSUE TITLE
How can use the s3 TransferUtility for multiprocessing ? 

### ISSUE THREAD

**Issue by eggcaker** [aws/aws-sdk-android#322]
for upload file to s3, I was using the TransferUtility with define a service in Androidmanifet file 
``` xml
<service android:name= "com.amazonaws.mobileconnectors.s3.transferutility.TransferService" android:enabled="true"  />
```
it's working without any problem. But when I add multiprocess in my app.  I have two places to call 
the transferutility to upload file: 

1: ui process with activity 
2: :data process with service 

right now, I only can use the uploader with one process, it's possible to define 2 TransferService with process ?

**Comment by kvasukib** [comment]
Hi @eggcaker, Thanks for reporting to us. You need not define TransferService twice. You can continue to call uploadFile from multiple places.

**Comment by jeffreyfjohnson** [comment]
@kvasukib I also cannot use `TransferUtility` to upload files outside of the process the `TransferService` is assigned to in the manifest. To be specific:

I define transfer utility like so:
```
<service
            android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
            android:process=":sync"/>
``` 

When I call `transferUtility.upload()`, the `TransferObserver`'s state never changes from `WAITING`. When I remove `android:process=":sync"` from the manifest, it works
