### ISSUE TITLE
Unable to access the same collection in rekognition

### ISSUE THREAD

**Issue by ez2k1** [aws/aws-sdk-android#323]
I have created an android mobile app which creates a rekognition collection using BasicAWSCredentials call with a access key and secret key.  It is successful.

```
BasicAWSCredentials credentials = new BasicAWSCredentials("xyz","abc");
client = new AmazonRekognitionClient(credentials);

CreateCollectionRequest request = new CreateCollectionRequest()
                            .withCollectionId("testcollection");
CreateCollectionResult result = client.createCollection(request);

```

I am have a EC2 instance which has AWS CLI and I have used `aws configure ` to setup the same access key and secret key.  When I try 

`aws rekognition list-collections`

I dont see the created collection.  Why?  What is happening?  Where collection is presisted?  How to access the same collection created from mobile in an EC2 instance or in a python code?

**Comment by kvasukib** [comment]
Hi @ez2k1,

Thanks for reporting to us. Can you login to the AWS Console and check if the collection is displayed?

**Comment by ez2k1** [comment]
Hi @kvasukib,

I dont know how to see the collections in AWS console.  I have been using the API or CLI to list the collections.  I do understand that it is supposed to have an arn.  How do I see the collections in AWS console?

**Comment by rohandubal** [comment]
Hello @ez2k1 
Are you getting any error in the Android debug output? 
Can you check and post the contents of `CreateCollectionResult` result object?

Thanks
Rohan
