### ISSUE TITLE
Call back for published messages in aws iot?

### ISSUE THREAD

**Issue by SanyasiraoM** [aws/aws-sdk-android#326]
I came to know that paho mqtt will give callback when message published to the server, Weather success or failure. But I'm not getting such call back when publishing messages using aws iot android sdk.

Example:
https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity.java#L330

**Comment by kvasukib** [comment]
Hi @SanyasiraoM,

Thanks for reporting to us and sorry for the inconvenience caused. Currently, the publish APIs don't have a callback.

What is the reason for using the callback for "publish" API?

Thanks

**Comment by SanyasiraoM** [comment]
I raised the same issue in ios sdk as well

https://github.com/aws/aws-sdk-ios/issues/717#issuecomment-328967474

**Comment by SanyasiraoM** [comment]
Hi @kvasukib ,

I would like to implement this feature request. Any guidelines I need to follow?

**Comment by SanyasiraoM** [comment]
Hi @kvasukib 

Today while I'm  trying to make a PR. I've observed a method for published message callback

https://github.com/aws/aws-sdk-android/blob/revert-164-master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L1026

May I know why you still made this issue as a feature request thought it exits?

**Comment by kvasukib** [comment]
Hi @SanyasiraoM,

Did you try to use the AWSIotMqttMessageDeliveryCallback  callback in publishString function that exists? Does that solve your use case?

**Comment by SanyasiraoM** [comment]
Yes @kvasukib . I tested it and it's working for my use case.

**Comment by kvasukib** [comment]
Thanks, @SanyasiraoM for confirming. Closing the issue.
