### ISSUE TITLE
Abstract HTTP logic

### ISSUE THREAD

**Issue by niqo01** [aws/aws-sdk-android#33]
Would it be possible to abstract the HTTP logic?
Being able to choose between different HTTP client like Apache HttpClient or OkHTTP would be great.

Removing HttpClient would save ~900k in our APK and plenty of methods count. It would also have the advantages to use a more up to date HttpClient.

**Comment by ddrscott** [comment]
Looks like the AWS team has a habit of including the source instead of using dependencies. I'm hitting `LinearAlloc exceeded capacity (5242880)` errors because of the duplicates.

I see the http client especially odd since it's included with every Android since the beginning of time.

**Comment by fosterzhang** [comment]
niqo01: That's a good suggestion. We'll take it into consideration of method count reduction in the future.
ddrscott: You shouldn't see duplicates. Apache HttpClient 4.2 is included in the core runtime via Jarjar under com.amazonaws namespace. It's believed to have less bugs compared to the build-in 4.0 version in the Android SDK. However we do realize the extra overhead of doing so and are currently seeking alternatives.

**Comment by fosterzhang** [comment]
v2.2.0 now supports pluggable HttpClient. You are able to implement your own HTTP layer. See http://aws.amazon.com/releasenotes/7859064698132437 for more details.

**Comment by niqo01** [comment]
Awesome thanks
