### ISSUE TITLE
Internal Error - verifyAttribute

### ISSUE THREAD

**Issue by darwin-android** [aws/aws-sdk-android#331]
I am trying to verify the phone_number attribute, for that i have called
user.getAttributeVerificationCodeInBackground("phone_number", callback);

and i am able get the verification code in my mobile.
after that i invoked the
user.verifyAttribute("phone_number", verificationCode, callback); service then i am getting "Internal Error".

i am using compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.4.6'

**Comment by darwin-android** [comment]
Hi all,
I am stuck with this issue, please provide me a solution or some workarounds.

**Comment by vlekakis** [comment]
can you post:
a requestID, timestamp, and aws-region ?

**Comment by darwin-android** [comment]
AWS Request ID:   c41d7648-8891-11e7-9fa1-7762eecd6b9a
Region : N.Virginia (US East-1)

![image](https://user-images.githubusercontent.com/30654223/29651948-e1afee70-88c0-11e7-8972-7a8b428f728c.png)

**Comment by vlekakis** [comment]
is that still an issue? My understanding is that you found the solution. Here's the [stackOverflow post](https://stackoverflow.com/questions/45711890/aws-cognito-android-internal-error-on-verifyattribute-api-call)

**Comment by darwin-android** [comment]
Yes, got the solutions. Thanks
