### ISSUE TITLE
TransferUtility for files bigger than 5MB, when using symmetric encryption, simply doesn't do anything in 2.4.6

### ISSUE THREAD

**Issue by hs8058** [aws/aws-sdk-android#332]
Hi,
A while ago we created https://github.com/aws/aws-sdk-android/issues/214 .

Update: This is to confirm that 2.4.6 does not raise the above exception anymore.

However, there is another problem: With the files that are bigger than 5M and will be uploaded in multiparts, the service won't simply do anything! it just raises that the state is InProgress but it remains so forever without further changes. If we pause and resume, it won't even go to InProgress state.

To temporarily deal with the issue, we went back to an older framework in which we manually modified the trnafsrutility code to deal with  https://github.com/aws/aws-sdk-android/issues/214 but with that, for large files (say above 20M), we get another exception.

What service are you using? TransferUtility with symmetric encryption. Keys fed to the client. 

In what version of SDK are you facing the problem? 2.4.6

Is the issue limited to Simulators / Actual Devices? BOTH

Can your problem be resolved if you bump to a higher version of SDK? NO

Is this problem related to specific Android/OS version? NO

Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Simply insatiate transferutility and private symmetric keys and use them to upload large files.

**Comment by rohandubal** [comment]
Hello @hs8058 

We have made a bunch of improvements on the SDK and are currently at the version `2.6.18`

Could you upgrade the SDK to 2.6.18 and see if the issue still exists for you?

Thanks,
Rohan

**Comment by kvasukib** [comment]
@hs8058  Sorry for the delayed response. We have deprecated the client-side encryption provided through the aws-android-sdk-s3 library. Instead we have two recommended approaches:
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#transfer-encryption

**Comment by changlongzj** [comment]
@kvasukib The documentation link is broken, is there any other documentation or workaround?
