### ISSUE TITLE
Get device shadow in Android without cognito pool id

### ISSUE THREAD

**Issue by Karandev** [aws/aws-sdk-android#335]
I found that device pool id is required to get shadow details using Android SDK with CognitoCachingCredentialsProvider. Is it possible to obtain shadow details without using the pool id as in node js or java library?
I was working with this particular sample https://github.com/awslabs/aws-sdk-android-samples/blob/master/TemperatureControl/src/com/amazonaws/demo/temperaturecontrol/TemperatureActivity.java . Relative to this i wanted to access the shadow without using cognito pool id, using MQTT protocol.

**Comment by kvasukib** [comment]
You can try the default constructor of AWSIotDataClient which uses default credentials provider and doesn't require the CognitoCachingCredentialsProvider.

**Comment by Karandev** [comment]
It gives an exception

**Comment by kvasukib** [comment]
Sorry for the inconvenience caused. Currently the AWS IoT SDK for Android supports APIs only with Cognito Identity Pool ID.

**Comment by willnewton** [comment]
Is there any plan to support e.g. mutual authentication in future? I have setup my API to use X509 certs and now it looks like I will have to redesign from scratch due to the Android SDK not supporting this method of authentication.
