### ISSUE TITLE
Upload Pdf/word file to s3 server

### ISSUE THREAD

**Issue by achinverma** [aws/aws-sdk-android#34]
Hi i am using aws android sdk  for uploading images to my bucket on the server it is running fine, but How can we upload Pdf/word files to my bucket , please anyone guide me with demo ?

**Comment by fosterzhang** [comment]
You sure can upload Pdf/word files. It can be done the same way as you upload an image. What difficulty do you see?

**Comment by achinverma** [comment]
thanku , it is working with my image uploading code, i have used this

PutObjectRequest por = new PutObjectRequest(
					Constants.getPictureBucket(), "app_images/" + fileName,resolver.openInputStream(selectedImage), metadata);


But is there any method or listener which tells that Number Of bytes uploaded while uploading  ?

**Comment by fosterzhang** [comment]
Yes you can track the progress. You can add a ProgressListener to an upload (or download) initiated by TransferManager. You can find the usage and sample code in [this blog post](http://mobile.awsblog.com/post/Tx1V588RKX5XPQB/TransferManager-for-Android).
