### ISSUE TITLE
Optimize Kinesis for multiple mixed stream records

### ISSUE THREAD

**Issue by themummy** [aws/aws-sdk-android#340]
* What service are you using?
**Kinesis Firehose**
* In what version of SDK are you facing the problem?
**2.6.0**
* Is the issue limited to Simulators / Actual Devices?
**Both**
* Can your problem be resolved if you bump to a higher version of SDK?
**No**
* Is this problem related to specific Android/OS version?
**No**
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
**This is a general issue with the way Kinesis batches and submits records.**
* Please include a stacktrace if applicable.
**N/A**

### Issue
Kinesis Firehose takes a very long time to batch and submit records when records from multiple streams are mixed in the record store.

### Description
Our Android client is submitting data to 14 different Firehose streams. The records are saved into the Kinesis recordStore as soon as they're generated. This result in a fragmented recordStore (i.e. 3 records from _stream1_, followed by 1 record from _stream2_, followed by 2 records from _stream3_).

The way [`submitAll()`](https://github.com/aws/aws-sdk-android/blob/0958a37b4757c41cac40597b973ff417e0b758c4/aws-android-sdk-kinesis/src/main/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/AbstractKinesisRecorder.java#L120) works is that it batches consecutive records belonging to one stream, submits them, then grabs the next batch of consecutive records belonging to another stream. This works well when the records are sorted by stream name. But as one can image, in a fragmented record store, this produces a lot of batches with very few records. This causes `submitAllRecords()` to run for a long time consuming device CPU and power, and very little bandwidth. In our case, it can run for more than an hour.

### Proposed Solution
We can minimize the number of batches being sent by grouping records of the same stream together before sending. We can do so efficiently by iterating through the records in the recordStore and saving them in a batch buffer according to their respective stream. Once the maximum batch size is reached for any of the stream batches, it gets submitted.

We are working on the code changes, and will submit a PR when finished for your review.

**Comment by kvasukib** [comment]
Hi @themummy,

Thanks for reporting to us and using our SDK.

We will wait for the PR and evaluate it.

Thanks

**Comment by lexlevi17** [comment]
Updated: There is now a PR open for this issue.
