### ISSUE TITLE
Phone gets hot while uploading big files

### ISSUE THREAD

**Issue by Anchorer** [aws/aws-sdk-android#345]
* What service are you using?
S3 Android SDK
* In what version of SDK are you facing the problem?
2.6.2
* Is the issue limited to Simulators / Actual Devices?
Actual Devices
* Can your problem be resolved if you bump to a higher version of SDK?
no
* Is this problem related to specific Android/OS version?
no

Hi, when I use S3 Android SDK to upload big files, my device get so hot. 

I checked my hardware temperature and find out that the CPU has high temperature.

This issue exists on every devices. Is there any optimization for this?

**Comment by kvasukib** [comment]
Hi @Anchorer,

Thank you for reporting to us. Sorry for the inconvenience caused.

Can you tell us the **size** and **type** of files that you are trying to upload? Does this happen for every large file?
What version of Android are you using?

**Comment by Anchorer** [comment]
Hi @kvasukib,

Thanks for your reply.

I try to upload files with many size, from 50M to 500M, and mostly mp4 or apk files. Yes this issue happens for every uploading process. 

We tested this case on many Android versions, from 4.x to 7.1.1.  This issue happens on all Android versions. 

I also tested the S3 example application you support and also has the same issue.

**Comment by rohandubal** [comment]
Hello @Anchorer 

Can you specify some devices you tested on? Also, could you provide a snippet by which we could reproduce this? It would help us reproduce on our side.

Thanks,
Rohan

**Comment by Anchorer** [comment]
Hi @rohandubal,

We tested on devices such like Samsung S3, Samsung S5, Redmi Note, Nexus 6p, OnePlus5, etc.

To reproduce this, you can use the sample: https://github.com/awslabs/aws-sdk-android-samples/tree/master/S3TransferUtilitySample. 

Just upload many big files, and during the uploading process, the device gets hot.

**Comment by kvasukib** [comment]
When you cloned the S3TransferUtilitySample, did you bump the version of S3 SDK to the latest version?

I tried the following experiments:
1) On Simulator:
File Size: 300MB
Tried download and upload
Peak CPU Utilization was 40% and average is around 25%

2) On OnePlus3 latest Android version
File Size: 300MB
Tried download and upload over WiFi
Peak CPU utilization was <10% and average is around 7%

**Comment by Anchorer** [comment]
In my case, the CPU utilization is also not high.

On my OnePlus5 latest Android version, I upload several 300MB files, CPU utilization was <10%, but the CPU temperature changed from 41°C to 50°C, which is really hot.

What about the device temperature in your tests?

**Comment by kvasukib** [comment]
Hi @Anchorer,

Thanks for the reply.

Temperature Measurements:
Device: OnePlus3
SDK: 2.6.+ with latest Android version
Base temp of phone before running the sample app: 26C
During the transfer, the temperature fluctuated between 26C and 27C and never crossed that.
The same happened for both upload and download.

Can you confirm the AWS SDK version of the app?
Can you share us the code snippet apart from the S3TransferUtilitySample app if you are able to reproduce?

Thanks

**Comment by Anchorer** [comment]
@kvasukib Here's some of my codes.

i. First, I have a S3Util class:

```
public class S3Util {

    // We only need one sInstance of the clients and credentials provider
    private static AmazonS3Client sS3Client;
    private static CognitoCachingCredentialsProvider sCredProvider;
    private static TransferUtility sTransferUtility;

    private volatile static S3Util mS3Util;

    /**
     * Initialize S3Util
     * @param context Context
     */
    public static void init(Context context) {
        getCredProvider(context);
        getS3Client(context);
        getTransferUtility(context);
    }

    public static S3Util getInstance() {
        if (mS3Util == null) {
            synchronized (S3Util.class) {
                if (mS3Util == null) {
                    mS3Util = new S3Util();
                }
            }
        }
        return mS3Util;
    }

    /**
     * Gets an sInstance of CognitoCachingCredentialsProvider which is
     * constructed using the given Context.
     *
     * @param context An Context sInstance.
     * @return A default credential provider.
     */
    private static CognitoCachingCredentialsProvider getCredProvider(Context context) {
        if (sCredProvider == null) {
            sCredProvider = new CognitoCachingCredentialsProvider(
                    context.getApplicationContext(),
                    S3Consts.COGNITO_POOL_ID,
                    Regions.US_WEST_2);
        }
        return sCredProvider;
    }

    /**
     * Gets an sInstance of a S3 client which is constructed using the given
     * Context.
     *
     * @param context An Context sInstance.
     * @return A default S3 client.
     */
    public static AmazonS3Client getS3Client(Context context) {
        if (sS3Client == null) {
            sS3Client = new AmazonS3Client(getCredProvider(context.getApplicationContext()));
        }
        return sS3Client;
    }

    /**
     * Gets an sInstance of the TransferUtility which is constructed using the
     * given Context
     *
     * @param context
     * @return a TransferUtility sInstance
     */
    public static TransferUtility getTransferUtility(Context context) {
        if (sTransferUtility == null) {
            sTransferUtility = new TransferUtility(getS3Client(context.getApplicationContext()),
                    context.getApplicationContext());
        }

        return sTransferUtility;
    }

    /**
     * Upload a file
     * @param key            the key to upload the file
     * @param file             File object to upload
     * @param transferListener TransferListener for this upload task
     * @return the TransferObserver object created for this upload
     */
    public TransferObserver uploadFile(String key, String bucketName, File file, S3FileTransferListener transferListener) {
        TransferObserver transferObserver = sTransferUtility.upload(bucketName, key, file);
        bindTransferListener(transferObserver, transferListener);
        return transferObserver;
    }

    /**
     * Create a upload task and start upload
     *
     * @param bucket bucket to upload file
     * @param key      key to upload file
     * @param file   File objet to upload
     * @return the TransferObserver object created
     */
    public TransferObserver createAndStartUploadFile(String bucket, String key, File file) {
        return sTransferUtility.upload(bucket, key, file);
    }
    public TransferObserver createAndStartUploadFile(String bucket, String key, File file, TransferListener transferListener) {
        TransferObserver transferObserver = sTransferUtility.upload(bucket, key, file);
        transferObserver.setTransferListener(transferListener);
        return transferObserver;
    }

    /**
     * Resume a transfer task
     * @param transferId the transfer ID to resume
     */
    public TransferObserver resumeTransfer(int transferId) {
        return sTransferUtility.resume(transferId);
    }

    /**
     * Pause a transfer task
     * @param transferId the transfer ID to pause
     */
    public void pauseTransfer(int transferId) {
        sTransferUtility.pause(transferId);
    }
}
```

ii. Then I have a UploadManager class to create new task: 

```
/**
 * Create a new upload task
 * @param channelId function-related parameter
 * @param shareId     function-related parameter
 * @param uploadDataList data for create new upload tasks
 */
public void createNewUpload(long channelId, long shareId, ArrayList<UploadData> uploadDataList) {
        GLog.i("Create New Upload For share: " + shareId);
        for (UploadData uploadData : uploadDataList) {
            GLog.i("UploadData ==> " + uploadData.toString());
        }
        UploadTask uploadTask = new UploadTask(channelId, shareId, uploadDataList);
        mUploadTasks.put(shareId, uploadTask);
        startNextUploadTask();
}
```
I have a TransferObserver List called mUploadTasks to manage multiple upload tasks.

iii. In UploadTask class, I have a start() method to start or resume the upload task:

```
public void start() {
        initTransferListener();

        int transferIdToStart = 0;
        for (FileUploadRecord uploadRecord : mUploadRecordMap.values()) {
            int state = uploadRecord.getUploadState();
            if (state == UploadState.PENDING || state == UploadState.PAUSED || state == UploadState.IN_PROGRESS || state == UploadState.FAILED) {
                if (transferIdToStart == 0) {
                    transferIdToStart = uploadRecord.getTransferId();
                }
                uploadRecord.setUploadState(UploadState.PENDING);
            }
        }

        GLog.i("UploadTask start. transferId: " + transferIdToStart);
        if (transferIdToStart > 0) {
            int currentState = getUploadState();
            if (currentState == UploadState.FAILED || currentState == UploadState.PAUSED) {
                setUploadState(UploadState.PENDING);
                UploadManager.getInstance().onUploadWaitingCallback(this);
            }
            TransferObserver transferObserver = S3Util.getInstance().resumeTransfer(transferIdToStart);
        }
}
```
Finally, this method calls S3Util.resumeTransfer() method to resume the specific upload task.

**Comment by kvasukib** [comment]
Hi @Anchorer, We couldn't reproduce the issue on the device. Are you still facing this issue?

**Comment by Anchorer** [comment]
Yes, it still exists in version 2.6.6.

**Comment by kvasukib** [comment]
Hi @Anchorer, We have added the option to configure the number of threads in the TransferUtility through the [TransferUtilityOptions#setTransferThreadPoolSize](https://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtilityOptions.html).

Please set this to a lower value, for example 2, and see if it solves your problem.
