### ISSUE TITLE
AWS SDK Android Auth Demo issue: invalid grant

### ISSUE THREAD

**Issue by dk67604** [aws/aws-sdk-android#349]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
I'm using AWS Android Auth SDK for sign-in sign-up
* In what version of SDK are you facing the problem?
aws-sdk-android
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific Android/OS version?
No
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
After login, I am getting invalid grant error.

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Hi Dharmendra,

Thanks for using our SDK and reporting to us. 
1. Can you share the code snippet that you used to launch the SignIn/SignUp UI?
2. What SignIn Providers are you using?
3. What's the version of SDK?
4. Can you share the exception/stack trace?

Thanks
