### ISSUE TITLE
S3 PersistableDownload is not contain range data.

### ISSUE THREAD

**Issue by smallwood69** [aws/aws-sdk-android#35]
so. I can't resume download.

**Comment by fosterzhang** [comment]
Would you please provide me more information, such as platform version, SDK version, stack trace, and code to reproduce the problem if possible?

**Comment by smallwood69** [comment]
I use s3 sdks 2.1.10 with android. 4.4.4.
no stack trace, just  persistable data not contain range.

iOS API  is perfect.

Thank you.


    public void pause(){
        try{

            PersistableDownload persistableDownload = downloadRequest.pause();

            String tempFilePath = common.Constants.dataPath + File.separator + "tmp" + File.separator + fileName + ".s3";
            File resumData = new File(tempFilePath);
            if(!resumData.exists())
                resumData.createNewFile();

            FileOutputStream fos = new FileOutputStream(resumData);
            // Serialize the persistable transfer to the file.
            persistableDownload.serialize(fos);
            fos.close();
        }
        catch (Exception e){
            LOG.error(getClass(), "ERROR", e);
        }

        this.cancel(Boolean.TRUE);
    }


-#### resume function
   private S3TaskResult resumeDownloadResources(String fileName, String fileToDownload) {

        S3TaskResult result = new S3TaskResult();

        String resumeData = Constants.dataPath + File.separator + "tmp" + File.separator + fileName + ".s3";
        File resumeFile = new File(resumeData);

        String tempFilePath = Constants.dataPath + File.separator + "tmp" + File.separator + fileName + ".download";
        File downloadFile = new File(tempFilePath);

        try{
            total = FileUtils.sizeOf(downloadFile);

            FileInputStream fio = new FileInputStream(resumeFile);
            PersistableDownload persistableDownload = PersistableDownload.deserializeFrom(fio);
            fio.close();

            downloadRequest = manager.resumeDownload(persistableDownload);
        }
        catch (Exception e){
            LOG.error(getClass(), "ERROR", e);

            if(downloadFile.exists())
                downloadFile.delete();

            downloadRequest = manager.download(biz.funebook.s3.Constants.BUCKET_NAME, fileToDownload, downloadFile);
        }
        finally {

        }
        try{
            resumeFile.delete();
            filesize = downloadRequest.getProgress().getTotalBytesToTransfer();
            downloadRequest.addProgressListener(this);

            downloadRequest.waitForCompletion();
        }
        catch (Exception e) {
            result.setErrorMessage(e.getMessage());
            LOG.error(getClass(), "resumeDownloadResources", e);
        }

        return result;

    }

**Comment by fosterzhang** [comment]
Thank you for the code snippet. I will look into this.

**Comment by suraj9781** [comment]
hey there,
I am also getting same exception for download when used 2.1.10 but when i downgraded the library to 2.1.8 it is working fine

**Comment by smallwood69** [comment]
thank you. 
I checked 2.1.8, presist data contain 'range'.  but, it's data is null.
so It can't resume download.

--> "versionId":null,"range":null,"responseHeaders":null,"isRequesterPays":false,"file":

Thank you...

**Comment by wdane** [comment]
Sorry about this issue, I've fixed and verified the transfer manager and it will be available in a new release soon.  In the mean time, you can resolve this issue, by using a GetObjectRequest with transferManager.download() and specifying the range of the full item.  So if the item in S3 is 1000 bytes, then doing getObjectRequst.setRange(0, 1000);  should work.  If you don't know the size of the object you can do a GetObjectMetadataRequest and then call metadata.getContentLength() to find out.

Will leave this issue open until we make a release to properly fix it.

**Comment by wdane** [comment]
This issue should be fixed with version 2.2.3 which is now available on the website.  Please re-open if this does not resolve your issue.
