### ISSUE TITLE
Cannot resolve symbol AmazonSimpleEmailServiceClientBuilder

### ISSUE THREAD

**Issue by saintjab** [aws/aws-sdk-android#351]
* What service are you using? AWS SES
* In what version of SDK are you facing the problem?2.6.4

* Is the issue limited to Simulators / Actual Devices? No

* Can your problem be resolved if you bump to a higher version of SDK? Not sure

* Is this problem related to specific Android/OS version? No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
I copied and modified the code from the sample code on AWS website
1. Add AWS Android SDK core and SES jar files into project
2. Import into Build gradle  and sync
3. Use the SES code for sending email like so
`AmazonSimpleEmailService client = new AmazonSimpleEmailServiceClientBuilder.standard()
                            .withRegion(Regions.EU_WEST_1).build();
            SendEmailRequest request = new SendEmailRequest()
                    .withDestination(
                            new Destination().withToAddresses(email))
                    .withMessage(new Message()
                            .withBody(new Body()
                                    .withHtml(new Content()
                                            .withCharset("UTF-8").withData(HTMLBODY))
                                    .withText(new Content()
                                            .withCharset("UTF-8").withData(HTMLBODY)))
                            .withSubject(new Content()
                                    .withCharset("UTF-8").withData("TESTING")))
                    .withSource("info@paybyana.com");
            client.sendEmail(request);`
4. After importing all libraries, you would get "Cannot resolve symbol AmazonSimpleEmailServiceClientBuilder"

**Comment by minbi** [comment]
Hi @saintjab ,

Could it be that you are using code meant for the AWS SDK for Java?
[AmazonSimpleEmailServiceClientBuilder](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-ses/src/main/java/com/amazonaws/services/simpleemail/AmazonSimpleEmailServiceClientBuilder.java)

**Comment by saintjab** [comment]
@minbi , I think you are right.
