### ISSUE TITLE
AWSIotMqttManager on Android (non-emulated) over 3G/4G/WiFi - Diconnection/Connection Looping - Eventual silent connection drop-out - Strange Behavior

### ISSUE THREAD

**Issue by hs8058** [aws/aws-sdk-android#352]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
IoT/Cognito , mostly aws-android-sdk-iot

* In what version of SDK are you facing the problem?
2.6.3

* Is the issue limited to Simulators / Actual Devices?
Only seen on Actual devices!

* Can your problem be resolved if you bump to a higher version of SDK?
No. This is the latest version used, already.

* Is this problem related to specific Android/OS version?
Currently we have tried Android 5.0.1 on a Samsung S4 device but this seems to have been witnessed on other devices too.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
We have given this quite a significant amount of attention and testing. Here is a summary:

Scenario:

Firstly, these would be good reads:
https://github.com/eclipse/paho.mqtt.java/pull/317
https://github.com/eclipse/paho.mqtt.java/issues/27
https://bugs.eclipse.org/bugs/show_bug.cgi?id=397651

Used services/setting: IoT over Cognito Identity over Web Sockets, logged in users can connect to "*" but are only allowed to subscribe to their own topics (using the {$iotClientId} policy variable).

Other settings:
mqttManager.setOfflinePublishQueueEnabled(false);
mqttManager.setKeepAlive(120);
mqttManager.setMaxAutoReconnectAttepts(-1);  // retry forever!
mqttManager.setAutoReconnect(true);

Outcome:
When the app is running on an emulator, no problem is faced. When the app is running on a real device over 3g, 4g or WiFi connections, however, the connection is made successfully and is retained for about 2 minutes or so and then we see that a disconnection event follows which later results in another connection attempt and then again for 2 minutes, the connection is retained and then lost again. 
Now, in a few hours' time, we observe that the connection seems to be dropping out silently with the client reporting its latest status as "Connected". There must be a correlation with this outcome and lack of connectivity on the device (say if you're in a lift with no reception). Now, luckily, we observed that if the mqttManager is asked to disconnect the connection, it will raise the exception that "Client is currently disconnecting (32102)", as if it's stuck in the state to try to disconnect.

Observation 1:
No matter if you change the keep-alive timer or not, which we have tried, or use the default 10-second one, the behavior will be the same, even the loop time which is around 2 minutes. Connection is retained and lost and then it repeats again, until a random event of drop-out permanently.

Observation 2:
We have changed the sample AndroidpubSubWebSocket and added a service to it with notifications on connection-related events. Similarly, clients can connect to "*" but can subscribe to their only topics (using {$iotClientId}). The exact same behavior is observed!!

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by hs8058** [comment]
Observation 3: if CognitoID which inludes ":" is used as client_id, the drop-outs and reconnection attempts will be happening more times than ensuring that the client_id has only "_" or alphanumeric characters, especially if client_id is also a thing name.

Observation 4: Even with all the modifications to ensure thing name and client ids are alpha numeric, at a lower frequency, the drop-out and re-connection still happens.

Observation 5: When the phone is powered by its charger, though we can not fully confirm the observation, but the connection seems to remain normally active. This may ring the bell that Android's batter-life increasing policies may be at play here.

Observation 6: For cases when there is long period of disconnection from the Internet, the client seems to have lost the state and can never revive the connection when left on its own!

**Comment by kvasukib** [comment]
Hi @hs8058,

Thank you for the detailed description and observations. Did you try different values of KeepAlive and see if the problem persists? Can you share us the service that you have added on top of AndroidpubSubWebSocket sample app?

**Comment by hs8058** [comment]
Yes, we have changed the keepAlive value. The smaller it is, the higher the chance we end up with a broken connection more frequently.

**Comment by hs8058** [comment]
I can email the service-based version of the sample/.

**Comment by hs8058** [comment]
OK, this is more of an obvious question than an observation.

Obviously, when using the SDK of a multi-billion dollar establishment, you'd imagine people have spent enough time testing things and that you don't need to look into the entire codebase of the SDK to see what is going on. That includes bothering to try things on real phones that are not connected to power sources.

AWSIotMqttManager's constructor does not get an execution context? right? and there is no method to set any context either.. right?

Then the question is how are you scheduling the keepalive timer?

It must be obvious that you either, at the cost of a wakelock, keep the entire phone awake to use thread scheduling functions/handler.post()/similar functions, OR, you need to use the alarm manager to send the keepalive ping periodically, both of which require a context.

If none of the above methods have been used in the SDK, then practically, we have been wasting our time trying to dodge Android's default behavior around process management and battery life preservation.

The second Android starts arranging things to save battery, the app (or the service) that owns the AWSIotMqttManager instance is going to be shut down and no ping will be sent. That explains why the connection keeps dropping, or eventually things get completely lost.




Observation 7:
To prove the above theory, we acquired a wakelock and held on to it in the service and at the cost of a big battery bill, apparently, the connection is preserved for a long time without connection/reconnection looping or drop-out.

Question:
Obviously, using a wakelock is a no-no in many cases.
Have you guys realized you may not have designed this IOT implementation for Android properly?
Do you guys have any plans to fix it, or should we get creative ourselves?

**Comment by hs8058** [comment]
https://stackoverflow.com/questions/37699240/pahos-mqtt-client-disconnects-after-the-device-locks

**Comment by bxpan** [comment]
Hi hs8058,

You're correct. The battery saving mechanism on Android does not allow periodic pings. As a result, it is the current behavior that the SDK connection to IoT gets lost after timeout when device is in idle/doze mode. This is the current limitation of the SDK. It does not force the ping to be sent out to network using wakelock or alarmmanager as this will drain out the battery very fast. However, feel free to modify or create logic yourselves to best suit your use case.

Thanks.

**Comment by hs8058** [comment]
Based on the answers provided, this issue is being closed.
