### ISSUE TITLE
Pinpoint SDK sends 3 character country code, causing API error

### ISSUE THREAD

**Issue by guillaumenel** [aws/aws-sdk-android#354]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Pinpoint
* In what version of SDK are you facing the problem?
2.6.5
* Is the issue limited to Simulators / Actual Devices?
Actual Devices
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific Android/OS version?
Unsure
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Pinpoint SDK fails to send requests when locale is detected as USA.
Found this issue and developer edition HTC M8.

TargetingClient::executeUpdate has the following line, which returns "USA".
```locale = endpointProfile.getDemographic().getLocale().getISO3Country();```

* Please include a stacktrace if applicable.

```
10-17 10:53:46.571 31628-31670/com.appname E/TargetingClient: AmazonServiceException occurred during endpoint update:
                                                                     com.amazonaws.services.pinpoint.model.BadRequestException: Locale should be in the following format: The ISO 639-1 alpha-2 code, followed by an underscore, followed by an ISO 3166-1 alpha-2 value or UN M.49 numeric-3 area code. (Service: AmazonPinpoint; Status Code: 400; Error Code: BadRequestException; Request ID: af1e3990-b318-11e7-bfef-39fd95a4a375)
                                                                         at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:729)
                                                                         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
                                                                         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                         at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:3303)
                                                                         at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:3053)
                                                                         at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:203)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
```

Updated with this for now:
```locale = String.format("%s_%s", endpointProfile.getDemographic().getLocale().getLanguage(), endpointProfile.getDemographic().getLocale().getCountry());```

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
We released 2.6.6 that fixes the issue.

**Comment by jonasfunk** [comment]
With the country value of CAN, Using 2.6.6 I'm getting this, 

```
com.amazonaws.services.pinpoint.model.BadRequestException: Country should be 2 character ISO 3166-1 Alpha-2 codes or UN M.49 numeric-3 area code (Service: AmazonPinpoint; Status Code: 400; Error Code: BadRequestException; Request ID: 2f9bd4bf-be42-11e7-b5bf-c75bf67bda00)
TargetingClient: at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:729)
TargetingClient: at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
TargetingClient: at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
TargetingClient: at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:3303)
TargetingClient: at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:3053)
TargetingClient: at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:194)
TargetingClient: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
TargetingClient: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
TargetingClient: at java.lang.Thread.run(Thread.java:762)
```

**Comment by Arpanbajpai** [comment]
@kvasukib  Please help me out to implement AWS Pinpoint notification in android. i am getting the same issue ( com.amazonaws.services.pinpoint.model.BadRequestException: Country should be 2 character ISO 3166-1 Alpha-2 or Alpha-3 codes or UN M.49 numeric-3 area code ) as above as in  TargetingClient class the EndpointLocation is unable to get city,country etc. I have researched and found that 
context.getApplicationContext().getResources().getConfiguration().locale.getISO3Country() has been deprecated since sdk 24 and new version  to get the list is
LocaleListCompat list = ConfigurationCompat.getLocales(Resources.getSystem().getConfiguration());

Please help to implement it ASAP.

**Comment by kvasukib** [comment]
@Arpanbajpai Sorry for the inconvenience caused. What Android API Level are you running against? Do you see the log message `"Locale getISO3Country failed, falling back to getCountry."` in your Logcat? Can you put a breakpoint at Line 45 in EndpointProfileLocation.java to find the localeCountry value retrieved?

**Comment by Arpanbajpai** [comment]
@kvasukib  Sir as requested i attached screenshot with breakpoints and result.I am using API level 28.
i am also not getting any deprecation message but when i tried to log getISO3Country() i got empty string. But using         LocaleListCompat list = ConfigurationCompat.getLocales(Resources.getSystem().getConfiguration());
i am able to get "IND".
I tried to search "Locale getISO3Country failed, falling back to getCountry." in logcat but not able to find.


![screenshot from 2019-02-07 15-54-46](https://user-images.githubusercontent.com/47378385/52405179-bcd36900-2af0-11e9-9df7-09ff2ef26187.png)

**Comment by kvasukib** [comment]
@Arpanbajpai Thank you for providing me with all the necessary details.

I added few log statements in the code to see if the location is fetched correctly.

```java
 @Test
    public void testUpdateEndpointProfile() {
        EndpointProfile endpointProfile = targetingClient.currentEndpoint();
        EndpointProfileUser endpointProfileUser = new EndpointProfileUser();
        endpointProfileUser.setUserId(credentialsProvider.getIdentityId());
        endpointProfile.setUser(endpointProfileUser);

        targetingClient.updateEndpointProfile();
        assertEquals("The userId should be the Cognito Identity ID",
                credentialsProvider.getIdentityId(),
                targetingClient.currentEndpoint().getUser().getUserId());
        assertNotNull(targetingClient.currentEndpoint().getUser());
        assertNotNull(targetingClient.currentEndpoint().getLocation());
        assertNotNull(targetingClient.currentEndpoint().getDemographic());
        assertNotNull(targetingClient.currentEndpoint().getDemographic().getAppVersion());
        assertNotNull(targetingClient.currentEndpoint().getDemographic().getLocale());
        assertNotNull(targetingClient.currentEndpoint().getDemographic().getMake());
        assertNotNull(targetingClient.currentEndpoint().getDemographic().getModel());
        assertNotNull(targetingClient.currentEndpoint().getDemographic().getPlatform());
        assertNotNull(targetingClient.currentEndpoint().getDemographic().getPlatformVersion());
        assertNotNull(targetingClient.currentEndpoint().getDemographic().getTimezone());

        Log.i(TAG, "Country = " + targetingClient.currentEndpoint().getDemographic().getLocale().getCountry());
    }
```

02-07 12:01:09.447 4736-4736/com.amazonaws.pinpointinstrumentationtester I/EndpointProfileLocation: Locale getISO3Country(): USA
02-07 12:01:09.675 4736-4758/com.amazonaws.pinpointinstrumentationtester I/EndpointProfileLocation: Locale getISO3Country(): USA
02-07 12:01:09.681 4736-4758/com.amazonaws.pinpointinstrumentationtester I/TargetingInstrumentedTest: Country = US

I am able to retrieve the information on API Level 28 emulator. Can you give some information on the device?

**Comment by Arpanbajpai** [comment]
@kvasukib  i am using devices of moto(API 25) and redmi(API 24) for testing. It seems it is working pefectly on your side but i am not able to implement it correctly

**Comment by samyakjain** [comment]
I am also facing the same issue. Why this issue has been closed?

```AmazonServiceException occurred during endpoint update: Country should be 2 character ISO 3166-1 Alpha-2 or Alpha-3 codes or UN M.49 numeric-3 area code
```

```AmazonServiceException occurred during endpoint update:
    com.amazonaws.services.pinpoint.model.BadRequestException: Country should be 2 character ISO 3166-1 Alpha-2 or Alpha-3 codes or UN M.49 numeric-3 area code (Service: AmazonPinpoint; Status Code: 400; Error Code: BadRequestException; Request ID: 48c67b12-1163-4c2a-b2c5-04a727af01ac)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:4081)
        at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:3775)
        at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:198)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)```

**Comment by Arpanbajpai** [comment]
> I am also facing the same issue. Why this issue has been closed?
> 
> `AmazonServiceException occurred during endpoint update: Country should be 2 character ISO 3166-1 Alpha-2 or Alpha-3 codes or UN M.49 numeric-3 area code`
> 
> ```
>     com.amazonaws.services.pinpoint.model.BadRequestException: Country should be 2 character ISO 3166-1 Alpha-2 or Alpha-3 codes or UN M.49 numeric-3 area code (Service: AmazonPinpoint; Status Code: 400; Error Code: BadRequestException; Request ID: 48c67b12-1163-4c2a-b2c5-04a727af01ac)
>         at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
>         at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
>         at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
>         at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:4081)
>         at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:3775)
>         at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:198)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:764)```
> ```

Just make sure to insert Locale of your country inside your app.

**Comment by samyakjain** [comment]
How to do that? Also what if my app gets downloaded from a different country would that be a problem?

**Comment by Arpanbajpai** [comment]
> How to do that? Also what if my app gets downloaded from a different country would that be a problem?

While initializing app just declare Locale with country code in your app

**Comment by samyakjain** [comment]
Thanks a lot. This solved the error
