### ISSUE TITLE
Updating Demographic info does not reflect

### ISSUE THREAD

**Issue by guillaumenel** [aws/aws-sdk-android#355]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Pinpoint
* In what version of SDK are you facing the problem?
2.6.5
* Is the issue limited to Simulators / Actual Devices?
Either
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific Android/OS version?
No
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I'm updating the pinpoint endpoint with demographic info. The initial endpoint was created in, i.e. "en_US" and then I modify the Demographic Country to "en_ZA" afterwards. 
The aws console under Analytics -> Demographics value doesn't update. Either the aws page or the request from the android sdk is bad. 
```
        EndpointProfile profile = pinpointManager.getTargetingClient().currentEndpoint();
        profile.getDemographic().setLocale(new Locale("en", "ZA"));
        profile.getLocation().setCountry("ZA");
        pinpointManager.getTargetingClient().updateEndpointProfile(profile);
```

I'd like to note that the Custom Attributes section just below it in the AWS Pinpoint gui reflects updates immediately. These should work the same way, shouldn't they?
* Please include a stacktrace if applicable.
Here is a request which updates my Demographic info on an endpoint which was already automatically registered on startup.
```
{Address: eXRUPrZD6MI:APA91bGjLnsTkLA_gokKxm5we9z4nbdbwVE3Lpuq1OiBTKGAqY6JaY2VSkVK8jMx-Ou-KnYnPuuc9JESNV086zH_n8odISjDC7SaEuee7IxlLABhLpuDnlMXzTkTAY7XMR-NGEej0sLN,Attributes: {},ChannelType: GCM,Demographic: {AppVersion: 2.9.5,Locale: en_ZA,Make: HTC,Model: HTC One_M8,Platform: ANDROID,PlatformVersion: 6.0,Timezone: Africa/Johannesburg},EffectiveDate: 2017-10-17T13:19:17.889Z,Location: {City: ,Country: ZA,Latitude: -33.8320494,Longitude: 18.6466148,PostalCode: ,Region: },Metrics: {},OptOut: NONE,User: {UserId: }}
```

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by balaji2591** [comment]
Hi guillaumenel, 
This issue(#355) is the consequence of the other issue which you raised.
https://github.com/aws/aws-sdk-android/issues/354
So closing this and tracking it over there.
