### ISSUE TITLE
Aws sdk - not able to upload file fue to

### ISSUE THREAD

**Issue by Abhilash-D** [aws/aws-sdk-android#356]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

* In what version of SDK are you facing the problem?

* Is the issue limited to Simulators / Actual Devices?

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific Android/OS version?

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by Abhilash-D** [comment]
Error message:
E/UploadTask: Failed to upload: 57 due to Unable to execute HTTP request: Write error: ssl=0x556d8dbe40: I/O error during system call, Connection reset by peer

Stack Trace:
`10-22 22:43:18.285 8235-11479/com.etaserve.ptm E/UploadTask: Failed to upload: 57 due to Unable to execute HTTP request: Write error: ssl=0x556de11430: I/O error during system call, Connection reset by peer
10-22 22:43:18.295 8235-8235/com.etaserve.ptm W/System.err: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Write error: ssl=0x556de11430: I/O error during system call, Connection reset by peer
10-22 22:43:18.295 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:430)
10-22 22:43:18.296 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
10-22 22:43:18.296 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4375)
10-22 22:43:18.296 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1704)
10-22 22:43:18.296 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:203)
10-22 22:43:18.296 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:85)
10-22 22:43:18.296 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:44)
10-22 22:43:18.296 8235-8235/com.etaserve.ptm W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-22 22:43:18.297 8235-8235/com.etaserve.ptm W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-22 22:43:18.297 8235-8235/com.etaserve.ptm W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-22 22:43:18.297 8235-8235/com.etaserve.ptm W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-22 22:43:18.297 8235-8235/com.etaserve.ptm W/System.err: Caused by: javax.net.ssl.SSLException: Write error: ssl=0x556de11430: I/O error during system call, Connection reset by peer
10-22 22:43:18.298 8235-8235/com.etaserve.ptm W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
10-22 22:43:18.298 8235-8235/com.etaserve.ptm W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:771)
10-22 22:43:18.298 8235-8235/com.etaserve.ptm W/System.err:     at com.android.okhttp.okio.Okio$1.write(Okio.java:76)
10-22 22:43:18.299 8235-8235/com.etaserve.ptm W/System.err:     at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
10-22 22:43:18.299 8235-8235/com.etaserve.ptm W/System.err:     at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
10-22 22:43:18.299 8235-8235/com.etaserve.ptm W/System.err:     at com.android.okhttp.okio.RealBufferedSink.write(RealBufferedSink.java:46)
10-22 22:43:18.299 8235-8235/com.etaserve.ptm W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:302)
10-22 22:43:18.299 8235-8235/com.etaserve.ptm W/System.err:     at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
10-22 22:43:18.299 8235-8235/com.etaserve.ptm W/System.err:     at com.android.okhttp.okio.RealBufferedSink$1.write(RealBufferedSink.java:198)
10-22 22:43:18.299 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:245)
10-22 22:43:18.300 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:165)
10-22 22:43:18.300 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:70)
10-22 22:43:18.300 8235-8235/com.etaserve.ptm W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)
10-22 22:43:18.300 8235-8235/com.etaserve.ptm W/System.err: 	... 10 more`


Amazon s3 bucket config:
`ClientConfiguration config = new ClientConfiguration();
        config.setConnectionTimeout(30000);
        config.setProtocol(Protocol.HTTPS);
        config.setSocketTimeout(3600000);
        config.setMaxErrorRetry(10);
        AmazonS3Client s3Client = new AmazonS3Client( new BasicAWSCredentials( accessKey,
                apiKey),config);`



Bucket configuration:
Region - U.S. East-1
public access has all permissions(List object, read object, read bucket permissions, write bucket permissions)

**Comment by minbi** [comment]
Hi @Abhilash-D ,

Does this happen if you retry the upload?

To help me reproduce this issue on my end, please provide the following information:
What version of the SDK are you using?
What network are you using? i.e. Wifi, 3G, 4G
What type of file are you uploading and would you be able to provide a sample?

Thanks
