### ISSUE TITLE
Missing "request.handlers"

### ISSUE THREAD

**Issue by rossimo** [aws/aws-sdk-android#36]
The request handler definition files are missing. I can find the "request.handler" files in the official releases at http://aws.amazon.com/mobile/sdk/, but they do not appear in a fresh build from the Github repository.

**Comment by fosterzhang** [comment]
Thank you for reporting. We'll fix it in the next release.

**Comment by fosterzhang** [comment]
This is resolved in v2.2.0 release. The source is laid out by module. Resource files are correctly placed.
