### ISSUE TITLE
unable to set accelration mode while using transfer utility

### ISSUE THREAD

**Issue by maliknaseer** [aws/aws-sdk-android#363]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

* In what version of SDK are you facing the problem?

* Is the issue limited to Simulators / Actual Devices?

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific Android/OS version?

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by maliknaseer** [comment]
I am usin amazon s3 web services 
I have version 2.6.6 updated it today
It is occuring in samsung galaxy s5 android version 5.0

When i use s3client options to enable accelerate mode endpoint i get exception while uploading the file and it says
Unable to resolve host "s3-accelerate.amazonaws.com": No address associated with hostname
previously it was working fine version 2.2.+ of sdk. here is the code snippet for creating transferutility
       
```
s3Client = new AmazonS3Client(credentialsProvider,config);
        s3Client.setRegion(Region.getRegion(Regions.US_EAST_1));
        s3Client.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());
        transferUtility = new TransferUtility(s3Client,getApplicationContext());
```

**Comment by kvasukib** [comment]
Hi @maliknaseer,

Thanks for reporting to us.
Can you tell us the ClientConfiguration you are passing into AmazonS3Client?
What network are you connected to? Wifi or cellular?

**Comment by maliknaseer** [comment]
sorry for the late reply. below is the code for client configurations.```
config  = new ClientConfiguration();
        config.setSocketTimeout(120000)
```;
It happens on both wifi and mobile data

**Comment by kvasukib** [comment]
Hi @maliknaseer,

I tried the code that you have posted here with 2.6.6 and I don't see any issues with the transfer.

1. Does your Cognito Identity pool have an IAM Role which has S3 Access to the bucket you are using?
2. Have you enabled Transfer Acceleration in the S3 Console?
3. Are the transfers successful without acceleration mode set?
4. How are you constructing the credentials Provider that is passed into the Amazon S3Client?
5. Can you post the complete exception message and the stack trace for further debugging?

**Comment by kvasukib** [comment]
Hi @maliknaseer, Any update on the current state of the issue in your app? Would you like to share us more details?

**Comment by kvasukib** [comment]
Closing the issue due to inactivity. Please reopen if the issue persists in the latest SDK.
