### ISSUE TITLE
User Pool getSessionInBackground retrieve UserNotFoundException

### ISSUE THREAD

**Issue by miguelguzmanconde** [aws/aws-sdk-android#366]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito

* In what version of SDK are you facing the problem?
com.amazonaws:aws-android-sdk-s3:2.6.0

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
My problem is that i create a user through the console.aws.amazon.com with email and phone confirmed (Because im just proving other aspects) but, when i excecute the void getSessionInBackground() it answers with UserNotFoundException.
It seems to be "solved" alone if i wait some time (I dont know how much).
I need to know if this is normal, if i have to still do a signin() before the getSession()... I need some information about this.
I have to say that this configuration was working during the las 5 hours, i repeated the procedure at least 3 or 4 times and, like i said, after a while, the getSession() returns success.

* Please include a stacktrace if applicable.
```
11-09 14:57:24.712 3408-3408/grupo.red.m.valetparkingadmin E/valetparking: className: grupo.red.m.valetparkingadmin.views.LoginView$2
                                                                           Method: UserPoolManager.login
                                                                           moreData: n/a
                                                                           log: com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoInternalErrorException: Failed to authenticate user
                                                                               at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:803)
                                                                               at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$5.run(CognitoUser.java:635)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: com.amazonaws.services.cognitoidentityprovider.model.UserNotFoundException: User does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserNotFoundException; Request ID: d37136ed-c57f-11e7-b818-4ff703acc8c5)
                                                                               at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:729)
                                                                               at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
                                                                               at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                               at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:2914)
                                                                               at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.initiateAuth(AmazonCognitoIdentityProviderClient.java:2051)
                                                                               at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.refreshSession(CognitoUser.java:1831)
                                                                               at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:796)
                                                                               at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$5.run(CognitoUser.java:635) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
```

***Here is some parts of the code im using

            UserPoolManager.getInstance(mContext).login(
                    email.getText().toString(), pass.getText().toString(), townListener
            ); //the email and password are setted in code in a EditText

    public void login(String email, String pass, TownListener townListener) {
        this.email = email; this.pass = pass; this.townListener = townListener;

        if(userPool == null) townListener.onError("not initialized UserPool");
        else {
            cognitoUserPool = new UserPoolManager();
            userPool.getUser(email).getSessionInBackground(signInCallback);
        }
    }

    private AuthenticationHandler signInCallback = new AuthenticationHandler() {

        @Override
        public void onSuccess(CognitoUserSession userSession, CognitoDevice newDevice) {

            if(userSession.isValid()) {
                CognitoManager.getInstance().setUserPool(userSession.getIdToken().getJWTToken());

                userPool.getCurrentUser().getDetailsInBackground(detailsListener);
            } else townListener.onError("Token ha quedado inutilizado por razones de seguridad.");

        }

        @Override
        public void getAuthenticationDetails(AuthenticationContinuation authenticationContinuation,
                                             String userId) {
            GLog.i("getAuthenticationDetails.continuation(): " + authenticationContinuation.toString());
            authenticationContinuation.setAuthenticationDetails(new
                    AuthenticationDetails(email, pass, null));
            authenticationContinuation.continueTask();
        }

        @Override
        public void getMFACode(final MultiFactorAuthenticationContinuation continuation) {
            GLog.i("getMFACode.continuation(): " + continuation.toString());
        }

        @Override
        public void authenticationChallenge(final ChallengeContinuation continuation) {
            GLog.i("authenticationChallenge.getChallengeName(): " + continuation.getChallengeName());

            if("NEW_PASSWORD_REQUIRED".equals(continuation.getChallengeName())) {
            }
        }

        @Override
        public void onFailure(Exception exception) {
            townListener.onError(exception);
        }
    };

**Comment by kvasukib** [comment]
Hi @miguelguzmanconde,

Are you facing the issue in the latest SDK version? Can you provide us logs where it succeeds and fails? Did you modify the AWS Region between the retries?

**Comment by snodnipper** [comment]
I have also triggered this issue.  I had some old tokens and I deleted the user via the cognito webpage.  Essentially, I encountered `com.amazonaws.services.cognitoidentityprovider.model.UserNotFoundException: User does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserNotFoundException; Request ID: 9911881f....)`.

The error message was "User does not exist." - you will note that the catch above clears the tokens with clearCachedTokens();.  I added the clear cached tokens and that resolved my issue.  Without the fix the user was stuck in a failure loop.

```java
   } catch (final Exception e) {
       clearCachedTokens(); // <- added
       throw new CognitoInternalErrorException("Failed to authenticate user", e);
   } 
```
https://github.com/aws/aws-sdk-android/blob/1c26696d4e06f193f463d7d3575624aa29740bfe/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L853

**Comment by kvasukib** [comment]
Hi @miguelguzmanconde, Can you provide us the implementation of UserPoolManager is possible?
@snodnipper, We will check and add the trigger accordingly. Thank you for the analysis.

**Comment by drxeno02** [comment]
I am running into the same issue. This is new, it was working before. I updated the cognito library to v2.6.14. The error I am receiving

> com.amazonaws.services.cognitoidentityprovider.model.UserNotFoundException: User does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserNotFoundException; Request ID: 334a4da1-42a3-11e8-8072-11ccbb2a2c28)

I was trying to get user details using the "GetDetailsHandler". I successfully signed the user in, then I tried to get user details. 

```
    private static void getUserDetails() {
        // set user
        mUser = mUserPool.getCurrentUser();

        GetDetailsHandler handler = new GetDetailsHandler() {
            @Override
            public void onSuccess(CognitoUserDetails cognitoUserDetails) {

            }

            @Override
            public void onFailure(Exception exception) {
                exception.printStackTrace();
                // get user details failed
                Log.e(TAG, exception.toString());
                if (!FrameworkUtils.checkIfNull(mDatabaseRegisterCompleteLister)) {
                    // set listener
                    mDatabaseRegisterCompleteLister.onFailure(exception);
                }
            }
        };
        mUser.getDetailsInBackground(handler);
```

mUser object is not null. It has all the correct information, e.g. the user data such as email, and other attributes. What happened?

**Comment by npalethorpe** [comment]
Experiencing the same issue suddenly too.

```
com.amazonaws.services.cognitoidentityprovider.model.UserNotFoundException: User does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserNotFoundException; Request ID: 62156912-4958-11e8-b18b-b1ca6355ff7d)
```

I have updated to the latest SDK (2.6.18) and still no luck. It only appears to be occurring with certain credentials though - other users are having no issue authenticating. The iOS SDK has no problem authenticating with the same accounts.

**Comment by hakansuluoglu** [comment]
Up
