### ISSUE TITLE
"invalid_client" error when getting token with User pool using client secret

### ISSUE THREAD

**Issue by daole** [aws/aws-sdk-android#368]
I always get "invalid_client" error when I try to get user token from a user pool app client with client secret. My code:
Auth.Builder builder = new Auth.Builder();
        builder
                .setAppClientId("MY_CLIENT_ID")
                .setAppClientSecret("MY_CLIENT_SECRET")
                .setAppCognitoWebDomain("MY_USER_POOL_DOMAIN")
                .setSignInRedirect("MY_REDIRECT_URL")
                .setSignOutRedirect("MY_REDIRECT_URL")
                .setApplicationContext(this.getApplicationContext());

I believe the cause is the new line character added to the Authorization header due to the method
public final static String encodeBase64(String str)
in this file
https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/util/Pkce.java

Please add a NO_WRAP flag as indicated here
https://stackoverflow.com/questions/30598357/who-is-adding-n-in-base64-encoded-image-when-i-write-it-in-a-file-java/30601485#30601485

**Comment by drxeno02** [comment]
@daole This is the same issue as #315. I resolved this issue and committed the fix. I am waiting for Amazon to accept. Thanks!

**Comment by kvasukib** [comment]
This has been fixed in 2.6.13 release of Android SDK.
