### ISSUE TITLE
How to use User Pools App Integration and Federation with native UI

### ISSUE THREAD

**Issue by daole** [aws/aws-sdk-android#370]
Hi, I wonder whether or not it is possible to use User Pools App Integration and Federation without the hosted UI. I have a Facebook login button which returns Facebook access token which I want to use to authenticate the Facebook user into my User Pool directly. Could anyone please tell me if this is possible as I don't want my users to log in to Facebook again in the hosted UI if they have already logged in in Facebook app.
Thanks in advance

**Comment by minbi** [comment]
This is possible.

You may look at this samples repo. https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoYourUserPoolsDemo

And also check out how it's done here. https://github.com/aws/aws-sdk-android/tree/master/aws-android-sdk-auth-facebook/src/main/java/com/amazonaws/mobile/auth/facebook

**Comment by daole** [comment]
@minbi 
I couldn't find any thing using Facebook Login button. Also, the code seems to use Federated Identities, not User Pools App Integration and Federation
