### ISSUE TITLE
Android : InvalidParameterException with AmazonSNSClient.publish()

### ISSUE THREAD

**Issue by desidigitalnomad** [aws/aws-sdk-android#371]
* What service are you using?
PinPoint, SNS
* In what version of SDK are you facing the problem?
Both services are version 2.6.6
* Is the issue limited to Simulators / Actual Devices?
Both
* Can your problem be resolved if you bump to a higher version of SDK?
Using latest versions
* Is this problem related to specific Android/OS version?
No

I need to send push notifications between Android devices for an AWS Mobile Hub project. It is only device-to-device messaging, no topics involved. I have already integrated FCM and PinPoint
`pinpointManager.getNotificationClient().registerDeviceToken(newToken);`

I'm getting the endPointID using this code
`String epID = pinpointManager.getTargetingClient().currentEndpoint().getEndpointId();`

I can successfully push messages to the device from PinPoint console using the above endPointID. However, since there isn't any publish API available in PinPoint, I have integrated SNS. I'm trying to publish with SNS using the endpointID received from PinPoint using this code:
`PublishRequest publishRequest = new PublishRequest();`
`publishRequest.setTargetArn(epID);`
`publishRequest.setMessage("Hello from android");`

`AmazonSNSClient snsClient = new AmazonSNSClient(App.getCCCProvider());`
`snsClient.publish(publishRequest);`

and receiving the following exception

> com.amazonaws.services.sns.model.InvalidParameterException: Invalid parameter: TargetArn Reason: An ARN must have at least 6 elements, not 1 (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: 7ff39768-c6f9-5a6e-8211-c5ec586276fb)

If it helps, my endpointID is : 1fa93529-a5ac-4d70-995a-be1584c68a37

Any pointers or solutions from you guys?

**Comment by kvasukib** [comment]
Hi @desidigitalnomad,

Thanks for reporting to us. The endpoint ID that is retrieved from Amazon Pinpoint will not be understood by AmazonSNSClient.

**Comment by desidigitalnomad** [comment]
Thanks man!
