### ISSUE TITLE
Proguard Issue - Can't find referenced method

### ISSUE THREAD

**Issue by CallumCoombes** [aws/aws-sdk-android#377]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

```
    compile 'com.amazonaws:aws-android-sdk-core:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-s3:2.2.+'
    compile "com.amazonaws:aws-android-sdk-kms:2.2.+"
```

* In what version of SDK are you facing the problem?

        compileSdkVersion 27
        minSdkVersion 19
        targetSdkVersion 22

Issue encountered in 5.0.2, 7.1.1 and 8.0.0 (not tested on other versions)

* Is the issue limited to Simulators / Actual Devices?

No, tested on 5.0.2 actual device and 7.1.1/8.0.0 simulator with same results

* Can your problem be resolved if you bump to a higher version of SDK?

No

* Is this problem related to specific Android/OS version?

No

* Please include a stacktrace if applicable.

`Warning:com.amazonaws.services.s3.model.transform.Unmarshallers$BucketNotificationConfigurationUnmarshaller: can't find referenced method 'com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$BucketNotificationConfigurationHandler parseNotificationConfigurationResponse(java.io.InputStream)' in program class com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser`

aws proguard rules:

```
#Amazon SDK rules
# Class names are needed in reflection
-keepnames class com.amazonaws.**
-keepnames class com.amazon.**
# Request handlers defined in request.handlers
-keep class com.amazonaws.services.**.*Handler
# The following are referenced but aren't required to run
-dontwarn com.fasterxml.jackson.**
-dontwarn org.apache.commons.logging.**
# Android 6.0 release removes support for the Apache HTTP client
-dontwarn org.apache.http.**
# The SDK has several references of Apache HTTP client
-dontwarn com.amazonaws.http.**
-dontwarn com.amazonaws.metrics.**
#end amazon sdk rules
```

The jar files I have in my lib folder are:
aws-android-sdk-cognito-2.6.7.jar
aws-android-sdk-cognitoidentityprovider-2.6.7.jar
aws-android-sdk-core-2.6.7.jar
aws-android-sdk-kms-2.6.7.jar
aws-android-sdk-s3-2.6.7.jar

**Comment by CallumCoombes** [comment]
I added to my proguard rules:

-dontwarn com.amazonaws.**

Which obviously makes it work, but will this have any detrimental effect?

**Comment by CallumCoombes** [comment]
However now I have the error

`Warning:Exception while processing task java.io.IOException: Can't write [/Users/callum/CalChat/calchat/app/build/intermediates/transforms/proguard/debug/jars/3/1f/main.jar] (Can't read [/Users/callum/.gradle/caches/modules-2/files-2.1/com.amazonaws/aws-android-sdk-core/2.2.22/c6789de00db9d1f93faec881fa0c1f5960fb8a15/aws-android-sdk-core-2.2.22.jar(;;;;;;**.class)] (Duplicate zip entry [aws-android-sdk-core-2.2.22.jar:com/amazonaws/auth/AWSAbstractCognitoIdentityProvider.class]))`

**Comment by kvasukib** [comment]
Hi @CallumCoombes,

Thanks for reporting to us. Sorry for the inconvenience caused. In your gradle file, you are depending on the 2.2.+ version of SDK and in the lib folder, you have 2.6.7. Can you make sure you depend on one version of SDK?

**Comment by CallumCoombes** [comment]
Ok, I have changed a few things around and taking your advice in an attempt to get it working.

Lib folder now only contains:
**aws-android-sdk-core-2.6.7.jar
aws-android-sdk-s3-2.6.7.jar**

Gradle dependencies are:
**compile 'com.amazonaws:aws-android-sdk-core:2.6.7'
compile 'com.amazonaws:aws-android-sdk-s3:2.6.7'**

and proguard rules are:
```
#Amazon SDK rules
# Class names are needed in reflection
-keepnames class com.amazonaws.**
-keepnames class com.amazon.**
# Request handlers defined in request.handlers
-keep class com.amazonaws.services.**.*Handler
# The following are referenced but aren't required to run
-dontwarn com.fasterxml.jackson.**
-dontwarn org.apache.commons.logging.**
# Android 6.0 release removes support for the Apache HTTP client
-dontwarn org.apache.http.**
# The SDK has several references of Apache HTTP client
-dontwarn com.amazonaws.http.**
-dontwarn com.amazonaws.metrics.**
#end amazon sdk rules
```

This now gives a single proguard error of:
`Warning:Exception while processing task java.io.IOException: Can't write [/blah/blah/blah/blah/app/build/intermediates/transforms/proguard/debug/jars/3/1f/main.jar] (Can't read [/blah/blah/.gradle/caches/modules-2/files-2.1/com.amazonaws/aws-android-sdk-s3/2.6.7/a27a80c813338419af897f8e8ab63b308ca86072/aws-android-sdk-s3-2.6.7.jar(;;;;;;**.class)] (Duplicate zip entry [aws-android-sdk-s3-2.6.7.jar:com/amazonaws/auth/AwsChunkedEncodingInputStream.class]))`

Any ideas how to solve this duplicate zip entry?

**Comment by CallumCoombes** [comment]
So after removing all jars from my libs folder it works fine. I thought as per the setup instructions these jar files were required for it to work?

**Comment by kvasukib** [comment]
Yes. You are supposed to either use import in gradle or add the jar files in lib directory. We recommend you to use the gradle imports.

Just adding the following lines to build.gradle under dependencies would work.

compile 'com.amazonaws:aws-android-sdk-core:2.6.7'
compile 'com.amazonaws:aws-android-sdk-s3:2.6.7'

**Comment by kvasukib** [comment]
Closing the issue. Please feel free to open an issue if the problem exists.
