### ISSUE TITLE
READ_PHONE_STATE added to the Manifest during Manifest merge

### ISSUE THREAD

**Issue by hameno** [aws/aws-sdk-android#380]
- aws-android-sdk-auth-core
- aws-android-sdk-auth-facebook
- aws-android-sdk-auth-google
- aws-android-sdk-auth-ui
- aws-android-sdk-auth-userpool
- aws-android-sdk-cognitoauth
- aws-android-sdk-kinesisvideo
- aws-android-sdk-lambda
- aws-android-sdk-lex
- aws-android-sdk-mobile-client

do not declare targetSDK which causes READ_PHONE_STATE to be added to the Manifest during Manifest merge.

Excerpt from Manifest merger log:
```
uses-permission#android.permission.READ_PHONE_STATE
IMPLIED from <project>/src/main/AndroidManifest.xml:2:1-36:12 reason: com.amazonaws.mobile.auth.core has a targetSdkVersion < 4
```

Please add targetSDK and minSDK to all projects which create AARs.

**Comment by kvasukib** [comment]
Hi @hameno, Thanks for reporting to us. We are looking into it.

**Comment by hameno** [comment]
I saw you did a new release without any fix for this. Could you please fix this? It's just a few lines in the  maven pom, see http://simpligility.github.io/android-maven-plugin/manifest-merger-mojo.html#manifestMerger.

**Comment by minbi** [comment]
Hi @hameno ,

We have just release version 2.6.12 of the SDK. Please see if this has fixed your issue.

**Comment by hameno** [comment]
I'm only seeing this change for 6 Manifests (I listed 10 aar projects) and only directly inside the AndroidManifest. It would have been easier to adjust the android-maven-plugin configuration and since that would apply that change to all AndroidManifests.

**Comment by hameno** [comment]
For reference:
$ find . -name AndroidManifest.xml -print -exec grep targetSdk {} \;
./aws-android-sdk-auth-core/src/main/AndroidManifest.xml
<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="25" /></manifest>
./aws-android-sdk-auth-facebook/src/main/AndroidManifest.xml
<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="25" /></manifest>
./aws-android-sdk-auth-google/src/main/AndroidManifest.xml
<uses-sdk android:minSdkVersion="23" android:targetSdkVersion="25" /></manifest>
./aws-android-sdk-auth-ui/src/main/AndroidManifest.xml
<uses-sdk android:minSdkVersion="23" android:targetSdkVersion="25" /></manifest>
./aws-android-sdk-auth-userpools/src/main/AndroidManifest.xml
<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="25" /></manifest>
./aws-android-sdk-cognitoauth/src/main/AndroidManifest.xml
./aws-android-sdk-kinesisvideo/src/main/AndroidManifest.xml
<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="25" /></manifest>
./aws-android-sdk-lambda/src/test/resources/com/amazonaws/mobileconnectors/util/AndroidManifest.xml
        android:targetSdkVersion="17" />
./aws-android-sdk-lex/src/main/AndroidManifest.xml
        android:targetSdkVersion="21" />
./aws-android-sdk-mobile-client/src/main/AndroidManifest.xml

Still missing for:
* aws-android-sdk-mobile-client
* aws-android-sdk-cognitoauth

**Comment by kvasukib** [comment]
We have fixed aws-android-sdk-mobile-client and aws-android-sdk-cognitoauth in v2.6.13 release. Closing the issue.
