### ISSUE TITLE
Amazon Lex - Override MicrophoneListener

### ISSUE THREAD

**Issue by MichZipp** [aws/aws-sdk-android#383]
Hi,

I'm using Amazon Lex and I'm wondering, if it is possible to override the MicrophoneListener.
In my case, I would like to implement my own logic, if the user didn't respond within the speech time out limit. 

Greetings,
Michael

**Comment by kvasukib** [comment]
Hi @MichZipp, Are you trying to create a class that implements MicrophoneListener and let the new listener be used by the SDK?

**Comment by MichZipp** [comment]
Yes exactly! The implementation of my own MicrophoneListener isn't the Problem.  But how can I set the Listener in my main Activity? For the Voice Interaction I use the InteractiveVoiceView, which only provides a method to set the InteractiveVoiceListener.

**Comment by MichZipp** [comment]
Problem solved, I used the InteractionClient instead of the InteractiveVoiceView!
