### ISSUE TITLE
How to use User Pools App Integration and Federation with native UI (Not using Mobile Hub)

### ISSUE THREAD

**Issue by daole** [aws/aws-sdk-android#385]
#370 
I open this issue because my old issue was closed without a satisfying answer.
I wonder whether or not it is possible to use User Pools App Integration and Federation without the hosted UI. I have a Facebook login button which returns Facebook access token which I want to use to authenticate the Facebook user into my User Pool directly. Could anyone please tell me if this is possible as I don't want my users to log in to Facebook again in the hosted UI if they have already logged in in Facebook app. Note that I am not using Mobile Hub.
Thanks in advance

**Comment by kvasukib** [comment]
It is not possible to bring your own token to Amazon Cognito User Pools.  That is only supported by Amazon Cognito Federated Identities.  User Pools must get the token from Facebook at this time through the hosted UI.

**Comment by daole** [comment]
Thank @kvasukib , are there any chances this feature will be supported soon?

**Comment by kvasukib** [comment]
Hi @daole, We will take it as a feature request.

**Comment by minbi** [comment]
The service does not support this use-case. Closing because SDK cannot implement this feature.
