### ISSUE TITLE
TransferUtility recursive call to upload method

### ISSUE THREAD

**Issue by gtux** [aws/aws-sdk-android#388]
I was coding and get an recursive call when I use upload method with this signature: 

upload(java.lang.String key, java.io.File file, ObjectMetadata metadata, CannedAccessControlList cannedAcl, TransferListener listener)

On the code on line 506 that method call itself, so it thrown a StackOverflowException.
Line:
https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L506

### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
S3

* In what version of SDK are you facing the problem?
2.6.12

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
There is no higher version

* Is this problem related to specific Android/OS version?
Yes

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Hi @gtux, Thanks for reporting to us. We are looking into it.

**Comment by kvasukib** [comment]
We have fixed this issue in 2.6.13 release. Thanks for pointing it out.
