### ISSUE TITLE
How can I implement CloudWatchLogs on Android?

### ISSUE THREAD

**Issue by gtux** [aws/aws-sdk-android#389]
What is the name of the package that contains AmazonCloudWatchLogsClient class?

### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Amazon CloudWatch Logs

* In what version of SDK are you facing the problem?
2.6.12

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
I dont know

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Hi @gtux, Thanks for reporting to us. Here it is: https://github.com/aws/aws-sdk-android/tree/master/aws-android-sdk-logs/src/main/java/com/amazonaws/services/logs

**Comment by gtux** [comment]
I order to be honest, I did not use the Cloudwatch Logs at that time, because my emergency I used other solution
