### ISSUE TITLE
Does not work solution for issue #389

### ISSUE THREAD

**Issue by gtux** [aws/aws-sdk-android#392]
Hi 

   Sorry if I do insist over this issue, but I can't load the CloudWatchLogs client, when add the line proposed as solution on issue #389 

compile 'com.amazonaws:aws-android-sdk-logs:2.6.+'

My proyect doesn't compile and says that file does not exists.

Also, maybe it is because on the main pom that module is not listed:

https://github.com/aws/aws-sdk-android/blob/master/pom.xml

This issue is reproducible: I tryed with a new project loading only that module and I does not work.

Could you please review this issue?

Thanks.

* What service are you using?
CloudWatch Logs

* In what version of SDK are you facing the problem?
Since 6.2.12

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

code: 

....
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    implementation 'com.google.android.gms:play-services-gcm:11.8.0'
    implementation 'com.amazonaws:aws-android-sdk-logs:2.6.+'
}
...

Message Error:

Error:(28, 20) Failed to resolve: com.amazonaws:aws-android-sdk-logs:2.6.+

* Please include a stacktrace if applicable.

**Comment by kvasukib** [comment]
Hi @gtux, Sorry for the inconvenience caused. We are looking into it.

**Comment by kvasukib** [comment]
We have resolved this in 2.6.14. Please let us know if it works.
