### ISSUE TITLE
DexArchiveMergerException: Unable to merge dex error with aws-android-sdk-cognitoidentityprovider jar file

### ISSUE THREAD

**Issue by KMiso** [aws/aws-sdk-android#396]
Hi, I am trying to use AWS cognito on android studio .
I learned that I need to import aws-android-sdk-cognitoidentityprovider jar file.
But when I import those jar files, I keep getting the same error...
I looked it up, and tried every way I found such as cleaning or setting multidexenabled true.
But couldn't solve the problem.
Please let me know if you have any ideas how to fix this.
Thank you

Error:
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by kvasukib** [comment]
Hi @KMiso, Can you post the contents of the build.gradle file?

**Comment by KMiso** [comment]
I do not get that error if I only import cognito jar file. 
I see that error now when I import cognitoidentityprovider jar file. 
Are there any other necessary steps to use cognitoidentityprovider jar file?
I synchronized, cleaned and rebuilt my project and gradle file... But I still see that error...

Here is my build.gradle file.

----------------------------------------------------------------------------------------------
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.kmiso.iotapplication"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}

**Comment by kvasukib** [comment]
Hi @KMiso, 

**What's the version of SDK you are using?**

**I tried the following:**

**$ ls libs**
aws-android-sdk-cognito-2.6.13.jar                 
aws-android-sdk-cognitoidentityprovider-2.6.13.jar

**my build.gradle file:**

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    compile 'com.amazonaws:aws-android-sdk-s3:2.6.+'
    compile "com.amazonaws:aws-android-sdk-mobileanalytics:2.3.+"
}

**:app:dependencies output**

Executing tasks: [androidDependencies]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/karthba/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
:androidDependencies
debug
debugCompileClasspath - Dependencies for compilation
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognito-2.6.13.jar
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognitoidentityprovider-2.6.13.jar
+--- com.amazonaws:aws-android-sdk-s3:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-mobileanalytics:2.3.9@jar
+--- com.amazonaws:aws-android-sdk-kms:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-core:2.6.13@jar
\--- com.google.code.gson:gson:2.2.4@jar

debugRuntimeClasspath - Dependencies for runtime/packaging
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognito-2.6.13.jar
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognitoidentityprovider-2.6.13.jar
+--- com.amazonaws:aws-android-sdk-s3:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-mobileanalytics:2.3.9@jar
+--- com.amazonaws:aws-android-sdk-kms:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-core:2.6.13@jar
\--- com.google.code.gson:gson:2.2.4@jar

debugAndroidTest
debugAndroidTestCompileClasspath - Dependencies for compilation
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognito-2.6.13.jar
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognitoidentityprovider-2.6.13.jar
+--- com.amazonaws:aws-android-sdk-s3:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-mobileanalytics:2.3.9@jar
+--- com.amazonaws:aws-android-sdk-kms:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-core:2.6.13@jar
\--- com.google.code.gson:gson:2.2.4@jar

debugAndroidTestRuntimeClasspath - Dependencies for runtime/packaging

debugUnitTest
debugUnitTestCompileClasspath - Dependencies for compilation
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognito-2.6.13.jar
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognitoidentityprovider-2.6.13.jar
+--- com.amazonaws:aws-android-sdk-s3:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-mobileanalytics:2.3.9@jar
+--- com.amazonaws:aws-android-sdk-kms:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-core:2.6.13@jar
\--- com.google.code.gson:gson:2.2.4@jar

debugUnitTestRuntimeClasspath - Dependencies for runtime/packaging
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognito-2.6.13.jar
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognitoidentityprovider-2.6.13.jar
+--- com.amazonaws:aws-android-sdk-s3:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-mobileanalytics:2.3.9@jar
+--- com.amazonaws:aws-android-sdk-kms:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-core:2.6.13@jar
\--- com.google.code.gson:gson:2.2.4@jar

release
releaseCompileClasspath - Dependencies for compilation
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognito-2.6.13.jar
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognitoidentityprovider-2.6.13.jar
+--- com.amazonaws:aws-android-sdk-s3:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-mobileanalytics:2.3.9@jar
+--- com.amazonaws:aws-android-sdk-kms:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-core:2.6.13@jar
\--- com.google.code.gson:gson:2.2.4@jar

releaseRuntimeClasspath - Dependencies for runtime/packaging
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognito-2.6.13.jar
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognitoidentityprovider-2.6.13.jar
+--- com.amazonaws:aws-android-sdk-s3:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-mobileanalytics:2.3.9@jar
+--- com.amazonaws:aws-android-sdk-kms:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-core:2.6.13@jar
\--- com.google.code.gson:gson:2.2.4@jar

releaseUnitTest
releaseUnitTestCompileClasspath - Dependencies for compilation
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognito-2.6.13.jar
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognitoidentityprovider-2.6.13.jar
+--- com.amazonaws:aws-android-sdk-s3:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-mobileanalytics:2.3.9@jar
+--- com.amazonaws:aws-android-sdk-kms:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-core:2.6.13@jar
\--- com.google.code.gson:gson:2.2.4@jar

releaseUnitTestRuntimeClasspath - Dependencies for runtime/packaging
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognito-2.6.13.jar
+--- /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/libs/aws-android-sdk-cognitoidentityprovider-2.6.13.jar
+--- com.amazonaws:aws-android-sdk-s3:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-mobileanalytics:2.3.9@jar
+--- com.amazonaws:aws-android-sdk-kms:2.6.13@jar
+--- com.amazonaws:aws-android-sdk-core:2.6.13@jar
\--- com.google.code.gson:gson:2.2.4@jar

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed


**:app:transformDexArchiveWithExternalLibsDexMergerForDebug output**

Executing tasks: [transformDexArchiveWithExternalLibsDexMergerForDebug]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/karthba/Library/Android/sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:checkDebugManifest UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:prepareLintJar UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:createDebugCompatibleScreenManifests UP-TO-DATE
:processDebugManifest UP-TO-DATE
:splitsDiscoveryTaskDebug UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:javaPreCompileDebug UP-TO-DATE
:compileDebugJavaWithJavac UP-TO-DATE
:transformClassesWithDexBuilderForDebug UP-TO-DATE
:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE

BUILD SUCCESSFUL in 0s
16 actionable tasks: 16 up-to-date

**Code:**

For example in code, I tried using an API from Cognito identity provider package and the code compiled without any error.

```java
ForgotPasswordHandler fp = new ForgotPasswordHandler() {
            @Override
            public void onSuccess() {

            }

            @Override
            public void getResetCode(ForgotPasswordContinuation forgotPasswordContinuation) {

            }

            @Override
            public void onFailure(Exception e) {

            }
        };
```

**Comment by KMiso** [comment]
I'm using the same version!
aws-android-sdk-cognitoidentityprovider-2.6.13.jar

But, it seems like having the same error on task called
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

Is this my android studio version problem?
I am using :
Android Plugin Version  3.0.1
Gradle version  4.2

**Comment by kvasukib** [comment]
Hi @KMiso,

Thank you for the quick response. I am able to reproduce the issue when I import both CognitoAuth and CognitoIdentityProvider in my app.

For example:

```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    compile 'com.amazonaws:aws-android-sdk-cognitoauth:2.6.13@aar'
    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.6.13'
}
```

And I ran `assembleRelease` task in gradle build which resulted in

```
Information:Gradle tasks [assembleRelease]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/amazonaws/cognito/clientcontext/data/ConfigurationConstant;
Error:Execution failed for task ':transformDexWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/build/intermediates/transforms/dex/release/0 --min-sdk-version 15 /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/build/intermediates/transforms/preDex/release/9.jar /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/build/intermediates/transforms/preDex/release/3.jar /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/build/intermediates/transforms/preDex/release/8.jar /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/build/intermediates/transforms/preDex/release/0.jar /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/build/intermediates/transforms/preDex/release/5.jar /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/build/intermediates/transforms/preDex/release/6.jar /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/build/intermediates/transforms/preDex/release/7.jar /Volumes/Unix/Projects/aws-sdk-android-samples/S3TransferUtilitySample/build/intermediates/transforms/preDex/release/4.jar}
Information:BUILD FAILED in 21s
Information:2 errors
Information:0 warnings
Information:See complete output in console

```

We released Advanced Security Feature in Cognito through a data collection library that is distributed as a jar inside the `cognitoauth` and `cognitoidentityprovider` jar files.

**So when I included both the libraries in my build.gradle I get the exception for release builds only.** 

Questions:

Can you confirm if you are using just `cognitoidentityprovider`? 
Can you clear the local maven/android-build/gradle caches and re-run gradle sync and build?
Can you consume `cognitoidentityprovider` via maven and see if you are still getting the issue?
Do you have a proguard file for your app? If so, can you share us the contents of it?

**Comment by KMiso** [comment]
Thank you for your help
I was able to resolve the issue by deleting all the jar files I put under libs directory and
compiling on app/build.gradle file instead!
I just put this code to compile the latest version.. and now it is working well..

    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.+'
    compile 'com.amazonaws:aws-android-sdk-core:2.+'
    compile 'com.amazonaws:aws-android-sdk-iot:2.+'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.+'

Have a good day!

**Comment by kvasukib** [comment]
Great! Hope it got resolved.
