### ISSUE TITLE
aws-android-sdk-2.6.13 issue with S3

### ISSUE THREAD

**Issue by rickysoung** [aws/aws-sdk-android#399]
I use aws-android-sdk-2.6.13
**private List<S3ObjectSummary> thumbObjList;
thumbObjList = s3.listObjects(Constants.THUMB_BUCKET_NAME).getObjectSummaries();
s3.getResourceUrl(Constants.THUMB_BUCKET_NAME, thumb.getKey())**
get a url from my S3 account
my region set to "us-east-1"
why does it always give me https://s3-us-east-1.amazonaws.com/xxxx, then i can't find my file
but i copy the string, change it to https://s3.amazonaws.com/xxxx
it works
is this a problem ?

**Comment by minbi** [comment]
Hi @rickysoung ,

I have tried the code with version 2.6.13, but was not able to reproduce.

Code:
```
CognitoCachingCredentialsProvider creds = new CognitoCachingCredentialsProvider(this, "poolid", Regions.US_EAST_1);
AmazonS3Client s3 = new AmazonS3Client(creds);
s3.setRegion(Region.getRegion(Regions.US_EAST_1)); // Optional
final String url = s3.getResourceUrl("water", "drop.txt");
Log.d("FINDME", url);
```

Output:
```
D/FINDME: https://water.s3.amazonaws.com/drop.txt
```

**Comment by rickysoung** [comment]
I use the S3TransferUtilitySample with aws-android-sdk-2.6.13
