### ISSUE TITLE
Rekognition: Class AmazonRekognitionClientBuilder not found

### ISSUE THREAD

**Issue by aleksei-tro** [aws/aws-sdk-android#405]
Hey,

Trying to use the following example (https://docs.aws.amazon.com/rekognition/latest/dg/get-started-exercise.html), with SDK version 2.6.+ it's unable to find the `AmazonRekognitionClientBuilder` class.

The example uses 
`import com.amazonaws.services.rekognition.AmazonRekognitionClientBuilder;` which isn't available in SDK it seems

**Comment by kvasukib** [comment]
Hi @aleksei-tro,

Thank you for reporting to us. The class and the document which you are referring is available in the AWS SDK for Java. The AWS SDK for Android provides [AmazonRekognitionClient](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-rekognition/src/main/java/com/amazonaws/services/rekognition/AmazonRekognitionClient.java) and not an associated builder class.
