### ISSUE TITLE
Cognito Unique Email Unrecognized Bug

### ISSUE THREAD

**Issue by zameelpichen** [aws/aws-sdk-android#410]
Userpool created with email as alias. While trying to login, users are created with unique username. Already existing username cannot be used.

but the ISSUE is : already created email address can be used. 

as i searched other places, this seems to be a persisting problem. But could you tell something to solve this? I want existing emailadresses to not be usable.

* What service are you using?
Cognito User Pools

* In what version of SDK are you facing the problem?
com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.6.8

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
this is the highest version

* Is this problem related to specific Android/OS version?
No

**Comment by Pantkowsky** [comment]
Is there anybody who could provide an answer to that?

**Comment by zameelpichen** [comment]
I realized even though this is a bug, in the long run, this does not create any holes (atleast that i could not find one)

so I have ignored it so far.

**Comment by mataide** [comment]
Cognito dont handle unique email as Alias. You should handle it by yourself inside the Presignup trigger.

Something like this:
```
    getUser(event["request"]["userAttributes"]["email"])
        .then((cognito) => {
            return cb(null, event);
        }).catch(err => {
        console.log(err);
        return cb(new Error('Email already exists'), event);
    });
```
