### ISSUE TITLE
TransferUtility reports incorrect progress values

### ISSUE THREAD

**Issue by sewar** [aws/aws-sdk-android#411]
* What service are you using?
Amazon S3

* In what version of SDK are you facing the problem?
2.6.15

* Is the issue limited to Simulators / Actual Devices?
Tested on actual device only.

* Can your problem be resolved if you bump to a higher version of SDK?
No, but reverting to 2.4.6 seems to fix it.

* Is this problem related to specific Android/OS version?
Don't think so.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I justed updated from 2.4.6 to 2.6.15 and started noticing incorrect upload progress. 

1. Call `TransferUtility.upload(bucket, key, file)` to start upload.
2. Call `TransferUtility.getTransferById(id)` to get `bytesTransferred` and `bytesTotal`.
3. `bytesTransferred` is bigger than `bytesTotal`.

Attached screenshot of AWS SDK table showing incorrect values.

![image](https://user-images.githubusercontent.com/4277809/36331818-17d7c5aa-1335-11e8-9933-7921aa6393fb.png)

**Comment by kvasukib** [comment]
Hi @sewar, Thank you for reporting to us. Sorry for the inconvenience caused. 
Does bytesCurrent exceed bytesTotal for every transfer? 
Can you give more information from the logs from the beginning of a transfer through the end of the transfer when bytesCurrent exceed bytesTotal? 
Are there any network disconnects and reconnects observed?
Are there app crashes and app restarts observed?

**Comment by sewar** [comment]
Thanks for the quick response.

> Does bytesCurrent exceed bytesTotal for every transfer?

No.

> Can you give more information from the logs from the beginning of a transfer through the end of the transfer when bytesCurrent exceed bytesTotal?

I'll try to do more testing on Monday, what kind of logs do you need? Is there a debug flag to enable?

> Are there any network disconnects and reconnects observed?

None that I noticed, the files were small though.

> Are there app crashes and app restarts observed?

No.

> Do you attach a listener object with the observer returned by the upload/download function and do you get callback from the onProgressChanged method?

Yes and yes.

I was uploading 4 small files at the same time, they all had a listener attached and `onProgressChanged` was called. From `onProgressChanged` I call my function which calculates total progress percentage using `TransferUtility.getTransferById(id)`.

**Comment by kvasukib** [comment]
>>>I was uploading 4 small files at the same time, they all had a listener attached and onProgressChanged was called. From onProgressChanged I call my function which calculates total progress percentage using TransferUtility.getTransferById(id).

Can you instead print out the `bytesCurrent` and `bytesTotal` from the `onProgressChanged` and see if they are correct? These are the parameters of the `onProgressChanged` callback function.

**Comment by sewar** [comment]
I did a few more testing and it seems fine now, I'll reopen if I spot it again.

**Comment by kvasukib** [comment]
Thank you @sewar for the confirmation. We are trying to find issues related to progress tracking and fix the same. If you find any anomaly, please collect logs and paste here and we will be able to root cause them faster. Thank you!
