### ISSUE TITLE
key name change 2.614 version

### ISSUE THREAD

**Issue by chandreshandroid** [aws/aws-sdk-android#416]
I uploaded file with the key name is `1184*2112*IMG_27_02_2018_07_29_1956.jpg`  but it converted the '*' symbol to %2A that why it is display 1184%2A2112%2AIMG_27_02_2018_07_29_1956.jpg so i am not able to access this.

I am using 2.6.14 version sdk.

**Comment by kvasukib** [comment]
Hi @chandreshandroid, Thank you for reporting to us. This used to work in versions prior to 2.4.1. Starting 2.4.1 we are facing this issue. We are working on to fix this.

**Comment by kvasukib** [comment]
@chandreshandroid Sorry for the delayed reply. This issue has been fixed in 2.7.4. Please upgrade and check and let us know if you have any issues.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
