### ISSUE TITLE
Data Encoding/encryption processing

### ISSUE THREAD

**Issue by mssureshmewara** [aws/aws-sdk-android#418]
Dear ,

Thank you for your support.

I just want to know that this library using any Data Encoding/encryption processing, if yes could you please give some information about it, if possible.

Thanks in advance.

**Comment by mssureshmewara** [comment]
Thank you @kvasukib for your reply.
I am using the below parts of the SDK
- aws-android-sdk-ses 
- aws-android-sdk-core

**Comment by minbi** [comment]
Hi @mssureshmewara  ,

Encryption is optional and is not on by default, please read more here: https://docs.aws.amazon.com/kms/latest/developerguide/services-ses.html

Please open another issue if there are further questions. Closed issues are not monitored.
