### ISSUE TITLE
NoClassDefFoundError: io/reactivex/Observable

### ISSUE THREAD

**Issue by devganiyahitesh1** [aws/aws-sdk-android#422]
* I am using aws dynamodb with android application

* SDK version : com.amazonaws:aws-android-sdk-ddb-mapper:2.6.15

* Issue facing and devices and emulator.

* Not facing issue greater android API 21

* Facing issue with kitkat and below versions

    private static AmazonDynamoDBClient ddb;
    private static DynamoDBMapper mapper;

    DynamoDBManager() {
        if (mapper == null) {
            ddb = MyApplication.clientManager.ddb();
            mapper = DynamoDBMapper.builder().dynamoDBClient(ddb) .build();
        }
    }
    void saveObject(Object object) {
        mapper.save(object); // Crash on this line
    }
    buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

apply plugin: 'realm-android'
android {
    
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.xxx"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            debuggable true
        }
    }
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/DEPENDENCIES'
    }
    productFlavors {
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.google.firebase:firebase-messaging:11.8.0'
    implementation 'com.google.firebase:firebase-crash:11.8.0'
    implementation 'com.google.android.gms:play-services-maps:11.8.0'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.android.gms:play-services-places:11.8.0'
    implementation 'io.reactivex:rxjava:1.3.6'
    implementation 'jp.wasabeef:glide-transformations:3.1.0'
    implementation 'com.facebook.android:facebook-login:4.31.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation "com.android.support:cardview-v7:$support_version"
    implementation "com.android.support:appcompat-v7:$support_version"
    implementation "com.android.support:design:$support_version"
    implementation "com.android.support:recyclerview-v7:$support_version"
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.google.android.gms:play-services-auth:11.8.0'
    implementation 'com.dlazaro66.qrcodereaderview:qrcodereaderview:2.0.3'
    implementation 'com.amazonaws:aws-android-sdk-ddb-mapper:2.6.15'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.6.15'
    implementation 'com.amazonaws:aws-android-sdk-lambda:2.6.15'
    implementation 'com.google.zxing:core:3.3.0'
    implementation 'org.elasticsearch.client:elasticsearch-rest-client-sniffer:6.2.1'
    implementation 'com.devbrackets.android:exomedia:4.1.0'
    implementation 'com.github.chrisbanes:PhotoView:2.1.3'
    compile('com.crashlytics.sdk.android:crashlytics:2.9.0@aar') {
        transitive = true;
    }
}

**Comment by kvasukib** [comment]
Thank you @devganiyahitesh1 for reporting to us. 

The following dependencies might have a conflicting file RxJava.
compile 'com.android.support.constraint:constraint-layout:1.0.2'
compile 'io.reactivex:rxjava:1.3.6'

**Comment by devganiyahitesh1** [comment]
Yes, got solution for the same. 
I have remove some unused dependency and also removed rx java dependency `io.reactivex.rxjava` . In replacement of Rx java i have added some dummy classes in my package which is already described here https://realm.io/docs/java/latest.

    // File 1
    package io.reactivex;
    public class Flowable {
    }
    // File 2
    package io.reactivex;
    public class Observable {
    }
    // File 3
    package io.reactivex;
    public enum BackpressureStrategy {
       LATEST;
    }
