### ISSUE TITLE
Warning A connection to https://******s3.us-west-2.amazonaws.com/ was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by noamsegv** [aws/aws-sdk-android#423]
### To help us solve your problem better, please answer the following list of questions.

* s3

* In what version of SDK are you facing the problem?

aws-android-sdk-s3:2.6.15

* Oreo Device specifically Google Pixel

* Can your problem be resolved if you bump to a higher version of SDK? No

* Is this problem related to specific Android/OS version? Maybe

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Upload 100 images to s3 bucket

**Comment by kvasukib** [comment]
Thank you @noamsegv for reporting to us. Can you share a code snippet and the logs from Logcat window for further debugging?

**Comment by noamsegv** [comment]
the above that is the log from the log cat.
happens on google pixel with oreo.
code snippet:

statically allocated in util class

public static TransferUtility getTransferUtility(Context context) {
    if (sTransferUtility == null) {
        sTransferUtility =
TransferUtility.builder().s3Client(getS3Client(context.getApplicationContext())).context(context.getApplicationContext()).build();
    }

    return sTransferUtility;
}

transferUtility = Util.getTransferUtility(this);

observer = transferUtility.upload(Constants.BUCKET_NAME, mDeviceId +
"/" + file.getName(), file);

Thanks

**Comment by rohandubal** [comment]
Hello,

Thanks for providing the code snippet. Any particular reason you are storing the client statically?

Could you try to create and use client non-statically and check if the warning goes away?

Thanks,
Rohan

**Comment by kvasukib** [comment]
Hi @noamsegv, We have updated the [S3TransferUtilitySample](https://github.com/awslabs/aws-sdk-android-samples/blob/master/S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/Util.java) app -> `Util.java `to not have a static reference to the transfer utility instance. Instead each activity has its own transfer utility instance. This will remove the warning you get due to static reference. Can you try this method and let us know if it works?
