### ISSUE TITLE
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by krish71** [aws/aws-sdk-android#426]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

* In what version of SDK are you facing the problem?

* Is the issue limited to Simulators / Actual Devices?

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific Android/OS version?

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by krish71** [comment]
can anyone provide me the solution
the build gradle file is here 
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "org.snowcorp.imageupload"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    buildscript {
        repositories {
            jcenter()
        }
    }
}

dependencies {
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
   // classpath 'com.android.tools.build:gradle:2.3.3'
    //noinspection GradleCompatible

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //noinspection GradleCompatible
    //implementation 'com.android.support:design:24.2.1'
    //noinspection GradleCompatible
    implementation 'com.android.support:design:25.2.0'
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'dev.dworks.libs:volleyplus:+'
    compile 'com.android.volley:volley:1.0.0'
    //compile 'com.google.android.gms:play-services:6.5.87'
    compile 'com.google.android.gms:play-services-location:11.0.1'
    compile 'com.google.android.gms:play-services:11.0.2'
    compile files('libs/json-20170516.jar')
    testCompile 'junit:junit:4.12'
    android {
        aaptOptions.cruncherEnabled = false
        aaptOptions.useNewCruncher = false
    }

}

**Comment by kvasukib** [comment]
Thank you @krish71 for reporting to us. I couldn't find any AWS Android SDK librarires in the dependencies section. Are you consuming any of the AWS Android SDK JAR artifacts through the libs folder?

Besides that,

compile fileTree(include: ['*.jar'], dir: 'libs')
and
compile files('libs/json-20170516.jar')

are importing the json-20170516 twice. You may have to check this.

**Comment by kvasukib** [comment]
Closing this issue. Please re-open if it exists.
