### ISSUE TITLE
Not able to upload file size greater than 5 mb

### ISSUE THREAD

**Issue by anuj7sharma** [aws/aws-sdk-android#428]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using? TransferUtility 

* In what version of SDK are you facing the problem? 2.6.+

* Is the issue limited to Simulators / Actual Devices? No

* Can your problem be resolved if you bump to a higher version of SDK? This is updated version

* Is this problem related to specific Android/OS version? No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Wifi speed is good. While uploading file of 10 mb facing issue Encountered error uploading part 
* Please include a stacktrace if applicable.
Encountered error uploading part 
com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
                                                                   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by cbommas** [comment]
Hello @anuj7sharma 

Sorry to hear that you are facing issues. Can you post your code/code snippet and logs/error messages to help debug?  Also, we made a big number of changes in version 2.6.16 of the SDK, so please make sure that you have that version ( or greater).
