### ISSUE TITLE
I am interested in porting aws-android-sdk-auth-ui to C#

### ISSUE THREAD

**Issue by mipnw** [aws/aws-sdk-android#430]
I would like the ability to use the [SignInUI ](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-auth-ui/src/main/java/com/amazonaws/mobile/auth/ui/SignInUI.java) in a [Xamarin.Android](https://docs.microsoft.com/en-us/xamarin/android/) C# application. To my knowledge Xamarin does not offer bindings to [aws-android-sdk-auth-ui](https://github.com/aws/aws-sdk-android/tree/master/aws-android-sdk-auth-ui), so I thought I might take it upon myself to just port aws-android-sdk-auth-ui from Java to C# by leveraging [AWS-SDK for .NET](https://aws.amazon.com/sdk-for-net/). It is afterall only 4 java source files (SignInActivity.java, SignInUI.java, SignInView.java, AuthUIConfiguration.java).

Unfortunately, I can't seem to find in AWS-SDK for .NET the types I would even need to port aws-android-sdk-auth-ui. For e.g., I do not see an equivalent for type [com.amazonaws.mobile.auth.core.IdentityManager](https://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobile/auth/core/IdentityManager.html) used in the java implementation of SignInUI in the following AWS-SDK for .NET namespaces:

- Amazon.IdentityManagment: a namespace which seems to provide functionality for programmatically administering IAM accounts, not helping authenticate end-users on C# applications

- Amazon.Mobile: a namespace which seems to provide functionality for programatically administering AWS Mobile HUB, i.e. creating and deleting Mobile Hub projects, not for helping mobile applications authenticate to AWS.

- Amazon.Runtime, Amazon.Util: I can't see anything related to identity and authentication in these namespaces either.

Could you please comment on whether AWS-SDK for .NET contains sufficient APIs for me to rebuild a SignInUI equivalent library in C#.

**Comment by kvasukib** [comment]
Thank you @mipnw for expressing interest in porting `SignInUI` to Xamarin.Android. To give you a little background on the Auth SDK, here is the tree of dependencies in the AWS Android SDK

```
`SignInUI` <`aws-android-sdk-auth-ui`>
     |
Auth Providers {UserPools, Fb, Google} <`aws-android-sdk-auth-userpools,` `aws-android-sdk-auth-google`, `aws-android-sdk-auth-facebook`>
     |
Auth Core {IdentityManager} <`aws-android-sdk-auth-core`>
     |
Cognito Federated Identities {CredentialsProvider} <`aws-android-sdk-core`>
```

AWS SDK for .NET only has the last layer which is the `CredentialsProvider`. Unfortunately we may have to port all the above three layers to Xamarin.Android - AWS SDK for .NET

We will take this as a feature request. Please feel free to submit a pull request or suggestions for porting OR improvements for `SignInUI` in Android. We would be happy to discuss about it.

**Comment by mipnw** [comment]
Thank you @kvasukib, that's precisely the type of answer that helps.

Indeed if AWS SDK for .NET is missing several layers between CredentialsProvider and SignInUI, I won't be able to port aws-android-sdk-auth-ui. It'd be a much bigger project than I can chew at the moment.
