### ISSUE TITLE
startService() call on Android 'O'

### ISSUE THREAD

**Issue by mohitmahi** [aws/aws-sdk-android#432]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?  TransferService

https://github.com/aws/aws-sdk-android/blob/dede9ff42c8e102581c36cb3b9964a161b9a6a66/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L873

* In what version of SDK are you facing the problem? Latest 

* Is the issue limited to Simulators / Actual Devices? Android O

* Can your problem be resolved if you bump to a higher version of SDK? NO

* Is this problem related to specific Android/OS version? YES

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Try to start "TransferService" when app is in background
* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by jhermida-agero** [comment]
@kvasukib Any updates on this?

**Comment by kvasukib** [comment]
@mohitmahi  Can you try the following and see if the transfer service starts? If you are invoking TransferUtility from a service context, please do the following in your AndroidManifest.xml file. The following example uses MainService from which TransferUtility is invoked.

<service
            android:name=".MainService"
            android:enabled="true"
            android:launchMode="singleTop"
            android:process=":main_service"
            android:stopWithTask="false" />
        <service
    android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
            android:enabled="true"
            android:process=":main_service" />
