### ISSUE TITLE
Incorrect ReadMe Andorid --> Android (Amazon Cognito)

### ISSUE THREAD

**Issue by mohitmahi** [aws/aws-sdk-android#433]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

https://github.com/aws/aws-sdk-android/blob/23c58741cfbcf8b2f06858b458765fa47abe967e/aws-android-sdk-cognito/README.md#L7

* In what version of SDK are you facing the problem?

* Is the issue limited to Simulators / Actual Devices?

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific Android/OS version?

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Thank you @mohitmahi for pointing it out. We are fixing it.

**Comment by kvasukib** [comment]
This has been fixed in 2.6.18. Closing it.
