### ISSUE TITLE
How to build Android aws-android-sdk-cognitoauth in android studio

### ISSUE THREAD

**Issue by Vijayakumr** [aws/aws-sdk-android#434]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

* In what version of SDK are you facing the problem?

* Is the issue limited to Simulators / Actual Devices?

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific Android/OS version?

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Thank you @Vijayakumr for reporting to us. You can depend on the library in gradle as follows:

dependencies = {
    compile('com.amazonaws:aws-android-sdk-cognitoauth:2.6.17@aar') {
        transitive = true;
    }
}

Are you looking to build the library from the source code?

**Comment by Vijayakumr** [comment]
No, I want to build the app itself (Name: aws-android-sdk-cognitoauth)
