### ISSUE TITLE
CognitoIdentityCredentials is not authorized to perform: mobiletargeting:GetEndpoint

### ISSUE THREAD

**Issue by Deepanshibajaj1503** [aws/aws-sdk-android#437]
Hi,

I am on the latest ver of the SDK, integrating Aws Pinpoint into my app. I do not use Cognito for user management, but have my own internal method for managing that. I am informing that to aws using : 

```
final UpdateEndpointRequest updateEndpointRequest = new UpdateEndpointRequest()
                .withApplicationId(appId)
                .withEndpointId(**ourInternallyManagedUserId**)
                .withEndpointRequest(endpointRequest);
```

WhileI have no trouble sending events and custom attributes, registering an endpoint for re-engagement is proving difficult. 

I have been trying to register a mobile phone number as an Endpoint using the example here 
https://docs.aws.amazon.com/pinpoint/latest/developerguide/endpoints.html so that we can trigger SMSes for our user.

However, I am consistently getting this err - 
`User: arn:aws:sts::XXXXXXXX:assumed-role/nostragamus_unauth_MOBILEHUB_XXXXXXX/CognitoIdentityCredentials is not authorized to perform: mobiletargeting:GetEndpoint on resource: arn:aws:mobiletargeting:us-east-1:XXXXXXXX:apps/XXXXXXXX/endpoints/3 (Service: AmazonPinpoint; Status Code: 403; Error Code: AccessDeniedException; Request ID: 3df82d79-381a-11e8-8192-df58266db5b7`

I had previously defined both pinpoint and cognito as advised using 
```
CognitoCachingCredentialsProvider cognitoCachingCredentialsProvider = new CognitoCachingCredentialsProvider(context, context.getString(R.string.aws_pinpoint_pool_id), Regions.AP_SOUTHEAST_1);
                PinpointConfiguration config = new PinpointConfiguration(context, context.getString(R.string.aws_app_id), Regions.US_EAST_1, cognitoCachingCredentialsProvider);
```
(My main aws setup runs in Singapore region, which is why Mobile Hub created Cognito with South East Asia zone).

Could you please assist understanding what exactly is causing an error for this ? 

Do let me know if you need any additional info.

Much appreciated!

**Comment by kvasukib** [comment]
Thank you @Deepanshibajaj1503 for reporting to us. Sorry for the inconvenience caused. Can you check if the unauth role in the Cogntio Identity Pool has the policy:action "mobiletargeting:GetEndpoint"?

**Comment by Deepanshibajaj1503** [comment]
Hi Karthikeyan,

We are not using Cognito dashboard on AWS. We are using Cognito only to
initialize Pinpoint Manager in our mobile app.
When I try to set this "if the unauth role in the Cogntio Identity Pool has
the policy:action "mobiletargeting:GetEndpoint"" , I am redirected to start
using cognito dashboard.

Regards,
Deepanshi Bajaj

**Comment by behrooziAWS** [comment]
Review your configuration for the role: nostragamus_unauth_MOBILEHUB_XXXXXXX in the IAM console.  Likely you haven't added permissions for mobiletargeting:GetEndpoint in the role policy.

**Comment by joshwolff1** [comment]
Hi, I was reading through this read and had the same issues.. Check out these two links.. I'm working on this now..

https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html

https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

**Comment by Thembelani** [comment]
Please, please, please for the love of the All-mighty, please create a doc for this additional configuration for people who only use specific functionality like Push Notification. This is not in the set up doc

**Comment by desokroshan** [comment]
@Thembelani Can you provide link to the set up doc you are referring to?

**Comment by mharlowfod** [comment]
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/mobile-hub-add-aws-mobile-analytics.html#mobile-hub-add-aws-mobile-analytics-app

The above doc does not mention anything about enabling different things in IAM. Please elaborate here and there.

**Comment by syumaK** [comment]
@mharlowfod , the Pinpoint IAM policy documentation link can be found under React Native section here: [https://aws-amplify.github.io/docs/js/analytics](https://aws-amplify.github.io/docs/js/analytics)

In summary, I use the following policy sample :

    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "mobiletargeting:PutEvents",
                    "mobiletargeting:GetEndpoint",
                    "mobiletargeting:UpdateEndpoint",
                    "mobiletargeting:GetUserEndpoints",
                    "mobiletargeting:UpdateEndpointsBatch",
                    "mobiletargeting:GetApplicationSettings"
                ],
                "Resource": [
                    "arn:aws:mobiletargeting:*:${accountID}:apps/${appId}*"
                ]
            }
        ]
    }
