### ISSUE TITLE
Problems enabling Proguard 

### ISSUE THREAD

**Issue by theo1208** [aws/aws-sdk-android#439]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS

* In what version of SDK are you facing the problem?
compile ('com.amazonaws:aws-android-sdk-mobile-client:2.6.18@aar') { transitive = true; }
compile 'com.amazonaws:aws-android-sdk-s3:2.6.18'
compile 'com.amazonaws:aws-android-sdk-cognito:2.6.18'

* Is the issue limited to Simulators / Actual Devices?
Generating a signed APK

* Can your problem be resolved if you bump to a higher version of SDK?
I am using the highest

* Is this problem related to specific Android/OS version?
no

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I enabled proguard and added the following lines in the proguard-rules.pro

```
#Amazon SDK rules
#Class names are needed in reflection
-keepnames class com.amazonaws.**
-keepnames class com.amazon.**
#Request handlers defined in request.handlers
-keep class com.amazonaws.services.**.*Handler
#The following are referenced but aren't required to run
-dontwarn com.fasterxml.jackson.**
-dontwarn org.apache.commons.logging.**
#Android 6.0 release removes support for the Apache HTTP client
-dontwarn org.apache.http.**
#The SDK has several references of Apache HTTP client
-dontwarn com.amazonaws.http.**
-dontwarn com.amazonaws.metrics.**
#end amazon sdk rules
```

When trying to compile the signed APK I get the following warnings:

Warning:com.amazonaws.mobile.client.AWSMobileClient: can't find referenced class com.amazonaws.mobile.auth.facebook.FacebookSignInProvider
Warning:com.amazonaws.mobile.client.AWSMobileClient: can't find referenced class com.amazonaws.mobile.auth.google.GoogleSignInProvider
Warning:com.amazonaws.mobile.client.AWSMobileClient: can't find referenced class com.amazonaws.mobile.auth.userpools.CognitoUserPoolsSignInProvider

I haven't used Facebook or Google sign in within the app. Any idea would be greatly appreciated. 

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by theo1208** [comment]
Thanks for your response.

I just checked in /build/outputs/mapping/release/ and it's empty. No trace of a 'usage.txt' file anywhere in the app. And this makes sense since I couldn't compile any build.

From documentation:
"With each build, ProGuard outputs the following files: dump.txt, mapping.txt, seeds.txt, usage.txt"

**Comment by chienteku** [comment]
Sorry, I forgot to tell you to disable ProGuard then build the app.

**Comment by theo1208** [comment]
I changed to "minifyEnabled false" and then built the app (signed and not), but the release folder is still empty.

**Comment by chienteku** [comment]
@theo1208 you are right, I mixed up the process order. 
And I found a web page that may help you.
keyword: 'Warning: can't find referenced class'
https://stuff.mit.edu/afs/sipb/project/android/sdk/android-sdk-linux/tools/proguard/docs/index.html#manual/troubleshooting.html

**Comment by minbi** [comment]
Hi @theo1208 ,

If you are not using Facebook, Google or Cognito User Pools to authenticate your users, then you can safely add dontwarn lines to your Proguard. These dependencies were not added to try to reduce artifact size and give developers the option to include them when necessary.

i.e.
```
-dontwarn com.amazonaws.mobile.auth.facebook.FacebookSignInProvider
```
