### ISSUE TITLE
Samples Missing

### ISSUE THREAD

**Issue by Hemant0601** [aws/aws-sdk-android#440]
I am unable to find any samples for AWS Rekognition just like S3 and other services for ANDROID , Please let me know where these are available.

**Comment by kvasukib** [comment]
Thank you @Hemant0601 for reporting to us. We will take it as a feature request. See [API Reference](https://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/)

**Comment by Hemant0601** [comment]
@kvasukib In the meanwhile can you suggest me an approach, my requirement is to capture image and match with the one I already have in my S3 bucket and to get the results with confidence level.
Thanks

**Comment by rohandubal** [comment]
Closing it in favor of #https://github.com/awslabs/aws-sdk-android-samples/issues/213
