### ISSUE TITLE
disable RequestTimeToo-Skewed

### ISSUE THREAD

**Issue by defaultbr** [aws/aws-sdk-android#441]
is there a way to disable this kind of check?  

Some devices (old ones) has problems about timezone and people need to adjust the clock manually, doing this, the library stop working and keep showing this error.

is there something like .useServerTimeToAvoidSkewedClock? hehehe

**Comment by rohandubal** [comment]
Hello @defaultbr currently we do not have a feature like this. The time is used to sign the request so we would need a correct time.

Thanks,
Rohan
