### ISSUE TITLE
how can i hide my identiy pool id using proguard when publishing my app 

### ISSUE THREAD

**Issue by Pd51** [aws/aws-sdk-android#443]
i want to hide my identiy pool id and all my dynamodb mapper classes in release mode so that people cannot see my credentials and moodify how can i achieve this i already used default progaurd rules but that doest helped me can i get the proguard rules to hide all my aws related classes and keys please

**Comment by rohandubal** [comment]
Hello @Pd51 that is not possible via proguard as it is required by the app to run correctly.

Thanks,
Rohan
