### ISSUE TITLE
When is the Amazon Translate sdk for android availiable?

### ISSUE THREAD

**Issue by heejaekim7161** [aws/aws-sdk-android#445]
When is the Amazon Translate sdk for android availiable?

**Comment by cbommas** [comment]
Hello @heejaekim7161 

I have added this as a feature request in our backlog and have submitted to the team for prioritization.  I do not have specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the SDK is released.

**Comment by cbommas** [comment]
Hello @heejaekim7161 

The translate SDK is now available in the latest version of the Android SDK, 2.6.20 that was launched on 5/25/2018. Please see https://docs.aws.amazon.com/translate/latest/dg/getting-started-android.html for more information.

Please feel free to reopen this thread if you run into issues and need help.
