### ISSUE TITLE
AWS Cognito create new account is missing selected attribute

### ISSUE THREAD

**Issue by mehmetkemalbayer** [aws/aws-sdk-android#446]
While creating new account using AWS Cognito built-in UI in Android, input form does not show the field that I added using AWS Console. I selected given name as required but form does not include this field. Is there a way to add this field to UI?

**Comment by kvasukib** [comment]
Thank you @mehmetkemalbayer for reporting to us. Are you following this [doc](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html#set-up-email-and-password) to add User Pools SignIn to your app?

Currently the SignInUI for the SignUp form is static and it doesn't honor the required attributes configured with the UserPool on the AWS console. We will take it as a feature request.
