### ISSUE TITLE
is the AWSIotMqttManager on android working on the same level as the AWSIoTDataManager on IOS? 

### ISSUE THREAD

**Issue by BenDenger** [aws/aws-sdk-android#447]
* What service are you using?
com.amazonaws:aws-android-sdk-iot
* In what version of SDK are you facing the problem?
2.6.18
* Is the issue limited to Simulators / Actual Devices?
no
* Can your problem be resolved if you bump to a higher version of SDK?
no

i saw that there is an AWSIoTDataClient on Android, but it seems like i can not use any callbacks there to get the realtime data. 
but at the moment i am unsure if the MqttManager on Android is the same thing as the DataManager on Android. 
i want to prevent that SDK changes at the iOS dataManager dont apply to the MqttManager.

**Comment by kvasukib** [comment]
@BenDenger Thank you for the detailed feedback. Sorry for the inconvenience caused.  We acknowledge the fact that there is inconsistency across platforms for the IoT SDK. 

`AWSIotMqttManager` provides methods to connect, publish, subscribe and disconnect. Here are the callbacks:

[connect](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L616)

[subscribe](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L996)

[publish](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L1089)

Are you referring to the callback to these methods? Can you tell us what callbacks are missing in these methods?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
