### ISSUE TITLE
Athena Query error

### ISSUE THREAD

**Issue by prathamesh1122** [aws/aws-sdk-android#454]
Hello,
I am getting below error on Athena when I try to run my Query-
User: arn:aws:sts::xxxxxxxxxx:assumed-role/xxxxxxxxxx/yyyyyyy is not authorized to perform: athena:StartQueryExecution (Service: AmazonAthena; Status Code: 400; Error Code: AccessDeniedException; Request ID: 49eee8d6-52a7-11e8-964f-c3a8fb8f6ffc)

I have checked that IAM policy has been correctly defined to have required Athena access and it is mapped to correct role.
Can anyone please help me what is going wrong here?

**Comment by kvasukib** [comment]
Thank you @prathamesh1122 for reporting to us. Are you using AWS Android SDK? We currently do not have a low-level client for Amazon Athena via the AWS Android SDK

**Comment by minbi** [comment]
Closing because AWS SDK for Android does not support Athena service
