### ISSUE TITLE
Show signup error without clearing signup fields - Improve the "Sign Up" error handling flow

### ISSUE THREAD

**Issue by anje89** [aws/aws-sdk-android#460]
#### I created a project on the Amazon Mobile Hub and then added the following sdks to my project (all at version 2.6.+@aar)
* aws-android-sdk-mobile-client
* aws-android-sdk-auth-userpools
* aws-android-sdk-auth-ui

What I experienced:
* Observe the "Sign-In" page (with buttons: "Sign In", "Create New Account" and "Forgot Password?")
* Press "Create New Account"
* Observe the "Sign Up" page, enter all details (enter a password that will fail validation) and press the "Sign Up" button
* UI goes back to the initial "Sign-In" page and a dialog with error message is shown (Password did not conform with policy: Password must have uppercase characters)

This means the user has to press "Create New Account" again and fill in all the details again.

It would be better if the error dialog was just shown on the "Sign Up" page, let the user correct their mistake and press "Sign Up" button again.

**Comment by kvasukib** [comment]
Thank you @anje89 for reporting to us. Sorry for the inconvenience caused. We will fix the bug and update this thread once the fix is released.

**Comment by minbi** [comment]
Hi,

We are looking into fixing this issue.

**Comment by minbi** [comment]
Hi @anje89 @BillBunting ,

Please see if SDK release 2.7.6 fixes this issue for you. We have added the following enhancements:
- Preserve sign-up form fields when sign-up validation fails so that end-users can correct and try again.
- Automatically sign-in user after actions such as sign-up or forgot password.

You may see all changes in the [changelog](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-276)

**Comment by BillBunting** [comment]
@minbi Thank you very much! This has been a significant issue for us. I really appreciate the improvements.

**Comment by muellerfr** [comment]
Great to hear @anje89, sounds like the improvements are working for you. If the the fix did not work for you, please comment on the issue, or if you need additional help, please open a new issue.
