### ISSUE TITLE
AWSIotMqttManager creates new threads while reconnect, but never release these threads.

### ISSUE THREAD

**Issue by aeroma** [aws/aws-sdk-android#461]
There is a class: com.amazonaws.mobileconnectors.iot.AWSIotMqttManager
In this class there is a function `scheduleReconnect` with following code:
```
final HandlerThread ht = new HandlerThread("Reconnect thread");
            ht.start();
            Looper looper = ht.getLooper();
            Handler handler = new Handler(looper);
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    LOGGER.debug("TID: " + ht.getThreadId() + " trying to reconnect to session");
                    if (mqttClient != null && !mqttClient.isConnected()) {
                        reconnectToSession();
                    }
                }
            }, MILLIS_IN_ONE_SECOND * currentReconnectRetryTime);
```

Each time when `scheduleReconnect` called it will create new `HandlerThread` but this thread will never be stopped. So number of threads will grow all the time.

Suggested simple solution is to add `ht.quitSafely()` call, after reconnect runnable completes:

```
handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    LOGGER.debug("TID: " + ht.getThreadId() + " trying to reconnect to session");
                    if (mqttClient != null && !mqttClient.isConnected()) {
                        reconnectToSession();
                    }
                    ht.quitSafely();
                }
            }, MILLIS_IN_ONE_SECOND * currentReconnectRetryTime);
```

**Comment by kvasukib** [comment]
Thank you @aeroma for reporting to us. Sorry for the inconvenience caused. We will fix the threading issue and update here once the release is out.

**Comment by aeroma** [comment]
Hello @kvasukib. 

Do you have any updates on this issue?

**Comment by kvasukib** [comment]
@aeroma Sorry for the delayed response. I am in the process of making the changes and testing it. Have you performed any testing with this change? Does it affect the reconnect behavior?
