### ISSUE TITLE
Unable to execute HTTP request: Hostname cognito-identity.us-east-1.amazonaws.com not verified

### ISSUE THREAD

**Issue by alejouribesanchez** [aws/aws-sdk-android#464]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?Amazon android sdk

* In what version of SDK are you facing the problem? 
    // Amazon SDK
    api 'com.amazonaws:aws-android-sdk-s3:2.6.17'
    api 'com.amazonaws:aws-android-sdk-core:2.6.19'
    api 'com.amazonaws:aws-android-sdk-ddb:2.6.17'
    api ('com.amazonaws:aws-android-sdk-mobile-client:2.6.+@aar') { transitive = true; }

* Is the issue limited to Simulators / Actual Devices? Actual devices

* Can your problem be resolved if you bump to a higher version of SDK?No

* Is this problem related to specific Android/OS version? YES just Android 8

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? I am just uploading a zip file.

* Please include a stacktrace if applicable.

Exception: com.amazonaws.AmazonClientException
Unable to execute HTTP request: Hostname cognito-identity.us-east-1.amazonaws.com not verified: certificate: sha1/YCYp9PgdoRNTskxXBbJOjKB8FUk= DN: CN=www.btwifi.com,OU=BT Wi-fi,O=British Telecommunications plc,L=London,ST=London,C=GB,2.5.4.5=#13083031383030303030,2.5.4.15=#131450726976617465204f7267616e697a6174696f6e,1.3.6.1.4.1.311.60.2.1.3=#13024742 subjectAltNames: [my.btopenzone.com, info.btopenzone.com, btopenzone.com, www.btopenzone.com, btwifi.co.uk, www.btwifi.co.uk, reg.btwifi.com, btwifi.com, info.btwifi.com, cdn.btwifi.com, my.btwifi.com, www.btwifi.com]

Caused by javax.net.ssl.SSLPeerUnverifiedException
Hostname cognito-identity.us-east-1.amazonaws.com not verified: certificate: sha1/YCYp9PgdoRNTskxXBbJOjKB8FUk= DN: CN=www.btwifi.com,OU=BT Wi-fi,O=British Telecommunications plc,L=London,ST=London,C=GB,2.5.4.5=#13083031383030303030,2.5.4.15=#131450726976617465204f7267616e697a6174696f6e,1.3.6.1.4.1.311.60.2.1.3=#13024742 subjectAltNames: [my.btopenzone.com, info.btopenzone.com, btopenzone.com, www.btopenzone.com, btwifi.co.uk, www.btwifi.co.uk, reg.btwifi.com, btwifi.com, info.btwifi.com, cdn.btwifi.com, my.btwifi.com, www.btwifi.com]

com.amazonaws.http.UrlHttpClient.writeContentToConnection (Unknown Source:34)
com.amazonaws.http.UrlHttpClient.execute (Unknown Source:49)
com.amazonaws.http.AmazonHttpClient.executeHelper (Unknown Source:392)
com.amazonaws.http.AmazonHttpClient.execute (Unknown Source:19)
com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke (Unknown Source:58)
com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity (Unknown Source:47)
com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito (Unknown Source:48)
com.amazonaws.auth.CognitoCredentialsProvider.startSession (Unknown Source:36)
com.amazonaws.auth.CognitoCredentialsProvider.getCredentials (Unknown Source:15)
com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials (Unknown Source:38)
com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials (Unknown Source)
com.amazonaws.services.s3.AmazonS3Client.invoke (Unknown Source:66)
com.amazonaws.services.s3.AmazonS3Client.putObject (Unknown Source:388)
com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion (Unknown Source:44)
com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call (Unknown Source:60)
com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call (Unknown Source)

Last 7 days
<img width="1140" alt="screen shot 2018-05-21 at 1 21 14 am" src="https://user-images.githubusercontent.com/3950665/40293189-58021ca8-5c95-11e8-90c6-94455fb71163.png">

Last 30 days
<img width="1144" alt="screen shot 2018-05-21 at 1 21 25 am" src="https://user-images.githubusercontent.com/3950665/40293198-65344b8a-5c95-11e8-88ed-6c3d6e79a1b7.png">

**Comment by kvasukib** [comment]
Thank you @alejouribesanchez for reporting to us. Sorry for the inconvenience caused. Have you added the necessary permissions in `AndroidManifest.xml` file?

```xml
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

**Comment by alejouribesanchez** [comment]
thanks @kvasukib  yeah I have that permissions:
`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.FLASHLIGHT" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />`

**Comment by alejouribesanchez** [comment]
For logs check the exception
[snippet.zip](https://github.com/aws/aws-sdk-android/files/2023861/snippet.zip)
