### ISSUE TITLE
Can't access users created via social sign-in

### ISSUE THREAD

**Issue by nbonatsakis** [aws/aws-sdk-android#467]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?

AWS Cognito User Pools

* In what version of SDK are you facing the problem?

2.6.1

* Is the issue limited to Simulators / Actual Devices?

Both

* Can your problem be resolved if you bump to a higher version of SDK?

No

* Is this problem related to specific Android/OS version?

No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I have integrated the identity provider for SDK to access cognito user pools as instructed here: https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html

As far as I understand it, I can allow users to authenticate with third party providers such as Facebook via the hosted web UI, which creates a cognito user in my user pool with mapped provider attributes. 

Now my issue: is there a way to instantiate a `CognitoUser` object representative of a user that has signed in with a social provider? This user exists in the user pool, but does not have a password. The only path I see to signing in a user with the identity provider SDK is via username/password.

To be clear, I would like to have a single path to interacting with my user objects (`CognitoUser`) regardless of whether they are email/password users or third party provider uses. 

 Please let me know if this is not clear or if i missed any required information, and thank you in advance.

**Comment by kvasukib** [comment]
Thank you @nbonatsakis for reporting to us. Sorry for the delayed response. Are you trying to federate a social provider signin with Cognito UserPools? Can you explain your use-case?
