### ISSUE TITLE
TransferUtility class does not respect additional headers

### ISSUE THREAD

**Issue by softwarejoint** [aws/aws-sdk-android#468]
Trying to upload file to s3 using

build.gradle
`
implementation 'com.amazonaws:aws-android-sdk-s3:2.6.20'
`

`
ObjectMetadata metaData = new ObjectMetadata();
metaData.setHeader(Headers.S3_TAGGING, "key=value");
transferUtility.upload(fileKey, file, metaData, CannedAccessControlList.Private);
`

The file on S3 file uploaded doesn't contain any tags. On close inspection the class TransferRecord does not carry forward any metadata custom headers. What will be the way to achieving this?

**Comment by kvasukib** [comment]
Thank you @softwarejoint for reporting to us. Sorry for the inconvenience caused. Does this problem occur only in 2.6.20 or in earlier releases too?

**Comment by softwarejoint** [comment]
I checked only the latest release. the root cause is that the transfertable doesnt store the extra parameters. Respecting tags in the call will be simply adding the x-amz-tagging header support.

**Comment by kvasukib** [comment]
Thank you @softwarejoint for the information. We are working on a fix and will update this thread once the fix is out.

**Comment by softwarejoint** [comment]
Thanks, hope this comes out soon. This will prevent a duplicate call that we have to make after each file upload

**Comment by softwarejoint** [comment]
Any updates on this?

**Comment by softwarejoint** [comment]
Hey guys, any update on this feature?

**Comment by kvasukib** [comment]
HI, @softwarejoint Sorry for keeping you waiting. We will have the fix out in our upcoming release. We will update this thread once the release is out.

**Comment by kvasukib** [comment]
Hi @softwarejoint, Thank you for the patience. We have released 2.6.23 with support for additional headers.

**1. Object Tagging - Single tag**

```java
        final ObjectMetadata objectMetadata = new ObjectMetadata();
        objectMetadata.setHttpExpiresDate(new Date(httpExpiresDate));
        objectMetadata.setUserMetadata(Collections.singletonMap(Headers.S3_TAGGING, "key=value"));

        final File tempFile = temp.newFile();
        TestUtil.fillFile(tempFile, contentLength);
        final TransferObserver observer = transferUtility.upload(BUCKET_NAME, key, tempFile, objectMetadata);
        observer.setTransferListener(new MockTransferListener());
```

**2. Object Tagging - Multiple Tag**

```java
        final ObjectMetadata objectMetadata = new ObjectMetadata();
        objectMetadata.setHttpExpiresDate(new Date(httpExpiresDate));
        objectMetadata.setUserMetadata(Collections.singletonMap(Headers.S3_TAGGING, "key1=value1&key2=value2"));

        final File tempFile = temp.newFile();
        TestUtil.fillFile(tempFile, contentLength);
        final TransferObserver observer = transferUtility.upload(BUCKET_NAME, key, tempFile, objectMetadata);
        observer.setTransferListener(new MockTransferListener());
```

**3. isRequesterPays**

```java
objectMetadata.setUserMetadata(Collections.singletonMap(Headers.REQUESTER_PAYS_HEADER, "requester"));
```

Please let us know if this works for you and any feedback you have.

**Comment by softwarejoint** [comment]
Much thanks. Just 1 question, the below call, is this object expiry or http cache expiry

setHttpExpiresDate

**Comment by softwarejoint** [comment]
Much appreciated it works well for me. However some points as this can hit other users of library.

Could you document the change in the code. It still says that it will prefix x-amz-meta- to the custom user tag. But the condition is not so.

Also while uploading directly the `populateRequestMetadata` process same user metadata differently.

```
AmazonS3Client s3client;

s3client.putobject(putobjectrequest)

populateRequestMetadata()
```

**Comment by kvasukib** [comment]
Thank you @softwarejoint for the feedback. We will update the Javadoc accordingly in the upcoming release. 

I understand your concern about `populateRequestMetadata()`. We are working on to fix this in the upcoming release. There are two places you can attach user metadata: the put object request and the object metadata. 

The populateRequestMetadata() treats the user metadata attached in the object metadata as user-specified metadata and adds headers correspondingly. (https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L4151)
