### ISSUE TITLE
Change CryptoRuntime.java to stop using "BC"(BouncyCastle) explicitly.

### ISSUE THREAD

**Issue by NikolayAtSony** [aws/aws-sdk-android#470]
* What service are you using?

AWS S3 (with Client-side encryption)

* In what version of SDK are you facing the problem?

Latest

* Is the issue limited to Simulators / Actual Devices?

Both

* Can your problem be resolved if you bump to a higher version of SDK?

No

* Is this problem related to specific Android/OS version?

Yes, latest code available on master branch on AOSP, as defined here: https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Any attempt to use S3 with client-side encryption will trigger this issue. The problem is because CryptoRuntime.java in AWS Android SDK (https://github.com/aws/aws-sdk-android/blob/8d91ac8014c3b2643fd92560f890c58d11fbe069/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/crypto/CryptoRuntime.java#L31) specifically requesting "BC" from Security.getProvider() and due to the change introduced on master branch on AOSP its producing warning for now (or may produce error later); refer to the example below (algorithm of course could be different depending which one is used but the idea should be clear):
 
******** DEPRECATED FUNCTIONALITY ********
* The implementation of the Cipher.AES/GCM/NoPadding algorithm from
* the BC provider is deprecated in this version of Android.
* It will be removed in a future version of Android and your
* application will no longer be able to request it.  Please see
* https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html
* for more details.
 
Relevant Google commit: https://android-review.googlesource.com/c/platform/libcore/+/510257/3/ojluni/src/main/java/sun/security/jca/Providers.java#536

* Please include a stacktrace if applicable.

No stacktrace, just a message in logcat system log so far.

**Comment by kvasukib** [comment]
Thank you @NikolayAtSony for bringing this to our attention. I am looking into it. Will post the next steps here.

**Comment by NikolayAtSony** [comment]
I disagree, this is still a valid issue which needs to be addressed. @kvasukib, any updates on when we can expect the fix?

**Comment by kvasukib** [comment]
@NikolayAtSony Sorry for the delayed response. We have deprecated the client-side encryption provided through the aws-android-sdk-s3 library. Instead we have two recommended approaches:
https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#transfer-encryption

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.

**Comment by tomekit** [comment]
> Instead we have two recommended approaches:
> https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#transfer-encryption

This 2018 link no longer works. What are the recommended approaches for client-side encryption?
