### ISSUE TITLE
Mobile Hub Logout in Offline mode and user need to sign back in when connection is established

### ISSUE THREAD

**Issue by vision669** [aws/aws-sdk-android#478]
I just downloaded android Mobile Hub app. I added user sign as the backend. Everything works fine when there is good connection, but when the phone is in offline mode ( no internet connection) the user is automatically sign out and the cache dataset save on the phone is wipe. User needs to login again when connection is established. Most app i know work flawlessly with or without connection with minimum or no user interference. is there a way to keep user sign in during offline mode and automatically sync account when connection is reestablished

**Comment by minbi** [comment]
Hi @vision669 ,

The demo app does not cover all use-cases. This behavior can be modified to suit your needs.
