### ISSUE TITLE
IOException: WebSocket Response header: Incorrect upgrade

### ISSUE THREAD

**Issue by beersheba** [aws/aws-sdk-android#479]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
IoT

* In what version of SDK are you facing the problem?
2.6.18

* Is the issue limited to Simulators / Actual Devices?
No

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

I use Eclipse Paho Android Service 1.1.0. When i try to use any Paho version above 1.1.0 (e.g. 1.2.0), AWSIotMqttManager is going to Reconnect after connect attempt throwing the exception:
`MqttException (0) - java.io.IOException: WebSocket Response header: Incorrect upgrade.`

Any advice how it can be resolved?

**Comment by cbommas** [comment]
Hello @beersheba 
Sorry to hear that you are running into issues. I tried to reproduce this behavior by using the AndroidPubSub sample (https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub) with multiple versions of paho, (1.1.0, 1.1.1, and 1.2.0) and was able to connect and have pub/sub working.

Can you share more details about your setup and, if possible, a code-snippet to help debug this further?

**Comment by beersheba** [comment]
In my setup i use both aws sdk and paho mqtt.
As i see in aws iot internals, it's also using paho mqtt 1.1.0 internally.

```
    implementation 'com.amazonaws:aws-android-sdk-core:2.6.15'
    implementation 'com.amazonaws:aws-android-sdk-iot:2.6.15'
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
```

When i increase paho version to 1.2.0 in app gradle, AWSIotMqttManager starting to throw the exception.

**Comment by kvasukib** [comment]
@beersheba Do you face this error when you use 1.1.0? Or does this error occur the moment you upgrade your app from 1.1.0 to 1.2.0?

**Comment by beersheba** [comment]
@kvasukib no, when i use 1.1.0 it works fine. Occurs on update

**Comment by kvasukib** [comment]
It appears to be an issue with 1.2.0 version of the paho client. I am testing to see the compatibility of IoT SDK with 1.2.0 version of the paho client. Will post an update here shortly.

**Comment by cidoni** [comment]
Is there a resolution identified for this issue?
I also noticed this while using 1.2.0, and it worked when I switched down to 1.1.0.
Thanks.

**Comment by desokroshan** [comment]
@cidoni 
Unfortunately, We do not have a resolution yet other than using paho version 1.1.0.
This is an ongoing paho issue and is being tracked [here](https://github.com/eclipse/paho.mqtt.java/issues/345)

**Comment by WooYu** [comment]
The following iot version appears
   def aws_version = "2.42.0"   
implementation("com.amazonaws:aws-android-sdk-iot:$aws_version")
    implementation("com.amazonaws:aws-android-sdk-mobile-client:$aws_version")

**Comment by GautamVolansys** [comment]
Hello @desokroshan,

We are still facing this issue with Google Pixel 3 device with the latest version 2.44.0. Any resolution for this issue?

Thanks & Regards,
Gautam Gelani
