### ISSUE TITLE
Authentication resets after restart when using developer auth provider

### ISSUE THREAD

**Issue by imilka** [aws/aws-sdk-android#48]
We're currently trying to integrate Cognito using developer authenticated identities using the following example:
https://mobile.awsblog.com/post/Tx3E3NJURV1LNV1/Integrating-Amazon-Cognito-using-developer-authenticated-identities-An-end-to-en

We can successfully receive data from Cognito after authentication, but the problem is that when we restart the application, SDK resets the identity to null for some reason and we need to perform authentication process once again (add an entry to logins hashmap, request token, etc).

It seems like sdk has correct sessionCredentials during the same launch when authentication happened, but loses them on restart. saveCredentials method in CognitoCachingCredentialsProvider is not being called, so I assume credentials are not cached or something like that. I don't know if sessionCredentials are to be obtained from SharedPreferences at all times so I'm not sure this is what causes the problem.

We have tried to use developer authenticated identities in CognitoSyncDemo project from aws-sdk-android-samples and it behaves the same way when implemented there.

Thanks!

**Comment by MarkMerc123** [comment]
Hi, 

I am looking into the issue you described. In the meantime can you send me 
(1) which SDK and version you are using?
(2) Possibly some logcat logs from the second start up?

-Mark

**Comment by imilka** [comment]
Hi Mark, thanks for prompt reply.

I'm using version 2.2.2.

Here are some logs from the first start up:
```
06-25 01:11:37.833    2614-2614/com.amazonaws.cognito.sync.demo D/CognitoCachingCredentialsProvider﹕ Clearing credentials from SharedPreferences
06-25 01:11:37.837    2614-3197/com.amazonaws.cognito.sync.demo D/CognitoCachingCredentialsProvider﹕ Clearing credentials from SharedPreferences
06-25 01:11:38.749    2614-3197/com.amazonaws.cognito.sync.demo I/CognitoSyncManager﹕ identity change detected
06-25 01:11:38.765    2614-3197/com.amazonaws.cognito.sync.demo D/CognitoCachingCredentialsProvider﹕ Identity id is changed
06-25 01:11:38.765    2614-3197/com.amazonaws.cognito.sync.demo D/CognitoCachingCredentialsProvider﹕ Saving identity id to SharedPreferences
```

And from the second start up:
```
06-25 01:15:41.569    6198-6255/com.amazonaws.cognito.sync.demo D/CognitoCachingCredentialsProvider﹕ Loading credentials from SharedPreferences
06-25 01:15:41.573    6198-6255/com.amazonaws.cognito.sync.demo D/CognitoCachingCredentialsProvider﹕ No valid credentials found in SharedPreferences
06-25 01:15:41.897    6198-6255/com.amazonaws.cognito.sync.demo D/CognitoCachingCredentialsProvider﹕ Identity id is changed
06-25 01:15:41.897    6198-6255/com.amazonaws.cognito.sync.demo D/CognitoCachingCredentialsProvider﹕ Saving identity id to SharedPreferences
```

Please let me know if you need some other logs.

**Comment by MarkMerc123** [comment]
Hello,

We have been able to replicate the issue you are experiencing, and are working on addressing the problem. I will update here as more information is available.

-Mark

**Comment by MarkMerc123** [comment]
Hello,

There was a bug that caused the credentials to not get cached correctly in certain cases with Developer Authenticated Identities. This bug will be fixed in an upcoming release of the Android SDK.

Thanks for pointing this out to us.

-Mark

**Comment by vsochinsky** [comment]
Hi, @MarkMerc123,

Thanks for taking this into account. Do you have any updates on the release date?

**Comment by MarkMerc123** [comment]
Hello @vsochinsky,

This change is out now.

-Mark

**Comment by bhupinder17** [comment]
Hello, 

I am facing the same issue. i am using following libs
    compile 'com.amazonaws:aws-android-sdk-core:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.2.+'
    compile 'com.amazonaws:aws-android-sdk-s3:2.2.+'

Regards

**Comment by oximer** [comment]
I'm also having the same issue.

**Comment by firasalmanna** [comment]
Hello, 
I am using sdk version `2.2.13`, and I am still receving the same problem!

it is loading from cahe, 
`D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences`
then clearing,
`D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences`
then loading from cache,
`D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences`
then no valid credentials found,
`D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences`
then it hit my api again to load them and save.
`V/AuthenticationProvider: Refreshing AuthToken`
`D/CognitoCachingCredentialsProvider: Saving credentials to SharedPreferences`

didn't you fix this problem?
