### ISSUE TITLE
Why HttpMethodName class not contains OPTIONS?

### ISSUE THREAD

**Issue by KateLeeCandy** [aws/aws-sdk-android#482]
The HTTP OPTIONS method is used to describe the communication options for the target resource.
Why HttpMethodName not contains OPTIONS?

**Comment by minbi** [comment]
Hi @KateLeeCandy ,

Can you clarify your use-case? Are you using API Gateway or AppSync and need that enum?

**Comment by KateLeeCandy** [comment]
We need to use AWS4Signer with com.amazonaws.DefaultRequest#setHttpMethod, and found HttpMethodName not contains OPTIONS...

**Comment by kvasukib** [comment]
Thank you @KateLeeCandy for the reply. What AWS service are you sending this request to?

**Comment by KateLeeCandy** [comment]
AWS Web Services https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/HttpMethodName.java

**Comment by KateLeeCandy** [comment]
Web Services has 'OPTIONS', Why android SDK not correspond it

**Comment by KateLeeCandy** [comment]
https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-core/src/main/java/com/amazonaws/http/HttpMethodName.java

**Comment by KateLeeCandy** [comment]
https://github.com/aws-amplify/aws-sdk-android/issues/644
