### ISSUE TITLE
IOT sdk loop Reconnecting

### ISSUE THREAD

**Issue by AIlll** [aws/aws-sdk-android#485]
* What service are you using?
aws-android-sdk-iot
* In what version of SDK are you facing the problem?
2.6.23
* Is the issue limited to Simulators / Actual Devices?

* Can your problem be resolved if you bump to a higher version of SDK?
no
* Is this problem related to specific Android/OS version?
android4.4.2

* Please include a stacktrace if applicable.
```
07-02 18:52:26.926 9038-9067/com.packagebutler. I/AWSIotMqttManager: metrics collection is enabled, username: ?SDK=Android&Version=2.6.23
    resetting reconnect attempt and retry time
07-02 18:52:31.936 9038-9182/com.packagebutler. I/AWSIotMqttManager: onSuccess: mqtt connection is successful.
07-02 18:52:31.946 9038-9182/com.packagebutler.  W/AWSIotMqttManager: connection is Lost
07-02 18:52:31.976 9038-9182/com.packagebutler.  I/AWSIotMqttManager: schedule Reconnect attempt 0 of 10 in 4 seconds.
07-02 18:52:35.976 9038-9184/com.packagebutler.  I/AWSIotMqttManager: attempting to reconnect to mqtt broker
07-02 18:52:40.626 9038-9233/com.packagebutler.  I/AWSIotMqttManager: Reconnect successful
    Auto-resubscribe is enabled. Resubscribing to previous topics.
07-02 18:52:40.636 9038-9233/com.packagebutler.  W/AWSIotMqttManager: connection is Lost
07-02 18:52:40.636 9038-9233/com.packagebutler.  I/AWSIotMqttManager: schedule Reconnect attempt 1 of 10 in 8 seconds.
07-02 18:52:48.646 9038-9235/com.packagebutler.  I/AWSIotMqttManager: attempting to reconnect to mqtt broker
07-02 18:52:50.056 9038-9241/com.packagebutler.  I/AWSIotMqttManager: Reconnect successful
```
When the connection is successful，connection is Lost and Reconnect immediately

**Comment by kvasukib** [comment]
Thank you @AIlll for reporting to us. Can you post a code snippet if possible?

**Comment by kvasukib** [comment]
@AIlll Thank you for the reply. 
1) Do you experience reconnect for every connect? Or does this happen only for certain connect calls?
2) Are there issues with network connectivity during the time you are trying to connect?
3) What type of network are you on?

**Comment by AIlll** [comment]
@kvasukib 
1. it doesn't happen repeatedly.
2.maybe for sometimes
3.wifi

**Comment by AIlll** [comment]
Is it related to the region? I am in China

**Comment by AIlll** [comment]
It seems that I have solved the problem , but I am not sure what the problem is.

**Comment by AIlll** [comment]
```
mAwsIotMqttManager.connect(clientKeyStore, new AWSIotMqttClientStatusCallback() {
                  @Override
                  public void onStatusChanged(AWSIotMqttClientStatus status, Throwable throwable) {
                       if (status == AWSIotMqttClientStatusCallback.AWSIotMqttClientStatus.Connected) {
                          throw new NullPointerException("When the status is connected,Exception will cause reconnect");
                        }
                   }
               });
```

**Comment by haggaishD** [comment]
I keep getting this problem - and I am not sure what was the resolution in this thread

**Comment by tylerjroach** [comment]
@haggaishD Given that 7 years have passed since the original report, can you create a new issue with details specific to your use case, with additional details such as:
* IoT library version used
* How you are authenticating IoT
* Version(s) of Android impacted, if not all.
* Any logs that could help us debug
