### ISSUE TITLE
AWS IoT Issues

### ISSUE THREAD

**Issue by Oxbowl** [aws/aws-sdk-android#490]
Hi, Thanks for viewing this. 
I will make a long story short. Basically, I connected the AWS IoT Core with my Raspberry Pi for the home automation system with Andriod App built by Android studio.
So far I will make everything successfully. But I wanted to add on something such as:
1. I want to create a button for - show the status of current devices. Example like I turned on my aircon in past 1 hours. And my wife on the way home can use another phone by clicking the button so that it will show I did turn on the Aircon.  So how can get this kind of feedback from AWS since the data will store in AWS.

**Comment by minbi** [comment]
Hi @Oxbowl ,

The github issues are for reporting issues and feature requests. For information like "How do I build X?" Please post a thread in [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=210). They will be better able to assist you. Thank you.
