### ISSUE TITLE
Delete, create then login error

### ISSUE THREAD

**Issue by andrey-kaiser** [aws/aws-sdk-android#491]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Cognito

Hello,
we are currently using a Cognito User Pool for authenticating our Application Users. All works fine, until I found "issue" with Deleting account. So, if user deletes account, then creates a new one with same email and then try to login he encounter error.

Here is the code:

```
CognitoManager.getPool().getUser(email).getSessionInBackground(authenticationHandler);

AuthenticationHandler authenticationHandler = new AuthenticationHandler() {
        @Override
        public void onSuccess(CognitoUserSession cognitoUserSession, CognitoDevice device) {
            LogUtils.log("login onSuccess");
            readProfile(email);
        }

        @Override
        public void onFailure(Exception e) {
            LogUtils.log("login onFailure: "+e);
        }

        @Override
        public void getAuthenticationDetails(AuthenticationContinuation authenticationContinuation, String username) {
            AuthenticationDetails authenticationDetails = new AuthenticationDetails(email, password, null);
            authenticationContinuation.setAuthenticationDetails(authenticationDetails);
            authenticationContinuation.continueTask();
        }

        @Override
        public void getMFACode(MultiFactorAuthenticationContinuation multiFactorAuthenticationContinuation) {}

        @Override
        public void authenticationChallenge(ChallengeContinuation continuation) {}
    };


private void readProfile(String email) {
        CognitoManager.getPool().getUser(email).getDetailsInBackground(new GetDetailsHandler() {
            @Override
            public void onSuccess(CognitoUserDetails cognitoUserDetails) {
                LogUtils.log("readProfile onSuccess");
            }

            @Override
            public void onFailure(Exception exception) {
                LogUtils.log("readProfile onFailure: "+exception.getMessage());
            }
        });
    }
```
And output:
```
login onSuccess
readProfile onFailure: User does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserNotFoundException; Request ID: 1ad1629f-7f93-11e8-8739-17803fb06cd7)
```
So, getSessionInBackground() works ok but getDetailsInBackground() produces error. It doesn't work until user uninstalls application, then it works. I suppose, I should do some sort of refresh of User Pool details for my user programmatically and I will appreciate your help with this.

**Comment by minbi** [comment]
Hi @andrey-kaiser ,

Thank you for reporting the issue. We will investigate and report back here.

**Comment by ashwindevendran** [comment]
Hi @andrey-kaiser 

Thanks for providing the request ID (obtained from here: "readProfile onFailure: User does not exist. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: UserNotFoundException; Request ID: 1ad1629f-7f93-11e8-8739-17803fb06cd7)"). 

In order to better investigate can you provide a timestamp (UTC is fine) of when that request was made as well as the region for your cognito user pool? 

If you prefer, you can private message me the information as well.

**Comment by andrey-kaiser** [comment]
@minbi , hello!
Thats it, simply calling signOut() before deleting account fixes my issue.
Thank you for assistance!
