### ISSUE TITLE
Android application already running on  EC2 now Explain how to  add SSO with FB & Gmail(IDB)

### ISSUE THREAD

**Issue by sapra5379** [aws/aws-sdk-android#493]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
EC2 hosted application

* Is this problem related to specific Android/OS version?
Android

Please explain to me it would be really appreciated as i have set the pool with my requirements! 

where i need to change as i dont have android developer with me but if you guys can guide me then we can do!

**Comment by cbommas** [comment]
@sapra5379 
The following link https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html contains the details on how to setup user signin and federation using AWS.
