### ISSUE TITLE
Feature Request - Add Identity Provider in Auth Builder

### ISSUE THREAD

**Issue by faizanmirza** [aws/aws-sdk-android#494]
In current **aws-android-sdk-cognitoauth** Auth builder, do not have identity provider parameter due to this i am unable to set identity provider directly. I have looked into Auth.java class but key was not found. Similarly parameter **identity provider** is available on [web](https://github.com/aws/amazon-cognito-auth-js) and [ios](https://github.com/awslabs/aws-sdk-ios-samples/tree/master/CognitoAuth-Sample) project. 
Any idea when a patch going to be released for android?

```    
Auth.Builder builder = new Auth.Builder();
builder.setAppClientId(cognitoClientId)

       .setAppCognitoWedDomain(cognitoAuthWebDomian)

       .setSignInRedirect(signInRedirectUri)

       .setSignOutRedirect(signOutRedirectUri);
```

**Comment by cbommas** [comment]
@faizanmirza 
I have added your request to the team's backlog. We will reply back on this thread once we get an update about whether the request has been priortized, ETA etc.

**Comment by minbi** [comment]
Closing in favor of #495 Thanks for the pull request.
