### ISSUE TITLE
Loading app offline causes the User to signout

### ISSUE THREAD

**Issue by danielvtan** [aws/aws-sdk-android#496]
* What service are you using?
AWS AppSync

* In what version of SDK are you facing the problem?
aws sdk android 2.6.24

* Is the issue limited to Simulators / Actual Devices?
no

* Can your problem be resolved if you bump to a higher version of SDK?
latest

* Is this problem related to specific Android/OS version?
no

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

followed the login tutorial here - https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html#tutorial-integrating-user-pools-console-android

1. Logged in successfully and Accessed data from AppSync.
2. Close the app. Turn off internet
3. Open the app
4. User signs out

Here are the logs after opening the app offline:

```
D/AWSMobileClient: Fetching the Cognito Identity.
D/IdentityManager: Creating the Cognito Caching Credentials Provider with a refreshing Cognito Identity Provider.
D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
D/AWSMobileClient: Using the SignInProviderConfig from `awsconfiguration.json`.
D/IdentityManager: Resume Session called.
D/IdentityManager: Looking for a previously signed-in session.
D/CognitoUserPoolsSignInProvider: initalizing Cognito User Pools
D/OpenGLRenderer: HWUI GL Pipeline
D/SignInManager: Providers: [{class com.amazonaws.mobile.auth.userpools.CognitoUserPoolsSignInProvider=com.amazonaws.mobile.auth.userpools.CognitoUserPoolsSignInProvider@73c43c4}]
I/CognitoUserPoolsSignInProvider: refreshUserSignInState: Signed in with Cognito.
D/SignInManager: Refreshing provider: Amazon Cognito Your User Pools
D/IdentityManager: Refreshing credentials with sign-in provider Amazon Cognito Your User Pools
D/IdentityManager: federate with provider: Populate loginsMap with token.
D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
D/CognitoCachingCredentialsProvider: Identity id is changed
D/CognitoCachingCredentialsProvider: Saving identity id to SharedPreferences
D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
D/IdentityManager: refresh credentials
D/AWSRefreshingCognitoIdentityProvider: Storing the Refresh token in the loginsMap.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/IdentityManager: SignInProviderResultAdapter.onCognitoError()
D/IdentityManager: Signing out...
E/IdentityManager: Federate with Cognito with Amazon Cognito Your User Pools Sign-in provider failed. Error: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.ap-southeast-1.amazonaws.com": No address associated with hostname
```

**Comment by kvasukib** [comment]
Thank you for reporting to us. Sorry for the inconvenience caused. When IdentityManager makes a network call to get the credentials based on the token presented, the network call fails and `onCognitoError` is called which currently invokes `signOut`. Source: https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-auth-core/src/main/java/com/amazonaws/mobile/auth/core/IdentityManager.java#L425. I am looking into it. Will update here once I have a fix.

**Comment by danielvtan** [comment]
Hi, i found the solution. iprevoiusly used IdentityManager for checking if the user is signed in and signing out. I removed it and just used cognito user poll for checking if signed in amd loging out.

**Comment by danielvtan** [comment]
Hi, i found the solution. iprevoiusly used IdentityManager for checking if the user is signed in and signing out. I removed it and just used cognito user poll for checking if signed in amd loging out.
