### ISSUE TITLE
AWS S3 upload issue

### ISSUE THREAD

**Issue by mpirogov** [aws/aws-sdk-android#499]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS S3
* In what version of SDK are you facing the problem?
2.6.24
* Is the issue limited to Simulators / Actual Devices?
Actual Device
* Can your problem be resolved if you bump to a higher version of SDK?
not yet.
But there are no update with S3.
* Is this problem related to specific Android/OS version?
Android8.0

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
I have attached firebase crash report screenshots.
* Please include a stacktrace if applicable.
![screenshot_071918_085636_am](https://user-images.githubusercontent.com/19306638/42946937-c801ce2a-8b31-11e8-93b2-3ba87fdd88d2.jpg)
![screenshot_071918_085813_am](https://user-images.githubusercontent.com/19306638/42946985-dfad4fcc-8b31-11e8-82fe-7eeccd8a3887.jpg)
![screenshot_071918_085845_am](https://user-images.githubusercontent.com/19306638/42947011-f317360e-8b31-11e8-8715-a458c144a793.jpg)

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Thank you @mpirogov for reporting to us. TransferService cannot be invoked from a background service in Android 8.0 due to the background service limitations imposed by Android 8.0. 

If you are invoking TransferUtility from a service context, please do the following in your AndroidManifest.xml file. The following example uses MainService from which TransferUtility is invoked.
```

<service
            android:name=".MainService"
            android:enabled="true"
            android:launchMode="singleTop"
            android:process=":main_service"
            android:stopWithTask="false" />
        <service
    android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
            android:enabled="true"
            android:process=":main_service" />
```

**Comment by mpirogov** [comment]
Thank you @kvasukib

**Comment by kvasukib** [comment]
@mpirogov Let me know if this works.  Closing for now. Please reopen if the issue persists.
