### ISSUE TITLE
IOT Publish error

### ISSUE THREAD

**Issue by AIlll** [aws/aws-sdk-android#506]
* What service are you using?
- **aws-android-sdk-iot**
* In what version of SDK are you facing the problem?
- **2.6.27**
* Is the issue limited to Simulators / Actual Devices?

* Can your problem be resolved if you bump to a higher version of SDK?
- **No**
* Is this problem related to specific Android/OS version?
- **Android4.4.2**
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

- **I post a message when the connection is successful (AWSIotMqttClientStatus.Connected),but an exception occurred,Client is disconnected or not yet connected.**

* Please include a stacktrace if applicable.
```java
com.amazonaws.AmazonClientException: Client is disconnected or not yet connected.
at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.publishData(AWSIotMqttManager.java:1182)
at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.publishData(AWSIotMqttManager.java:1119)
at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.publishString(AWSIotMqttManager.java:1079)
```

**Comment by AIlll** [comment]
Sometimes this happens, and reconnecting a few times may not happen.

**Comment by kvasukib** [comment]
Hi @AIlll, Do you have permissions to publish to that topic? I have noticed this error when you don't have sufficient permissions with the authentication you have configured in AWS to access the topic. Currently, the SDK doesn't surface this error well. 

Can you double check the topic name and the required policies to access the topic?

**Comment by AIlll** [comment]
@kvasukib We confirm permission to access this topic，and cannot receive messages when "Client is disconnected or not yet connected".
Connecting again after disconnecting may become normal,can pubulish messages and receive message at this time

**Comment by kvasukib** [comment]
@AIlll 

What version of Paho client are you using? 
Can you share a code snippet if possible? 
Are you using MQTT or MQTT over WebSockets?

**Comment by yogeshsingh01** [comment]
I am still facing this issue, Any help?
I/AWSIotMqttManager: metrics collection is enabled, username: ?SDK=Android&Version=2.13.2
    resetting reconnect attempt and retry time
D/com.example.myiotapp.MainActivity: Status = Connecting
D/com.example.myiotapp.MainActivity: topic = myTopic/1
E/com.example.myiotapp.MainActivity: Subscription error.
    com.amazonaws.AmazonClientException: Client error when subscribing.
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.subscribeToTopic(AWSIotMqttManager.java:1152)
        at com.example.myiotapp.MainActivity.subscribeClick(MainActivity.java:126)
        at com.example.myiotapp.MainActivity$4.onClick(MainActivity.java:213)
        at android.view.View.performClick(View.java:5204)

**Comment by Lenin-B** [comment]
I am also having the same issue of exception client is not connected yet when i try to push a data to my AWS iot core but my client is connected
![Android error](https://user-images.githubusercontent.com/63389314/78990134-82959b00-7aea-11ea-9a80-50a3fa733efe.PNG)

**Comment by biobeat-aws** [comment]
help?

**Comment by meashumishra** [comment]
Facing the same issue multiple times, please help
