### ISSUE TITLE
Amazon S3 SDK TransferObserver called before transfer is completed

### ISSUE THREAD

**Issue by softwarejoint** [aws/aws-sdk-android#507]
### To help us solve your problem better, please answer the following list of questions.

Amazon S3
S3  sdk version: 2.6.23

We are using "TransferUtility" to download files from Amazon S3.

```
TransferObserver observer = transferUtility.download(s3fileKey, localFile);

observer.setTransferListener(new TransferListener() {
            @Override
            public void onStateChanged(int id, TransferState state) {
                switch (state) {
                    case COMPLETED:
                        markTransferCompleted(observer);
                        break;
                    case FAILED:
                        markTransferFailed(observer);
                        break;
                    default:
                        break;
                }
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                if (bytesTotal > 0) {
                    float progress = bytesCurrent * 100 / bytesTotal;
                    Logger.debug(TAG, "progress: " + progress);
                }
            }

            @Override
            public void onError(int id, Exception ex) {
                Logger.debug(TAG, "onUploadError", ex);
            }
        });
```

Issue:

"Observers: onStateChanged: completed" gets called before file is saved completely. After "onStateChanged: completed" is called, we try to load the file in player, but it fails as file has not been saved yet.

This behaviour is random, that is for first 1-2 downloads it gets called after file has been saved, other times it gets called after save.

**Comment by kvasukib** [comment]
@softwarejoint Sorry for the inconvenience caused. In the [DownloadTask](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/DownloadTask.java#L107), we save the file using BufferedOutputStream and after the file write is complete, we update the state of the transfer to COMPLETED. 

What player do you use and what's the file extension?
Can you add a print statement in `onStateChanged` to print the length of the file before attempting to load the file in the player?

**Comment by softwarejoint** [comment]
There are lot of tasks, it will be few weeks, before we go into finding out how this occurs, for now we have put a delay of about a second and it seems to hold well. This issue can be closed
