### ISSUE TITLE
AWSBasicSessionCredentialsProvider (IOS) alternative in Android - Question

### ISSUE THREAD

**Issue by praveshkhatana** [aws/aws-sdk-android#510]
### No Credential Provider for BasicSession in Android.

I have user's session credentials and want to pass it to mqttManager but unable to find any suitable provider which support it. IOS version has  "**AWSBasicSessionCredentialsProvider**" which solves the purpose.

_STSSessionCredentialsProvider required long-lived credentials._

* What service are you using?
Auth service for IOT

* In what version of SDK are you facing the problem?
@2.6.+

* Is the issue limited to Simulators / Actual Devices?
Question

* Can your problem be resolved if you bump to a higher version of SDK?

* Is this problem related to specific Android/OS version?
Android
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

>  **IOS working Code**

```
credentialsProvider =  new AWSBasicSessionCredentialsProvider(this.credentials.accessKeyId,this.credentials.secretAccessKey,this.credentials.sessionToken);
let iotEndPoint = new AWSEndpoint(this.IOT_ENDPOINT);
        
        // // Configuration for AWSIoT control plane APIs
        let iotConfiguration = new AWSServiceConfiguration(this.AWSRegion, credentialsProvider);
        
        // Configuration for AWSIoT data plane APIs
        let iotDataConfiguration = new AWSServiceConfiguration(this.AWSRegion,
                                                           iotEndPoint,
                                                           credentialsProvider);

        AWSServiceManager.defaultServiceManager().defaultServiceConfiguration = iotConfiguration;
        
        this.iotManager = AWSIoTManager.defaultIoTManager();
        this.iot = AWSIoT.defaultIoT();
        
        AWSIoTDataManager.registerIoTDataManagerWithConfigurationForKey(iotDataConfiguration, this.ASWIoTDataManager);

        this.iotDataManager = AWSIoTDataManager.IoTDataManagerForKey(this.ASWIoTDataManager);
 this.iotDataManager.connectUsingWebSocketWithClientIdCleanSessionStatusCallback( this.clientId, true, (status)=>{
                                
                                this.callback &&
                                    this.callback.onMqttEventCallback &&
                                    this.callback.onMqttEventCallback(status);
                            });
```

> **Android NON WORKING CODE :(.**
```
let cred = new BasicSessionCredentials(accessKeyId,secretAccessKey,sessionToken);
let credentialsProvider = new STSSessionCredentialsProvider(cred);
mqttManager = new AWSIotMqttManager(clientId, CUSTOMER_SPECIFIC_ENDPOINT);

        mqttManager.setKeepAlive(10);

mqttManager.connect(credentialsProvider, new AWSIotMqttClientStatusCallback() {
                    @Override
                    public void onStatusChanged(final AWSIotMqttClientStatus status,
                            final Throwable throwable) {
                        Log.d(LOG_TAG, "Status = " + String.valueOf(status));
                    }
                });
```

**Comment by sunchunqiang** [comment]
Hello @praveshkhatana 

In a java project, you can pass credential received from 'BasicSessionCredentials' to 'AWSStaticCredentialsProvider(credential)', like code below. However, the class 'AWSStaticCredentialsProvider' is  not available in android SDK. We are researching when we can add this feature to android SDK.

BasicSessionCredentials sessionCredentials = new BasicSessionCredentials(
   session_creds.getAccessKeyId(),
   session_creds.getSecretAccessKey(),
   session_creds.getSessionToken());

AmazonS3 s3 = AmazonS3ClientBuilder.standard()
                        .withCredentials(new AWSStaticCredentialsProvider(sessionCredentials))
                        .build();

**Comment by praveshkhatana** [comment]
@sunchunqiang Thanks for reply, Yes this is what i did and it's working fine now.

**Comment by kiranalpha** [comment]
@praveshkhatana  and @sunchunqiang  can you provide full code for Android  AWS IOT Web socket, i was try your code but it show only Reconnecting message.
