### ISSUE TITLE
S3 Bucket Acceleration : Android example

### ISSUE THREAD

**Issue by AdityaS-Cybage** [aws/aws-sdk-android#515]
Hello,

I'm using **AWS SDK** for android for uploading and downloading the video files in my app.

version is : **com.amazonaws:aws-android-sdk-s3:2.6**

I want the file transfer to be accelerated using your bucket acceleration process, I've enabled the acceleration from the dashboard/console settings for the bucket. But I'm unable to enable to find any code snippet/example for the changes I've to do from the code side to make the uploads faster.

For **IOS**, in your documentation there is proper example for enabling it, but when i select **java/kotlin** tab, it shows me multithread upload APIs and not the acceleration APIs.

On different forums and API doc, I found some APIs like **BucketAccelerateConfiguration**, **S3ClientOptions**.builder() etc. But there is no way to find out how it has to be used?

Please help me regarding this, with a code sample in **Kotlin**.

Thanks in advance.

**Comment by kvasukib** [comment]
@AdityaS-Cybage 

```java
AmazonS3Client sS3Client = new AmazonS3Client(new CognitoCachingCredentialsProvider(getApplicationContext(), "pool-id", "pool-region"));
sS3Client.setRegion(Region.getRegion(Regions.fromName("us-east-1")));
sS3Client.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());

TransferUtility sTransferUtility = TransferUtility.builder()
                    .context(getApplicationContext())
                    .s3Client(sS3Client)
                    .defaultBucket("bucket")
                    .build();
```

Reference: https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/S3ClientOptions.java#L114

**Comment by AdityaS-Cybage** [comment]
Thanks @kvasukib, worked for me!

Actually, i tried this one earlier but i was putting my **sub-directory** name with the bucket name itself, instead of putting it in **Key** along with the file name, my bad.

hey, is there any way to print/intercept the aws upload/download call details to get the actual endpoint url? so that this type of mistakes can be avoided?

thanks again.


[**wrt**: "For IOS, in your documentation there is proper example for enabling it, but when i select java/kotlin tab, it shows me multithread upload APIs and not the acceleration APIs."
Can you add the above code snippet in the documentation, it's missing there]

**Comment by kvasukib** [comment]
@AdityaS-Cybage Thank you for the feedback. 

1) You can attach a RequestHandler (Interceptor) before the request is being executed by the Client Runtime.

```java
AmazonS3Client amazonS3Client = new AmazonS3Client(new CognitoCachingCredentialsProvider(this, "pool-Id", "region"));
        amazonS3Client.addRequestHandler(new RequestHandler2() {
            @Override
            public void beforeRequest(Request<?> request) {
               // get the information required from the request
            }

            @Override
            public void afterResponse(Request<?> request, Response<?> response) {

            }

            @Override
            public void afterError(Request<?> request, Response<?> response, Exception e) {

            }
        });
```

2) We will work on updating the documentation for Android.

Thank you!
