### ISSUE TITLE
no getSessionInBackground with username/password like in the iOS SDK ? 

### ISSUE THREAD

**Issue by nashfive** [aws/aws-sdk-android#516]
I've noticed that there is a method in the iOS SDK to do an explicit getSession without using any cached tokens/refresh tokens (source: [AWSCognitoIdentityUser.m:230](https://github.com/aws/aws-sdk-ios/blob/master/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L230)). I am using it to perform a straight sign in and I can't find a similar way to do it on Android. 
Is there a reason why that method hasn't been implemented ? 
How can I implement it myself ?

I was thinking of implementing a custom `getSessionInBackground` method that would directly set the authentication details in the `getAuthenticationDetails` callback... 
Is it something not too ugly ? ;)

**Comment by kvasukib** [comment]
@nashfive Thank you for reporting to us. Sorry for the inconsistency in the API across Android and iOS. This was a design choice made based on the platform. The Android SDK for Cognito UserPools uses a callback and continuation pattern to accept user input.
