### ISSUE TITLE
S3TransferUtility doesn`t start uploading.

### ISSUE THREAD

**Issue by yebonkim** [aws/aws-sdk-android#517]
My sdk version is 26 and i`m using actual device

I added service in the right place of manifest.xml.
And I gave permission too.

When starting uploading, onProgressChanged is executed once.
~~~
D/YourActivity: ID:4 bytesCurrent: 0 bytesTotal: 29326 0%
~~~

but nothing happened. There is no error message.

My code is like this.
~~~
transferUtility =
                TransferUtility.builder()
                        .context(getApplicationContext())
                        .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                        .s3Client(new AmazonS3Client(AWSMobileClient.getInstance().getCredentialsProvider()))
                        .build();

        final TransferObserver uploadObserver =
                transferUtility.upload(Constants.BUCKET_NAME,
                        filename,
                        new File(imgUrl));


        // Attach a listener to the observer to get state update and progress notifications
        uploadObserver.setTransferListener(new TransferListener() {

            @Override
            public void onStateChanged(int id, TransferState state) {
                if (TransferState.COMPLETED == state) {
                    // Handle a completed upload.
                }
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                int percentDone = (int)percentDonef;

                Log.d("YourActivity", "ID:" + id + " bytesCurrent: " + bytesCurrent
                        + " bytesTotal: " + bytesTotal + " " + percentDone + "%");
            }

            @Override
            public void onError(int id, Exception ex) {
                // Handle errors
            }

        });
~~~

is there something i missed?

**Comment by kvasukib** [comment]
@yebonkim Sorry for the inconvenience caused. Are you invoking this code from an activity or from a service?

Also, can you try the following:

**Workaround-1:**

```xml
<service
            android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
            android:process=":sync"/>
```

**Workaround-2:**

```xml
<service
            android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
            android:process=":main"/>
```

Can you try the above two workarounds and see the behavior?

**Comment by yebonkim** [comment]
Thank you for your prompt reply!

But both workarounds are not worked. They didn`t reach into onProgressChanged.

**Comment by kvasukib** [comment]
@yebonkim 
Can you see any exception in the Logcat window? 
Can you see the logs from the point where the transfer is submitted to TransferUtility? 
Also, what are the number of available processors on your mobile device? You can get this by executing `Runtime.getRuntime().getAvailableProcessors()?`

**Comment by yebonkim** [comment]
both workarounds didn`t write any log.

only these logs were written.

~~~
D/ViewRootImpl@d660952[JoinActivity]: ViewPostIme pointer 0 D/ViewRootImpl@d660952[JoinActivity]: ViewPostIme pointer 1
~~~

and my phone`s the number of available processor is 8

my dependencies are

~~~
implementation 'com.amazonaws:aws-android-sdk-s3:2.6.+'
    implementation 'com.amazonaws:aws-android-sdk-cognito:2.6.+'
    implementation('com.amazonaws:aws-android-sdk-mobile-client:2.6.+@aar') {
        transitive = true;
    }
~~~

**Comment by kvasukib** [comment]
What version of Android platform is your device running against?

**Comment by yebonkim** [comment]
my device`s version is 8.0.0

**Comment by kvasukib** [comment]
@yebonkim Is your app in the foreground or background when you are initiating the transfer?

**Comment by yebonkim** [comment]
It`s foreground...

**Comment by kvasukib** [comment]
@yebonkim I am looking into the issue and working on a fix. I will update this thread once the fix is released. Thank you for the patience.

**Comment by kvasukib** [comment]
@yebonkim 

Apologies for the delay.

This problem of uploads waiting to start should go away with 2.7.0 version of the SDK. 

We have made some changes to TransferUtility in 2.7.0 version of the SDK. The summary of the changes can be found in [CHANGELOG](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md) or [Documentation](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#long-running-transfers).

Summary:

Starting version 2.7.0 of the SDK, TransferService logic has been refactored. This service now will be responsible only for monitoring network connectivity changes. When the network goes offline, the transfers that are in progress will be paused. When the network comes back online, the transfers that are paused will be resumed. If you expect your app to perform long-running transfers in the background, you need to initiate the transfers from a background service of your choice.

The TransferService will not be started or stopped by TransferUtility anymore. You have to start TransferService manually from your application. A recommended way is to start the service upon Application startup. One way you can do this is to include the following line in the onCreate method of your app's Application class.

```java
    getApplicationContext().startService(new Intent(getApplicationContext(), TransferService.class));
```

**Comment by GerardoRobledo** [comment]
If you start the service as follows you get an RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

`  if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            startForegroundService(Intent(this, TransferService::class.java))
        } else {
            startService(Intent(this, TransferService::class.java))
        }`

**Comment by kvasukib** [comment]
@GerardoRobledo Sorry for the delayed response. Just to re-iterate. TransferService starting from 2.7.0 will only be responsible for listening to network connectivity changes and auto resumes transfers that are paused when network is offline. 

If you are looking to have this feature of pausing transfers when network is offline and auto-resume transfers when network is online (both when the app is in foreground/background), you can use TransferService until devices running API 1 through 25. For Oreo and above you can implement this feature by looking into TransferService in a service of your own choice. Some examples include JobManager and JobScheduler. 

If you are looking to have transfers that are long-running in the background, you can wrap the calls to `transferUtility.upload` and `transferUtility.download` in a service of your choice.

Please let me know if you have further questions.
