### ISSUE TITLE
Method typo 'setMaxAutoReconnectAttepts'

### ISSUE THREAD

**Issue by spmvanmierlo** [aws/aws-sdk-android#518]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
aws-android-sdk-iot
* In what version of SDK are you facing the problem?
2.6.28
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No, highest at the moment.
* Is this problem related to specific Android/OS version?
No
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Method 'setMaxAutoReconnectAttepts' is declared in the file: 'aws-sdk-android/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java'

Should be named 'setMaxAutoReconnectAttempts'.

* Please include a stacktrace if applicable.
-
If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by spmvanmierlo** [comment]
#519 created a PR.

**Comment by kvasukib** [comment]
The PR is merged. Closing the issue.
