### ISSUE TITLE
Failing to upload image after ~30-40 minutes

### ISSUE THREAD

**Issue by emhagman** [aws/aws-sdk-android#52]
We can authenticate with Cognito using Digits and upload images; however, after about 30 to 40 minutes of just having the app sit there, we get an error saying we can't access it when trying to upload a new image. Seen below:

```
com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Access to Identity 'us-east-1:NotTheActualPoolId' is forbidden. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 96d61bb5-3553-11e5-ae36-8be8ef351d5f)
```

The second time we try to upload the image, immediately after the first error, we get:
```
Unauthenticated access is not supported for this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: a9b498c2-3557-11e5-be30-5b1603ee422d)
```

It looks like the first error clears our credentials and the second makes sense since we don't have credentials anymore and we have unauthenticated access turned off in Cognito.

Any ideas?

**Comment by jbailey2010** [comment]
Two notes:
1) Are you managing the life cycle of that Digits token? 
It's possible that the token is expiring in that time and that's what's causing you the issue. If you are not, you will need to be, as Cognito does not manage the refresh of the tokens for you.
2) What SDK and version are you using? The second message sounds similar to a bug that was fixed in a recent release of the Android SDK.

**Comment by emhagman** [comment]
```
compile('com.amazonaws:aws-android-sdk-core:2.+') {
    exclude group: 'commons-logging', module: 'commons-logging'
}
compile('com.amazonaws:aws-android-sdk-cognito:2.+') {
   exclude group: 'commons-logging', module: 'commons-logging'
}
compile('com.amazonaws:aws-android-sdk-s3:2.+') {
   exclude group: 'commons-logging', module: 'commons-logging'
}
```

It is our understanding that the Digits token does not expire unless we explicitly tell Digits we want to logout which is not the case here. We are using the latest SDK as far as I can tell. We have cleaned the build to make sure we have the latest and are stilling getting this issue.

Thanks for the quick response!

**Comment by jbailey2010** [comment]
Sorry about the issues. Would you mind sending me your account id and pool being used so I can further investigate? My email is jeffbail at amazon.com. 

Also, if you could give me some context into what the code is doing and some excerpts of it doing it, that would be very helpful in debugging. Are you using multiple credentials providers, how is it communicating with S3, the interactions with Digits...etc.

**Comment by emhagman** [comment]
Thanks! I will e-mail you the details
