### ISSUE TITLE
Where to find documentation on how to use Cognito User Pools and Facebook with federated identities

### ISSUE THREAD

**Issue by angli13** [aws/aws-sdk-android#520]
Cognito User Pools, Cognito Federated Identities
ADK 2.6
 
I've been struggling for days to find information about this, I just can't figure it out. I have created a project on mobile hub, which created an identity pool, a user pool and facebook integration with de identity pool. The sample app works great, but I need to use a custom UI (not just changing colors), so that is when the things get ver confusing very quickly. I have found information on how to implement User Pools, how to get Cognito Credentials, how to integrate Facebook, but there is no documentation on how to implement everything together.

What I want is to use the same logic used in Mobile's Hub Sample App with my custom UI. Maybe what is driving me crazy are the names of the classes, they are SO similar it is very difficult to wrap my head around it. I think it would be very useful if someone could answer what are this classes used for and what is the difference.

**SingInManager
IdentityManager**
CognitoCachingCredentialsProvider
CognitoUserPoolsSignInProvider
FacebookSignInProvider
 
I'm guessing I can use CognitoUserPoolsSignInProvider or FacebookSignInProvider with SingInManager and IdentityManager to get CognitoCachingCredentialsProvider. This is what seems logic for me, but I cant find a way tu put it all together.

Any help would be incredibly useful, thanks!

**Comment by kvasukib** [comment]
@angli13 Hi Fernando! Sorry for the delayed response. Here is the summary of the classes. But can you explain the use-case that you are trying to solve?

SingInManager: Orchestrates a sign-in flow irrespective of the SignInProvider (UserPools, Facebook and Google, etc)

IdentityManager: Creates a CognitoCachingCredentialsProvider, handles refresh, federates a token from any SignInProvider with the CognitoCachingCredentialsProvider, resume a previosuly signed-in session.

CognitoCachingCredentialsProvider: Helps you retrieve a Cognito Identity ID and AWSCredentials; supports caching of credentials on the device.

CognitoUserPoolsSignInProvider: A high-level wrapper over the Cognito UserPools SDK (aws-android-sdk-cognitoidentityprovider) that invokes the different methods in the authentication flow and is tied to the SignIn UI.

FacebookSignInProvider: Like CognitoUserPoolsSignInProvider, but for Facebook Android SDK. A high-level wrapper over the Facebook (facebook-android-sdk) that invokes the different methods in the authentication flow.

Sorry for the confusion in the classes and their interactions. If you can explain your use-case, we can work on the code snippet that you might need in your app.

**Comment by minbi** [comment]
Please feel free to open another issue if you are still having trouble. Closed issues are not actively monitored. Thank you.
