### ISSUE TITLE
android GCM on Oreo devices crash issue 

### ISSUE THREAD

**Issue by Anonymous123456789123** [aws/aws-sdk-android#525]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
GCM services since we will aim to use fire-base but need a quick solution for now.
* In what version of SDK are you facing the problem?
Sdk Version 26
* Is the issue limited to Simulators / Actual Devices?
the issue is limited to Oreo devices
* Can your problem be resolved if you bump to a higher version of SDK?
it was working on low SDK version but due to store restriction they aim to make the SDK 26 or higher in order to upload an apk to store
* Is this problem related to specific Android/OS version?
the issue related to android 8.0 and higher
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

java.lang.RuntimeException: 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3397)
  at android.app.ActivityThread.-wrap18 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1780)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6938)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: 
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1538)
  at android.app.ContextImpl.startService (ContextImpl.java:1484)
  at android.content.ContextWrapper.startService (ContextWrapper.java:663)
  at android.content.ContextWrapper.startService (ContextWrapper.java:663)
  at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService (SourceFile:89)
  at com.google.android.gms.gcm.GcmReceiver.zzf (Unknown Source:22)
  at com.google.android.gms.gcm.GcmReceiver.zze (Unknown Source)
  at com.google.android.gms.gcm.GcmReceiver.onReceive (Unknown Source:98)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:3390)

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/). 

Please i need a fix permanently till i switch to FCM 

Regards

**Comment by rohandubal** [comment]
Hello,

Could you please specify:

> What AWS Service are you using?

> What is the SDK version which you are using?

> Can you show the code snippet of how you are using the SDK in your application?

Thanks,
Rohan

**Comment by Anonymous123456789123** [comment]
Hello,

please find the below as requested

What AWS Service are you using?
Google cloud messaging 
 compile "com.google.android.gms:play-services-gcm:15.0.1"

What is the SDK version which you are using?
 compileSdkVersion 26
 buildToolsVersion '26.0.2'
 targetSdkVersion 23

Can you show the code snippet of how you are using the SDK in your application?

public class MyInstanceIDListenerService extends InstanceIDListenerService {
    private static final String TAG = "MyInstanceIDLS";
    @Override
    public void onTokenRefresh() {
         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            appContext.startForegroundService(new Intent(this, RegistrationIntentService.class));
        } else {
            appContext.startService(new Intent(this, RegistrationIntentService.class));
        }
    }


public class MyGcmListenerService extends GcmListenerService {
   public void onMessageReceived(String from, Bundle data) {
        String message = data.getString("Message");
        String title = data.getString("Title");

NotificationManager notificationManager =
                (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
        NotificationChannel channel = new NotificationChannel("default",
                "Yabadoo Channel Name",
                NotificationManager.IMPORTANCE_DEFAULT);
        channel.setDescription("Yabadoo Channel description");
        notificationManager.createNotificationChannel(channel);

NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this, "default")
                    .setSmallIcon(icon)
                    .setContentTitle(title)
                    .setContentText(message)
                    .setAutoCancel(true)
                    .setSound(defaultSoundUri)
                    .setColor(color)
                    .setContentIntent(pendingIntent) ;
            Notification notification = notificationBuilder.build();

        NotificationManager notificationManager = (NotificationManager) 
 getSystemService(Context.NOTIFICATION_SERVICE);

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                startForeground(id, notification);
                notificationManager.notify(id, notification);
            }
            else
            {
                notificationManager.notify(id, notification);
            }
}



always when app is in background the app crashes while if app is foreground the app is working correctly. i just want to recive the notification without crashing if app is in background 

Thanks,

**Comment by rohandubal** [comment]
Hello,

This github repo is for AWS SDKs and not the general GCM SDKs. Closing it as it is not relevant here.

**Comment by Anonymous123456789123** [comment]
Hi

How did you know its is aws and what do u mean by aws since im using the same ass google website and it is gcm


Regards
Sent from my iPhone

On Sep 7, 2018, at 20:37, rohandubal <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

This github repo is for AWS SDKs and not the general GCM SDKs. Closing it as it is not relevant here.
