### ISSUE TITLE
Custom sign-in with cognito

### ISSUE THREAD

**Issue by achatina** [aws/aws-sdk-android#529]
Hello! 
I have a stack and can't find solution. Back-end, after custom login, returns me username, refreshToken, idToken and accessToken. But how can i start a cognito session with this data? Just calling `getUser(username).getSessionInBackground(authenticationHandler);` not enough (getting UserNotFoundException). what can i do? Or cognito sdk has no opportunity to do this?
Using this parts of sdk:
```
    implementation 'com.amazonaws:aws-android-sdk-s3:2.+'
    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.4.3'
```

**Comment by JeetSA** [comment]
Hello @achatina ,
Did you find the solution for this as I am trying to implement like same thing.
