### ISSUE TITLE
SSLException during upload file in the bucket in aws-sdk 2.2.4

### ISSUE THREAD

**Issue by rafalzawadzki** [aws/aws-sdk-android#53]
SO thread: http://stackoverflow.com/questions/30565422/sslexception-due-uploading-item-for-amazon-service gave me hope, but unfortunately I have the same error.

Tried TransferManager and TransferUtility
Tried 2.1, 2.2.2, 2.2.4
Tried upload on Wifi, mobile transfer, Wifi + mobile transfer
Bucket: EU_WEST_1
Device: 5.1, API 22

On every one of them I have the same in log:
```
Unable to execute HTTP request: Write error: ssl=0x9dd68000: I/O error during system call, Connection reset by peer
    javax.net.ssl.SSLException: Write error: ssl=0x9dd68000: I/O error during system call, Connection reset by peer
            at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:765)
            at com.android.okio.Okio$1.write(Okio.java:70)
            at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
            at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291)
            at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
            at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
...
```

I am just tired of juggling versions and classes, please give me a hint how to use S3 upload.

**Comment by wdane** [comment]
I'm unfortunately unable to reproduce your issue.  Are you explicitly setting the region on the S3 Client?  This is required when your bucket is not in the default standard region.  If you are specifying the region could you answer a few questions it might help narrow down the issue.

A.  Are you behind any sort of firewall or similar network block
B.  Does this problem only occur when contact Frankfurt?  Does it work for other regions?
C.  If you have access to, have you tried a different device?
D. Do you get this error if you switch to the Apache Http client?
-To do this when creating the S3 client used in the Transfer Utility, pass a 3rd argument as below
ClientConfiguration conf = new ClientConfiguration();
AmazonS3Client s3 = new AmazonS3Client(CREDENTIALS, conf, new ApacheHttpClient(conf));

I'm sorry this is still giving you trouble, and hope to get you up and running ASAP.

**Comment by rafalzawadzki** [comment]
Thank you for suggestions, here are my answers/results:

A. Does not matter, neither do wifi or mobile carrier data transfer work
B. I will try to test it today, because I do not have direct access to AWS dashboard to fiddle there
C. I tried a different device (Sony Xperia, 4.4), but with the same exact results
D. Tried this one, then I have:
```
E/UploadTask﹕ Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 6E2148B2A262A15C)
```
Can't tell if it's an improvement? :)

I use also DDB and auth works fine, and I use the same constants, so I would not look for problems there.

Any other ideas?

**Comment by rafalzawadzki** [comment]
@wdane Ok I tested region EU-CENTRAL-1 with success, I managed to upload a photo.
Is it possible that there are issues with EU-WEST-1 region?

**Comment by wdane** [comment]
Could you please post a code snippet showing the initialization of the S3 Client, the Transfer Utility, and the call to upload?  It's almost certainly not an issue with the EU-WEST-1 region, at least from the service's perspective.

**Comment by rafalzawadzki** [comment]
Not a problem, here is my code snippet:

```
public static void uploadShopPhoto(Context ctx, final File file, String guid){

        CognitoCachingCredentialsProvider credentials = new CognitoCachingCredentialsProvider(
                context,
                Constants.AWS_IDENTITY_POOL_ID,
                Regions.EU_WEST_1);

        s3 = new AmazonS3Client(credentials);
        s3.setRegion(Region.getRegion(Regions.EU_WEST_1));

        String key = "test/"+guid+".jpg";

        TransferUtility transferManager = new TransferUtility(s3, ctx);
        TransferObserver observer = transferManager.upload("mybucket", key, file);
        observer.setTransferListener(new TransferListener() {
            public void onStateChanged(int id, TransferState state) {
                if (state==TransferState.COMPLETED)
                    EventBus.getDefault().post(new Event.UploadShopPhotoSuccess());
            }

            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                Log.i(TAG, "Upload photo progress: " + bytesCurrent +"/"+bytesTotal);
            }

            public void onError(int id, Exception e) {
                Log.e(TAG, "Shop photo transfer failed: " + e.toString());
                EventBus.getDefault().post(new Event.UploadShopPhotoFail());
            }
        });
    }
```

Any help is welcome :)

**Comment by rafalzawadzki** [comment]
Ok after some more tests on my own AWS account I noticed these errors are showing up when in bucket config, under "Permissions" is set only the owner of the bucket. When I add Upload rights to Authenticated users or Everyone, the error goes away.

By the way,
```
javax.net.ssl.SSLException: Write error: ssl=0x9dd68000: I/O error during system call, Connection reset by peer
```
Does not say much about setting proper permissions ;)

**Comment by wdane** [comment]
Agreed, that is not a very helpful message.  I will see if it can be made more meaningful.  Thanks, and glad you got it working.

**Comment by kac-** [comment]
Hi, I had similar issue with java-sdk and node-sdk, what helped me was limiting concurrent connections:

    TransferManager manager = new TransferManager(s3Client, Executors.newFixedThreadPool(3));

which defaults to **10**.

DoS filters, concurrent multipart-upload parts resolution glitch, bug on aws side? I don't know but now my backups lands gracefully on s3.

**Comment by erikcaffrey** [comment]
@rafalzawadzki  I have the dame issue how resolve it? Could you help me please.

**Comment by rafalzawadzki** [comment]
hey @erikcaffrey, as I said in the comment:

> I noticed these errors are showing up when in bucket config, under "Permissions" is set only the owner of the bucket. When I add Upload rights to Authenticated users or Everyone, the error goes away.

That solved my problem, hope it helps you too!

**Comment by erikcaffrey** [comment]
@rafalzawadzki  you're right, the problem is about of permissions , we change upload to everyone and I can upload a photo file but even we need to review more about it as we would like to have better control of permissions. When I find a safer way to do that I share the solution with all of them. Thank you!
