### ISSUE TITLE
Proguard Issue : "java.lang.IllegalArgumentException: Illegal query expression: No hash key condition is found in the query"

### ISSUE THREAD

**Issue by mlnarola** [aws/aws-sdk-android#535]
HI, I have used AWS services and used dynemo db in my application.

I am using following 3 Services of AWS. 
**implementation 'com.amazonaws:aws-android-sdk-core:2.6.15'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.6.15'
    implementation 'com.amazonaws:aws-android-sdk-ddb-mapper:2.6.15'**

Everything works fine and project successfully builds too.

Now I have enabled proguard in my project and added following  rules in proguard.pro file.

> -keepnames class com.amazonaws.**
> -keepnames class com.amazon.**
> -keep class com.amazonaws.services.**.*Handler
> -dontwarn com.fasterxml.jackson.**
> -dontwarn org.apache.commons.logging.**
> -dontwarn org.apache.http.**
> -dontwarn com.amazonaws.http.**
> -dontwarn com.amazonaws.metrics.**

But I am getting following error when i try to request for query using DynamoDBQueryExpression 
`Error : "java.lang.IllegalArgumentException: Illegal query expression: No hash key condition is found in the query". `

Could you please help me with this issue?

**Comment by cbommas** [comment]
hello @mlnarola 

Sorry to hear that you are running into issues. I tried to reproduce your locally, but wasn't sucessful.
To help debug your issue further,
- can you share your build.gradle and proguard.pro files
- let me know if have you turned on code obfuscation
- also, are you using the DynamoDBObject Mapper?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.

**Comment by avinash8083** [comment]
i am also getting this error while trying to query on a gsi index 

 Transaction transaction=new Transaction();
        TxnInfoDTO txnInfoDTO=new TxnInfoDTO();
        txnInfoDTO.setRrn(rrn);
        transaction.setTxnInfoDTO(txnInfoDTO);
            DynamoDBQueryExpression<Transaction> queryExpression = new DynamoDBQueryExpression<Transaction>()
                .withIndexName("idx_txn_info_rrn").withHashKeyValues(transaction).withConsistentRead(false);
        List<Transaction> transactions = dynamoDBMapperSlave.query(Transaction.class, queryExpression);
