### ISSUE TITLE
callback = COMPLETED, but no file uploaded

### ISSUE THREAD

**Issue by gwicks56** [aws/aws-sdk-android#537]
**Describe the bug**
99% of the time it works fine, but occasionally, usually on ZTE phone, i get a callback saying COMPLETED, but when I check my bucket, no files have been upload.

Still using:
  implementation 'com.amazonaws:aws-android-sdk-core:2.6.18'

mainly because I don't like changing production code without good reason.

Just wondering if this was a known bug?

Example logcat:
10-04 10:57:33.482 7031-7031/gwicks.com.sleep D/Util: onStateChanged: Transfer ID: 2 | New State: COMPLETED
10-04 10:57:33.482 7031-7031/gwicks.com.sleep D/Util: Transfer ID 2 has completed
10-04 10:57:33.483 7031-7031/gwicks.com.sleep D/LogUploadTask: This is AWSBIT
10-04 10:57:33.483 7031-7031/gwicks.com.sleep D/SensorUploadReceiver: Callback onComplete() | ID: 2 | State: COMPLETED
10-04 10:57:33.485 7031-7031/gwicks.com.sleep D/Util: (04102018_105731281_3.encrypted)–File deleted: true

But no file in bucket

**Environment(please complete the following information):**
 - SDK Version: 2.6.18
**Device Information (please complete the following information):**
 - Device: ZTE
 - Android Version:  Nougat 7.1.1

**Comment by kvasukib** [comment]
@gwicks56 Sorry for the inconvenience caused. 

What version of Android are you using? 
What is the name of the key of the object that you are uploading?
Did you get onProgressChanged callback?
What is the size and type of file? What is the content type?
Do you have any object metadata associated with it?

**Comment by gwicks56** [comment]
The phone is a ZTE  (N9560) I use for testing purposes, Android 7.1.1.
It should have uploaded 8 files this morning, I got an IN_PROGRESS callback for each of them,
then a few seconds later a COMPLETED callback for each of them. They were then deleted from the phone, as I do that in the COMPLETED callback. Size is a text file, encrypted on the device, between 10KB and 500KB.

Not sure what you mean by the name of the key of the object, or the object metadata?

**Comment by gwicks56** [comment]
Also in case it helps, I got this logcat output between IN_PROGRESS and COMPLETED, can't find out what it means:

10-04 10:57:31.913 7031-7031/gwicks.com.sleep D/SensorUploadReceiver: Callback onStart() | ID: 8 | State: IN_PROGRESS
10-04 10:57:32.191 7031-3044/gwicks.com.sleep D/CognitoCachingCredentialsProvider: Saving credentials to SharedPreferences
10-04 10:57:32.270 7031-3052/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.270 7031-3052/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.280 7031-3036/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.280 7031-3036/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.285 7031-3051/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.286 7031-3051/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.290 7031-3034/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.291 7031-3034/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.294 7031-3023/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.294 7031-3023/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.303 7031-3049/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.304 7031-3049/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.305 7031-3044/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.306 7031-3044/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.672 7031-3036/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.673 7031-3036/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.676 7031-3044/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.677 7031-3044/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.679 7031-3023/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.680 7031-3023/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.684 7031-3051/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.685 7031-3051/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.687 7031-3049/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.687 7031-3049/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.690 7031-3034/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.691 7031-3034/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.706 7031-3052/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:32.707 7031-3052/gwicks.com.sleep I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
10-04 10:57:33.045 7031-7031/gwicks.com.sleep D/Util: onStateChanged: Transfer ID: 8 | New State: COMPLETED
10-04 10:57:33.045 7031-7031/gwicks.com.sleep D/Util: Transfer ID 8 has completed
10-04 10:57:33.046 7031-7031/gwicks.com.sleep D/LogUploadTask: This is AWSBIT
10-04 10:57:33.046 7031-7031/gwicks.com.sleep D/SensorUploadReceiver: Callback onComplete() | ID: 8 | State: COMPLETED
10-04 10:57:33.047 7031-7031/gwicks.com.sleep D/Util: (04102018_105731696_1.encrypted)–File deleted: true

**Comment by gwicks56** [comment]
The bucket name is: sleepmelissa, the identifier inside that bucket was b33f160a04c40ba4. Works most of the time, but not everytime, despite the COMPLETED call back.

`public class Util {

    private static final String TAG = "Util";

    public interface FileTransferCallback {
        void onStart(final int id, final TransferState state);

        void onComplete(final int id, final TransferState state);

        void onCancel(final int id, final TransferState state);

        void onError(final int id, final Exception e);
    }


    // We only need one instance of the clients and credentials provider
    private static AmazonS3Client sS3Client;
    private static CognitoCachingCredentialsProvider sCredProvider;
    private static TransferUtility sTransferUtility;
    private static String userId;
    
    /**
     * Gets an instance of CognitoCachingCredentialsProvider which is
     * constructed using the given Context.
     *
     * @param context An Context instance.
     * @return A default credential provider.
     */
    private static CognitoCachingCredentialsProvider getCredProvider(Context context) {
        if (sCredProvider == null) {
            sCredProvider = new CognitoCachingCredentialsProvider(
                    context.getApplicationContext(),
                    Constants.COGNITO_POOL_ID,
                    Regions.US_WEST_2);
        }
        return sCredProvider;
    }

    private static void initUserId() {
        if (TextUtils.isEmpty(userId)) {
           userId = FinishScreen.secureID;

            Log.d(TAG, "initUserId: secure id is: " +userId);
        }
    }

    /**
     * Gets an instance of a S3 client which is constructed using the given
     * Context.
     *
     * @param context An Context instance.
     * @return A default S3 client.
     */
    public static AmazonS3Client getS3Client(Context context) {
        if (sS3Client == null) {
            ClientConfiguration config = new ClientConfiguration();
            config.setMaxErrorRetry(500);
            config.setConnectionTimeout(50000);
            sS3Client = new AmazonS3Client(getCredProvider(context.getApplicationContext()), config);

        }
        return sS3Client;
    }

    /**
     * Gets an instance of the TransferUtility which is constructed using the
     * given Context
     *
     * @param context
     * @return a TransferUtility instance
     */
    public static TransferUtility getTransferUtility(Context context) {
        if (sTransferUtility == null) {
            sTransferUtility = new TransferUtility(getS3Client(context.getApplicationContext()),
                    context.getApplicationContext());
        }
        return sTransferUtility;
    }

    /**
     * Converts number of bytes into proper scale.
     *
     * @param bytes number of bytes to be converted.
     * @return A string that represents the bytes in a proper scale.
     */
    public static String getBytesString(long bytes) {
        String[] quantifiers = new String[]{
                "KB", "MB", "GB", "TB"
        };
        double speedNum = bytes;
        for (int i = 0; ; i++) {
            if (i >= quantifiers.length) {
                return "";
            }
            speedNum /= 1024;
            if (speedNum < 512) {
                return String.format("%.2f", speedNum) + " " + quantifiers[i];
            }
        }
    }

 public static void uploadFilesToBucket(final List<File> files, final boolean deleteAfter,
                                           final Util.FileTransferCallback callback, Context context, String folder) {
        Log.d("Log", "This is in AWSUTIL upload files to bucket");

        if (sTransferUtility == null) {
            sTransferUtility = new TransferUtility(getS3Client(context.getApplicationContext()),
                    context.getApplicationContext());
        }



        for (final File file : files) {
            uploadFileToBucket(file, file.getName(), deleteAfter, callback, folder);
        }
    }


    public static void uploadFileToBucket(final File file, final String filename,
                                          final boolean deleteAfter, final Util.FileTransferCallback callback, String folder) {
        initUserId();
        Log.d("Log", "This is in AWSUTIL upload file to bucket");
        final String filePath = String.format("%s%s", userId + folder, filename);
        final TransferObserver observer =
                //transferUtility.upload(BuildConfig.AWS_BUCKET_NAME, filePath, file);
                sTransferUtility.upload(Constants.BUCKET_NAME, filePath, file);
        observer.setTransferListener(new TransferListener() {
            @SuppressLint("DefaultLocale")
            @Override
            public void onStateChanged(int id, TransferState state) {
                final String logLine =
                        String.format("onStateChanged: Transfer ID: %d | New State: %s", id, state);
                Log.d(TAG, logLine);
                switch (state) {
                    case IN_PROGRESS:
                        Log.d(TAG, String.format("Transfer ID %d has begun", id));
                        callback.onStart(id, state);
                        break;
                    case COMPLETED:

                        long unixTime = System.currentTimeMillis() / 1000L;
                        String desination = Environment.getExternalStorageDirectory().getAbsolutePath() + "/Sleep/"+ filename + unixTime + ".copy";


                        File destination = new File(desination);
                        try {
                            FileUtils.copyFile(file, destination);
                            Log.d("LogUploadTask", "Copyting file to VideoDIARY");

                        } catch (IOException e) {
                            e.printStackTrace();
                        }


                        Log.d(TAG, String.format("Transfer ID %d has completed", id));
                        callback.onComplete(id, state);
                        if (deleteAfter) {
                            final String filename = file.getName();
                            final boolean deleted = file.delete();
                            Log.d(TAG, String.format("(%s)–File deleted: %s", filename, deleted));
                        }
                        break;
                    case CANCELED:
                        Log.d(TAG, String.format("Transfer ID %d has been cancelled", id));
                        callback.onCancel(id, state);
                        break;
                    default:
                        break;
                }
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
            }

            @SuppressLint("DefaultLocale")
            @Override
            public void onError(int id, Exception ex) {
                Log.e(TAG, String.format("onError: Transfer ID: %d", id), ex);
                callback.onError(id, ex);
            }
        });
    }
}
`

**Comment by kvasukib** [comment]
@gwicks56 Thank you for posting the code snippet. Can you print the `filePath` variable and the `key name` for the file where the upload fails to complete however the callback is invoked?

**Comment by kvasukib** [comment]
@gwicks56 Also, can you upgrade to 2.7.4 where we have made stability improvements in `TransferUtility` and check if the issues is still reproducible?

**Comment by gwicks56** [comment]
One of the files should have appeared in bucket: melissasleep/b33f160a04c40ba4/Sensors/Acc/04102018_105731281_2.encrypted

melissasleep/b33f160a04c40ba4/Sensors/Acc/04102018_105731281_1.encrypted

is another one of them.

I have upgraded to 2.7.3, and have not noticed the problem again, but it's hard to be sure because it was very intermittent. Again, this was only on a ZTE device, which makes me suspicious, as they exhibit lots of strange behavior in my experience.

**Comment by kvasukib** [comment]
@gwicks56 Thank you for the confirmation. I still couldn't see any progress updates for the transfer where the file is missing in S3. Can you add a log statement in the `onProgressChanged` callback method and see if TransferUtility is reporting any progress updates?

```java
        public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
            Log.d(TAG, "Progress: bytesCurrent = " + bytesCurrent + "; bytesTotal = " + bytesTotal);
        }
```

To answer your question, the issue that you reported seems intermittent. I have added few more assert statements in the tests we have to catch this. I will let you know if my tests can catch it.

But if possible can you add the above mentioned log statement in `onProgressChanged` and grab the logs?

**Comment by gwicks56** [comment]
OK, no problem, I'll do that now. The uploads only happen once a day, so I'll continue monitoring it, and see if it happens again. If so, I'll let you know ASAP. When I can I'll do some extra testing as well.

**Comment by kvasukib** [comment]
Thank you for the confirmation @gwicks56

**Comment by gwicks56** [comment]
Also, @kvasukib, could you tell me in regards to:

Starting version 2.7.0 of the SDK, TransferService logic has been refactored. This service now will be responsible only for monitoring network connectivity changes. When the network goes offline, the transfers that are in progress will be paused. When the network comes back online, the transfers that are paused will be resumed. If you expect your app to perform long-running transfers in the background, you need to initiate the transfers from a background service of your choice.

The TransferService will not be started or stopped by TransferUtility anymore. You have to start TransferService manually from your application. A recommended way is to start the service upon Application startup. One way you can do this is to include the following line in the onCreate method of your app's Application class.

    `getApplicationContext().startService(new Intent(getApplicationContext(), TransferService.class));`

if I need to add the above? I changed to 2.7.3 from 2.6, but I have not changed my code at all, and it still seems to be working?

**Comment by kvasukib** [comment]
@gwicks56 

**2.6.x**

The TransferService in 2.6.x had the responsibilities of starting a transfer, listening to network and pausing/resuming transfers when the network connectivity changes. 
1) You need to declare the TransferService in the AndroidManifest.xml file. 
2) The TransferUtility starts the TransferService and you don't have to manually start the service.

**2.7.x**

The TransferService in 2.7.x will only own the responsibility of listening to network connectivity changes and not starting a transfer anymore. 
1) You need to  declare the TransferService in the AndroidManifest.xml file. 
2) You need to manually start the service from your app because the SDK doesn't start the service.

Hence you would not notice a difference in the transfer operations between 2.6 and 2.7.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
