### ISSUE TITLE
No CloudFront in Android SDK

### ISSUE THREAD

**Issue by deibid** [aws/aws-sdk-android#54]
Hi,

Do you know how can i generate a signedURL for consuming private S3 content served through CloudFront? i cant seem to find any information on this.
I can generate signedURL from S3 and consume the files from there, but doing this through CloudFront seems impossible.
Thanks

**Comment by fosterzhang** [comment]
I replied you on [StackOverflow](http://stackoverflow.com/questions/31994908/using-aws-cloudfront-and-android). Closing this issue to keep the discussion at one place.
