### ISSUE TITLE
first time call generatePresignedUrl seem not use v4 sign

### ISSUE THREAD

**Issue by jchbh-duplicate** [aws/aws-sdk-android#542]
**Describe the bug**

it seems the first time generatePresignedUrl will get something like 
https://bucket.s3.amazonaws.com/file?AWSAccessKeyId=accesskey&Expires=yyyy&Signature=xxxxxxx

and after a little time, it will return 

https://bucket.s3.amazonaws.com/file?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20181013T025706Z&X-Amz-SignedHeaders=host&X-Amz-Expires=299&X-Amz-Credential=mmmmmmmmm&X-Amz-Signature=nnnnnnnnnnnnn

**To Reproduce**
1. Create the client use:
```
                val credential = BasicAWSCredentials("awsAccessKeyId", "awsSecretAccessKey")
                val config = ClientConfiguration().withSocketTimeout(20000)
                        .withEnableGzip(true)
                m_S3Client = AmazonS3Client(credential, config)
```
2. upload something (optional)
2. ``m_S3Client.generatePresignedUrl(bucketname, file, timeout)`` to sign anything. 
3. check the signed url. 
5. upload something else, sign the url again. 

**Which AWS service(s) are affected?**
S3

**Expected behavior**
use version 4 return the correct signed url. 

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: 2.7.5

**Device Information (please complete the following information):**
 - Device: Samsung S6 Edge
 - Android Version: not official 9.0
 - Specific to simulators:

**Additional context**
<img width="1031" alt="screen shot 2018-10-12 at 11 17 03 pm" src="https://user-images.githubusercontent.com/785571/46900754-4346a980-ce75-11e8-86ab-aff74452e77f.png">
I see the source code and maybe it is because the client didn't setup the bucket region and there is no bucketRegionCache so region is empty and code jump into v2 sign. 
the next time run,  the bucketRegionCache has been setup some where so after that it start use v4 sign.

**Comment by kvasukib** [comment]
@jchbh-duplicate Thank you for reporting to us. Have you tried setting the region in the `AmazonS3Client` object and generate the presigned URL?
