### ISSUE TITLE
YourUserPools does not recover if you give wrong phone number in Sign Up

### ISSUE THREAD

**Issue by desokroshan** [aws/aws-sdk-android#543]
**Which AWS Services is the feature request for?**
Cognito

**Is your feature request related to a problem? Please describe.**
Steps to repro:
-Do Sign Up 
-Fill all asked fields, enter incorrect phone number
-Tap Sign up button -> View is changed to Confirm view, SMS confirmation is sent to wrong number
-Return from Confirmation view to fix phone number
-Fix phone number and tap sign up button
Actual result:
Sign up failed, User already exists. 
-> User account is already created with wrong phone number. Confirm code is never received. Account sign-in is not possible since account is not confirmed. Changing phone number of already created account is not possible since sign-in is not possible.

**Describe the solution you'd like**
It should be possible to return for fixing wrong information and then return confirm code again.

**Comment by muellerfr** [comment]
Related to https://github.com/awslabs/aws-sdk-android-samples/issues/69

**Comment by muellerfr** [comment]
Opened originally by @jukka-palomaki and commented on by @litalch.

**Comment by minbi** [comment]
This issue was resolved in previous thread awslabs/aws-sdk-android-samples#69
This is a service limitation at this time.
