### ISSUE TITLE
Allow to append metadata to files added through TransferUtility

### ISSUE THREAD

**Issue by angelromero** [aws/aws-sdk-android#55]
With TransferUtility I can upload files which will become objects in S3.
I'd like to append metadata to this files so I can read them on S3 through Lamda.

**Comment by wdane** [comment]
I cannot make direct promises as to when, but I can say we're working on it!  I'll keep this issue open so others are aware.

**Comment by daggaz** [comment]
:+1:

**Comment by wdane** [comment]
With the release of 2.2.6 of the SDK (https://aws.amazon.com/releasenotes/Android/3264977967699398) I'm happy to close this issue.

The TransferUtility now supports adding Object Metadata to uploads requests. Look for the upload(bucketName, key, file, objectMetadata) API. You can retrieve object metadata using the low level S3 API getObjectMetadata(bucket, key).

**Comment by angelromero** [comment]
Great work! congratulations! and thanks!
