### ISSUE TITLE
UserPools  SignUpActivity, Username field, no keyboard displayed

### ISSUE THREAD

**Issue by BillBunting** [aws/aws-sdk-android#550]
**Describe the bug**
The UserPools SignUpActivity does not show the keyboard for Username when the SignUpView is displayed

**To Reproduce**
1. Go to Sign-in UI 
2. Click on "Create New Account"
3. Observe "Enter your information to sign up. screen appears.
4. Observe, cursor in Username field and no keyboard 

**Which AWS service(s) are affected?**
aws-android-sdk-auth-userpools/src/main/java/com/amazonaws/mobile/auth/userpools/

**Expected behavior**
The keyboard should appear when the user touches inside the Username field or when the activity is initially displayed.

**Environment(please complete the following information):**
 - SDK Version: Any including 24, 25, 26, and 27.

**Device Information (please complete the following information):**
 - Device: Pixel 2 API 27 in Simulator (or others)
 - Android Version: Any > 7.0
 - Specific to simulators: No, simulator and device.

**Additional context**
The user must click into any other field (password or given name, etc) and the keyboard will appear. They can then return to enter the username as a workaround.

**Comment by desokroshan** [comment]
@BillBunting This issue has been fixed in the latest release ```2.7.6```. Can you please update to the latest version and confirm if the keyboard is displayed appropriately?

**Comment by minbi** [comment]
Hi @anje89 @BillBunting ,

Please see if SDK release 2.7.6 fixes this issue for you. We have added the following enhancements:
- UI activities will show keyboard by default when requesting input from the end-user.

You may see all changes in the [changelog](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-276)

**Comment by BillBunting** [comment]
@minbi Thank you very much!  Tested briefly and I see the keyboard now.
