### ISSUE TITLE
Could not find version 2.7.6.

### ISSUE THREAD

**Issue by ppamorim** [aws/aws-sdk-android#554]
**State your question**
The version 2.7.6 is not published on Maven and I cannot use it. When it gonna be fixed?
Thanks.

**Which AWS Services are you utilizing?**
Core and S3

**Environment(please complete the following information):**
 - SDK Version: 2.7.6 (Not available on Maven Repository)

**Comment by kvasukib** [comment]
@ppamorim The maven release is in progress. It should be available soon. I will let you know when the artifacts are available on maven repository.

**Comment by kvasukib** [comment]
@ppamorim The maven release is complete. I performed a gradle sync with `2.7.6` version and I am able to pull it now. Apologies for the inconvenience caused in the meantime. Please let me know if you face any issues in getting it.

**Comment by ppamorim** [comment]
@kvasukib Thank you, it's working now.
