### ISSUE TITLE
Allow resetting an upload with new parameters

### ISSUE THREAD

**Issue by angelromero** [aws/aws-sdk-android#56]
Through TransferUtility I can pause a file transfer.
If I cancel the transfer I'd like to easily reset the initial transfer parameters like original bucket and folder where it's been mapped.
It could be something like a new overload
TransferUtility.upload(id, newbucketpath);
That overload would be possible only if the transfer is in a canceled or failed state.

**Comment by fosterzhang** [comment]
Thank you for your suggestion. We've thought about it. However it's better not to alter an existing transfer, regardless of its status. TransferUtility may needs the information to perform additional operations, say clean up. You'd better initiate a new transfer instead. The TransferObserver of the existing transfer can provide you the file path in case you need it.

If it doesn't work out for you, we are open to discussion.

**Comment by fosterzhang** [comment]
Closing this as lack of information.
