### ISSUE TITLE
Javadoc for Amazon Kinesis

### ISSUE THREAD

**Issue by fabiopimentel** [aws/aws-sdk-android#560]
Hey there,

i'm looking for com.amazonaws.services.kinesis.AmazonKinesisClient in javadoc but, apparently, there isn't any references about kinesis services [there](https://aws.github.io/aws-sdk-android/docs/reference//).
However for Kinesis Video there is.

Is there another place to see Kinesis reference?

**Which AWS service(s) are affected?**
Amazon Kinesis

**Comment by fabiopimentel** [comment]
Hello Kvasubik,
thanks for the answer.

KinesisRecorder is not same KinesisClient. The proposals are different.

**Comment by kvasukib** [comment]
@fabiopimentel This issue has been fixed in the release 2.7.7. Now we have the javadoc for KinesisClient.

**Comment by fabiopimentel** [comment]
Thks @kvasukib!
