### ISSUE TITLE
S3 TransferUtility all uploads are in "WAITING" state

### ISSUE THREAD

**Issue by chatterjb** [aws/aws-sdk-android#57]
I am seeing an issue where all of the uploads that are being queued end up in the 'WAITING" state. The status never changes from waiting to "In Progress" and ultimately "Complete".  I'm calling this code inside a ScheduledExecutorService which means it doesn't run in the main thread, but I didn't expect this to be an issue. Here's the code:

        // kick off the scheduled executor service to clean up files that are complete
        scheduledExecutorService.scheduleAtFixedRate(new Runnable() {
            public void run() {
                String filename = "jdVehicleUpload_" + new SimpleDateFormat("MM-dd-yyyy_HH-mm-ss").format(new Date()) + ".json";
                FileOutputStream outputStream;

                // check for any transfers that have successfully completed
                // and delete corresponding json file from disk
                try {
                    for (TransferObserver observer : awsS3Observers) {
                        if (observer.getState() == TransferState.COMPLETED ||
                                observer.getState() == TransferState.CANCELED) {
                            File fileToDelete = new File(observer.getAbsoluteFilePath());
                            if (fileToDelete != null && fileToDelete.delete()) {
                                Log.i(TAG, "Successfully deleted file from disk: " + observer.getAbsoluteFilePath());
                            }
                        }
                    }

                    // write the file to disk for the current state of the vehicle
                    outputStream = getActivity().openFileOutput(filename, Context.MODE_PRIVATE);
                    outputStream.write(new Gson().toJson(wvaHelper.currentVehicle).getBytes());
                    outputStream.close();

                    File fileToUpload = new File(getActivity().getFilesDir() + "/" + filename);
                    Log.i(TAG, "Current vehicle state file written to disk: " + Uri.fromFile(fileToUpload));

                    // upload the file to AWS S3
                    TransferObserver observer = transferUtility.upload(Constants.BUCKET_NAME, fileToUpload.getName(), fileToUpload);
                    observer.setTransferListener(new AWSUploadListener());
                    awsS3Observers.add(observer);
                } catch (Exception ex) {
                    Log.e(TAG, ex.toString());
                }
            }
        }, 1, 1, TimeUnit.MINUTES);

The transferUtlity is being initialized in the onCreate() method of the fragment. The only thing I could think of is that I am getting the application context through the parent activity. However, this fragment has the setRetainInstance flag set to true so it should never be destroyed and re-instantiated and I didn't think this would cause any issues.

        // called in onCreate()
        transferUtility = AWSHelper.getTransferUtility(getActivity().getApplicationContext());

Any ideas on why this might be happening?

**Comment by fosterzhang** [comment]
I will look into this. This is a duplicate question of one on the [AWS forum](https://forums.aws.amazon.com/thread.jspa?threadID=216466&tstart=0). I will post further replies there.
