### ISSUE TITLE
Better error reporting in TransferObserver

### ISSUE THREAD

**Issue by jghazarian** [aws/aws-sdk-android#61]
Hi, I have an app that is uploading videos to S3 and am having trouble handling failed uploads from testers. I've been doing upload successfully when testing on several devices, but some of the testers on the team have been reporting failed uploads. My biggest problem is that when an upload fails, all that's reported in the onError callback is a generic illegal state exception saying "transfer failed" and an id of the upload. This gives me very little ability to followup on the failure. Is it possible to get more data reported back on transfer failures? I believe the underlying AmazonS3.putObject call has more information in its thrown exception, but the UploadTask appears to just log out that message and not pass the exception along.

**Comment by wdane** [comment]
I agree an API for this would be nice.  But for now all requests to S3 should log the error to LogCat.  Are you not seeing messages there? For puts, the tag should include either "UploadTask" or "UploadPartTask", which should help you search LogCat.

**Comment by jghazarian** [comment]
Yeah, I'm seeing the messages in logcat, but that means I had to put in an extra reporting system for the test users, but even if I have the logs to try to figure out problems with the app, it still means I can't necessarily handle those issues on the fly. An example issue that I ran into was a file with invalid data, in which case I should be able to handle in the app by letting it know the file is bad, but because I don't have the error reporting that information directly, I can't be sure. It's not the biggest issue, but I believe it would be really helpful to pass that information along to where errors are being handled.

**Comment by wdane** [comment]
I completely agree, I'll keep this issue open as a feature request.

**Comment by jghazarian** [comment]
Thanks, much appreciated.

**Comment by fosterzhang** [comment]
AWS SDK for Android v2.2.11 was released just now. The original exception will be reported to associated listener via [TransferListener.onError(int, Exception)](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/s3/transferutility/TransferListener.html#onError(int,%20java.lang.Exception)). Check out the [release notes](http://aws.amazon.com/releasenotes/Android/2037471825124826) for more details.

**Comment by jghazarian** [comment]
Thanks so much. I'll look into implementing this right away.

**Comment by fosterzhang** [comment]
Closing this. Feel free to reopen it if the issue persists.
