### ISSUE TITLE
Incorrect content-length when multibyte UTF-8 characters are present in calls to API Gateway

### ISSUE THREAD

**Issue by setn** [aws/aws-sdk-android#62]
The Content-Length calculation in ApiClientHandler.java calculates the number of characters in the content rather than the "decimal number of OCTETs". The untested code below attempts to resolve this.
    
    // Row 137-140 ApiClientHandler.java
    if (hasContent) {
        byte[] contentBytes = content.getBytes(StringUtils.UTF8);
        request.setContent(new ByteArrayInputStream(contentBytes));
        request.addHeader("Content-Length", String.valueOf(contentBytes.length));
    }

**Comment by wdane** [comment]
Thanks for pointing this out! I've fixed this, and it will be released soon.  I'll leave this issue open until it is.

**Comment by wdane** [comment]
Fixed in 2.2.7! https://aws.amazon.com/releasenotes/Android/5837075661246179
