### ISSUE TITLE
TransferUitlity should have ACL option for uploading file (needs 2 request to upload a public-read file)

### ISSUE THREAD

**Issue by fernando-closs-clansoft** [aws/aws-sdk-android#63]
The transfer utility is fantastic, but there is too much limitation on changing the putobjectrequest, it is only possible to set the metadata. Something like the TransferUtilityUploadRequest (as in .Net sdk) should be also available in Android.

To upload a public-read file using it, i need to handle the successful upload, then set the ACL, then finally notify the success on uploading the file. One unnecessary extra request, but i wouldn't like to lose all the benefits of the TransferService and Transfer Utility.

Thanks for your attention.

**Comment by rafael-fantini-movile** [comment]
+1
Java also has support for this as shown in http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-using-java-sdk.html
Using the Android SDK would be the best, however.

**Comment by fernando-closs-clansoft** [comment]
The PutObjectRequest has the ACL Option (withCannedAcl) but the TransferUtility and its UploadTask does not have an option to set it, so it will be null. =Z

**Comment by wdane** [comment]
Thanks for the request guys, I'll keep this issue open and I've added this to our feature request list.  If others feel like this is a feature they want please +1 so we can adjust our priorities accordingly!

**Comment by angelromero** [comment]
+1
It's an important feature.

2015-10-06 14:29 GMT-05:00 wdane <notifications@github.com>:

> Thanks for the request guys, I'll keep this issue open and I've added this
> to our feature request list. If others feel like this is a feature they
> want please +1 so we can adjust our priorities accordingly!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-android/issues/63#issuecomment-145972751>.
>



-- 
Angel Romero Salazar

**Comment by pedro-almeida-clansoft** [comment]
+1
I also need this feature!

**Comment by claudio-jeremias-clansoft** [comment]
+1
Nice feature!!!

**Comment by fernando-closs-clansoft** [comment]
Thanks for the so fast reply, wdane!

**Comment by fpg1503** [comment]
+1
This would help a lot!

**Comment by ganlaw** [comment]
+1

**Comment by jitendraramoliya** [comment]
+1
This Feature really require. make this feature ASAP so User can use this feature

**Comment by niteshgoel** [comment]
+1
Any alternate to this as of now. As I need it very urgently.

**Comment by raul1991** [comment]
So till this feature request is implemented, Is there way around to this situation ?

**Comment by fosterzhang** [comment]
A work around is that you can apply bucket policy to the bucket you upload objects. See [Bucket Policy Examples](https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html). The following bucket policy grants read only permission to objects under `bar` and `foobar` path in the bucket `foo`.

```javascript
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"AddPerm",
      "Effect":"Allow",
      "Principal": "*",
      "Action":["s3:GetObject"],
      "Resource":["arn:aws:s3:::foo/bar/*","arn:aws:s3:::foo/foobar/*"]
    }
  ]
}
```

See my original answer on StackOverflow [How to specify public-read policy on a complete bucket in aws?](http://stackoverflow.com/questions/33679187/how-to-specify-public-read-policy-on-a-complete-bucket-in-aws).

**Comment by fernando-closs-clansoft** [comment]
The problem with this solution is that you change the whole bucket policy when you just want to change one object ACL. And if you want to change only one file you have to do an extra call to set ACL while it could be already set on the object in the upload.

My solution was not to use TransferUtility, which is sad because it has a good implementation on a separate service, etc, but i've used the PutObjectRequest inside an AsyncTask. Here is the code:

private class UploadFileTask extends AsyncTask<Void, Long, Exception> {

        private FileUploadCallback callback;
        private AWSCredentials credentialsProvider;
        private String fileUrl;
        private boolean publicRead;
        private String bucket;
        private FileUploader uploaderInstance; //used to store client for reuse in same Uploader Instance
        private AmazonS3Client s3Client = null;
        private boolean cancelled = false;
        private long totalSize = 0;
        private long totalTransferred = 0;

        public UploadFileTask(AmazonS3Client s3Client, String fileUrl, String bucket,boolean publicRead, FileUploadCallback callback, AWSCredentials credentialsProvider, FileUploader instanceReference)
        {
            this.s3Client = s3Client;
            this.fileUrl = fileUrl;
            this.bucket = bucket;
            this.publicRead = publicRead;
            this.credentialsProvider = credentialsProvider;
            this.callback = callback;
            this.uploaderInstance = instanceReference;
        }
        protected Exception doInBackground(Void... urls) {
            if(s3Client == null) {
                s3Client = new AmazonS3Client(credentialProvider);
                s3Client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));

                s3Client.setRegion(defaultRegion);

                uploaderInstance.setS3Client(s3Client);
            }


            //Instantiate and store reference on uploader Instance
            File f = new File(fileUrl);
            try {
                totalSize = f.length();
            }
            catch (Exception e)
            {
                return e;
            }

            PutObjectRequest por = new PutObjectRequest(this.bucket,f.getName(),f);
            if(this.publicRead)
            {
                por.setCannedAcl(CannedAccessControlList.PublicRead);
            }

            por.setGeneralProgressListener(new ProgressListener() {
                @Override
                public void progressChanged(ProgressEvent progressEvent) {
                    //Log.i("PROGRESS",progressEvent.getEventCode() + " - " + progressEvent.getBytesTransferred());
                    if(progressEvent.getEventCode() == 0)
                    {
                        totalTransferred += progressEvent.getBytesTransferred();
                        publishProgress(totalTransferred);
                    }
                    else if(progressEvent.getEventCode() == ProgressEvent.CANCELED_EVENT_CODE)
                    {
                        cancelled = true;
                    }

                }
            });

            try {
                s3Client.putObject(por);

                //Notify success
                return null;
            }
            catch (Exception e)
            {
                //Notify error
                return e;
            }


        }

        protected void onProgressUpdate(Long... progress) {
            if(callback!=null)
            {
                callback.onUploadProgressChanged(progress[0].longValue(),totalSize);
            }
        }

        protected void onPostExecute(Exception exception) {
            if(callback!=null) {
                if (exception == null) {
                    if(!cancelled) {
                        callback.onUploadSuccess();
                    }
                    else
                    {
                        callback.onUploadCanceled();
                    }
                }
                else
                {
                    callback.onUploadError(exception);
                }
            }
        }
    }

**Comment by fosterzhang** [comment]
@fernando-closs-clansoft that should do the job :).

What I proposed is an alternate solution and is applicable most of the time. There are a few benefits.
- Better management of objects as they are grouped by certain prefixes (or directories). For example, public objects go to `public/` and private ones go to `private/`.
- Easy to change access permission. Simply update the bucket policy.

Just my two cents.

Back to the original topic, I'll leave this issue open as feature request.

**Comment by fernando-closs-clansoft** [comment]
@fosterzhang I completely agree with you. In my case there was no way to have this directory structure due to retro compatibility with an existing iOs app. But this is a good solution until we have the ACL option in the feature. =)

**Comment by avdheshyadav** [comment]
+1

**Comment by erichkleung** [comment]
+1, would rather not have to use 2 calls if using TransferUtility.

**Comment by nemanjavuk** [comment]
+1

**Comment by yurii-diachenko** [comment]
+1

**Comment by guillaumenel** [comment]
+1

**Comment by jeandavid** [comment]
+1

**Comment by vault101** [comment]
+1

**Comment by Mrzy** [comment]
+1！！！！！

**Comment by shanuka** [comment]
+

**Comment by mrdevilbynature** [comment]
+1

**Comment by Suresh1988** [comment]
+1

**Comment by shroge** [comment]
+1

**Comment by jhermida-agero** [comment]
+1

**Comment by cimenmus** [comment]
+1

**Comment by hsyadav733** [comment]
+1

**Comment by eligreenfeld** [comment]
+1

**Comment by schrockblock** [comment]
+1

**Comment by sibeliusseraphini** [comment]
:+1:

**Comment by foteros** [comment]
+1

**Comment by anuragopenxcell** [comment]
+1 , been months and still waiting.

**Comment by Irfan55121** [comment]
+1

**Comment by esodot** [comment]
please please add it

**Comment by fosterzhang** [comment]
Hi all, this feature has been added to v2.2.15. See [release notes](http://aws.amazon.com/releasenotes/Android/9052762089998010).

**Comment by sibeliusseraphini** [comment]
thanks @fosterzhang, please close this

**Comment by gaojiusong** [comment]
+1, would rather not have to use 2 calls if using TransferUtility.

**Comment by nnbanerjee** [comment]
Is it implemented? Why a feature? It is a bug!
