### ISSUE TITLE
iot hackseries cloudformation link

### ISSUE THREAD

**Issue by desalegnbiru** [aws/aws-sdk-android#64]
Can you make this link work please? otherwise, you did a great job.

https://s3-us-west-2.amazonaws.com/iot-hackseries-aws-loft-public/cfn/connected_backend_dashboard_v4.json

**Comment by bhadrip** [comment]
Hi @desalegnbiru ,

Can you please give more information on the link. Are you trying out the IoT Hack Series link ?
The latest link is http://iot-hackseries.s3-website-us-west-2.amazonaws.com/

Thanks

**Comment by desalegnbiru** [comment]
Hi,
I am following the steps in this page http://iot-hackseries.s3-website-us-west-2.amazonaws.com/particle-aws-launch.html
In the above page is this link that doesn't work https://s3-us-west-2.amazonaws.com/iot-hackseries-aws-loft-public/cfn/connected_backend_dashboard_v4.json
Thanks 


     On Monday, October 12, 2015 6:55 PM, bhadrip <notifications@github.com> wrote:
   

 Hi @desalegnbiru ,Can you please give more information on the link. Are you trying out the IoT Hack Series link ?
The latest link is http://iot-hackseries.s3-website-us-west-2.amazonaws.com/Thanks—

**Comment by bhadrip** [comment]
Hi @desalegnbiru ,

Sorry for the delayed response. 

That hackseries is no longer supported. 

We have a new IoT service called [AWS IoT](https://aws.amazon.com/iot/). Please evaluate this service. We currently have 3 [SDK's](https://aws.amazon.com/iot/sdk/) that could be used on various hardware platforms.
Please use [this](https://forums.aws.amazon.com/forum.jspa?forumID=210&start=0) forum for any questions related to AWS IoT service.

Also, the updated hackseries with the new AWS IoT service could be found [here](http://iot-hackseries.s3-website-us-west-2.amazonaws.com/aws.html).

Thanks
Bhadri
