### ISSUE TITLE
TransferUtility Can't provide public-read permission with upload

### ISSUE THREAD

**Issue by jitendraramoliya** [aws/aws-sdk-android#65]
I have tried upload image on Amazon server. Picture uploaded successfully but Could have permission like public-read. I can't view picture by clicking on picture. I have to set permission after uploading that image to amazon server via s3Object.setObjectAcl. that is required extra unnecessary request on server. Could any one provide me solution on that ?

**Comment by wdane** [comment]
Closing, as this is a duplicate to https://github.com/aws/aws-sdk-android/issues/63.  Please +1 that request to add interest.  We understand that a lot of developers would like this feature and would certainly like to address it.
