### ISSUE TITLE
Not able to set the content type for video uploaded via the SDK

### ISSUE THREAD

**Issue by shklnrj** [aws/aws-sdk-android#68]
I am uploading video from the Android app to set. When the upload is finished, I generate the pre-signed url.
When I put the presigned url in the browser, instead of opening the video in the browser, it is downloading it. Here is some of the code that I am using-
            `ObjectMetadata objectMetadata = new ObjectMetadata();
            String mime = FileHandlingUtils.getMimeType(fileUri, getContext());
            objectMetadata.setContentType(mime);
            objectMetadata.addUserMetadata("Content-Type", mime);
            videoUploadObserver = amazonTransferUtitlity.upload(
                    bucketName,
                    keyName,
                    file,
                    objectMetadata
            );`

In this case, the mime type was "video/3gpp".
Why is this happening? and is it expected?

**Comment by fosterzhang** [comment]
The usage is correct. What's the content-type of the object in S3 console?

**Comment by shklnrj** [comment]
I checked it again, the data type given out by the web browser is the same as that set. It seems that the browser is not able to play that format and hence downloads it instead of playing. This is probably the expected behaviour. 
Closing this .
