### ISSUE TITLE
HandlerChainFactory hangs when getting resources

### ISSUE THREAD

**Issue by francoiscampbell** [aws/aws-sdk-android#69]
When trying to instantiate an AmazonS3Client in the Application class's onCreate, the initialization hangs at this point in com.amazonaws.handlers.HandlerChainFactory:

    private List<RequestHandler2> createRequestHandlerChain(String resource,
            Class<?> handlerApiClass) {
        List<RequestHandler2> handlers = new ArrayList<RequestHandler2>();
        BufferedReader reader = null;

        try {
            InputStream input = getClass().getResourceAsStream(resource); //hangs here
            if (input == null)
                return handlers;

            reader = new BufferedReader(new InputStreamReader(input));
    ........

Sometimes, the code will continue successfully after about 5 minutes but most of the time it just blocks.

Here is my stacktrace:

    "main@20960" prio=5 waiting
      java.lang.Thread.State: WAITING
	  at com.amazonaws.handlers.HandlerChainFactory.createRequestHandlerChain(HandlerChainFactory.java:66)
	  at com.amazonaws.handlers.HandlerChainFactory.newRequestHandlerChain(HandlerChainFactory.java:44)
	  at com.amazonaws.services.s3.AmazonS3Client.init(AmazonS3Client.java:463)
	  at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:410)
	  at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:368)
	  at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:340)
	  at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:324)
	  at [appname].fileserver.S3Server.<init>(S3Server.java:27)
	  at [appname].fileserver.FileServerFactory.createForConfig(FileServerFactory.java:23)
	  at [appname].CommonData.downloadConfigFile(CommonData.java:141)
	  at [appname].CommonData.onCreate(CommonData.java:105)
	  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1021)
	  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5986)
	  at android.app.ActivityThread.access$1700(ActivityThread.java:197)
	  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1742)
	  at android.os.Handler.dispatchMessage(Handler.java:102)
	  at android.os.Looper.loop(Looper.java:145)
	  at android.app.ActivityThread.main(ActivityThread.java:6891)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at java.lang.reflect.Method.invoke(Method.java:372)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by fosterzhang** [comment]
Thank you for reporting the issue. Would you please provide more information?
- version of the SDK. The latest version is 2.2.7.
- device/emulator information. What's the make of the device, running which Android version, on Wifi or cellular?
- a reliable way to reproduce the issue if possible.

**Comment by francoiscampbell** [comment]
*I was on version 2.2.6 and tried 2.2.7 today but that did not fix it
*The devices are Samsung Galaxy S5 on Android 5.0, S6 on Android 5.1, and S6 edge+ on Android 5.1.1
*All devices are on a working LTE connection
*The S6 are rooted and the S5 is not
*In our use case, the issue appears when trying to instantiate an AmazonS3Client with BasicAwsCredentials. The issue happens no matter what thread or when in the app lifecycle the client is instantiated.

I even reverted to a previous version of our app that was known to be working and it took about 5 minutes to instantiate the client in this case. The device has not had any software update between these two times.

**Comment by fosterzhang** [comment]
BasicAwsCredentials shouldn't matter. getResourceAsStream() may be slow as the app loads the library into memory, but I don't expect it take 5 minutes. Let me investigate and I will get back to you ASAP.

**Comment by lutaseb** [comment]
same issue here,
used version 2.2.7 and got the following stacktrace
network can be 3G+, 4G or Wifi doesn't change anything
```
I/dalvikvm-heap(19628): Clamp target GC heap from 71.394MB to 64.000MB
D/dalvikvm(19628): GC_BEFORE_OOM freed 0K, 3% free 63648K/65536K, paused 242ms, total 242ms
E/dalvikvm-heap(19628): Out of memory on a 280-byte allocation.
I/dalvikvm(19628): "main" prio=5 tid=1 RUNNABLE
I/dalvikvm(19628):   | group="main" sCount=0 dsCount=0 obj=0x41b05578 self=0x41a3f6a8
I/dalvikvm(19628):   | sysTid=19628 nice=-16 sched=0/0 cgrp=apps handle=1074167804
I/dalvikvm(19628):   | state=R schedstat=( 13937135589 430272745 4829 ) utm=1316 stm=77 core=2
I/dalvikvm(19628):   at java.lang.Throwable.nativeFillInStackTrace(Native Method)
I/dalvikvm(19628):   at java.lang.Throwable.fillInStackTrace(Throwable.java:161)
I/dalvikvm(19628):   at java.lang.Throwable.<init>(Throwable.java:84)
I/dalvikvm(19628):   at java.lang.Error.<init>(Error.java:37)
I/dalvikvm(19628):   at java.lang.VirtualMachineError.<init>(VirtualMachineError.java:35)
I/dalvikvm(19628):   at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:33)
I/dalvikvm(19628):   at java.util.HashMap.makeTable(HashMap.java:-1)
I/dalvikvm(19628):   at java.util.HashMap.<init>(HashMap.java:158)
I/dalvikvm(19628):   at java.util.jar.Attributes.<init>(Attributes.java:207)
I/dalvikvm(19628):   at java.util.jar.InitManifest.initEntries(InitManifest.java:59)
I/dalvikvm(19628):   at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:332)
I/dalvikvm(19628):   at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:276)
I/dalvikvm(19628):   at java.util.jar.JarFile.getInputStream(JarFile.java:399)
I/dalvikvm(19628):   at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:226)
I/dalvikvm(19628):   at java.net.URL.openStream(URL.java:462)
I/dalvikvm(19628):   at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:436)
I/dalvikvm(19628):   at java.lang.Class.getResourceAsStream(Class.java:967)
I/dalvikvm(19628):   at com.amazonaws.handlers.HandlerChainFactory.createRequestHandlerChain(HandlerChainFactory.java:66)
I/dalvikvm(19628):   at com.amazonaws.handlers.HandlerChainFactory.newRequestHandlerChain(HandlerChainFactory.java:44)
I/dalvikvm(19628):   at com.amazonaws.services.s3.AmazonS3Client.init(AmazonS3Client.java:463)
I/dalvikvm(19628):   at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:410)
I/dalvikvm(19628):   at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:368)
I/dalvikvm(19628):   at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:352)
I/dalvikvm(19628):   at com.tructv.truc.upload.AwsUtils.getS3ClientInstance(AwsUtils.java:70)
I/dalvikvm(19628):   at com.tructv.truc.upload.AwsUtils.getTransferUtilityInstance(AwsUtils.java:85)
I/dalvikvm(19628):   at com.tructv.truc.upload.VideoUploadToS3Manager.<init>(VideoUploadToS3Manager.java:109)
I/dalvikvm(19628):   at com.tructv.truc.upload.VideoUploadManager.<init>(VideoUploadManager.java:92)
I/dalvikvm(19628):   at com.tructv.truc.services.Servicestruc.onCreate(Servicestruc.java:316)
I/dalvikvm(19628):   at android.app.ActivityThread.handleCreateService(ActivityThread.java:2687)
I/dalvikvm(19628):   at android.app.ActivityThread.access$1700(ActivityThread.java:159)
I/dalvikvm(19628):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
I/dalvikvm(19628):   at android.os.Handler.dispatchMessage(Handler.java:99)
I/dalvikvm(19628):   at android.os.Looper.loop(Looper.java:176)
I/dalvikvm(19628):   at android.app.ActivityThread.main(ActivityThread.java:5419)
I/dalvikvm(19628):   at java.lang.reflect.Method.invokeNative(Native Method)
I/dalvikvm(19628):   at java.lang.reflect.Method.invoke(Method.java:525)
I/dalvikvm(19628):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
I/dalvikvm(19628):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
I/dalvikvm(19628):   at dalvik.system.NativeStart.main(Native Method)
I/dalvikvm(19628): 
W/dalvikvm(19628): Exception thrown (Ljava/lang/OutOfMemoryError;) while throwing internal exception (Ljava/lang/OutOfMemoryError;)
D/AndroidRuntime(19628): Shutting down VM
```
with a OOM crash on galaxy S3
and a high CPU usage on alcatel Idol3

so, is there a workaround about this?

**Comment by fosterzhang** [comment]
@francoiscampbell I did a profiling recently and confirmed that `getResourceAsStream()` in `createRequestHandlerChain` do have a performance impact. However I am not seeing it cause the app to hang. I suspect the impact may vary depending on the size of the APK and whether it's multi-dex.

@lutaseb My guess is your APK size is considerable large. `getResourceAsStream()` may load the library (or APK) into memory and ultimately causes OOM. I suggest you trim down your APK size. Proguard may help in this case.

Stay tuned for the fix.

**Comment by fosterzhang** [comment]
@francoiscampbell [AWS Mobile SDK for Android v2.2.9](http://aws.amazon.com/releasenotes/7213377076701301) is released today to address this issue. Please check out the latest version.
