### ISSUE TITLE
TransferUtility hangs in WAITING_FOR_NETWORK

### ISSUE THREAD

**Issue by corbt** [aws/aws-sdk-android#70]
I noticed that on flaky connections TransferUtility uploads sometimes were stalling forever.

I've managed to reproduce the issue by doing the following:

1. Begin an upload with TransferUtility
2. Turn wifi off for an extended period of time (5-10 minutes)
3. Turn wifi back on

During the time that wifi is off, the transfer remains in the `WAITING_FOR_NETWORK` state indefinitely, as expected. However, on turning wifi back on (and confirming connectivity in other apps, etc), the transfer does not resume as expected.

I've also noticed this behavior (transfer stuck waiting eternally) on flaky networks, which is why I began investigating it in the first place. The transfer is never resumed -- I left one waiting for several days, actually, and it didn't ever resume.

**Comment by fosterzhang** [comment]
Thanks for reporting this issue. We are researching this issue and will get back to you ASAP.

**Comment by jitendraramoliya** [comment]
Fosterzhand, Please! provide solution on this issue ASAP.

**Comment by fosterzhang** [comment]
The service stops itself after a period of inactivity, say no active transfers. When network is off, all transfers are on hold, and the service thinks it should stop itself. However it'd better stay active till the network comes back. I'll fix it in the next release.

**Comment by fosterzhang** [comment]
This has been fixed in v2.2.10 release. Please check out the [release notes](http://aws.amazon.com/releasenotes/Android/4230087492325095).

**Comment by corbt** [comment]
Great, thanks.
