### ISSUE TITLE
Getting timeout then pause when throttling connection

### ISSUE THREAD

**Issue by jghazarian** [aws/aws-sdk-android#75]
I'm currently having issues with an app that requires uploading videos to S3. I'm having trouble getting consistent results, but in general, if I throttle my upload speeds to 1mbps, then try to upload a large video file (in my most recent test, it failed on a 18.5MB file), then the upload will fail after it appears most of the data has been uploaded. Monitoring through Charles, it appears that the different parts(5MB chunks) are succeeding, but I'll get back a "Read timed out" stacktrace, followed by about a minute of inactivity in the logs, then the TransferObserver changes the status to PAUSED. I've been trying unsuccessfully to understand what is happening and what I can do to remedy this situation. It appears that the aws library automatically splits the videos into 5MB parts for upload. Should I be sending smaller chunks? Why does the upload switch to paused if it actually fails without trying to resume? Should I be handling the pause state change in this case?

If it's helpful, I have the stacktrace from the timeout here: http://pastebin.com/uASUDFTE

**Comment by fosterzhang** [comment]
@jghazarian Not sure what throttling software you use on the device and how it works. If you are experiencing timeout issue, I suggest you increase the socket timeout of the S3 client via [ClientConfiguration](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html). FYI, the default is 15 seconds.

**Comment by jghazarian** [comment]
So I'm using Charles Proxy to throttle, but I originally started getting reports of failed uploads from testers in Mexico. I was told they were on a 1mbps upload line, so that's what I was using as a base. This seems to be dependent on how much I throttle my connection. The larger the file is, the less I need to throttle for it to fail. It also doesn't send that timeout message until the uploads appear to be almost fully uploaded. Does that seem normal? I'll try tweaking the timeout configuration.

**Comment by fosterzhang** [comment]
@jghazarian I am not familiar with Charles Proxy's throttling feature, so I can't answer your question. The behavior after throttling may not be the same as slow network. Have you tried to limit the network speed on Android emulator? See [Network Speed Emulation](http://developer.android.com/tools/devices/emulator.html#netspeed).
