### ISSUE TITLE
Is it possible to force TLS

### ISSUE THREAD

**Issue by rimeissner** [aws/aws-sdk-android#76]
As most of the AWS services don't support SSLv3 anymore and require TLS it would be nice to force this client side (as all modern Android versions should support that). 

Also is it possible to change the Network stack to archive that (let's say to OkHttp?)

**Comment by fosterzhang** [comment]
@rimeissner Usually Android uses the best available SSL protocol to handshake with remote server. There is no need to force a particular protocol. The SDK prefers to rely on the platform behavior unless there is a compelling reason not to do so.

If you want to play with it, you probably need to manipulate [SSLSocket](http://developer.android.com/reference/javax/net/ssl/SSLSocket.html).

**Comment by fosterzhang** [comment]
Close this as it's not related to the SDK.
