### ISSUE TITLE
No support for errors from the API

### ISSUE THREAD

**Issue by ataormina-rmn** [aws/aws-sdk-android#77]
The SDK does not have any support for dealing with 400's and 500's coming from the API. I'm reading the source-code for iOS and Android, and it looks like this SDK just isn't even trying. iOS and JS both have support for this, is this a requested feature on Android? Throwing exceptions seems like the opposite of what we want here. ApiClientHandler.handleResponse() is the problematic bit. Even the sample code at http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk.html shows that the other two support this feature. Has this been requested before?

**Comment by wdane** [comment]
Hey ataormina,

Can you be a little bit more specific in what you are asking for?  Throwing an exception seems like reasonable behavior when calling a remote API and encountering an exception.

**Comment by ataormina-rmn** [comment]
Well, my API sends down 400s generally as a response to my user doing something incorrectly. I would still like to be able to parse the JSON response that I'm being sent regardless of what the status code is. And given that this is an Android application, I need any error handling to happen gracefully as to not crash the user's experience.

**Comment by ataormina-rmn** [comment]
If instead of `ApiClientException ase = new ApiClientException("Service returned code: "
                    + code + ", error: " + error);` we instead made it `ApiClientException ase = new ApiClientException(error);` then at least the error could be caught a properly parsed into JSON (or whatever format). This would at least give back the String representation of the server's response. Looking at the stack traces and code, it looks like AmazonServiceException.getMessage() is already appending all of this additional information.

`try {
    myClient.myCall();
} catch (ApiClientException e) {
    // e.getErrorMessage() and e.getStatusCode() would let me figure out what this is and how to handle it
}

**Comment by ataormina-rmn** [comment]
https://github.com/aws/aws-sdk-android/pull/78

**Comment by fosterzhang** [comment]
#78 is accepted. Thank you.
