### ISSUE TITLE
Upload stuck : how I can force to start uploading

### ISSUE THREAD

**Issue by polok** [aws/aws-sdk-android#81]
Hi,

First my problem/case.

I have my own custom service which uses your SDK (basically TransferUtility). All works fine when I have internet connection. The whole fun begins when:
 - my service was killed
-  when I loose network connection the transfer doesn't want to start (sometimes it works  but more often it seems to stuck : the records have RESUMED_WAITING and then when I run the app/my service (btw.I  start my service during app launch) the records have status WAITING and nothing is uploaded

Also, for first case when my service was killed. I wanted to force it the upload agin. However, I don't see how I can do this. I tried to use resume but the state has to be PASUED, so first I run pause method which doesn't do the trick for me as it is setting PENDING_PAUSE and won't change to PAUSE so I can't resume it. How I can force, notify the TransferUtility or it's service to start uploading once again.

I am writing in a small rush so if I don't put enough information, just let me know. I will try to put more light on it then.

Thanks in advance for help.

**Comment by fosterzhang** [comment]
Thanks for reporting it. We are working on the fix. Stay tuned.

**Comment by polok** [comment]
Thanks for quick answer. Is there any chance that you will release new version with fix for above in very near future ?  Our core functionality is based on uploading and this is really crucial for us ;/

**Comment by fosterzhang** [comment]
@polok I'll definitely fix it ASAP, but sorry that I can't promise you an exact date. The service idles due to lost of network connection and eventually stops itself. An alternate solution is to delete the transfer and add it back to reactivate the service.

**Comment by fosterzhang** [comment]
AWS SDK for Android v2.2.11 was released just now. The service should stay alive as long as there are active transfers. It'll resume transfers automatically when network is back. Also, you can use [TransferUtility.resume(int)](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.html#resume(int)) to resume a transfer which is not in `TransferState.COMPLETED` state. Check out the [release notes](http://aws.amazon.com/releasenotes/Android/2037471825124826) for more details.

**Comment by polok** [comment]
Awesome! I will check. Thx

**Comment by fosterzhang** [comment]
Closing this. Feel free to reopen it if the issue persists.
