### ISSUE TITLE
No SNI support

### ISSUE THREAD

**Issue by dancudds** [aws/aws-sdk-android#82]
SNI support was added in SSLCertificateSocketFactory.
By not using SNI, certain G/Ws block the connections to AWS services because they don't see the hostname of the connection (only the IP address).
AWS IP ranges are blocked at a lot of Enterprise networks because of proxy usage and other skunkworks. Having SNI support will allow Enterprise network admins to allow these services.

**Comment by fosterzhang** [comment]
@dancudds according to http://developer.android.com/training/articles/security-ssl.html, SNI is supported by HttpsURLConnection since Android 2.3 (API level 9) and is on by default. The AWS Mobile SDK for Android doesn't manipulate neither SSLSocketFactory nor SSLSocket of HttpsURLConnection. In theory, SNI should still be on. Do you see any issue regarding SNI?

**Comment by fosterzhang** [comment]
Here is the source code that shows SNI is set in HttpURLConnection.

- Android 4.3.1 https://android.googlesource.com/platform/libcore/+/android-4.3.1_r1/luni/src/main/java/libcore/net/http/HttpConnection.java#203
- Android 6.0 https://android.googlesource.com/platform/external/okhttp/+/android-6.0.0_r7/okhttp/src/main/java/com/squareup/okhttp/internal/Platform.java#212

**Comment by dancudds** [comment]
That's not what I see in practice from PCAPs. SNI is never set in the Client Hello

**Comment by fosterzhang** [comment]
@dancudds would you please share your code and explain how to test it?

**Comment by fosterzhang** [comment]
@dancudds any update?

**Comment by dancudds** [comment]
@fosterzhang Sorry for the delay - hope to get you something by the end of the week

**Comment by dancudds** [comment]
[pcapsforawssni.pcap.pcapng.zip](https://github.com/aws/aws-sdk-android/files/100138/pcapsforawssni.pcap.pcapng.zip)

**Comment by fosterzhang** [comment]
@dancudds I turned on [WireShark](https://www.wireshark.org) 2.0.1 on my Mac, then ran several samples on emulator. I verified SNI is enabled on Android 2.3.3 and 6.0. I believe it's true for versions in between.

For example, a snippet from Android emulator 6.0 talking to SNS. Server name is indeed set.
```
Secure Sockets Layer
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 229
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 225
            Version: TLS 1.2 (0x0303)
            Random
            Session ID Length: 0
            Cipher Suites Length: 44
            Cipher Suites (22 suites)
            Compression Methods Length: 1
            Compression Methods (1 method)
            Extensions Length: 140
            Extension: server_name
                Type: server_name (0x0000)
                Length: 32
                Server Name Indication extension
                    Server Name list length: 30
                    Server Name Type: host_name (0)
                    Server Name length: 27
                    Server Name: sns.us-east-1.amazonaws.com
            Extension: ec_point_formats
            Extension: elliptic_curves
            Extension: SessionTicket TLS
            Extension: signature_algorithms
```

If you see something different, please share your testing environment, e.g. platform, device, make, etc.

**Comment by dancudds** [comment]
Let's close this one down and I will revert if I have time to test again. Thanks for investigating.
