### ISSUE TITLE
add common types to Mimetypes.java

### ISSUE THREAD

**Issue by paleozogt** [aws/aws-sdk-android#83]
Could we get some common mime-types added to Mimetypes.java?  For example, `application/json` and `text/yaml` would be very useful.

**Comment by fosterzhang** [comment]
Probably a better approach is to provide a method to let user register new mime types. What do you say?

**Comment by paleozogt** [comment]
That would also work.  At the moment you have to stand on your head to do it by feeding it an InputStream.  Also, it feels weird manipulating an "internal" class.

**Comment by fosterzhang** [comment]
@paleozogt That's true :). I don't mind moving it out of internal if there is a valid reason. The method using InputStream isn't very helpful. I'll add a friendly method shortly. Stay tuned.

**Comment by paleozogt** [comment]
Sounds great.  Thanks!

**Comment by fosterzhang** [comment]
This has been added to v2.2.10 release. Please check out the [release notes](http://aws.amazon.com/releasenotes/Android/4230087492325095).

**Comment by paleozogt** [comment]
Thanks!
