### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by dvg4000** [aws/aws-sdk-android#84]
When try to upload with `TransferUtility`
```
transferUtility.upload(imageBucket, uploadFileName, uploadFile)
```
TransferState switches from `IN_PROGRESS` to `PAUSED` and nothing happens after that.

`uploadFile` exists. Permissions added to manifest. Service added too.

Tried to upload file from cache dir and extnernal cache dir - same result.
Tried from fragment and from activity - same result.

aws version 2.2.9

**Comment by fosterzhang** [comment]
Would you please share more information?
- Device or emulator? What Android version?
- What is the S3 region? Any special character in the bucket name? What's the file size? Is the state changed immediately after `IN_PROGRESS`?

**Comment by dvg4000** [comment]
Emulator: Nexus 5 API 23 x86
Devices with: Android `5.0` and `4.2.2`

Region: `US_West_2`
Bucket: `img-incoming.cmpny`

File sizes: 30 000 - 200 000 `bytes`

State changes after about 30 seconds.

Strange thing is that everything working in empty new project. I just copy activity code and manifests parts to new project and upload starts fine - i'm getting progress events.

**Comment by fosterzhang** [comment]
Is there a way to reproduce it in a reliable way? Otherwise it's really hard for me to figure out what's going on there. Please let me know if the problem occurs again.

**Comment by dvg4000** [comment]
Found what was the problem - wrong `proguard` settings in `app/build.gradle`
Anyway thank you for your replies.
