### ISSUE TITLE
What is a proper way to refresh FAILED transfer

### ISSUE THREAD

**Issue by polok** [aws/aws-sdk-android#87]
Hi,

I have a view where I show progress of the update. The problem is that sometimes because of low internet connection I get such error Unable to execute HTTP request: Read timed out... and transfer gets FAILED status what is fine but the problem is how I should force the SDK to start upload again. I don't want to close the app and run once again. Is there a possibility that this could be done automatically,  scheduled or something ?

Thanks in advance,

**Comment by fosterzhang** [comment]
Currently the SDK doesn't allow you to retry a failed transfer. Instead, you need to start a new transfer. I've seen similar requests several times. I'll research the best approach to address it. Stay tuned.

**Comment by polok** [comment]
Cool, looking forward for it. Thanks

**Comment by fosterzhang** [comment]
AWS SDK for Android v2.2.11 was released just now. You can use [TransferUtility.resume(int)](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.html#resume(int)) to resume a transfer which is not in `TransferState.COMPLETED` state. Check out the [release notes](http://aws.amazon.com/releasenotes/Android/2037471825124826) for more details.

**Comment by polok** [comment]
Awesome! I will check. Thx

**Comment by fosterzhang** [comment]
Closing this. Feel free to reopen it if the issue persists.

**Comment by diogomonte** [comment]
Does it still working for version 2.3.3? I've tried to call TransferUtility.resume(int) several times for a failed file and nothing happens. 

And also  transferUtility.getTransfersWithTypeAndState(TransferType.ANY, TransferState.FAILED) returns an empty list even with FAILED files.
