### ISSUE TITLE
Signature expired / Signature not yet current

### ISSUE THREAD

**Issue by rimeissner** [aws/aws-sdk-android#88]
We are using SNS, SQS and Kinesis for various services. All services report the following errors for some users: 
```
com.amazonaws.AmazonServiceException
Signature expired: 20151130T204723Z is now earlier than 20160119T133514Z (20160119T135014Z - 15 min.) (Service: AmazonSQS; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 9f58eb2d-329a-5b8b-be24-a43573ccd373)
```
or
```
com.amazonaws.AmazonServiceException
Signature not yet current: 20301206T194311Z is still later than 20160105T194814Z (20160105T194314Z + 5 min.) (Service: AmazonKinesis; Status Code: 400; Error Code: InvalidSignatureException; Request ID: 8efe1613-b3e4-11e5-abdc-270e435f23fb)
```

This happens when the AmazonHttpClient uses the device time, which can be changed by the user. We have a synchronised time available, is there any possibility to use that one for the request signing?

**Comment by fosterzhang** [comment]
The SDK has a mechanism to automatically calibrate device time and redo the request. Do you turn off retries?
If you want to use your own time, you can set it in the SDK. See [SDKGlobalConfiguration.setGlobalTimeOffset(int)](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/SDKGlobalConfiguration.html#setGlobalTimeOffset(int)).

**Comment by rimeissner** [comment]
Thanks. We did not specifically disable retries. But when an error occurs while sending the request we remove it from our queue so it won't be resend by us.

The method was exactly what I was looking for thanks.
