### ISSUE TITLE
No possibility to change HttpClient for AmazonSNSAsyncClient

### ISSUE THREAD

**Issue by rimeissner** [aws/aws-sdk-android#89]
The super class AmazonSNSClient has a constructor where it is possible to pass a custom HttpClient. It would be appreciated if this is also possible for this class.

**Comment by fosterzhang** [comment]
@rimeissner it's not possible now. As a matter of fact, the async client isn't actively maintained. It adds way too many methods but it doesn't bring much value. Do you mind letting me know the use case of this async client? Thank you.

**Comment by rimeissner** [comment]
We use that to update the endpoint status in the client, as this should not block the UI thread I used this client.

I agree that has a lot of overhead methods, therefore I created my own class that just implement the 2 methods I need.

**Comment by fosterzhang** [comment]
@rimeissner cool. We'll revisit async APIs. The probably deserve a redesign IMO. Stay tuned.

**Comment by fosterzhang** [comment]
Closing this, as the question has been answered.
