### ISSUE TITLE
SDK v1 deprecated methods

### ISSUE THREAD

**Issue by TOMKHAN** [aws/aws-sdk-android#91]
Hello.

In my app, I use Android Services and IntentServices to do some background stuff. In that background stuff I upload things to my server and also photos to Amazon using "aws-android-sdk-s3:2.2.9" lib. While using v1, there are no problems because there is that call waitForCompletion() on Upload object that was blocking the current thread (my Service) and when its finished, I can update my UI.

When I switch to v2 SDK, those classes (Upload and TransferManager) are deprecated and instead we should use TransferUtility that has no such thing as blocking the current thread (instead using UploadListener as callback mechanism that I don't need). My service background thread is long finished while uploading is still in progress (and I want to be sure that everything is uploaded before updating the UI thread).

Now, I'm just curious, why are they deprecated? And when will they be removed from the APIs? Will there be an announcement when that happens or? One day when that happens, my code won't run anymore or the app in production (and all the other old versions) won't run anymore?

Thanks for the info :)

**Comment by fosterzhang** [comment]
I understand your frustration. It's a hard decision to deprecate TransferManager, but we do have compelling reasons to move forward. TransferUtility covers 90% of what TransferManager has. It provides better support of pause and resume and better handling of network connectivity changes. Its design is more friendly to Android. For more details, please see [AWS SDK for Android Transfer Manager to Transfer Utility Migration Guide](https://mobile.awsblog.com/post/Tx2KF0YUQITA164/AWS-SDK-for-Android-Transfer-Manager-to-Transfer-Utility-Migration-Guide).

To update UI upon completion of a transfer, there are two solutions
- done via the callback of TransferListener. Implement [onStatusChanged(int, TransferState)](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/s3/transferutility/TransferListener.html#onStateChanged(int,%20com.amazonaws.mobileconnectors.s3.transferutility.TransferState)). Update UI when the state becomes [COMPLETED](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/s3/transferutility/TransferState.html#COMPLETED).
```
TransferObserver transfer = TransferUtility.upload(bucket, key, file);
transfer.setListener(new TransferListener() {
    @Override
    public void onStateChanged(int id, TransferState state) {
        if (TransferState.COMPLETED.equals(transfer.getState())) {
            // update UI
        }
    }
});
```
- write your own waitForCompletion
```
TransferObserver transfer = TransferUtility.upload(bucket, key, file);
transfer.setListener(listener); // required, or else you need to call refresh()
while (true) {
    if (TransferState.COMPLETED.equals(transfer.getState())
        || TransferState.FAILED.equals(transfer.getState())) {
        break;
    }
}
```

There is no exact date when TransferManager will be removed. We encourage you migrate to TransferUtility if possible. However if you want to stick to TransferManager, it's always available in older versions of the SDK. Your production app shouldn't be impacted as long as you freeze the SDK version.

**Comment by TOMKHAN** [comment]
Yes, I believe you did a lot to improve the SDK and as I saw, you did a pretty good job. But for my case, I was frustrated to find that there was no way to stop the current thread. Read that guide and it didn't say anything about waitForCompletion() replacement. Also tried that infinite loop to simulate the waitForCompletion(), but was unsure what states can transfer object take.

You cleared all of my questions. Will use TransferUtility with the inifnite loop, hoping for not staying in it forever :) Thank you @fosterzhang :+1:

**Comment by jplazcano87** [comment]
still no alternative in the official sdk this issue? the given solutions seems like a hack to me

**Comment by TOMKHAN** [comment]
@jplazcano87 see #119, #199 and linked issues. It's labeled as feature request. No ETA.

**Comment by harshbhavsar011** [comment]
How to do this for multiple files?
